candlepin/candlepin

- server/src/main/java/org/candlepin/dto/api/v1/DeletedConsumerDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/DeletedConsumerTranslator.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/DeletedConsumer.java
- server/src/main/java/org/candlepin/model/OwnerEnvContentAccessCurator.java
- server/src/main/resources/db/changelog/20190813155224-add-principal-to-deleted-consumers.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/dto/api/v1/DeletedConsumerDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/DeletedConsumerTranslatorTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- DeletedConsumer now has a column to store the name of the principal
that triggered the deletion of a consumer
- ConsumerCurator.delete now sets the name of the current principal
on the deleted consumer record it creates
> [2.7] 1741209: Added principal to consumer deletion records (ENT-1572)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Added an additional null check to an entitlement revocation
operation in CandlepinPoolManager to avoid attempting to
iterate through a null collection
> [2.7] Added an additional null check during entitlement revocation

- server/src/main/java/org/candlepin/liquibase/LiquibaseCustomTask.java
- server/src/main/java/org/candlepin/liquibase/LiquibaseCustomTaskWrapper.java
- server/src/main/resources/META-INF/persistence.xml
- server/src/test/java/org/candlepin/junit/LiquibaseExtension.java
- The HSQLDB instance used for general unit tests has moved from
the in-memory DB, to a file-system DB in the system temp
directory (/tmp)
- LiquibaseExtension now uses IF EXISTS when executing a
DROP SCHEMA command
- LiquibaseExtension now drops any existing known/expected
schema immediately after connecting to the DB, before
attempting to create any new schemas
- LiquibaseCustomTask now implements Closeable and closing
a custom task will forcefully close any open prepared statements
created through the preparedStatement or executeQuery methods
- LiquibaseCustomTaskWrapper now uses the new .close method
after executing any custom task to ensure opened statements
are explicitly closed
- LiquibaseExtension now uses a direct Statement object and
explicitly closes it, rather than offloading …
> [M] Moved testing HSQLDB instance to a file rather than memory

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- Splitted transaction of Entitler.revokeUnmappedGuestEntitlements into a series of bulks by 1000 items
- Remove mocks marked as redundant from EntitlerTest
Reviewer notes:
- Instead of splitting the transaction itself I decided to split its input.
> 1561798 - Split transaction of unmapped cleaner job into multiple transactions

- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- Switch to JUnit5
- Remove unused dependencies on OwnerProductCurator and ProductCurator
- Remove redundant type arguments
- Remove unused test data
- Remove redundant throws declarations
> Switch EntitlerTest to JUnit5

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Added the @Verify annotation to ConsumerResource.consumerExists
to allow consumers to check for self-existence on a given
Candlepin node without needing to fetch and serialize the entire
Consumer object via ConsumerResource.getConsumer
> [M] Added the @Verify annotation to ConsumerResource.consumerExists

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/guice/CandlepinRequestScope.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/resources/db/changelog/20181121151738-add-async-job-tables.xml
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/controller/OwnerManagerTest.java
- Owner is no longer strongly referenced by the jobs table
- OwnerManager no longer performs any job cleanup on owner deletion
- JobManager no longer uses UnitOfWork when setting up the job
environment
- JobManager now performs better transaction isolation and tracking
during job initialization and execution
- JobManager will now attempt to automatically commit or rollback an
open database transaction after job execution completes or fails
- JobManager now properly saves and restores MDC state before/after
job execution
- Cancelled jobs no longer cause a JobInitializationException when
its respective message is received
- AsyncJobStatus is now versioned and uses optimistic locking to
prevent update collisions
> [F]  Updated JobManager's scoping capabilities (ENT-1562)

- server/spec/unmapped_guest_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- Update Auto-Attach to revoke host specific entitlements the guest is no longer eligible for
> 1402945: Guests should be eligible for the temporary guest pool after migration

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Now, when deleting pools, the revocation of entitlements of those
pools will use a delete query instead of a hibernate batch detach,
in order to avoid memory overuse.
> [2.7] 1748406: When deleting pools, delete entitlements using ids; ENT-1583

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Now, when deleting pools, the revocation of entitlements of those
pools will use a delete query instead of a hibernate batch detach,
in order to avoid memory overuse.
> [M] 1742806: When deleting pools, delete entitlements using ids; ENT-1583

- server/bin/artemis/README.md
- server/bin/artemis/configure-artemis.py
- server/bin/deploy
- server/conf/candlepin.conf.template
- server/src/main/java/org/candlepin/async/impl/ActiveMQSessionFactory.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/ActiveMQStatusMonitor.java
- server/src/main/resources/broker.xml
- Also, now candlepin.conf is populated with remote artemis
properties when running the deploy script with -b -a
> [F] ENT-869: Use SSL when deploying Artemis remotely

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java
- In case of hypervisor update async flow, If existing hypervisorid entry is null then create new hypervisorid entry and add it to the consumer.
> [M] 1751727: update new hypervisorid when existing hypervisorid is null; ENT-1603

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
-In case of hypervisor update async flow, If existing hypervisorid entry is null then create new hypervisorid entry and add it to the consumer.
> [2.6] 1746912: update new hypervisorid when existing hypervisorid is null; ENT-1603

- build.gradle
- buildfile
- server/build.gradle
- server/pom.xml
- server/src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- Now, when creating a JSS provider on deployment, we also create
a JSS CryptoManager, which initializes the NSS db.
- Downgraded JSS to 4.4.6 to be in line with the jars/libraries
distributed in RHEL 7. This means with this fix, candlepin is
not compatible with RHEL 8, which ships with JSS 4.5.x.
- Added https://barnabycourt.fedorapeople.org/repo/candlepin as
a new, temporary, artifact repository for our builds, which holds
the jss 4.4.6 dependency for now.
Co-authored-by: Alexander Scheel ascheel@redhat.com
> [2.7] 1753201: Initialize the NSS db when loading a JSS provider; ENT-1656

- server/src/main/java/org/candlepin/audit/QpidEventMessageReceiver.java
- Minor logging change to print stack trace
> [ENT-1140]1667952: candlepin refuses to start when having too many messages in ActiveMQ journal

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- Updated default configuration to no longer attempt to load the
removed DatabaseListener class
> [2.6] 1753255: ActiveMQContextListener no longer attempts to load DatabaseListener

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- Updated default configuration to no longer attempt to load the
removed DatabaseListener class
> [2.7] 1753256: ActiveMQContextListener no longer attempts to load DatabaseListener

- Vagrantfile
- vagrant/README.md
Due to ongoing issues had by a few developers with gradle lock files & nfs, switch to sshfs in order to unblock immediate development.
> Change from nfs to sshfs for mounting filesystem in vagrant

- server/client/ruby/candlepin_api.rb
- server/spec/owner_product_resource_spec.rb
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/dto/StandardTranslator.java
- server/src/main/java/org/candlepin/dto/api/v1/BrandingDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/ProductBrandingTranslator.java
- server/src/main/java/org/candlepin/dto/api/v1/ProductDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/ProductTranslator.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductBranding.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/resources/db/changelog/20190919132617-create-product-branding-join-table.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/ContentManagerTest.java
- server/src/test/java/org/candlepin/controller/ProductManagerTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ProductBrandingTranslatorTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ProductCertificateTranslatorTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ProductDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ProductTranslatorTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Now Product holds Branding information by means of
the cp_product_branding table.
- ProductDTO supports BrandingDTO information in POST/GET
product API requests.
- Updated/Created unit and spec tests
- Updated method javadocs in ProductManager.java
> [F] ENT-1610: Add Branding to Product model

- server/src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- JSSProvider/CryptoManager are now loaded once, during
context initialization, and not during classloading of
JSSProviderLoader.java
> 1754488: remove addProvider call from static block; ENT-1676

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
Allow setting the autoheal attribute of consumer during the rest call that creates the consumer.
> 1702035 - [RFE] Set autoheal as part of consumer creation.

- common/po/zanata.xml
- Switched url to fedora zanata
- Removed deprecated locales block
> ENT-1682: Update build process to use Fedora Zanata

- server/build.gradle
- server/conf/candlepin.conf.template
- server/pom.xml
- server/src/main/java/org/candlepin/cache/JCacheManagerProvider.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/resources/META-INF/persistence.xml
- server/src/main/resources/ehcache.xml
- I did not find a clean way to configure cache in Java and use it into JPA initialization process. Hence continue using XML to configure cache properties.
- Updated net.sf.ehcache:ehcache:2.10.3 (ehcache 2) with org.ehcache:ehcache:3.8.0 (ehcache 3 latest version)
- Updated org.hibernate:hibernate-ehcache:5.3.8.Final with org.hibernate:hibernate-jcache:5.4.6.Final to support ehcache 3 and fix related to ehcache.xml file.
- Remove org.ehcache:jcache:1.0.0 as it is not required in ehcache 3.
- Updated ehcache.xml as per ehcahce 3 specifications.
- Updated persistence.xml to use ehcache 3 JCacheRegionFactory.
- Added hibernate.javax.cache.missing_cache_strategy = create to avoid warning related to missing cache definition in ehcache.xml.
- Updated JCacheManagerProvider to get CacheManager …
> ENT-797: Update ehcache version from 2.10.3 to 3.8.0

- server/code/setup/cpdb
Bug suggested to pass ssl and sslfactory in case of external database.
- Added ssl, sslfactory, and sslcertpath options in cpdb command
- Connection with the database can be with or without SSL validations
> 1698469: [RFE] Add options for cpdb command

- server/build.gradle
If merged, we can close PRs #2477 and #2478 opened by dependabot.
> [M] Bump dependency versions of netty-all and keycloak

- docker/candlepin-base/cp-test
- docker/candlepin-base/setup-devel-env.sh
- docker/gating-test-images/README.mkd
- docker/gating-test-images/cp-latest-stage/setup-env-extras.sh
- docker/gating-test-images/temp-base-cp/setup-env.sh
- docker/gating-test-images/temp-cp/cp-test
- server/code/setup/cpsetup
- vagrant/README.md
- Building/Running the gating test containers will always use gradle
from now on (those use the candlepin version used by Hosted, which
will always have gradle from now on).
- Building the base container (used to run tests in jenkins) will
now use gradle from now on. The scripts running within that
container will keep using either buildr or gradle depending on
the branch that is checked out.
- Fix bug in cpsetup that would misconfigure tomcat to only support
TLSv1 (instead of additionally supporting TLSv1.1 and TLSv1.2).
> ENT-1701; Containers now use gradle instead of buildr

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java
Incorrect hypervisor id/system uuid reconcilliation fix
Added ability to update the consumer name from the hypervisor checkin. It previously
would only use the hypervisor report names on hypervisor creation
> 1766345: hypervisor checkin fails with cp_consumer_hypervisor_ukey error [ENT-1767]

- server/src/main/java/org/candlepin/model/CertificateSerial.java
- server/src/main/java/org/candlepin/model/CertificateSerialIdGenerator.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/test/java/org/candlepin/model/CertificateSerialCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/test/TestUtil.java
 - Removed unique long id generation code from CertificateSerial constructor
 - Updated all the references to pass id while creating CertificateSerial object
 - Updated Junits related to this change
> ENT-497: Update CertificateSerial to no longer generate UUIDs on instantiation

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerTest.java
- server/src/test/java/org/candlepin/model/OwnerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/PreEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/EntitlementResourceTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/sync/ConsumerExporterTest.java
- server/src/test/java/org/candlepin/test/TestUtil.java
- Removed entry of ensureUUID() from constructor Consumer()
- Added new Constructor(String uuid) to accept UUID
- Updated the references where parameter less constructor is called
> ENT-496: Update Consumer to no longer generate UUIDs on instantiation

- server/src/main/java/org/candlepin/audit/EventMessageReceiver.java
- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- server/src/test/java/org/candlepin/audit/EventMessageReceiverTest.java
- server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
- server/src/test/resources/logback-test.xml
- Changed the event messaging format to use an explicit TEXT type,
and updated the method used to write the message body to avoid
extraneous sizing values
- Added two new properties to event messages: EVENT_TYPE and
EVENT_TARGET, representing the event type and target, respectively
- Updated the EventSinkImpl and EventMessageReceiver tests to use
JUnit 5
- Removed a couple tests that were no longer needed from the
EventSinkImpl test suite
> [M] 1772194: Updated event messaging to use TEXT_TYPE and simple strings

- server/src/main/java/org/candlepin/audit/DefaultEventMessageReceiver.java
- server/src/main/java/org/candlepin/audit/EventMessageReceiver.java
- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- server/src/main/java/org/candlepin/audit/QpidEventMessageReceiver.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisMessage.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisSession.java
- server/src/test/java/org/candlepin/audit/DefaultEventMessageReceiverTest.java
- server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
- server/src/test/java/org/candlepin/audit/QpidEventMessageReceiverTest.java
- Changed the event messaging format to use an explicit TEXT type,
and updated the method used to write the message body to avoid
extraneous sizing values
- Added two new properties to event messages: EVENT_TYPE and
EVENT_TARGET, representing the event type and target, respectively
- Updated the EventSinkImpl and EventMessageReceiver tests to use
JUnit 5
- Removed a couple tests that were no longer needed from the
EventSinkImpl test suite
> [F] Updated event messaging to use TEXT_TYPE and simple strings

- docker/candlepin-base/setup-devel-env.sh
- docker/test
- Docker containers will install and configure rvm and Ruby again
- The test script now provides an option to skip pulling images
from the repo in favor of using local images
> [M] Restored the rvm+ruby setup step during container construction (ENT-1816)

- server/spec/autobind_spec.rb
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
attribute when a space exists after a comma
- Added trim() in get_common_role and retrievePoolAttributeValues function
- Added JUnit to test the roles having white-spaces
> 1655731: Auto-Attach will not correctly match on role/addon product

- server/src/main/java/org/candlepin/util/Transactional.java
- server/src/test/java/org/candlepin/util/TransactionalTest.java
- Added the output validator functional interface and the two
registration methods: commitIf and rollbackIf
- Transactions managed by the Transactional wrapper can now be
commited or rolled back conditionally based on the output of
the wrapped operation using the new validator and hooks
> [F] Added conditional commit and rollback to the Transactional helper

- docker/candlepin-base/setup-devel-env.sh
- docker/test
- Docker containers will install and configure rvm and Ruby again
- The test script now provides an option to skip pulling images
from the repo in favor of using local images
> [M] Restored the rvm+ruby setup step during container construction (again)

- docker/candlepin-base/setup-devel-env.sh
- Skip the system update for ruby gems, as this forces bundler 2.1
to be used as the default bundler version
- Manually specify bundler v1.16 to be installed
> [M] Adjusted bundler version and skip container gem system update

- server/src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
between marketing product and associated provided and derived provided products.
- Created a table cp2_product_provided_products to hold mapping of products with provided products.
- Created a table cp2_derproduct_derprov_products to hold mapping of derived product with derived provided products.
- Updated the changelog files.
> [F] ENT-1825: Add new tables to hold mapping

- server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
- server/src/main/java/org/candlepin/controller/ActiveMQStatusMonitor.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisContextListener.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- Updated consumes type value from wildcard to aplication json in ConsumerResource.consumerExistsBulk method
- Added consumes type in HypervisorResource.hypervisorHeartbeatUpdate method
- Added method to cleanup thread and executorService in ActiveMQStatusMonitor
- updated CandlepinContextListener.contextDestroyed method to fix shutdown warnings
- Stop ActiveMQ status monitoring
- Clear ActiveMQ client thread pools
- Stop PersistService to avoid jdbc connect/pool related warning
- De-register drivers to avoid jdbc connection/pool related warning
This PR will fix memory leak warnings related to thread cleanup, JDBC connection and driver de-registration. Still, there are few ThreadLocalMap related warning logs available in shutdown logs.
> [M] 1548048: fix warning messages in tomcat shutdown log (ENT-519)

- server/bin/create_test_repos.py
- server/bin/test_data.json
* It is possible to include some files in testing RPMS
- Files should not be platform specific
- Files should not require any other dependency
* Added one more product, content and repo containing RPM
with fake insights-client, because this RPM is not available
in any repo for CentOS or Fedora
* It is useful for testing cockpit plugin, e.g. this PR: https://github.com/candlepin/subscription-manager/pull/2180
> Fake insights-client in testing repository

- server/src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml
Removed cp2_derproduct_derprov_products table. Since we are moving to keep the single table for provided products irrespective of product being normal/derived.
> ENT-1825: Add new tables to hold mapping

- server/src/main/java/org/candlepin/async/JobManager.java
- JobManager.cleanupJobs is now flagged with the @Transactional
annotation to ensure it operates within the context of a
transaction
> [M] 1790468: Fixed transaction requirement in JobCleaner task

- api/candlepin-api-config.json
- api/candlepin-api-spec.yaml
- build.gradle
- server/build.gradle
- settings.gradle
After this is in place, the process for porting a given resource or DTO to spec-first is:
1. Add the resource definition to `api/candlepin-api-spec.yaml` ([editor.swagger.io](https://editor.swagger.io/) works well for this).
2. Add any DTOs to `api/candlepin-api-spec.yaml`.
3. Change the resource to implement the generated API interface.
4. Remove all `javax.ws.rs` annotations from the resource implementation.
5. Remove all `io.swagger` annotations from the resource implementation.
6. Remove old DTOs from the codebase (refactor to use the generated ones instead).
7. Fix any broken code or tests.
8. Ensure unit tests still pass and the resource still works.
9. Ensure swagger.json is still generated and is equivalent.
Note: After building, you can view generated code in …
> Add spec-first build changes

- build.gradle
- buildSrc/src/main/resources/templates/returnTypeInterface.mustache
Add custom openapi vendor extension to override collection type
This makes it so that if for an operation you specify a line such as:
```yaml
x-java-response-container-type: java.util.stream.Stream
```
on an operation with a response return type of
```yaml
responses:
200:
description: OK
content:
application/json:
schema:
type: array
items:
$ref: '#/components/schemas/Link'
```
then the generated return type becomes `java.util.stream.Stream<Link>`
Specifically, this goes at the same level as `operationId`, because there is not a easy way to get the vendor extension for a response incorporated into the return type.
> Add custom openapi vendor extension to override collection type

- docker/gating-test-images/build.sh
- Use --no-cache when building docker images for gating tests
to avoid using stale images, and causing build errors when
hosted has upgraded to a newer version of candlepin.
> Always rebuild gating test docker images from scratch

- server/src/main/java/org/candlepin/dto/api/v1/ProductDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ProductDTO.java
- server/src/main/java/org/candlepin/model/dto/ProductData.java
- server/src/main/java/org/candlepin/service/model/ProductInfo.java
- server/src/test/java/org/candlepin/dto/manifest/v1/ProductDTOTest.java
- server/src/test/java/org/candlepin/model/dto/ProductDataTest.java
- Added method to get provided products from ProductInfo. 
(Note: `getProvidedProducts` and `getDerivedProvidedProducts` will get removed from subscriptionInfo in later PR's)
PS : 
- This is done to isolate it from refresh code flow.
- This will help to fix rspec issues related to #2565 changes.
Merge order :
This or #2563
> [F] ENT-1911 Add method to get provided products from ProductInfo

- server/bin/import_test_data.rb
- server/client/ruby/candlepin_api.rb
- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/candlepin_scenarios.rb
- server/spec/consumer_bonus_pool_provided_spec.rb
- server/spec/consumer_resource_dev_spec.rb
- server/spec/derived_product_spec.rb
- server/spec/import_spec.rb
- server/spec/one_sub_pool_per_stack_spec.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/dto/api/v1/PoolTranslator.java
- server/src/main/java/org/candlepin/dto/manifest/v1/PoolTranslator.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/test/java/org/candlepin/sync/EntitlementImporterTest.java
- Update org/candlepin/dto/api/v1/PoolTranslator.java to populate provided products into PoolDTO from Pool.Product.ProvidedProducts
- Updated org/candlepin/sync/Exporter.java to copy provided products from product and derived product
- Updated product creation logic in rspec
- Updated org/candlepin/dto/manifest/v1/PoolTranslator.java to populate provided products into PoolDTO from pool.product.providedProducts
- Updated rspec and junit as per code changes
- Removed spec tests related to accumulating provided products in case of stacked entitlements as marketing product and stack id has one to one relationship i.e. different marketing product will not have the same stacking id and all the required provided products will be available in marketing product itself from the adapter.
> [F] [ENT-1831][ENT-1830] update pool response and manifest export flow

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
constraint in Satellite 6.
Changes are cherry-picked from: 
1774640: Provide configuration option to disable UUID uniqueness constraint in Satellite 6.
> 1787599 - Provide configuration option to disable UUID uniqueness 

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
constraint in Satellite 6
Changes are done from reference of:
1774640: Provide configuration option to disable UUID uniqueness constraint in Satellite 6.
> 1787601 - Provide configuration option to disable UUID uniqueness

- build.gradle
Having checkstyle defined at the root even though we have no source that is
using it & no toolversion specified was causing errors when running dependency
analysis. Removing it fixes the dependencies tasks and removes the need for
masking in projects where we don't want it.
> Remove checkstyle from the root project

- build.gradle
- pom.xml
See #2606 for details. This PR includes changes to build.gradle as well as the pom.xml changes.
> [M] Updated repository URLs to use https instead of http

- server/spec/cert_revocation_spec.rb
- server/spec/client_v1_size_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/CertificateSerialDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/CertificateSerialTranslator.java
- server/src/main/java/org/candlepin/resource/CdnResource.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/dto/api/v1/CertificateDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CertificateSerialDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CertificateSerialTranslatorTest.java
- server/src/test/java/org/candlepin/dto/api/v1/UeberCertificateDTOTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Expected (UEP) serial# [u'9160844745519149032']
- Revert "1476028: ENT-528: Changed serial number datatype to String"
- This reverts commit 6be9ea3d1ad620ae1c7313d8d65bce5d13fe9d34.
- CertificateSerialDto.java is not reverted from this commit. This is removed as a part of a discussion in #2523. Hence kept this change to use CertificateSerialDTO.
> ENT-2068: 1798699: Found (local) serial# [9160844745519149032L];

- server/src/main/java/org/candlepin/async/JobMessageReceiver.java
- server/src/main/java/org/candlepin/async/tasks/UndoImportsJob.java
- server/src/test/java/org/candlepin/async/JobMessageReceiverTest.java
- Use UnitOfWork to open/close a sessions when starting/stopping a
job. Currently hibernate sessions are staying open when artemis
jobs are running, which causes a lot of issues, one of them being
manifested as stale data when the same artemis thread happens to
execute the same job sequentially, resulting in intermittent
spec test failures in import_spec.rb
> [M] ENT-2049: Use new hibernate session per job

- server/src/main/java/org/candlepin/async/JobMessageReceiver.java
- server/src/main/java/org/candlepin/async/tasks/UndoImportsJob.java
- server/src/test/java/org/candlepin/async/JobMessageReceiverTest.java
- Use UnitOfWork to open/close a sessions when starting/stopping a
job. Currently hibernate sessions are staying open when artemis
jobs are running, which causes a lot of issues, one of them being
manifested as stale data when the same artemis thread happens to
execute the same job sequentially, resulting in intermittent
spec test failures in import_spec.rb
Note: this is a cherry-pick from master to get the random test failures down.
> [F] ENT-2049: Use new hibernate session per job

- server/spec/job_status_spec.rb
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisProducer.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisSession.java
- Currently, jobs cannot run in parallel because we synchronize on
the JobManager singleton object on the execute method.
Once an artemis thread starts running a job, no other job can run
in parallel because the other artemis threads are waiting for the
lock. Not only that, but we also can't queue jobs at the same
time that a job is running, because the queue method is also
synchronized. This fix removes synchronization from these two
methods (and a couple more that don't need it).
- Added synchronization on ArtemisProducer & ArtemisSession to avoid
an artemis client warning when we try to queue jobs (AMQ212051:
Invalid concurrent session usage. Sessions are not supposed to be
used by more than one thread concurrently). This appeared once
the queueJob method stopped being synchronized.
> [M] ENT-2107: Make jobs run in parallel

- server/mead.chain
To test, you can use:
```
tito release --dry-run --no-build --no-cleanup mead
```
(answer yes to any questions, `--dry-run` prevents pushes); then:
```
brew maven-chain --skip-tag --scratch  candlepin-1-maven-candidate $changeme/candlepin/mead.chain
```
where `$changeme` is the path mentioned in tito output (like: `/tmp/tito/release-candlepinwkd3skn0` from `WARNING: leaving /tmp/tito/release-candlepinwkd3skn0 (--no-cleanup)`)
> Update mead build chain for api sub-project

- docker/.env
- docker/gating-test-images/README.mkd
- docker/gating-test-images/build.sh
- docker/gating-test-images/run.sh
The old one has been decommissioned
Note: this is a cherry-pick of the fix from master
> [2.9] ENT-2065 Migrate to new docker registry

- server/src/main/java/org/candlepin/resource/OwnerResource.java
- Added @Transactional annotation to the method listPools()
> ENT-2134: 1806575 - GET /owners/{owner_key}/pools is very slow

- docker/.env
The old one has been decommissioned
Note: this is a cherry-pick from master to fix jenkins builds
> [2.6] ENT-2065 Migrate to new docker registry

- Gemfile.lock
Reverts candlepin/candlepin#2629
This breaks our vagrant setups, as our current base images do not have (easy) access to ruby 2.2+ without adding rvm or changing the image. Reverting this change until we can get around to updating the vagrant config to be compatible with this change.
> Revert "Bump rake from 0.9.2.2 to 13.0.1"

- server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
Current rule code is only to consider consumer installed products to calculate the pool's average priority. Hence added any additional products into consumer’s installed products to correctly calculate pool average priority.
> 1692411: Added additional product ids into consumer installed products (ENT-1285)

- server/spec/oauth_spec.rb
oauth spec tests are failing with the newly created vagrant box (destroy and up). As per my investigation, either we need to pass only #{uri} or URL object instead of #{site}#{uri} in Net::HTTP::Get.new.
> [M] Fix oauth spec test

- server/spec/oauth_spec.rb
oauth spec tests are failing with the newly created vagrant box (destroy and up). As per my investigation, either we need to pass only #{uri} or URL object instead of #{site}#{uri} in Net::HTTP::Get.new.
> [F] Fix oauth spec test

- server/src/main/java/org/candlepin/async/tasks/ExportJob.java
- server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- ExportJob no longer requires a non-null and non-empty CDN label
to perform an export
> [M] Removed the constraint on the CDN label in ExportJob (ENT-2218)

- buildSrc/src/main/resources/templates/pojo.mustache
- Override the existing template present in openapi-generator
4.0.1 version from src/main/resources/JavaJaxRS/spec/pojo.mustache.
- Another Commit 4dc8e86bafad6beaf3e4bbf5fdbc5083183a7c3c is added to keep 
existing and new template changes separate. 
- Added the code to assign a collection to null and instantiate if it is required. These changes are followed by PR: https://github.com/OpenAPITools/openapi-generator/pull/3615 for pojo.mustache.
> ENT-2204: Make collections on openapi-generated DTOs null 

- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/resteasy/AnnotationLocator.java
- server/src/main/java/org/candlepin/resteasy/MethodLocator.java
- server/src/main/java/org/candlepin/resteasy/ResourceLocatorMap.java
- server/src/test/java/org/candlepin/resteasy/filter/AuthenticationFilterTest.java
- server/src/test/java/org/candlepin/resteasy/filter/AuthorizationFeatureTest.java
- server/src/test/java/org/candlepin/resteasy/filter/ConsumerCheckInFilterTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Added new class MethodLocator to hold interface method and concrete method mapping
- Updated ResourceLocatorMap class to use MethodLocator
- Update AnnotationLocator class to use MethodLocator instead of internal
> [F] ENT-2177: Use concrete method to locate ResourceLocator

- common/src/main/java/org/candlepin/common/filter/LoggingFilter.java
- Truncate correlation id to 40 characters instead of dropping it.
> [M] ENT-2215: truncate correlation id to 40 characters

- server/candlepin.spec.tmpl
- This fixes the following error thrown by the Cheetah template
engine used by tito, when building the rpm:
File "/usr/lib64/python2.7/site-packages/Cheetah/Compiler.py", line 1711, in `__init__`
source = unicode(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8104: ordinal not in range(128)
> [M] Remove non-ASCII character that breaks tito rpm build

- server/src/main/java/org/candlepin/async/impl/ActiveMQSessionFactory.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/ActiveMQStatusMonitor.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisContextListener.java
- server/src/main/resources/broker.xml
- Added support for the using the ActiveMQJAASSecurityManager when
creating the embedded ActiveMQ broker
- Added new configurations for modifying which entries are used
in a JAAS config file
- Updated the broker.xml with details about using external
connections to the embedded Artemis instance
> [M] Added support for JAAS in the embedded ActiveMQ broker (ENT-2154)

- server/spec/oauth_spec.rb
oauth spec tests are failing with the newly created vagrant box (destroy and up).
As per my investigation, either we need to pass only #{uri} or URL object
instead of #{site}#{uri} in Net::HTTP::Get.new.
Note: This is a cherry-pick from master
> [2.9] Fix oauth spec test

- server/spec/consumer_resource_spec.rb
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
Fixes - 
- Removed Pool validation on Consumer Existing SLA from rules.js
- SLA is only going to be used to prioritize/de-prioritize pools.
PS: Will raise a PR against `candlepin-2.6-HOTIFX` when this is reviewed.
> Bug 1751848 Stopped checking & consider pools irrespective of Consumer Entitlement SLA for auto attach. (ENT-2278)

- server/spec/consumer_resource_spec.rb
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
Fixes :
- Removed Pool validation on Consumer Existing SLA from rules.js
- SLA is only going to be used to prioritize/de-prioritize pools.
(cherry picked from commit 442877f10a7e9f10c3ad5aac873bb8d4e60e03c6)
> 1740346: Stopped checking & consider pools irrespective of Consumer Entitlement SLA for auto attach. (ENT-2278) (2.6-HOTFIX)

- api/pom.xml
- build.gradle
- checks/pom.xml
- common/pom.xml
- server/pom.xml
- server/src/main/resources/broker.xml
Upgraded Artemis to 2.12.0, primarily to address a security issue in one of its dependencies (netty), as this was easier than attempting to fix the transitive dependency on netty itself.
The upgrade can be verified by running the following two commands:
```./gradlew clean assemble; unzip -l server/build/libs/*.war | grep netty```
```./gradlew pom; mvn package; unzip -l server/target/candlepin-*.war | grep netty```
Both may take a bit to run, but the output should show the netty jars included in the war files built by both gradle and maven, and both should include only netty jars with a version greater than or equal to 4.1.46 (actual version was 4.1.48 in my testing).
> [M] Bumped Artemis version from 2.10.1 to 2.12.0 (ENT-2321)

- server/spec/consumer_resource_dev_spec.rb
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/controller/refresher/RefreshResult.java
- server/src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/controller/refresher/RefreshWorkerVersioningTest.java
- Added versioning tests for the full RefreshWorker execute
code path
- Removed ContentManager.importContent, as it is entirely
obsoleted by the RefreshWorker framework
- Deprecated the ProductManager and ContentManager classes
as a whole
> [F] Removed unnecessary code and added missing refresh tests (ENT-2207)

- server/client/ruby/cpc
- The cpc utility now catches HTTP errors originating from the
targeted request and will print the error code, friendly name,
and server response rather than dumping a stack trace
> [M] Added handling of HTTP errors to the cpc utility

- server/src/main/java/org/candlepin/model/CloudProfileFacts.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/GuestId.java
- server/src/main/resources/db/changelog/20200430172317-add-column-rh-cloud-profile-modified.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/model/ConsumerTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/HypervisorCloudProfileTest.java
- Added `rh_cloud_profile_modified` column in consumer
- Updated the ConsumerResource, HypervisorResource and HypervisorUpdateAction
to add modified timestamp on certain conditions
- Added Enum for specific facts
- Test suites added for the respective changes
> ENT-2316: Introduce Swatch Profile Timestamp

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- This resolves a scenario where after a virt-who check-in that resulted in a
new consumer creation, that same consumer (using username/password)
would try to register without specifying an owner key, and fail with a
duplicate hypervisor key error because we would attempt to create another
consumer.
- Now, during registration, first resolve the owner (even if no key was
specified), and then check if we have an existing hypervisor record for
this user, instead of blindly creating a new consumer record.
> [M] 1815172: Upon registration, first resolve owner; ENT-2246

- common/src/main/java/org/candlepin/common/util/JaxRsExceptionResponseBuilder.java
- common/src/test/java/org/candlepin/common/util/JaxRsExceptionResponseBuilderTest.java
Fixes 
- Resteasy 4.2.2 now throws `javax.ws.rs.NotFoundException` which needed to be mapped to BAD_REQUEST via candlepin NotFoundExceptionMapper.
> 1836988: Fix for datetime parsing error with bad TZ offset (ENT-2379)

- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- Instead of only users with Owner-wide access, now allow users
with Owner-Pool access to fetch Owner-syspurpose attributes
> [M] 1834372: Adjust owner syspurpose user access; ENT-2372

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- Fixed an issue during entitlement deletion that could cause a
query to be generated that attempts to use more parameters than
the backend database supports
- Flagged the bulkSQLDelete method as deprecated, as it lacks
protection for the database parameter limit
> [M] 1840850: Fixed parameter overflow in bulk entitlement deletion (ENT-2437)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- Fixed an issue during entitlement deletion that could cause a
query to be generated that attempts to use more parameters than
the backend database supports
- Flagged the bulkSQLDelete method as deprecated, as it lacks
protection for the database parameter limit
> [2.9] 1840823: Fixed parameter overflow in bulk entitlement deletion (ENT-2437)

- server/src/main/resources/broker.xml
- Currently, when we remove an artemis queue from broker.xml and
redeploy/restart candlepin, the queue is not actually removed
from the artemis broker by default. This has caused a problem
for all Satellite customers that upgraded to 6.6+ from earlier
versions, since that is the version that the DatabaseListener
queue and DatabaseListener.java listener were removed, because
the queue is still there, receiving messages, but the listener
is not there to consume them. So the queue gets filled up,
causing all it's messages to get paged to the journal.
Once the journal gets large enough, and on Candlepin startup,
artemis tries to read all these messages from the journal into
memory, causing extremely high CPU/memory usage, hanging
indefinitely, and bringing the machine on it's knees.
- This …
> [M] 1667952: Delete removed Artemis queues on broker.xml reload; ENT-2465

- server/src/main/resources/broker.xml
- Currently, when we remove an artemis queue from broker.xml and
redeploy/restart candlepin, the queue is not actually removed
from the artemis broker by default. This has caused a problem
for all Satellite customers that upgraded to 6.6+ from earlier
versions, since that is the version that the DatabaseListener
queue and DatabaseListener.java listener were removed, because
the queue is still there, receiving messages, but the listener
is not there to consume them. So the queue gets filled up,
causing all it's messages to get paged to the journal.
Once the journal gets large enough, and on Candlepin startup,
artemis tries to read all these messages from the journal into
memory, causing extremely high CPU/memory usage, hanging
indefinitely, and bringing the machine on it's knees.
- This …
> [2.6] 1842936: Delete removed Artemis queues on broker.xml reload; ENT-2465

- server/src/main/resources/broker.xml
- Currently, when we remove an artemis queue from broker.xml and
redeploy/restart candlepin, the queue is not actually removed
from the artemis broker by default. This has caused a problem
for all Satellite customers that upgraded to 6.6+ from earlier
versions, since that is the version that the DatabaseListener
queue and DatabaseListener.java listener were removed, because
the queue is still there, receiving messages, but the listener
is not there to consume them. So the queue gets filled up,
causing all it's messages to get paged to the journal.
Once the journal gets large enough, and on Candlepin startup,
artemis tries to read all these messages from the journal into
memory, causing extremely high CPU/memory usage, hanging
indefinitely, and bringing the machine on it's knees.
- This …
> [2.9] 1842933: Delete removed Artemis queues on broker.xml reload; ENT-2465

- server/client/ruby/candlepin_api.rb
- server/spec/job_status_spec.rb
- server/src/main/java/org/candlepin/model/AsyncJobStatusCurator.java
- server/src/main/java/org/candlepin/model/InvalidOrderKeyException.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/test/java/org/candlepin/model/AsyncJobStatusCuratorTest.java
- server/src/test/java/org/candlepin/resource/JobResourceTest.java
- The JobResource.listJobStatuses endpoint now supports paging the
results if specified by the caller
> [M] Added paging functionality to the JobResource.listJobStatuses endpoint (ENT-2527)

- server/src/main/java/org/candlepin/async/JobManager.java
- JobManager.queueJob has been given the @Transactional annotation
to ensure it is performed within the context of a transaction. This
should help avoid a race condition that can occur when queueing jobs
from outside a transaction which allowed messages to be dispatched
before the database could be updated completely
> [M] JobManager.queueJob is now always executed in a transactional context (ENT-2571)

- server/src/main/resources/logback.xml
- The SyslogAppender configuration is commented on
because it is opening a random UDP port to send messages
to the Syslog server.
Candlepin is sending messages to the Syslog server.
But the Syslog server is not configured to listen to the messages.
Hence this part of the code is commented for now.
> [2.6] ENT-2376: Find out why Tomcat binds to a udp6 port

- server/src/main/resources/logback.xml
- The SyslogAppender configuration is commented on
because it is opening a random UDP port to send messages
to the Syslog server.
Candlepin is sending messages to the Syslog server.
But the Syslog server is not configured to listen to the messages.
Hence this part of the code is commented.
> [2.9] ENT-2376: Find out why Tomcat binds to a udp6 port

- server/src/main/resources/logback.xml
- The SyslogAppender configuration is commented on
because it is opening a random UDP port to send messages
to the Syslog server.
Candlepin is sending messages to the Syslog server.
But the Syslog server is not configured to listen to the messages.
Hence this part of the code is commented.
> [M] ENT-2376: Find out why Tomcat binds to a udp6 port

- server/src/main/java/org/candlepin/async/tasks/HypervisorUpdateJob.java
- Restored a return statement which was erroneously removed during
the transition to the updated JobExecutionContext
> [M] Restored omitted return statement in the hypervisor update job (ENT-2577)

- docker/gating-test-images/cp-latest-stage/setup-env-extras.sh
- docker/gating-test-images/temp-base-cp/setup-env.sh
- docker/gating-test-images/temp-cp/docker-compose.yml
Changes/fixes -
- Updated PostgreSQL download URL
- Mount point fix for ```invalid mount config for type “bind”: bind source path does not exist``` during docker stack deploy. 
- Due to issues with latest version of tito v0.6.14, falling back to older version of tito v0.6.12 as a workaround. The issue has been reported - https://github.com/rpm-software-management/tito/issues/380
> ENT-2515: Fix jenkins docker build

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- When a job is put into the ABORTED state due to being blocked
by existing, active jobs, the job result will be updated with
an error message containing the blocking jobs
> [M] 1855847: Added blocking jobs to job result for ABORTED jobs (ENT-2606)

- server/src/main/java/org/candlepin/resource/ActivationKeyResource.java
- server/src/main/java/org/candlepin/resource/CertificateSerialResource.java
- server/src/main/java/org/candlepin/resource/ContentOverrideResource.java
- server/src/main/java/org/candlepin/resource/DistributorVersionResource.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/resource/GuestIdResource.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/main/java/org/candlepin/resource/OwnerContentResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resource/RoleResource.java
- server/src/main/java/org/candlepin/resource/UserResource.java
- Mark endpoints that return CandlepinQuery<> or Stream<> as
returning a 'List', for accurate swagger UI representation.
- Update endpoint annotations with DTO instead of model entity
as their response types.
> [M] Update swagger annotations for accurate API docs

- server/src/main/resources/db/changelog/20200715155048-add-ak-name-owner-constraint.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- Creating activation keys with the same name for the same owner
was already disallowed for postrgresql. This fix adds the same
constraint for mysql/mariadb.
> [M] Add constraint for unique activation key names

- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/test/java/org/candlepin/resource/JobResourceTest.java
- An HTTP 400 will be returned now when the GET /jobs request does
not specify paging arguments and it is about to return more than
10000 results, with an error message asking clients to use paging
instead.
> [M] 1855412: Add a result limit on the GET /jobs endpoint

- server/src/main/resources/db/changelog/20200717020619-add-job-arguments-constraints.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- Added the missing foreign key constraint to the cp_async_job_arguments
table on the job_id column
- Added an index on the cp_async_jobs.job_key column, as this is a very
common field to be used in lookups
- Added a MySQL-/MariaDB-specific index on the value column of the
cp_async_job_arguments table to address a performance issue unique
to the InnoDB engine when performing certain argument-centric queries
> [M] Added missing constraints and indexes to the job tables (ENT-2646)

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- The JobManager will now properly parse Quartz configuration from
candlepin.conf and reinitialize the Quartz scheduler factory
with the settings
> [M] 1859693: JobManager now loads Quartz config from candlepin.conf (ENT-2652)

- server/src/main/resources/rules/rules.js
ExpiredPoolsCleanupJob runs into race condition when multiple instances of this job is executed in parallel, resulting in concurrent modification & locking exceptions since jobs compete to delete pools in parallel. This should resolve once we have job scheduling synchronization in place.
Changes 
- Added a null check in rules.js to guard against TypeError exceptions.
> Bug 1858320: Expired Pools Cleanup Job - EcmaError: TypeError: Cannot read property "length" from null (ENT-2647)

- build.gradle
- buildSrc/src/main/java/org/candlepin/gradle/SpecVersion.java
Also simplifies the SpecVersion plugin by hard coding
the path to the candlepin spec file.
> Move version specification to the root build.gradle

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/tasks/JobCleaner.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/java/org/candlepin/model/AsyncJobStatusCurator.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/async/tasks/JobCleanerTest.java
- server/src/test/java/org/candlepin/model/AsyncJobStatusCuratorTest.java
- JobCleaner will now abort non-terminal, non-running jobs older
than three days (by default; configurable)
- JobCleaner will now abort running jobs older than two days
(by default; configurable)
- JobManager will now attempt to "rewind" the job state for
abandoned jobs during startup, where an "abandoned" job is
defined as one in the RUNNING state with the same executor
as the node which is performing the check
> [M] 1854221: Added additional job cleanup to JobManager and JobCleaner (ENT-2632, ENT-2630, ENT-2586)

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/messaging/CPMContextListener.java
- server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisContextListener.java
- server/src/main/java/org/candlepin/messaging/impl/noop/NoopContextListener.java
Now, when tomcat is shut down gracefully:
- First wait for Artemis client threads to finish before
closing the sessions, to make sure that commits happen
instead of potentially finishing a job and the broker
not getting a commit back.
- Don't use ActiveMQClient.clearThreadPools() to quiesce
the threads, because it:
* Waits only 10 seconds for jobs to finish before force
shutting them down.
* Uses ExecutorService.shutdownNow() which will interrupt
threads, causing an InterruptedException and not wait for
the jobs to finish.
- Use ExecutorService.shutdown() which will gracefully wait
for the threads to finish their work.
- Introduce new config "candlepin.async.thread.shutdown.timeout"
to specify how long (in seconds) to wait for job threads to
finish before forcefully shutting them down.
> [M] 1854221: Graceful shutdown of Artemis job threads; ENT-2586

- server/bin/artemis/configure-artemis.py
- server/conf/candlepin.conf.template
- server/src/main/java/org/candlepin/async/impl/ActiveMQSessionFactory.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/ActiveMQStatusMonitor.java
- Don't build Artemis client connection URLs using individual
properties for keystore/truststore and their passwords. Instead
use only candlepin.audit.hornetq.broker_url to specify the full
URL with query parameters.
- Drop the following properties:
* candlepin.audit.hornetq.keystore
* candlepin.audit.hornetq.keystore_password
* candlepin.audit.hornetq.truststore
* candlepin.audit.hornetq.truststore_password
- Alter our dev external artemis setup script (deploy -ba)
to download and setup Artemis 2.12.0 instead of 2.4.0, and also
to use port 61613 instead of 61617, since that is what Katello
has chosen to use. Also make sure that it doesn't error out
when run consecutive times.
> [M] Remove redundant Artemis connection properties; ENT-2325

- server/src/main/java/org/candlepin/async/JobMessageDispatcher.java
- server/src/test/java/org/candlepin/async/JobMessageDispatcherTest.java
- Fixed a race condition with messaging session committal that could
occur if two threads queue a job at the same time: the first thread
to complete its database transaction would commit the messaging
session shared by both, causing both job messages to be sent and
potentially picked up before the second thread's database session
had finished persisting the job status
> [M] Fixed a race condition with messaging session committal in the job system (ENT-2679)

- server/src/main/java/org/candlepin/async/JobMessageReceiver.java
- Problem: When an externally deployed Artemis broker goes down,
trying to stop the job-related Artemis client sessions
results in one of the following errors
* AMQ219019: Session is closed
* AMQ219016: Connection failure detected. Unblocking a blocking call that will never get a response
* AMQ219014: Timed out after waiting 30,000 ms for response when sending packet 68
with the JobManager in a bad state, and the sessions
never recreated when the broker goes up again.
- Solution: close the sessions instead of stopping them.
> [M] 1861739: Close sessions when external Artemis goes down; ENT-2704

- docker/candlepin-base/cp-test
- The project directory path is set to the server package.
This leads to execute the test only from the server package.
Hence added the path of commons package to execute
the test of commons.
> ENT-2703: Jenkins isn't running unit tests of common package

- common/src/test/java/org/candlepin/common/resteasy/filter/LinkHeaderResponseFilterTest.java
- Appended the query params in URL
> Fixing JUnit tests for link headers with params.

- server/spec/content_access_spec.rb
- server/spec/unpack.rb
- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/java/org/candlepin/util/X509Util.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- Certificates generated for Simple Content Access (SCA) will
use a placeholder value for the ENTITLEMENT_DATA certificate
extension when generated from a Candlepin instance not running
in standalone mode
- Content prefixes are no longer generated while Candlepin is not
running in standalone mode
> [M] 1866525: Updated SCA certificate content prefixes and paths (ENT-2717)

- server/client/ruby/candlepin_api.rb
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
- Clients registering with activation keys to organizations using
simple content access (SCA) mode will no longer fail if a key
cannot be fully entitled
> [M] 1591315: Registration with activation keys no longer fails in SCA mode (ENT-2747)

- common/src/main/java/org/candlepin/common/exceptions/ExceptionMessage.java
- common/src/main/java/org/candlepin/common/filter/LoggingFilter.java
- common/src/main/java/org/candlepin/common/logging/LoggingUtil.java
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/resteasy/filter/VerifyAuthorizationFilter.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- Added the LoggingUtil class in the common package to hold
constants for the various MDC keys used throughout Candlepin
- All instances of MDC.set and MDC.get now use the constants
defined in the LoggingUtil class rather than hard-coded
strings or locally-defined constants
> [M] Standardized string keys used for modifying the logging context

- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- Fixed a null pointer exception (NPE) that can occur during refresh
if an existing pool which does not define a derived product is
updated to have a derived product
> [M] 1871873: Fixed an NPE during refresh when adding new derived products (ENT-2785)

- server/bin/upstream_subscription_loader.rb
- server/client/ruby/hostedtest_api.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- Added the new upstream_subscription_loader.rb tool for assisting
in reproducing and debugging issues during refresh and other
adapter-backed operations reliant on upstream data
- Removed some unnecessary logging code in CandlepinPoolManager
- Added a missing existence check in HostedTestSubscriptionResource
> [M] Added the upstream_subscription_loader debugging tool

- build.gradle
- buildSrc/src/main/resources/templates/api.mustache
- buildSrc/src/main/resources/templates/formParams.mustache
- Add the default api/formParams mustache templates that ship
with openapi-generator for the JavaJaxRS/spec/ generator type.
- The openapi-generator type we use (pure JAX-RS spec) has no
knowledge of our JAX-RS implementation (RESTEasy) and by
default generates '@FormParam InputStream' as the input type
when declaring to consume 'multipart/form-data' for file
uploads.
This change alters the default templates used for code
generation to use RESTEasy's 'MultipartInput' utility class
instead of '@FormParam InputStream' for file uploads.
> [F] Use RESTEasy's MultipartInput for multipart/form-data

- server/src/main/resources/db/changelog/20200910161135-purge-stale-quartz-data.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- Add liquibase task to truncate all Quartz tables in order
to avoid stale data from the old Pinsetter job framework
causing startup errors when the new Artemis-based job
framework is initialized after an upgrade to Candlepin 3
> [M] 1877340: Remove stale Quartz data on upgrade; ENT-2859

- buildSrc/src/main/java/org/openapitools/codegen/DefaultCodegen.java
'An unexpected exception has occurred' and status code 200
is added to API endpoints.
- Overridden status code to 500 as default response code.
Initially, it is set as 0 but fails with regular expression
in openapi schema json. It needs 3 occurrences of a number.
Also, it cannot be set a "default" string because the ApiResponse
class has an int type code. Hence keeping the default status code to 500.
> ENT-2794: @ApiResponse annotation with message

- server/client/ruby/candlepin_api.rb
- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Add back negation operator that was accidentally removed
which resulted in failure to register manifest consumer
when the provided content access mode was in fact allowed by
the owner.
> [M] 1879494: Allow consumer registration with SCA mode; ENT-3062

- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- Fixed a null pointer exception (NPE) that can occur during refresh
if an existing pool which does not define a derived product is
updated to have a derived product
> [2.9] 1881181: Fixed an NPE during refresh when adding new derived products

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- In a clustered environment, if somehow a job that is
already in the RUNNING state would get picked up for
execution, we would update the executor field for that record
(before eventually failing), causing the original node that
previously executed it to never recover that job.
- This change makes it so that we error out early when trying to
execute a job that is in the RUNNING state, and don't end up
updating it's record.
- In the special case that the job is in the RUNNING state, but
was previously executed on the current node, we don't fail at
all, but move the job to QUEUED, so that it will be executed
as normal.
> [M] 1854221: Validate early if executing job in RUNNING state

- api/pom.xml
- build.gradle
- checks/pom.xml
- common/pom.xml
- common/src/test/java/org/candlepin/common/guice/HttpMethodMatcherTest.java
- docker/candlepin-base/cp-test
- docker/candlepin-base/setup-devel-env.sh
- pom.xml
- server/candlepin.spec.tmpl
- server/pom.xml
Changes 
- Dependencies upgraded to support Java 11
How to test/verify this PR locally ?
1. For Local Gradle build 
- Install Java-11
```java-11-openjdk-devel```
- Make it a default
```update-alternatives --config java```
- Run gradle build
2. For Vagrant (Dependent on https://github.com/candlepin/ansible-role-candlepin/pull/14)
Update [requirement.yml](https://github.com/candlepin/candlepin/blob/master/vagrant/requirements.yml) file to checkout the above PR's branch.
> ENT-1675: Upgrade candlepin to use Java 11

- api/pom.xml
- build.gradle
- checks/pom.xml
- common/pom.xml
- server/pom.xml
Apparently specifying "4.13" doesn't automatically pull the latest Z version as I had expected. Updated the version to be specific.
> [M] Updated JUnit version from 4.13 to 4.13.1

- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
Changes 
- Updated ContentAccessManager to only add content from active pools on the SCA certificate.
- Added Spec and unit test cases
> ENT-2806: Only add content from active pools on the SCA certificate

- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/resources/db/changelog/20201103112757-purge-current-sca-certs.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- Content paths in certificates for simple content access (SCA)
no longer encode the forward slash of any containing environment
name
> [3.1] 1893836: Fixed encoding of environment name in SCA certificates (ENT-3211)

- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/resources/db/changelog/20201103112757-purge-current-sca-certs.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- Content paths in certificates for simple content access (SCA)
no longer encode the forward slash of any containing environment
name
> [M] 1894035: Fixed encoding of environment name in SCA certificates (ENT-3211)

- rel-eng/releasers.conf
- server/mead.chain
- A new brew/mead target was added for explicitly
building with Java 11. We will target it from now on.
- Remove jdk 11 from the required packages, since it
is redundant now.
> Set Java 11 specific mead target

- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/healing_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
Changes/Fix 
- There was ambiguity in handling exception for conditions, where auto-attach is disabled for org & when org in SCA mode. This was leading to misleading exception messages.
- Added functional tests.
> 1884410: Fix for misleading exception message in auto-attach (ENT-3128)

- jenkins/Jenkinsfile
- jenkins/check_pr_branch.py
- jenkins/lint.sh
- jenkins/rspec-tests.sh
- jenkins/unit-tests.sh
This will run all the existing tests (with minimal changes to them) as part of a single Jenkins pipeline vs the many individual jobs we have today.  It will require changes to candlepin-jobs which can be worked on after https://github.com/candlepin/candlepin-jobs/pull/61 is merged.
> RHSMQE-2273: Adding Jenkins pipeline

- server/bin/org_migrator/cp_connectors.py
- server/bin/org_migrator/org_migrator.py
- server/bin/refresh_data_extractor.sh
- Added the --ignore_dupes flag on org_migrator, which, as the name
implies, instructs it to ignore duplicate entities during import
- Added the refresh data extractor tool, which will pull the raw
JSON out of a Candlepin.log-formatted text file and output it
for easy use with the upstream data injector tool
> [M] Updated organization migration tooling to allow multi-org imports

- server/candlepin.spec.tmpl
- server/code/setup/cpdb
- server/code/setup/cpsetup
- Update spec dependency to 'java-11', since 'java' is
used for the default in RHEL which is 8
- Set JAVA_HOME to 11 for liquibase migration call
- Set JAVA_HOME to 11 in tomcat.conf
> [M] Update rpm spec and cpsetup/cpdb for Java 11; ENT-3255

- docker/candlepin-base/cp-test
- Don't try to find out candlepin version through git tag
because we might be in a detached HEAD
> Figure out candlepin version through spec file

- common/src/main/java/org/candlepin/common/exceptions/NotImplementedException.java
- server/src/main/java/org/candlepin/auth/CloudRegistrationAuth.java
- server/src/main/java/org/candlepin/auth/KeycloakAuth.java
- server/src/main/java/org/candlepin/auth/permissions/OwnerPermission.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/dto/api/v1/CloudRegistrationDTO.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/guice/DefaultConfig.java
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/model/User.java
- server/src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- server/src/main/java/org/candlepin/resteasy/filter/AuthenticationFilter.java
- server/src/main/java/org/candlepin/service/CloudRegistrationAdapter.java
- server/src/main/java/org/candlepin/service/exception/CloudRegistrationAuthorizationException.java
- server/src/main/java/org/candlepin/service/exception/MalformedCloudRegistrationException.java
- server/src/main/java/org/candlepin/service/impl/DefaultCloudRegistrationAdapter.java
- server/src/main/java/org/candlepin/service/model/CloudRegistrationInfo.java
- server/src/test/java/org/candlepin/auth/CloudRegistrationAuthTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CloudRegistrationDTOTest.java
- server/src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- server/src/test/java/org/candlepin/resteasy/filter/AuthenticationFilterTest.java
- Added support for automated cloud registration via JWT tokens
- Added the CloudRegistrationAdapter and CloudRegistrationInfo
adapter and interface for allowing service adapters to implement
the organization resolution logic for cloud registration details
- Added new JWT configurations for controlling the issuer name and
TTL
- Updated the mutators in Owner to return itself for fluent-style
method chaining
- Updated KeycloakAuth to no longer end authentication on
unsupported auth types, or failed authentication in general
> [M] Added support for cloud registration (ENT-3213) (ENT-3214)

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
Since original bug was harder to reproduce locally, judging form the exception trace the crash happens around ```deleteJob()``` area.
This PR has minor update to efficiently unschedule (& delete) quartz jobs using Trigger-keys. Internally ```unscheduleJobs()``` is a bulk operation which faster & efficient. We can leverage this as all of our Quartz job are non-durable which means job gets automatically deleted from the scheduler once there are no longer any active triggers associated with it.
> 1884047: Unable to unschedule trigger while deleting job crash during startup (ENT-3129)

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- Fixed a bug that would cause job cleanup to match all jobs if
only non-terminal states were provided to the job cleanup
operation
> [M] 1905199: Fixed bug with state filtering validation during job cleanup (ENT-3330)

- server/src/main/resources/broker.xml
- Set the default-consumer-window-size setting to zero for the job
address in broker.xml to prevent a single consumer from grabbing
multiple job messages while other threads are waiting for work
> [M] Set the default consumer window size to zero in broker.xml (ENT-3066)

- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/Branding.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Branding.equals no longer checks the product UUID reference
as part of the equality check
- Fixed a bug in the product and content version lookups that
would cause JDBC failures if too many versions were matched
or requested
> [M] Fixed hash collision resolution bug with branding (ENT-3304)

- docker/build-images
- docker/candlepin-base/cp-test
- Added the -R option to cp-test to trigger generation of test
repos during Candlepin deployment
- Added the -a option to cp-test to pass through any custom
argument to the Candlepin deploy script that is not otherwise
supported by cp-test
- Fixed an issue with build-images that would prevent it from
working properly on python 3
- Removed the -p option from cp-test for selecting which
subproject to build, as Candlepin no longer has subprojects
> [M] Added an option to cp-test for generating test repos on deploy (ENT-3088)

- docker/README.mkd
- docker/candlepin-base/setup-devel-env.sh
- docker/docker-compose-mysql.yml
- docker/docker-compose-postgres.yml
- docker/test
- Add packages required for the generation of test content & rpms
- Add flag for detached mode to the test script, which will run
containers detached from the docker/test script and will not
stop/remove them once it exits. It will also expose ports 8443,
8080 and 22 to the host machine
> ENT-3088: Fix container repo generation & add detached mode

- server/src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- Removed the unnecessary ordering and added the missing distinct
keyword to the product and content lookup by version queries
- Fixed a bug that was causing the orphan cleanup job to output
the product and content counts backward
> [M] Added missing query modifiers to the entity version lookup queries

- server/src/main/resources/broker.xml
- Increased the max-disk-usage Artemis setting from the default 90
to 99, to help avoid erroneously hitting the limit before
running out of disk space on larger, modern disks/drives
> [3.1] Increased the Artemis disk usage limit (ENT-3337)

- server/src/main/resources/broker.xml
- Increased the max-disk-usage Artemis setting from the default 90
to 99, to help avoid erroneously hitting the limit before
running out of disk space on larger, modern disks/drives
> [M] 1898605: Increased the Artemis disk usage limit (ENT-3337)

- docker/build-images
- docker/candlepin-base/Dockerfile
- docker/gating-test-images/build.sh
- docker/gating-test-images/postgres/Dockerfile
- docker/gating-test-images/temp-base-cp/Dockerfile
- Downloading images from the central docker registry may result in
"You have reached your pull rate limit" errors. This avoids the
issue by pulling our internal copies of centos/postgres
> Pull internal centos/postgres images to avoid rate limits

- jenkins/Jenkinsfile
- Added a library `fh-pipeline-library` for
trusting Jenkins pipeline.
> ENT-3390: Implement trusting of jenkins pipelines

- docker/docker-compose-build.yml
- docker/docker-compose-mysql.yml
- docker/docker-compose-postgres.yml
- Updated version of docker-compose files
> ENT-3406: Failing docker build: --build-arg is not supported

- docker/build-images
- docker/candlepin-base/Dockerfile.template
- docker/gating-test-images/build.sh
- docker/gating-test-images/postgres/Dockerfile.template
- docker/gating-test-images/temp-base-cp/Dockerfile.template
- Added sed commands to replace variable with path to docked registry
- These changes are temporary and should be reverted once we update docker or migrate to podman
> ENT-3406: Fix docked build - ARG not supported befor FROM

- server/spec/consumer_resource_activation_key_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/ConsumerActivationKeyDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/ConsumerDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/ConsumerTranslator.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerActivationKey.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/resources/db/changelog/20210118141207-create-consumer-activation-key-table.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/dto/api/v1/ConsumerDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ConsumerTranslatorTest.java
Changes made to show activation key name when consumer has been registered via activation key.
> ENT-2348: Show activation key name when consumer has been registered via activation key

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- Removed the providedProducts and derivedProvidedProduct pool
attributes
- Fixed a sporadic unit test failure in the hypervisor update job
test suite
> [F] Removed Pool.providedProducts and Pool.derivedProvidedProducts (ENT-1832)

- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
- server/src/test/java/org/candlepin/policy/js/pool/PoolHelperTest.java
- Fix a refresh issue, where virt_limit is removed from a
master pool, but the corresponding sub pool is not deleted
> [M] Delete sub pool when virt_limit removed

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- Updated the entitlement curator and pool curator to no longer
reference the cp_pool.provided_products column, or the
cp2_pool_provided_products or cp2_pool_derprov_products tables
> [F] Updated queries to remove references to removed pool attributes (ENT-1837)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/controller/Refresher.java
- server/src/main/java/org/candlepin/model/EntitlementCertificateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorFilterTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/sync/ImporterTest.java
- Fix too many params issue in manifest import
- Replace batch delete of entitlements with batch delete by ids
- Refactor updatePoolsFromStack to avoid calling deletePools n times
- Some cleanup as I went through the code (replace finally with try with resources, remove redundant type params, etc..)
> ENT-3286: Manifest delete takes 24 hours or more in large environment (60k consumers in owner)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
- Fix too many params issue in manifest import
- Refactor updatePoolsFromStack to avoid calling deletePools n times
> [3.1]ENT-3286: Manifest delete takes 24 hours or more in large environment (60k consumers in owner)

- server/src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/test/java/org/candlepin/async/tasks/OrphanCleanupJobTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- OrphanCleanupJob will now avoid removing orphaned products which are
still referenced by other products
- Fixed a null pointer exception that could occur in OwnerProductCurator
if creating owner-product links with a null owner or product collection
> [F] Updated the OrphanCleanupJob to be aware of product to product references (ENT-2011)

- server/bin/import_test_data.rb
- server/bin/org_migrator/org_migrator.py
- Test data importer now properly adds provided and derived products
to the product, rather than the pools
- Updated the org migrator to be aware of the product provided
products, and no longer manage the provided products tables
associated with pools
> [F] Updated tooling to use new tables and APIs for children products (ENT-3429)

- server/src/main/java/org/candlepin/model/Content.java
- server/src/test/java/org/candlepin/model/ContentTest.java
- Fixed a bug that could cause equality checks for two Content
instances to fail if one had empty strings for certain fields
and the other had nulls
> [M] Fixed a bug with Content equality checks for fields with empty strings

- server/src/main/java/org/candlepin/model/ConsumerActivationKey.java
- server/src/main/resources/db/changelog/20210118141207-create-consumer-activation-key-table.xml
- Rename table cp2_consumer_activation_key to cp_consumer_activation_key
- Update activation_key_name to VARCHAR(255)
- Update foreign and primary key references
> 1920158: ERROR: value too long for type character varying(32)

- server/client/ruby/candlepin_api.rb
- server/spec/filter_response_spec.rb
- server/src/main/java/org/candlepin/guice/CandlepinFilterModule.java
- server/src/main/java/org/candlepin/servlet/filter/CandlepinContentTypeFilter.java
- Added a CandlepinContentTypeFilter. It will execute before
each request to validate the content-type.
- Added the RSpec test.
> 1919458: invalid Content-Type yields 500 (ENT-3439)

- server/build.gradle
- server/pom.xml
Changes/Fix -
Used the ```unpack``` goal of maven dependency plugin to unpack the desired classes to a folder ```target/openapi_generated_classes``` and allowing maven war plugin to includes this folder during packaging.
> ENT-3519: Fix to include auto-generated classes in WAR/RPM file

- server/candlepin.spec.tmpl
- Switch filedigest algorithm to sha-256
> [3.1]1929681: Candlepin will not install in FIPS mode

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
(This fixes both satellite bzs, related to manifest import/delete: 1840803 & 1840805)
- Fix too many params issue in manifest import
- Refactor updatePoolsFromStack to avoid calling deletePools n times
> [2.9] 1894455: (second part of the fix): Manifest delete takes too long

- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/content_access_spec.rb
- server/spec/healing_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
via Anaconda, the user is presented with
a spurious error message if their Organization
has simple content access (SCA) enabled.
- Updated the code to ignore the exception thrown
when owner has content mode settings enabled.
> 1928072: When registering a system to RHSM (ENT-3549)

- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceDisableStatusTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- Fixed several tests which had hard-coded end dates for pools
which have since expired. The new dates are now dynamically
generated such that they are always in the future.
> [3.1] Fixed some hard-coded end dates in unit tests (ENT-3621)

- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/content_access_spec.rb
- server/spec/healing_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- No-op and return HTTP status 200 when auto-attaching on SCA mode
> [3.1] 1928072: On SCA mode, stop throwing an error during auto-attach (ENT-3549)

- docker/candlepin-base/cp-test
- docker/candlepin-base/setup-devel-env.sh
- jenkins/Jenkinsfile
- server/bin/generate_custom_yaml.py
- server/conf/candlepin.conf.template
- Added a `generate_custom_yaml.py` to generate a 
custom YAML file to override the `candlepin.auth.cloud.enable` property
in `candlepin.conf`.
This is executed only on Jenkins for hosted mode.
> ENT-3446: Make Jenkins run cloud auth spec

- server/spec/one_sub_pool_per_stack_spec.rb
- server/src/main/java/org/candlepin/bind/PostBindBonusPoolsOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- Fixed a severe issue that was causing all derived pools sharing
a stacking ID to be removed when an entitlement for any of the pools
was revoked
- Rewrote the PoolCurator.getSubPoolsByStackIds to no longer use
deprecated Hibernate criteria queries
> [3.2] 1937931: Fixed stacked entitlement recovation deleting unrelated pools (ENT-3632)

- server/spec/one_sub_pool_per_stack_spec.rb
- server/src/main/java/org/candlepin/bind/PostBindBonusPoolsOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- Fixed a severe issue that was causing all derived pools sharing
a stacking ID to be removed when an entitlement for any of the pools
was revoked
- Rewrote the PoolCurator.getSubPoolsByStackIds to no longer use
deprecated Hibernate criteria queries
> [M] 1936505: Fixed stacked entitlement recovation deleting unrelated pools (ENT-3632)

- server/spec/one_sub_pool_per_stack_spec.rb
- server/src/main/java/org/candlepin/bind/PostBindBonusPoolsOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- Fixed a severe issue that was causing all derived pools sharing
a stacking ID to be removed when an entitlement for any of the pools
was revoked
- Rewrote the PoolCurator.getSubPoolsByStackIds to no longer use
deprecated Hibernate criteria queries
> [2.9] 1937692: Fixed stacked entitlement recovation deleting unrelated pools (ENT-3632)

- server/spec/one_sub_pool_per_stack_spec.rb
- server/src/main/java/org/candlepin/bind/PostBindBonusPoolsOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- Fixed a severe issue that was causing all derived pools sharing
a stacking ID to be removed when an entitlement for any of the pools
was revoked
- Rewrote the PoolCurator.getSubPoolsByStackIds to no longer use
deprecated Hibernate criteria queries
> [3.1] 1937691: Fixed stacked entitlement recovation deleting unrelated pools (ENT-3632)

- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/consumer_resource_spec.rb
- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Added more spec tests around SCA mode.
> On SCA mode, stop throwing an error during dry-run auto-attach

- server/src/main/resources/db/changelog/20210317160453-drop_pool_provided_product_fks.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- Removed the foreign key constraints from cp2_pool_provided_products
and cp2_pool_derprov_products, as these tables have been obsoleted
and existing data in them could prevent pools or products from
being deleted properly.
> [M] Removed foreign key constraints from obsolete pool tables (ENT-3668)

- server/src/main/java/org/candlepin/policy/js/compliance/hash/HashableStringGenerators.java
- server/src/test/java/org/candlepin/policy/js/compliance/hash/ComplianceStatusHasherTest.java
Issue - 
Consumer create API called with null facts, results in NPE for **all** consumer types (other than ```candlepin```). 
Additional Info - 
We don't calculate the compliance hashes for consumer(while creating consumers) with consumer type ```candlepin```. There is data corruption on stage ENV, where ```isManifest``` flag is set to ```false``` for consumer type ```candlepin``` resulting in forced calculation of hash leading to NPE. 
Changes - 
Defensively added a null check for consumer facts while calculating compliance hashes.
> 1886556: Fixed NPE originating from consumer create API when facts are null

- server/bin/gen_fake_report.py
Changes - 
Updated virt-who report generator testing script.
```"virtWhoType":"libvirt"``` & ```"hypervisor.type":"QEMU"``` properties are kept as constants.
Additional Info -
1) Async format
```
./gen_fake_report.py --hypervisors 1 --guests 1 --report 1 --format async
```
```
{
"hypervisors":[
{
"hypervisorId":{
"hypervisorId":"a7c9cf7c-67cb-4b68-9553-a279262b5e34"
},
"name":"thinkpad-LA738B",
"guests":[
{
"guestId":"ec79c6ca-3146-47bb-8cb1-9fc7b9f11bbd",
"state":2,
"attributes":{
"virtWhoType":"libvirt",
"active":1
}
}
],
"facts":{
"cpu.cpu_socket(s)":3,
"hypervisor.type":"QEMU",
"dmi.system.uuid":"c7790a3a-43f7-41ca-9389-644915cc075d"
}
}
]
}
```
2) Sync format (Underlying API (POST /hypervisor) is now deprecated in master, but I believe it is still in use for older candlepin)
``` …
```
> ENT-2580: Updated virt-who report generator testing script

- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/content_access_spec.rb
- server/spec/healing_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- No-op and return HTTP status 200 when auto-attaching on SCA mode
Additional changes
- Returned Empty list in dryBind() of ConsumerResource, instead of
throwing exception.
- Used isContentAccessEnabled method, instead of
isUsingSimpleContentAccess
(cherry picked from commit be654c64b388311cc9d5ec2970e8d3e92031ba3e)
> [3.2] 1944558: On SCA mode, stop throwing an error during auto-attach (ENT-3705)

- server/spec/import_update_spec.rb
- The issue is in MySQL which does not store partial seconds.
This was already addressed in commit 82a4051. To resolve,
added `sleep 2` before the next export operation executes. 
This ensures there is a time difference between the exports.
> ENT-3491: Addressing sporadic spec test failure in import_update_spec.rb

- server/bin/test_data.json
Issue :
Incomplete test data for dev SKU product. Commit - https://github.com/candlepin/candlepin/pull/2918/commits/10eefcac2ca1c2aa3b9f306587cd7adfea74edc9 changed the working of dev pools which now consider provided products as well.
Changes : 
- Added provided product to ```dev-sku-product```
- Created another dev product with no provided product ```dev-sku-no-provided-product```
> 1932662: Fixed candlepin test data for dev-sku (ENT-3600)

- server/spec/import_update_spec.rb
- The issue is in MySQL which does not store partial seconds.
This was already addressed in commit 82a4051. To resolve,
added `sleep 2` before the next export operation executes.
This ensures there is a time difference between the exports.
- Cherry-picked commit e33a7b3 from master
> [3.2] ENT-3491: Addressing sporadic spec test failure in import_update_spec.rb

- server/spec/import_update_spec.rb
- The issue is in MySQL which does not store partial seconds.
This was already addressed in commit 82a4051. To resolve,
added `sleep 2` before the next export operation executes.
This ensures there is a time difference between the exports.
- Cherry-picked commit e33a7b3282cdcadd33a3c5f116beea7ad38d7a0d from master
> [3.1] ENT-3491: Addressing sporadic spec test failure in import_update_spec.rb

- server/bin/org_migrator/cp_connectors.py
- server/bin/org_migrator/org_migrator.py
- Fixed a bug that would trigger an extra exception if the DB
connector fails to establish a connection early
- Fixed the NameError that could occur when running on python3
when processing binary data
> [M] Fixed several Python2/3 compatibility issues in the org_migrator

- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerDBTest.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed a duplicate key error that could occur when regenerating
SCA certs for a consumer that already had an expired or outdated
certificate that was part of an environment
> [3.1] 1949698: Fix SCA cert regeneration for consumers in environments (ENT-3784)

- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerDBTest.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed a duplicate key error that could occur when regenerating
SCA certs for a consumer that already had an expired or outdated
certificate that was part of an environment
> [4.0] 1949980: Fix SCA cert regeneration for consumers in environments (ENT-3784)

- server/spec/content_access_spec.rb
- Test that when an SCA capable and enabled org has it's SCA
capability removed from the contentAccessModeList, it's mode
should be forcibly changed to the default (entitlement)
> Add spec test for removal of SCA capability

- server/spec/candlepin_scenarios.rb
- server/spec/consumer_resource_spec.rb
- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- During the creation of a manifest consumer, if no content access mode
is provided, a default value will be chosen by using the "best" mode
from the org's available modes: SCA if available, entitlement mode
otherwise
> [3.2] 1949122: Changed how content access mode is selected for new consumers (ENT-3755)

- Gemfile.lock
- api/pom.xml
- build.gradle
- common/pom.xml
- server/pom.xml
- Bumped commons-io to v2.7
- Bumped Ruby oauth to v0.5.5
> [M] Bumped version of commons-io and ruby oauth

- server/spec/candlepin_scenarios.rb
- server/spec/consumer_resource_spec.rb
- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- During the creation of a manifest consumer, if no content access mode
is provided, a default value will be chosen by using the "best" mode
from the org's available modes: SCA if available, entitlement mode
otherwise
> [M] 1949125: Changed how content access mode is validated for new consumers (ENT-3755)

- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
- Updated the system purpose compliance reasons to mark
to be translated. After `./gradlew gettext`, the `keys.pot`
file gets updated. These text will be available for translation.
- Cherry-picked from 450b84a9c659f64d6bb1053d299da164c3203f6a
> [3.1] ENT-3747: 1947367 - Missing Compliance/SyspurposeCompliance translations

- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
- Updated the system purpose compliance reasons to mark
to be translated. After `./gradlew gettext`, the `keys.pot`
file gets updated. These text will be available for translation.
- Cherry-picked from 450b84a9c659f64d6bb1053d299da164c3203f6a
> [3.2] ENT-3747: 1947368 - Missing Compliance/SyspurposeCompliance translations

- api/candlepin-api-spec.yaml
- server/client/ruby/candlepin_api.rb
- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- Removed the ability to perform eager certificate regeneration
during refresh when triggered from an API call. API-triggered
refresh will now always mark certificates for later regeneration
> [M] Removed eager certificate regeneration during API-triggered refresh (ENT-3117)

- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
Changes
- Fix to revoke SCA cert when client unregisters.
> ENT-3856: Fix to revoke SCA cert upon client unregistration

- buildSrc/src/main/groovy/Rspec.groovy
- docker/candlepin-base/cp-test
> [M] Print rspec results to file

- buildSrc/src/main/groovy/Rspec.groovy
- docker/candlepin-base/cp-test
> [4.0] Print rspec results to file

- buildSrc/src/main/groovy/Rspec.groovy
- docker/candlepin-base/cp-test
> [3.2] Print rspec results to file

- buildSrc/src/main/groovy/Rspec.groovy
- docker/candlepin-base/cp-test
> [2.9] Print rspec results to file

- buildSrc/src/main/groovy/Rspec.groovy
- docker/candlepin-base/cp-test
> [3.1] Print rspec results to file

- common/src/main/java/org/candlepin/common/config/PropertyConverter.java
- common/src/main/java/org/candlepin/common/util/Util.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/util/Arch.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- server/src/test/java/org/candlepin/policy/SystemPurposeComplianceRulesTest.java
- server/src/test/java/org/candlepin/util/UtilTest.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- Extracted utillity method Util.toList
- Reused toList for other places where we handled whitespace
- Updated rules to handle whitespace when splitting addons and roles
> ENT-3811: Trim whitespace in addons and roles

- server/spec/subscription_resource_spec.rb
- server/src/main/java/org/candlepin/model/dto/Subscription.java
- This was changed while moving derived product from pool to product feature.
Updated code to return the `Collections.emptySet()` instead of null.
- Added spec test around this to test the required o/p.
> [4.0] ENT-3911: 1964106: derivedProvidedProducts is now null where it was previously [] 

- server/spec/subscription_resource_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/PoolToSubscriptionTranslator.java
- In OpenAPI, autogenerated classes have collections initializes
to null by default. It is found in the regression that it affects
the Katello.
Updated the `PoolToSubscriptionTranslator` to populate the
`providedProducts` and `derivedProvidedProducts` with empty set.
And it will get replaced with the appropritate values later.
- Added spec test around this to test the required o/p.
> [M] ENT-3911: 1965208: derivedProvidedProducts is now null where it was previously []

- server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml
- Removed the subtask to preemptively remove a non-temporary temporary
table from the orphan pools purging task. The subtask was originally
intended to ensure the pool does not persist should the whole
changeset fail to run, but ended up causing problems in some
environments.
> [M] Removed semi-extraneous cleanup task from the purge orphan pools db task

- buildSrc/src/main/groovy/Gettext.groovy
Changes -
- Removed the ```-j``` aka ```--join-existing``` flag. This was relevant for older project structure where we have to join the results of ```gettext``` command from ```server``` & ```common``` sub-projects.    
- Removed obsolete reference to /common folder.
> Fix for Gettext plugin extension

- src/main/resources/db/changelog/20210412145432-drop_content_cache.xml
- The cp_cont_access_cert table no longer requires the content column
to be non-null to address a potential problem with the migration
of an already-populated table
> [M] Removed non-nullable restriction from the SCA cert cache table

- candlepin.spec.tmpl
- This fixes the following error thrown by the Cheetah template
engine used by tito, when building the rpm on RHEL7:
File "/usr/lib64/python2.7/site-packages/Cheetah/Compiler.py", line 1575, in __init__
source = unicode(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 15318: ordinal not in range(128)
> [M] ENT-3979: Remove non-ascii chars that break rpm build

- build.gradle
- pom.xml
Changes : 
Maven dependency check plugin tries to download NVDCVE metadata file, which fails when host is not reachable.
Additional configuration is added to ignore such failure without affecting the maven build.
> [M] Ignore Maven dependency-check failure on missing NVD file

- CONTRIBUTING.md
- build.gradle
- pom.xml
Changes -
Dependency check plugin rely on fetching the metadata from NVD (external network). Our MEAD build was failing as node don't have access to outside network. Therefore we removed the OWASP Dependency Check plugin from maven build & added it to gradle build. This way we have better control when to run dependency checks (& will not be the part of actual build).
> [M] Removed the OWASP Dependency Check plugin from maven build & added it to Gradle build.

- spec/owner_product_resource_spec.rb
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Fixed an internal server error that could occur when attempting to
delete a product, or remove it from an organization, that has been
associated with an activation key
> [M] Fixed an error when deleting products associated with activation keys (ENT-4002)

- docker/candlepin-base/setup-devel-env.sh
Changes to fix docker build -
- Replaced the unreachable keyserver URL from ```hkp://keys.gnupg.net``` to ```hkp://keyserver.ubuntu.com:80```
> Changed the key server URL to import the keys

- bin/deployment/bash_functions
- docker/mysql.cnf
- docker/test
- jenkins/Jenkinsfile
This is to investigate/fix the misbehavior of the spec test
in the environment created for #3001
- Added below options to get the isolation level
-N : Don't write column names in results.
-s : This option results in nontabular output
format and escaping of special characters.
- Updated the mysql.cnf file permission and
the file owner to MySQL user and group.
> Update mysql.cnf file owner to be readable in mariadb container

- buildSrc/build.gradle
Fixed
- Version conflict for Spock dependency. Spock is a transitive dependency, which resulted in version conflicts.
Ref - [Spock Groovy version compatibility](https://spockframework.org/spock/docs/2.0/known_issues.html)
> Fixed version conflicts for spock dependency

- server/spec/content_access_spec.rb
- server/spec/content_resource_spec.rb
- server/src/main/java/org/candlepin/util/X509Util.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- The fix applies to content for both SCA and Entilement certs
> [3.1] 1985360: Don't filter out content with no arch specified [ENT-4128]

- bin/bash_functions
- docker/mysql.cnf
- docker/test
- jenkins/Jenkinsfile
Cherry-picked the changes from cffcabc
This is to investigate/fix the misbehaviour of the spec test
in the environment created for #3001
- Added below options to get the isolation level
-N : Don't write column names in results.
-s : This option results in nontabular output
format and escaping of special characters.
- Updated the mysql.cnf file permission and
the file owner to mysql user and group.
> [3.1]Update mysql.cnf file owner to be readable in mariadb container

- bin/bash_functions
- docker/mysql.cnf
- docker/test
- jenkins/Jenkinsfile
Cherry-picked the changes from cffcabc
This is to investigate/fix the misbehaviour of the spec test
in the environment created for #3001
- Added below options to get the isolation level
-N : Don't write column names in results.
-s : This option results in nontabular output
format and escaping of special characters.
- Updated the mysql.cnf file permission and
the file owner to mysql user and group.
> [2.9]Update mysql.cnf file owner to be readable in mariadb container

- bin/bash_functions
- docker/mysql.cnf
- docker/test
- jenkins/Jenkinsfile
Cherry-picked the changes from cffcabca975e7b644d63f494e62a3e61e7348833
This is to investigate/fix the misbehavior of the spec test
in the environment created for #3001
- Added below options to get the isolation level
-N : Don't write column names in results.
-s : This option results in nontabular output
format and escaping of special characters.
- Updated the mysql.cnf file permission and
the file owner to mysql user and group.
> [4.0]Update mysql.cnf file owner to be readable in mariadb container

- spec/content_access_spec.rb
- spec/content_resource_spec.rb
- src/main/java/org/candlepin/util/X509Util.java
- src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- The fix applies to content for both SCA and Entilement certs
> [M] 1984984: Don't filter out content with no arch specified [ENT-4128]

- server/spec/content_access_spec.rb
- server/spec/content_resource_spec.rb
- server/src/main/java/org/candlepin/util/X509Util.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- The fix applies to content for both SCA and Entilement certs
> [4.0] 1985359: Don't filter out content with no arch specified [ENT-4128]

- docker/test
- Even though we do this cleanup in a Jenkins post script, it
is a good idea to also do it within the docker/test script
to perform the cleanup when one runs the script manually
> [M] Add back 'docker-compose down' to docker/test script

- server/spec/pool_unlimited_master_spec.rb
- server/spec/post_bind_bonus_pool_spec.rb
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
Changes :
- All unlimited pools are restricted to -1 quantity.
- Unmapped guest & Bonus pools specifically to have unlimited quantity in both cases: a) the master pool quantity is unlimited, b) virt_limit is unlimited.
> [4.0] 1989474: Fix for pool quantity calculations (ENT-3974)

- server/spec/pool_unlimited_master_spec.rb
- server/spec/post_bind_bonus_pool_spec.rb
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
Changes :
- All unlimited pools are restricted to -1 quantity.
- Unmapped guest & Bonus pools specifically to have unlimited quantity in both cases: a) the master pool quantity is unlimited, b) virt_limit is unlimited.
> [3.2] 1989541: Fix for pool quantity calculations (ENT-3974)

- src/main/resources/db/changelog/20201103112757-purge-current-sca-certs.xml
- Rollback the changes made for an author in this script.
Because a changeset is uniquely tagged by both an author
and an id attributes (author:id). It considers the changeset
as a new entry if it differs.
> [M] 1980370: Replace DELETE with TRUNCATE where possible [ENT-4065]

- src/main/java/org/candlepin/auth/CloudRegistrationAuth.java
- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/resteasy/filter/AuthenticationFilter.java
- src/test/java/org/candlepin/auth/CloudRegistrationAuthTest.java
- Added an additional check to the cloud registration resource
to prevent token generation when cloud registration is not enabled
- Added additional logging to the AuthenticationFilter to list the
auth providers used during a given request
- Added logic to consumer registration to avoid proceeding in cases
where no owner or principal information is available
> [M] Various minor improvements to the cloud registration flow (ENT-4188)

- build.gradle
- buildSrc/src/main/groovy/Msgfmt.groovy
The msgfmt custom task was updated to specify it's input & output files
so that the gradle cache can skip it if there are no updates to perform.
Previously the openapi generation tasks were using the same generation directory
which meant that every time one of the tasks ran it invalidated the cache entry
for the other. Using separate target directories allows gradle to properly track
whether the task needs to be re-run.
To test, if you run "gradle war" and especially "gradle war --build-cache" you will start to see tasks being skipped because they are already up to date & builds running considerably faster on each run. In addition you will only see the output from the openapi generation tasks the first time things are run. A gradle clean will still force a rebuild of everything.
> Update msgfmt task & openapi tasks to support cached input/output

- build.gradle
This change removes our use of the spring dependency management plugin.
Gradle now has full support of maven BOM files and can provide equivalent
capabilities by using a BOM to specify the version for groups of related
packages. The gradle BOM support also gives better support for specifying
constraints to update specific libraries to newer versions than those
proscribed by a BOM.
Where I could find a BOM it was included at the beginning of the dependencies block. For the libraries that did not, I specified the versions in-line. 
There were small number of jars that have been updated, added, and removed from the generated jar based on the changes. 
Updated: These are library updates that were specified by the BOM support which the spring-dependency plugin was not finding/updating for us …
> Remove spring dependency management in favor of gradle bom support

- build.gradle
I can't find any references to what is provided by this library in our code. Trying it through the test pipeline to see if anything breaks.
> Remove unused ldapjdk library

- build.gradle
- pom.xml
**Changes** :
- Instead to reverting back to use Spring dependency management plugin, we now manually handle versions via ext properties. Because of Gradle ```platform``` component, pom task was not able to infer the sub-dependency versions from BOM, as we need to explicitly mention the dependency version for pom auto generation task to work. 
- Removed the ```api``` project clause inside pom task in build.gradle file.
- Upgraded Artemis (#3111) & Keyclock (#3110) dependencies
**Note for reviewer** :
There is one change related to XML header for pom.xml, although was able to build war & deploy Candlepin. 
**Before** 
`<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" …
> [M] Gradle/Maven dependency fix

- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/java/org/candlepin/model/CertificateSerialCurator.java
- server/src/test/java/org/candlepin/model/CertificateSerialCuratorTest.java
- Fixed case where after updated certificate got a new serial the old serial was left
unrevoked.
> [3.1] 1958127: Serials left unrevoked after update

- src/main/java/org/candlepin/async/JobManager.java
- src/main/java/org/candlepin/async/JobMessageDispatcher.java
- src/main/java/org/candlepin/async/JobMessageReceiver.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/main/resources/broker.xml
- src/test/java/org/candlepin/async/JobManagerTest.java
- src/test/java/org/candlepin/async/JobMessageDispatcherTest.java
- src/test/java/org/candlepin/async/JobMessageReceiverTest.java
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- Updated the configuration behind job scheduling and job execution
to separate the two functions entirely and avoid configuration
difficulties associated with the two areas
- Jobs can no longer be disabled
- Removed the job blacklist, whitelist and enabled configurations
- Added a new special value for specifying a job should only run on
a manual schedule: "manual"
- JobManager will now throw an exception if the job scheduler cannot
be updated or configured as expected during startup
- Added new configurations for controlling job message flow:
candlepin.async.dispatch_address, candlepin.async.receive_address,
and candlepin.async.receive_filter
- Updated the packaged broker configuration
> [M] 1981887: Updated and separated job scheduling and execution configuration (ENT-4253)

- spec/environment_spec.rb
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- Added a cleanup to bulk revoke identity and content access
certificates of the consumers deleted with the environment
> 1980404: No consumer deletion cleanup when deleting Environment

- src/main/java/org/candlepin/model/Product.java
- src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml
- src/main/resources/db/changelog/20210127105630-migrate-product-hierarchy.xml
- Updated the migration scripts for the product model changes
to correctly move provided and derived products from pools to
newly created products for the migration
- Product.equals now uses a transient collection of provided
product UUIDs when loaded from the database to avoid circular
references when a given set of products are loaded
> [M] Rewrote the migration script for the product model changes (ENT-4184)

- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml
- server/src/main/resources/db/changelog/20210127105630-migrate-product-hierarchy.xml
- Updated the migration scripts for the product model changes
to correctly move provided and derived products from pools to
newly created products for the migration
- Product.equals now uses a transient collection of provided
product UUIDs when loaded from the database to avoid circular
references when a given set of products are loaded
> [4.0] Rewrote the migration script for the product model changes (ENT-4184)

- server/src/main/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJob.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/test/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJobTest.java
- server/src/test/java/org/candlepin/model/OwnerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
Final query was exceeding the overall query parameter limit for /products/owners endpoint. Broke the query to avoid exceeding the limit for IN clause & overall query parameter limit.
Backport of (#3126)
> [3.2] 1990832: Fix to avoid exceeding the overall query parameter limit

- server/src/main/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJob.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/test/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJobTest.java
- server/src/test/java/org/candlepin/model/OwnerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
Final query was exceeding the overall query parameter limit for /products/owners endpoint. Broke the query to avoid exceeding the limit for IN clause & overall query parameter limit.
Backport (https://github.com/candlepin/candlepin/pull/3126)
> [4.0] 2008443: Fix to avoid exceeding the overall query parameter limit

- server/spec/owner_product_resource_spec.rb
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Fixed an internal server error that could occur when attempting to
delete a product, or remove it from an organization, that has been
associated with an activation key
> [4.0] Fixed an error when deleting products associated with activation keys (ENT-4436)

- Vagrantfile
This allows the ansible provisioner to use things like urllib and requests so it can install things.  There are other options like a full yum update to the image or turning off SSL checking at this stage (possible more info here https://access.redhat.com/articles/2039753#red-hat-enterprise-linux-7-resolution-4 ), but this seems the fastest and cleanest.
To test this: vagrant destroy; vagrant up  should now work
> updating ca-certs so the ansible provisioner can run

- api/pom.xml
- build.gradle
- checks/pom.xml
- common/pom.xml
- server/pom.xml
- Bump JUnit version to prevent JUnit vintage from failing to parse version of junit: 4.13.1
> [4.0] Update JUnit5 version to 5.7

- server/src/main/java/org/candlepin/model/ProductContent.java
- The @XmlTransient annotations have been restored in ProductContent
to avoid an infinite recursion that would otherwise occur during
testing
> [4.0] Reverted removal of XmlTransient tags in ProductContent

- spec/refresh_pools_spec.rb
- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/OwnerProduct.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductContent.java
- src/test/java/org/candlepin/model/ProductTest.java
- Fixed a bug in Product.equals and ProductContent.equals which
would fail to properly compare products when either had children
that did not yet have a UUID
- Updated how entity versioning is calculated and cached for both
products and content: the entity version will be retained until
any mutator which would affect a field that is used in the
version is called
- Product.equals and Content.equals now attempt to use the UUID
and entity versions to avoid checking individual fields wherever
possible
- Product.equals and ProductContent.equals will now perform
recursive calls to its children where necessary
- Product.setDerivedProduct, Product.addProvidedProduct, and
Product.setProvidedProducts now attempt to check for a cycle
in the product definitions and will throw an exception if
one is …
> [M] Addressed issues with Product.equals and immutable entity versioning (ENT-4464)

- CONTRIBUTING.md
- build.gradle
- docker/candlepin-base/cp-test
- jenkins/Jenkinsfile
- Sonarqube gradle task now depends on the test task.
- When sonarqube is run from within our test container,
fail-fast the unit tests to save cycles on Jenkins nodes.
- Run sonarqube stage in parallel with the rest of the
stages in Jenkins to avoid extending the overall
duration of the pipeline.
- Print location of JaCoCo code coverage report.
> [M] Upload code coverage report with sonarqube

- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestDataStore.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- Substantially reduced the number of times flush is called
during a refresh operation by removing the flush from the
iterative sections to the end of each block where possible
- Changed how subscription pools are fetched during refresh
to a single instance at the beginning of the operation,
rather than once for every pool during refresh
> [4.0] Optimized refresh to avoid slow, repetitive operations (ENT-4489)

- spec/refresh_pools_spec.rb
- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/hostedtest/HostedTestDataStore.java
- src/main/java/org/candlepin/model/PoolCurator.java
- src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- src/test/java/org/candlepin/controller/PoolManagerTest.java
- src/test/java/org/candlepin/model/PoolCuratorTest.java
- Substantially reduced the number of times flush is called
during a refresh operation by removing the flush from the
iterative sections to the end of each block where possible
- Changed how subscription pools are fetched during refresh
to a single instance at the beginning of the operation,
rather than once for every pool during refresh
- Fixed an issue with the hosted test adapter clearing a
subscription's product when no change was intended
- Added additional tests surrounding refresh and entitlement
generation
> [M] Optimized refresh to avoid slow, repetitive operations (ENT-4489)

- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Changed the versioned entity lookup for products and quantity
to use a correlated subquery rather than a join to avoid
table scans on the join tables
> [4.0] Optimized versioned entity lookup for products and content (ENT-4489)

- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Changed the versioned entity lookup for products and quantity
to use a correlated subquery rather than a join to avoid
table scans on the join tables
> [M] Optimized versioned entity lookup for products and content (ENT-4489)

- rel-eng/releasers.conf
- This avoids a bug in gettext, which has been fixed in RHEL9,
which resulted in no translation classes being compiled.
> [M] Use new maven mead target [ENT-4392]

- rel-eng/releasers.conf
- This avoids a bug in gettext, which has been fixed in RHEL9,
which resulted in no translation classes being compiled.
> [4.0] Use new maven mead target [ENT-4392]

- spec/identity_spec.rb
- src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
- src/test/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapterTest.java
This brings the identity certificate in line with what we are already doing in entitlement certificates
> Add the Owner key to the consumer identity certificate

- server/spec/identity_spec.rb
- server/src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
- server/src/test/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapterTest.java
This brings identity certificates in line with what we are already doing for entitlement/sca certificates. (Backporting https://github.com/candlepin/candlepin/pull/3165)
> [4.0] Add the Owner key to the consumer identity certificate

- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/controller/ContentAccessManager.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- server/src/test/java/org/candlepin/test/TestUtil.java
- Now we only wrap the SCA cert into a fresh ContentAccessCertificate
copy after the db changes are flushed (to make sure the 'updated'
date that is marked with @PreUpdate annotation has been changed) to
avoid sending a stale 'lastUpdated' date to the client.
- The date sent in the If-Modified-Since header does not have
millisecond accuracy, so make sure to round down the server-side
certificate dates we compare it with to the second.
> [4.0] 2023725: SCA 'lastUpdated' & If-Modified-Since date fixes [ENT-4428]

- spec/content_access_spec.rb
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/test/TestUtil.java
- Now we only wrap the SCA cert into a fresh ContentAccessCertificate
copy after the db changes are flushed (to make sure the 'updated'
date that is marked with @PreUpdate annotation has been changed) to
avoid sending a stale 'lastUpdated' date to the client.
- The date sent in the If-Modified-Since header does not have
millisecond accuracy, so make sure to round down the server-side
certificate dates we compare it with to the second.
> [M] 2010251: SCA 'lastUpdated' & If-Modified-Since date fixes [ENT-4428]

- config/candlepin/candlepin.conf.template
- docker/candlepin-base/cp-test
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/config/CandlepinCommonTestConfig.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- Do not allow registering or updating a consumer with environment
data when the environments resource is hidden.
- Do not hide the environments resource when autogenerating the
config file, to make sure environment spec test can run properly.
> [F] Disallow consumer environment data when resource hidden [ENT-4182]

- server/client/ruby/candlepin_api.rb
- server/src/main/java/org/candlepin/resteasy/DateFormatter.java
- server/src/test/java/org/candlepin/resteasy/DateFormatterTest.java
- Starting with Java 9, the CLDR is used as the default locale
provider, which has an effect on how java.text and java.time utils
format/parse certain date formats. Specifically, the format used
by the If-Modified-Since header value is affected when the server
is run with system locale set to some locales such as en_AU or
en_CA, which results in a parsing error to be thrown. Enforcing
the locale used when parsing dates to en_US solves this.
> [4.0] Enforce locale when parsing Date from String [ENT-4536]

- client/ruby/candlepin_api.rb
- src/main/java/org/candlepin/resteasy/converter/OffsetDateTimeParamConverterProvider.java
- src/test/java/org/candlepin/resteasy/converter/OffsetDateTimeParamConverterProviderTest.java
- Starting with Java 9, the CLDR is used as the default locale
provider, which has an effect on how java.text and java.time utils
format/parse certain date formats. Specifically, the format used
by the If-Modified-Since header value is affected when the server
is run with system locale set to some locales such as en_AU or
en_CA, which results in a parsing error to be thrown. Enforcing
the locale used when parsing dates to en_US solves this.
> [M] Enforce locale when parsing Date from String [ENT-4536]

- src/main/java/org/candlepin/model/Consumer.java
- src/main/resources/db/changelog/20211123093750-migrate-environment-column.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/ConsumerTest.java
- Migrate cp_consumer.environment_id to cp_consumer_environment table
- Delete cp_conusmer.environment_id column
- Remove redundant code from Consumer.setEnvironmentIds
> ENT-4183: DB Upgrade for environment data

- client/ruby/candlepin_api.rb
- spec/environment_spec.rb
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- src/main/java/org/candlepin/controller/util/ContentPrefix.java
- src/main/java/org/candlepin/controller/util/EntitlementContentPrefix.java
- src/main/java/org/candlepin/controller/util/PromotedContent.java
- src/main/java/org/candlepin/controller/util/ScaContentPrefix.java
- src/main/java/org/candlepin/model/UeberCertificateGenerator.java
- src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- src/main/java/org/candlepin/util/Util.java
- src/main/java/org/candlepin/util/X509ExtensionUtil.java
- src/main/java/org/candlepin/util/X509Util.java
- src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
- src/test/java/org/candlepin/controller/util/EntitlementContentPrefixTest.java
- src/test/java/org/candlepin/controller/util/PromotedContentTest.java
- src/test/java/org/candlepin/controller/util/ScaContentPrefixTest.java
- src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- src/test/java/org/candlepin/util/UtilTest.java
- src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- Generate entitlement cert using multiple environments
- Deduplicate promoted content
- Handle environment-specific content paths
Note: Due to the high amount of shared code I had to handle all content prefixes not just entitlement ones.
> ENT-3900: Add support for multi-env entitlement cert regeneration

- bin/scripts/upstream_subscription_injector.rb
- The upstream subscription injector no longer requires the
organization to be specified on the command line and will
now use the organization present in the subscription info
- The USI now supports gzipped subscription JSON files
- Added a flag to automatically create local organizations
in Candlepin during subscription injection
> [M] Improved upstream subscription injector usability

- spec/import_spec.rb
- src/main/java/org/candlepin/pki/impl/JSSPKIUtility.java
- Private keys will no longer be converted to PKCS1 when written
to PEM files
> [M] Removed PKCS1 conversion when writing PEM keys (ENT-4452)

- candlepin.spec.tmpl
- In recent Fedora releases, and also RHEL9, the hardlink command
has changed location (from /usr/sbin/ to /usr/bin/) and is
provided by a different package (from hardlink to util-linux,
to eventually util-linux-core). These spec changes fix building
the candlepin rpm with that regard.
> [M] Fix rpm build for Fedora 29 to 35

- server/src/test/java/org/candlepin/model/AsyncJobStatusCuratorTest.java
- When choosing a random set of job ids to validate operations on,
we sometimes got duplicates, which led to a discrepancy when
asserting (e.g. expecting 3 updates, but only 2 happened).
> [4.0] Fix flaky job tests

- src/test/java/org/candlepin/model/AsyncJobStatusCuratorTest.java
- When choosing a random set of job ids to validate operations on,
we sometimes got duplicates, which led to a discrepancy when
asserting (e.g. expecting 3 updates, but only 2 happened).
> [M] Fix flaky job tests

- bin/deployment/deploy
- build.gradle
- candlepin.spec.tmpl
- mead.chain
- pom.xml
- src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- Candlepin is already loading jss (both the .jar and the .so) as a
library from the file system when deployed in Tomcat.
For compilation purposes though a fixed jss jar was used as a
maven/gradle dependency in a fedorapeople repo. Also, for unit
testing, the .so was loaded on startup using a hack in Java code.
Now in gradle, load them both (.jar and .so) directly from
the file system for compilation/unit testing purposes, and in maven
use the jar (only) from the file system for compilation.
- Starting with Fedora 35 and RHEL9, the jss library has upgraded
to major version 5, and the file names have now changed from
'jss4.jar' to 'jss.jar', and from 'libjss4.so' to 'libjss.so'.
Now they are loaded regardless of their name.
> [M] ENT-3930: Compile against jss from the file system

- spec/content_versioning_spec.rb
- spec/product_versioning_spec.rb
- src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/SystemLock.java
- src/main/resources/db/changelog/20220117152105-add_system_lock_table.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- Added the cp_system_locks table to act as a basis for
a system-wide read/write locking system
- Added AbstractHibernateCurator.getSystemLock for obtaining
named locks backed by the database
- Removed the write locks on queries used by orphan entity
cleanup and various product and content versioning operations
- Added use of system locks during refresh, product or content
API endpoints, and the orphan entity cleanup job
- Updated the conflict spec test to ensure the orphan cleanup
job actually completes successfully
> [M] Updated locking model surrounding orphan entity cleanup

- server/spec/content_versioning_spec.rb
- server/spec/product_versioning_spec.rb
- server/src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/SystemLock.java
- server/src/main/resources/db/changelog/20220117152105-add_system_lock_table.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- Added the cp_system_locks table to act as a basis for
a system-wide read/write locking system
- Added AbstractHibernateCurator.getSystemLock for obtaining
named locks backed by the database
- Removed the write locks on queries used by orphan entity
cleanup and various product and content versioning operations
- Added use of system locks during refresh, product or content
API endpoints, and the orphan entity cleanup job
- Updated the conflict spec test to ensure the orphan cleanup
job actually completes successfully
> [4.0] Updated locking model surrounding orphan entity cleanup

- rel-eng/releasers.conf
- This avoids a bug in gettext, which has been fixed in RHEL9,
which resulted in no translation classes being compiled.
> [3.2] Use new maven mead target

- spec/content_access_spec.rb
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/util/ScaContainerContentPrefix.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/controller/util/ScaContainerContentPrefixTest.java
- Handle content from multiple environments in content access certs
- Remove OU from SCA DN
> ENT-3901: SCA cert regeneration for multi-environment consumers

- Vagrantfile
- bin/deployment/bash_functions
- bin/deployment/deploy
- vagrant/README.md
- vagrant/candlepin.yml
- vagrant/requirements.yml
- Updated the Vagrant files to support the forthcoming Candlepin
Ansible role for individual el7 and el8 support
- Updated bash_functions to support either the mysql or mariadb
connector jars (el7/el8 support)
- Improved Tomcat version detection logic in the deploy script
> [M] Updated Vagrantfile to support el8-ready Ansible role (ENT-4468)

- spec/conditional_content_spec.rb
- spec/hypervisor_check_in_spec.rb
- src/main/java/org/candlepin/model/EntitlementCurator.java
- src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
While generating entitlement certificates, products from existing entitlements on a consumer are included as entitled products, and not from new entitlements selected as a result of an auto-attach or bulk-pool attach.
This fix is to include products from new entitlements selected via auto-attach or bulk-pool attach operations as well.
> 1964379: Fix to include products from new entitlements selected via auto-attach or bulk-pool attach operations

- server/spec/conditional_content_spec.rb
- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
Fix -
While generating entitlement certificates, products from existing entitlements on a consumer are included as entitled products, and not from new entitlements selected as a result of an auto-attach or bulk-pool attach.
This fix is to include products from new entitlements selected via auto-attach or bulk-pool attach operations as well.
(cherry picked from commit 58fe40e2febaccfaf8b627d95df01ad666e74f6d)
> [4.0] 1964376: Fix to include products from new entitlements selected via auto-attach or bulk-pool attach operations

- jenkins/Jenkinsfile
- jenkins/check_pr_branch.py
- Recent changes to bugzilla require the use of API keys only
from client applications
> [M] Use bugzilla API key instead of username/password

- jenkins/Jenkinsfile
- jenkins/check_pr_branch.py
- Recent changes to bugzilla require the use of API keys only
from client applications
> [4.1] Use bugzilla API key instead of username/password

- docker/candlepin-base/cp-test
- jenkins/upload-on-sonarqube.sh
- Use the new sonarqube candlepin project key:
'chainsaw:candlepin-server'.
- Use the correct branch name variable for uploading a PR analysis
instead of the default master branch analysis.
> [4.1] Fix Sonarqube jenkins task; ENT-4754

- src/main/java/org/candlepin/async/JobManager.java
- src/test/java/org/candlepin/async/JobManagerTest.java
- JobManager.executeJob now properly handles Errors and will
cleanup and fail jobs when they occur
> [M] Improved error handling during async job execution (ENT-4636)

- Vagrantfile
- ansible/candlepin.yml
- Added Fedora 35 support in the Candlepin Vagrantfile
- Abstracted out Ansible provisioning logic in the Vagrantfile
- Improved tagging on the custom user role
> Added support for Fedora 35 to Vagrant

- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Split testSearchConsumersRequiresPagingForLargeResultSets test
into two tests to avoid an issue where the mocked object would
sometimes return the wrong value
> [M] Addressed inconsistent test failures in ConsumerResourceTest

- spec/content_access_spec.rb
- spec/refresh_pools_spec.rb
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/async/tasks/ActiveEntitlementJobTest.java
- src/test/java/org/candlepin/async/tasks/HealEntireOrgJobTest.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/controller/EntitlerTest.java
- src/test/java/org/candlepin/model/OwnerCuratorTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
- src/test/java/org/candlepin/resource/util/InstalledProductStatusCalculatorTest.java
Changed the default content access mode to ORG_ENVIRONMENT for newly created orgs.
> ENT-3756: Implementation of SCA-by-default for newly created Owners

- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Split paging test in owner resource test
- Clean ResteasyContext before paging tests
> Addressed inconsistent test failures

- bin/deployment/deploy
- bin/deployment/liquibase.sh
- bin/scripts/code/setup/cpdb
- build.gradle
- pom.xml
- src/main/java/org/candlepin/liquibase/LiquibaseCustomTaskWrapper.java
- Use the LiquibaseCommandLine class instead of the deprecated Main.
- Use dash-case cli arguments instead of deprecated camelCase.
- Apply workaround for a new liquibase bug.
> ENT-4804: Upgrade liquibase to 4.8.0

- docker/README.mkd
- docker/docker-compose-no-db.yml
- docker/docker-compose-postgres.yml
- docker/docker-compose-sonarqube.yml
- docker/test
- jenkins/candlepin-validate-text.sh
- jenkins/lint.sh
- jenkins/unit-tests.sh
- jenkins/upload-on-sonarqube.sh
- Add docker-compose option for only running the candlepin container
when there is no need for a db (e.g. when running unit tests,
checkstyle, translation validations), to avoid waisting resources.
- Move the requirement for a sonarqube certificate as docker secret
to it's own docker-compose file, so that the default/postgres
one can be run locally without it.
> [4.1] Separate docker-compose responsibilities

- docker/README.mkd
- docker/docker-compose-no-db.yml
- docker/docker-compose-postgres.yml
- docker/docker-compose-sonarqube.yml
- docker/test
- jenkins/candlepin-validate-text.sh
- jenkins/lint.sh
- jenkins/unit-tests.sh
- jenkins/upload-on-sonarqube.sh
- Add docker-compose option for only running the candlepin container
when there is no need for a db (e.g. when running unit tests,
checkstyle, translation validations), to avoid waisting resources.
- Move the requirement for a sonarqube certificate as docker secret
to it's own docker-compose file, so that the default/postgres
one can be run locally without it.
> [M] Separate docker-compose responsibilities

- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/model/Branding.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductContent.java
- src/main/resources/db/changelog/20220314130000-clear_product_entity_versions.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- src/test/java/org/candlepin/model/ProductTest.java
- Fixed a bug that could cause a versioning collision in some cases
- Added an additional exception when a version collision is detected
during product and content management
- Added method chaining to mutators in ProductContent and Branding
> [M] Fixed a potential collision with product entity versioning (ENT-4805)

- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/Branding.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductContent.java
- server/src/main/resources/db/changelog/20220314130000-clear_product_entity_versions.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/ContentManagerTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- Fixed a bug that could cause a versioning collision in some cases
- Added an additional exception when a version collision is detected
during product and content management
- Added method chaining to mutators in ProductContent and Branding
- Existing product entity versions will be cleared to rebuild database
and avoid collisions with existing versions
> [4.0] Fixed a potential collision with product entity versioning (ENT-4805)

- bin/deployment/artemis/configure-artemis.py
- build.gradle
- Update the external artemis deployment script to work on python3,
and to use the latest artemis version.
> [4.1] Upgrade artemis to 2.20.0

- spec/hypervisor_check_in_spec.rb
We were using the same hypervisor id across tests which probably led to colliding data.
I have run the individual spec test as well as the spec file hundreds of times but cannot reproduce the issue in the Jira ticket.
This is my best guess based on the testing code.
> Update hypervisor id creation to remove collisions

- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductContent.java
- src/main/java/org/candlepin/util/LongHashCodeBuilder.java
- src/main/resources/db/changelog/20220314130000-64bit_entity_versions.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- src/test/java/org/candlepin/model/ProductTest.java
- src/test/java/org/candlepin/util/LongHashCodeBuilderTest.java
- Entity versions on Product, ProductContent, and Content are now
64 bits instead of 32bits
- Rewrote the version calculation *again*, ensuring that even
null and empty collections are represented in the final version
hash
- The initial value and multipliers have been made unique between
all versioned entities
> [M] Changed entity versions to a 64bit value; ENT-4831

- docker/candlepin-base/cp-test
- The cp-test script has been updated to support running the
Java spec tests along with rspec when the spec tests are
invoked
> [M] Added support for the Java spec tests to cp-test (ENT-4620)

- server/src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- server/src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- server/src/main/java/org/candlepin/model/Content.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductContent.java
- server/src/main/java/org/candlepin/util/LongHashCodeBuilder.java
- server/src/main/resources/db/changelog/20220314130000-64bit_entity_versions.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- server/src/test/java/org/candlepin/util/LongHashCodeBuilderTest.java
- Entity versions on Product, ProductContent, and Content are now
64 bits instead of 32bits
- Rewrote the version calculation *again*, ensuring that even
null and empty collections are represented in the final version
hash
- The initial value and multipliers have been made unique between
all versioned entities
> [4.0] Changed entity versions to a 64bit value (ENT-4831)

- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductContent.java
- src/main/java/org/candlepin/util/LongHashCodeBuilder.java
- src/main/resources/db/changelog/20220314130000-64bit_entity_versions.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- src/test/java/org/candlepin/model/ProductTest.java
- src/test/java/org/candlepin/util/LongHashCodeBuilderTest.java
- Entity versions on Product, ProductContent, and Content are now
64 bits instead of 32bits
- Rewrote the version calculation *again*, ensuring that even
null and empty collections are represented in the final version
hash
- The initial value and multipliers have been made unique between
all versioned entities
> [4.1] Changed entity versions to a 64bit value (ENT-4831)

- bin/deployment/test_data_importer.py
- Marketing products tagged with the "skip_pools" attribute will
now be skipped during subscription/pool creation
> [M] Added support for skipping pool creation while processing test data (ENT-4849)

- bin/bash_functions
- buildSrc/src/main/groovy/Rspec.groovy
- docker/candlepin-base/cp-test
- docker/mysql.cnf
- docker/test
- jenkins/Jenkinsfile
- jenkins/check_pr_branch.py
- jenkins/cleanup.sh
Some explanation here: Satellite 6.9 is on 3.1.28, while candlepin-3.1-HOTFIX has too many unneeded commits (it is up to 3.1.31) that may destabilize it. Therefore we need a separate branch for 3.1 to be able to backport and release critical fixes only at this point (and to stop using candlepin-3.1-HOTFIX). This is what candlepin-3.1.28-4-HOTFIX will be.
This PR, is simply for only adding the needed infrastructure-related (jenkins/docker) commits to this branch, and to test that the pipeline works.
> [3.1] Add infrastructure related cherry-picks from candlepin-3.1-HOTFIX

- api/candlepin-api-spec.yaml
- spec/deleted_consumer_spec.rb
- src/main/java/org/candlepin/dto/api/v1/DeletedConsumerTranslator.java
- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/DeletedConsumer.java
- src/main/resources/db/changelog/20220329140000-add_consumer_name_to_cp_deleted_consumers.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/dto/api/v1/DeletedConsumerTranslatorTest.java
- src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- src/test/java/org/candlepin/model/DeletedConsumerCuratorTest.java
- src/test/java/org/candlepin/model/DeletedConsumerTest.java
We are wanting to add the consumer name to the cp_deleted_consumer table so that you get back more information than the uuid of the consumer when you use the deleted_consumers endpoint.
I included a screen shot and the steps of the workflow I used to test:
1. I registered using subscription-manager, and checked cp_consumer table to get uuid and name of the consumer.
2. I unregistered and checked the cp_deleted_consumers table and verified that the correct consumer name was inserted.
3. I then verified the correct deleted consumers  information was returned from the deleted_consumers endpoint.
> [M] Added consumer name to cp_deleted_consumer table (ENT-4570)

- api/candlepin-api-spec.yaml
- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java
- buildSrc/src/main/resources/templates/api.mustache
- buildSrc/src/main/resources/templates/pojo.mustache
- client/build.gradle
- pom.xml
- src/main/java/org/candlepin/dto/api/v1/EntitlementTranslator.java
- src/main/java/org/candlepin/model/OwnerInfoBuilder.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/main/java/org/candlepin/resource/PoolResource.java
- src/test/java/org/candlepin/model/ConsumerTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- src/test/java/org/candlepin/resource/PoolResourceTest.java
- Merge changes from upstream v5.4.0 to our local copies of:
* AbstractJavaJAXRSServerCodegen.java
* api.mustache
* pojo.mustache
* Keep our custom workarounds introduced in d6a9b9e7f, bfa2bc88f
and 733fc0b8a
- Remove our custom workaround from 25c2c0d48 because the fix is in
upstream and use the new method convention 'put/add*Item()'
- Fix issue with ambiguous operationId name generation
- Update the client openapi config to use the JDK8 date/time API
> [M] Add openapi-generator 5.4.0 upgrade accompanying changes

- bin/deployment/test_data.json
After the switch to SCA by default [1], new owners are created with
content access mode set to org_environment. Since the test data did not
explicitly set the access mode for the "admin" & "donaldduck" owners,
they are now created in org_environment mode, breaking test cases that
use the test data. Since the "snowwhite" owner already has
org_environment, explicitly set the entitlement mode for the other
owners.
[1] https://github.com/candlepin/candlepin/pull/3239
> test data: explicitly set entitlement mode for admin & donaldduck owners

- src/main/java/org/candlepin/resource/OwnerResource.java
- src/main/java/org/candlepin/resource/util/InfoAdapter.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/util/UtilTest.java
- Fixed an exception that could occur in Util.toMap when
processing an attribute list with any of the following:
- a null attribute
- an attribute with a null or empty key
- an attribute with a null value
> [M] 2073015: Fixed a bug in Util.toMap when processing null values (ENT-4882)

- src/main/java/org/candlepin/async/JobManager.java
- src/main/java/org/candlepin/auth/Principal.java
- src/main/java/org/candlepin/auth/SystemPrincipal.java
Setting the principal name for system generated job instead of it just being null. I included some output from the cp_async_jobs table from testing the code.
```
candlepin=> Select id, name, job_key, principal from cp_async_jobs;
id                |          name          |        job_key         |           principal           
----------------------------------+------------------------+------------------------+-------------------------------
ff808181801e769a01801e80d0380b21 | ActiveEntitlementJob   | ActiveEntitlementJob   | System_ActiveEntitlementJob
ff808181801e769a01801e80d04d0b22 | ExpiredPoolsCleanupJob | ExpiredPoolsCleanupJob | System_ExpiredPoolsCleanupJob
ff808181801e769a01801e817aaa0b23 | ManifestCleanerJob     | ManifestCleanerJob     | admin
(3 rows)
```
> [M] Added principal name for system generated jobs (ENT-4855)

- build.gradle
- pom.xml
- src/main/resources/META-INF/persistence.xml
- src/main/resources/ehcache.xml
The issue we had with empty collections was because this was fixed in hibernate 5.5.3:
https://hibernate.atlassian.net/browse/HHH-4808
We were relying on the connection remaining open when the CandlepinQuery is passed to the interceptor.
The setting "hibernate.connection.release_mode" allows it to behave the way it did before the bug was fixed.
> Update cache jars [ENT-4860]

- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/policy/AutobindRulesTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- src/test/java/org/candlepin/util/UtilTest.java
- Fixed a bug with null-versioned product attributes causing
version collisions due to being used in the version calculation
before being silently discarded during entity persistence
- Null-valued attributes are now silently discarded at the API
layer to retain the current behavior
- Product entities will no longer accept null values for product
attributes, as Hibernate throws them out anyway
> [M] 2075587: Fixed attribute storage issue causing version collisions (ENT-4907)

- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/test/java/org/candlepin/controller/ProductManagerTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Fixed a bug with null-versioned product attributes causing
version collisions due to being used in the version calculation
before being silently discarded during entity persistence
- Null-valued attributes are now silently discarded at the API
layer to retain the current behavior
- Product entities will no longer accept null values for product
attributes, as Hibernate throws them out anyway
> [4.0] 2076659: Fixed attribute storage issue causing version collisions (ENT-4907)

- bin/deployment/bash_functions
- bin/deployment/deploy
- bin/deployment/liquibase.sh
- build.gradle
- pom.xml
We are also making a change to use the mariadb-java-client jar from the classpath so that we always use the same version that is defined by gradle. I was able to verify the changes be deploying candle pin in a Vagrant vm for el7, el8, and f35.
> [M] Removed mysql-connector-java from gradle dependencies. (ENT-4783)

- bin/deployment/create_test_repos.py
* When ./bin/deployment/deploy script was started with -r
option and test RPM repository was generated, then deploy
script failed, when Python 3 was used (e.g. RHEL 8)
> Fix issue with deploy script, when Python 3 is used

- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/resources/db/changelog/20220420165513-drop_pool_derived_product_constraint.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/model/ProductTest.java
- Fixed a null pointer exception (NPE) that could occur while testing
a product for a cyclical product reference if one or more products
in the graph had a collection of provided products containing a null
product
- Product.setProvidedProducts now filters null elements from the incoming
collection
- Dropped an obsolete foreign key from pool to products on the derived
product field
- Removed some obsolete code surrounding pool provided product
hydration, as these fields are now stored on the products
> [4.1] 2076954: Fixed null pointer exception while testing products for cycles (ENT-4936)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/resources/db/changelog/20220420165513-drop_pool_derived_product_constraint.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- Fixed a null pointer exception (NPE) that could occur while testing
a product for a cyclical product reference if one or more products
in the graph had a collection of provided products containing a null
product
- Product.setProvidedProducts now filters null elements from the incoming
collection
- Dropped an obsolete foreign key from pool to products on the derived
product field
- Removed some obsolete code surrounding pool provided product
hydration, as these fields are now stored on the products
> [4.0] 2076955: Fixed null pointer exception while testing products for cycles (ENT-4936)

- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/resources/db/changelog/20220420165513-drop_pool_derived_product_constraint.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/model/ProductTest.java
- Fixed a null pointer exception (NPE) that could occur while testing
a product for a cyclical product reference if one or more products
in the graph had a collection of provided products containing a null
product
- Product.setProvidedProducts now filters null elements from the incoming
collection
- Dropped an obsolete foreign key from pool to products on the derived
product field
- Removed some obsolete code surrounding pool provided product
hydration, as these fields are now stored on the products
> [M] 2076952: Fixed null pointer exception while testing products for cycles (ENT-4936)

- src/main/java/org/candlepin/resteasy/ResourceLocatorMap.java
- src/test/java/org/candlepin/resteasy/ResourceLocatorMapTest.java
Checks the interfaces for the Resource classes
Downgraded log warning to info for PUT/POST with no @Consumes as this
is the expected state
> 2070159: Update resource locator annotation warnings

- docker/docker-compose-postgres.yml
Updated the candlepin repo at quay.io to include the postgresql 12.10 docker image from docker.io.
> Update postgresql container to use version 12

- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/sync/Exporter.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/sync/ExporterTest.java
I also verified the changes with the following steps:
1. Register with Subscription Manager to an organization that is org_environment content access mode.
2. Use a Get request on the candlepin/consumers/<Consumer ID>/certificates endpoint and use and serial number as a query parameter. (curl -k -u admin:admin --request GET --header 'accept: application/json' "https://localhost:8443/candlepin/consumers/<Consumer ID>/certificates?serials=12345678")
3. Verify that we do not get any certificates back.
> 2078780: Added filter for fetching SCA certs with cert serial Id

- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/PomToolkit.groovy
- pom.xml
Changed build.gradle to use the maven-publish plugin instead of the maven plugin for compatibility using Gradle 7+.  Unfortunately we are somewhat limited with the properties and methods with maven-publish and I had to generate most of the pom.xml with the withXml method.
https://docs.gradle.org/current/dsl/org.gradle.api.publish.maven.MavenPom.html
**Pom is generated running the following:**
`gradlew generatePomFileForLocalPublication`
> [M] Changed Maven plugin to maven-publish for Gradle 7+ (ENT-4797)

- jenkins/Jenkinsfile
This PR uses the built in milestones plugin https://www.jenkins.io/doc/pipeline/steps/pipeline-milestone-step/  to stop previous builds.  Instead of manually tracking milestone steps as in the docs of this plugin we're setting them to the build number so that the latest milestone is always the latest job.  We are also setting the previous milestone in case it wasn't set.  (see https://issues.jenkins.io/browse/JENKINS-43353 ).   Some implementations of this do this in a for loop to ensure that all previous builds have a milestone set  (for example: https://github.com/RedHatInsights/insights-tag-service/blob/44abadea01427601e8962f35f099f870d4b2e754/Jenkinsfile#L27 ), however this does take time and it slows down the system for PRs with a large number of builds (hundreds?).  If we see any …
> adding milestones to abort previous builds

- src/main/java/org/candlepin/async/tasks/ActiveEntitlementJob.java
- src/test/java/org/candlepin/async/tasks/ActiveEntitlementJobTest.java
- The ActiveEntitlementJob now performs each individual consumer
status recalculation within its own transaction
> [M] ActiveEntitlementJob now operates transactionally (ENT-4948)

- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/OwnerProduct.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/resources/db/changelog/20220517162755-add_owner_product_orphaned_date.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Products orphaned during refresh or manifest import can now
have a grace period before they will be deleted
- Added the config "candlepin.refresh.orphaned_entity_grace_period"
to control the duration of the grace period in days, or disable
it entirely. By default this option is set to 30 days.
> [M] Added grace period for product deletion during refresh/import (ENT-4881)

- .github/dependabot.yml
Reason: dependabot is opening PRs for upgrading maven plugins, and we don't want that because we auto-generate them from gradle. Also, we don't necessarily need upgrading normal maven libraries, because we auto-generate them during the release pipeline anyway.
> [M] Remove maven from dependabot config

- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/OwnerProduct.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/resources/db/changelog/20220517162755-add_owner_product_orphaned_date.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Products orphaned during refresh or manifest import can now
have a grace period before they will be deleted
- Added the config "candlepin.refresh.orphaned_entity_grace_period"
to control the duration of the grace period in days, or disable
it entirely. By default this option is set to 30 days.
> [4.1] 2069160: Added grace period for product deletion during refresh/import (ENT-4881)

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- server/src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- server/src/main/java/org/candlepin/model/OwnerProduct.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/resources/db/changelog/20220517162755-add_owner_product_orphaned_date.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Products orphaned during refresh or manifest import can now
have a grace period before they will be deleted
- Added the config "candlepin.refresh.orphaned_entity_grace_period"
to control the duration of the grace period in days, or disable
it entirely. By default this option is set to 30 days.
> [4.0] 2069165: Added grace period for product deletion during refresh/import (ENT-4881)

- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/main/resources/db/changelog/20130315171104-migrate-upstream-uuid.xml
- src/main/resources/db/changelog/20140408160212-add-pool-source-sub-table.xml
- src/main/resources/db/changelog/20150401140006-add-pool-type-to-db.xml
- src/main/resources/db/changelog/20180110092945-cleanup-uebercerts-round4-premigration.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- src/test/java/org/candlepin/junit/LiquibaseExtension.java
Check to determine if any changesets have not been run by liquibase.
Failure results in a runtime error that will end the intialization.
> 1993223: Stop Candlepin initialization if database is not updated

- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- Fixed a bug that could occur while updating owner-product
references during refresh or manifest import in organizations
with many activation keys
- Removed use of the bulkSQLUpdate native query builder
> [4.0] Fixed JDBC packet size overrun in updateOwnerProductReferences

- server/src/main/java/org/candlepin/controller/refresher/builders/ProductNodeBuilder.java
- server/src/test/java/org/candlepin/controller/refresher/builders/ProductNodeBuilderTest.java
- Fixed an issue which could cause owner-product mappings for existing
entities to go missing in cases where a product is received during
refresh that uses the "no change" null value for its children content
or products
> [4.0] Fix issue with owner-product mapping during refresh/import (ENT-5110)

- server/src/main/java/org/candlepin/controller/refresher/builders/ProductNodeBuilder.java
- server/src/test/java/org/candlepin/controller/refresher/builders/ProductNodeBuilderTest.java
- Fixed an issue which could cause owner-product mappings for existing
entities to go missing in cases where a product is received during
refresh that uses the "no change" null value for its children content
or products
> [4.0h] Fix issue with owner-product mapping during refresh/import (ENT-5110)

- src/main/java/org/candlepin/controller/refresher/builders/ProductNodeBuilder.java
- src/test/java/org/candlepin/controller/refresher/builders/ProductNodeBuilderTest.java
- Fixed an issue which could cause owner-product mappings for existing
entities to go missing in cases where a product is received during
refresh that uses the "no change" null value for its children content
or products
> [4.1] Fix issue with owner-product mapping during refresh/import (ENT-5110)

- src/main/java/org/candlepin/controller/refresher/builders/ProductNodeBuilder.java
- src/test/java/org/candlepin/controller/refresher/builders/ProductNodeBuilderTest.java
- Fixed an issue which could cause owner-product mappings for existing
entities to go missing in cases where a product is received during
refresh that uses the "no change" null value for its children content
or products
> [M] Fix issue with owner-product mapping during refresh/import (ENT-5110)

- build.gradle
- buildSrc/src/main/groovy/PomToolkit.groovy
- pom.xml
- Pin jaxb-runtime to a specific version to avoid issue with maven
resolution of transitive dependencies with a version range.
- Also, add autogenerated pom changes based on gradle upgrades.
> Fix maven transitive dependency resolution issue

- bin/bash_functions
- server/bin/deploy
- server/bin/liquibase.sh
- The postgresql/mysql/mariadb rpms are no longer part of the
docker image. Use the jars from our java dependencies instead.
> [4.0] Use jdbc jars from java dependencies instead of rpm

- bin/deployment/bash_functions
- bin/deployment/deploy
- bin/deployment/liquibase.sh
- The postgresql/mysql/mariadb rpms are no longer part of the
docker image. Use the jars from our java dependencies instead.
> [4.1] Use jdbc jars from java dependencies instead of rpm

- bin/deployment/test_data_importer.py
- Marketing products tagged with the "skip_pools" attribute will
now be skipped during subscription/pool creation
> [4.1] Added support for skipping pool creation while processing test data (ENT-4849)

- server/bin/test_data_importer.py
- Marketing products tagged with the "skip_pools" attribute will
now be skipped during subscription/pool creation
> [4.0] Added support for skipping pool creation while processing test data (ENT-4849)

- api/candlepin-api-spec.yaml
- spec/cloud_registration_spec.rb
- Cloud registration info no longer has a size requirement on
the signature field; the field is still required to be present,
and null values are still not permitted, but empty signature
strings are now allowed
> [M] Removed length requirement on cloud registration signature (ENT-5283)

- api/candlepin-api-spec.yaml
- spec/cloud_registration_spec.rb
- Cloud registration info no longer has a size requirement on
the signature field; the field is still required to be present,
and null values are still not permitted, but empty signature
strings are now allowed
> [4.1] Removed length requirement on cloud registration signature (ENT-5283)

- CONTRIBUTING.md
- spec-tests/README.md
There was some discussion about the standardization of spec-test test names and display names and I thought that we should document these standards.
> [M] Added spec-test naming standards documentation

- bin/bash_functions
- server/bin/deploy
- server/bin/liquibase.sh
- The postgresql/mysql/mariadb rpms are no longer part of the
docker image. Use the jars from our java dependencies instead.
> [4.0-HOSTED] Use jdbc jars from java dependencies instead of rpm

- server/spec/export_spec.rb
- server/src/main/java/org/candlepin/dto/manifest/v1/CertificateSerialDTO.java
- server/src/test/java/org/candlepin/dto/manifest/v1/CertificateSerialDTOTest.java
- server/src/test/java/org/candlepin/dto/manifest/v1/CertificateSerialTranslatorTest.java
- Add back the 'collected' field from certificates exported in
manifests, to avoid breaking old (2.4 or older) candlepins
importing manifests that expect it to be there.
> [4.0-HOSTED] 2112391: Add back the collected field to certs in manifest

- spec/export_spec.rb
- src/main/java/org/candlepin/dto/manifest/v1/CertificateSerialDTO.java
- src/test/java/org/candlepin/dto/manifest/v1/CertificateSerialDTOTest.java
- src/test/java/org/candlepin/dto/manifest/v1/CertificateSerialTranslatorTest.java
- Add back the 'collected' field set by default to 'false' for
certificates exported in manifests, to avoid breaking old (2.4
or older) candlepins importing manifests that expect it to be
there.
> [M] 2112883: Add back the collected field to certs in manifest

- spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java
- Move the call for wating for the job to finish at the end.
The test was always waiting the full timeout (15 seconds) for the
job to finish because the scheduler was turned off, waisting time.
> [M] Fix long-running job spec test

- Vagrantfile
- ansible/requirements.yml
- Updated the requirements.yml to include non-core Ansible collections
used by the Candlepin role
- Updated the Vagrantfile to use a newer compatibility mode and support
fetching both roles and collections via ansible-galaxy
> [M] Updated Vagrant configuration to support upcoming Ansible changes (ENT-5303)

- Vagrantfile
- vagrant/requirements.yml
- Updated the requirements.yml to include non-core Ansible collections
used by the Candlepin role
- Updated the Vagrantfile to use a newer compatibility mode and support
fetching both roles and collections via ansible-galaxy
> [4.1] Updated Vagrant configuration to support upcoming Ansible changes (ENT-5303)

- docker/cp-test
- Addressed an issue with the usage of trap and set -e in cp-test
which caused errors in testing to skip cleanup and artifact
collection
- Addressed an issue with a previous refactoring of the rspec
filtering that missed the assignement of the filter variable,
causing spec filters to not be evaluated or used
> [M] Fixed cp-test artifact collection and spec test filtering (ENT-5313)

- src/main/java/org/candlepin/config/EncryptedConfiguration.java
- src/main/java/org/candlepin/config/FileConfiguration.java
- src/main/java/org/candlepin/config/PropertiesFileConfiguration.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/test/java/org/candlepin/config/EncryptedConfigurationTest.java
- src/test/java/org/candlepin/config/PropertiesFileConfigurationTest.java
- src/test/java/org/candlepin/guice/CustomizableModulesTest.java
- Removed the getEncoding and setEncoding methods from
FileConfiguration and all implementation classes, as it could
not be applied in all cases, and could be lost or desync'd in
some cases
- Added new methods to FileConfiguration for specifying the
character encoding during config load
> [M] Removed setting encoding on FileConfiguration implementation (ENT-5322)

- spec-tests/src/test/java/org/candlepin/spec/jobs/InactiveConsumerCleanerJobSpecTest.java
toString truncates the seconds if the date hits an exact minute.
> Use formatter instead of toString for date field [ENT-5301]

- common/src/main/java/org/candlepin/common/config/EncryptedConfiguration.java
- common/src/main/java/org/candlepin/common/config/FileConfiguration.java
- common/src/main/java/org/candlepin/common/config/PropertiesFileConfiguration.java
- common/src/test/java/org/candlepin/common/config/EncryptedConfigurationTest.java
- common/src/test/java/org/candlepin/common/config/PropertiesFileConfigurationTest.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/test/java/org/candlepin/guice/CustomizableModulesTest.java
- Removed the getEncoding and setEncoding methods from
FileConfiguration and all implementation classes, as it could
not be applied in all cases, and could be lost or desync'd in
some cases
- Added new methods to FileConfiguration for specifying the
character encoding during config load
> [4.0] Removed setting encoding on FileConfiguration implementation (ENT-5322)

- src/main/java/org/candlepin/config/EncryptedConfiguration.java
- src/main/java/org/candlepin/config/FileConfiguration.java
- src/main/java/org/candlepin/config/PropertiesFileConfiguration.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/test/java/org/candlepin/config/EncryptedConfigurationTest.java
- src/test/java/org/candlepin/config/PropertiesFileConfigurationTest.java
- src/test/java/org/candlepin/guice/CustomizableModulesTest.java
- Removed the getEncoding and setEncoding methods from
FileConfiguration and all implementation classes, as it could
not be applied in all cases, and could be lost or desync'd in
some cases
- Added new methods to FileConfiguration for specifying the
character encoding during config load
> [4.1] Removed setting encoding on FileConfiguration implementation (ENT-5322)

- config/candlepin/candlepin.conf.template
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
The report of the missing sets will still happen, but the runtime error
will not be thrown. This will allow the startup to continue
> 2110031: add config for enabling/disabling the DB check on startup

- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/Product.java
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitorTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- The versioned entity update logic will now clear the entity version
for an existing entity on collision when the colliding entities
have the same entity ID
> [M] Added same-ID entity version collision resolution (ENT-5324)

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/JobsClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/ActivationKeys.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Branding.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Consumers.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Owners.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Pools.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Products.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Roles.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Subscriptions.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/StringUtil.java
- spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateV3SpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/InactiveConsumerCleanerJobSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/JobScheduleSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/pools/PoolSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
- Updated how random string generation works, allowing for specific
character sets to be used, removing the automatic hyphenation, and
generating fixed-length strings rather than dynamic-lengthed ones
- Updated the API around waiting for jobs, permitting both the job ID
and the job object itself; the latter of which will also verify
the job itself exists and has a valid job ID
- waitForJob now throws an exception if a job vanishes during the
wait loop, or if the job does not terminate within the alloted time
- Updated several tests and builders to use the new string generation
method with appropriate charsets
- Updated several tests to also verify jobs they wait on terminate
with a successful status
> [M] Improved spec test random string generation and job waiting routines (ENT-5354)

- candlepin.spec.tmpl
I was unable to test these changes as the `tito build --rpm --test --verbose` command is not working for me.
The error that I was running into when attempting to run the tito command:
```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.swWspV
+ umask 022
+ cd /tmp/tito/rpmbuild-candlepinxisoscm9/BUILD
+ cd /tmp/tito/rpmbuild-candlepinxisoscm9/BUILD
+ rm -rf candlepin-4.2.7
+ /usr/bin/gzip -dc /tmp/tito/rpmbuild-candlepinxisoscm9/SOURCES/candlepin-4.2.7-complete.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd candlepin-4.2.7
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ pathfix.py -pni '/usr/bin/python3 -s' bin/scripts/code/setup/cpdb bin/scripts/code/setup/cpsetup
usage: pathfix.py [-h] [--config CONFIG] path
pathfix.py: error: unrecognized arguments: -pni …
```
> [M] Made logback.xml a config file to prevent overwriting (ENT-5300)

- docker/README.mkd
- docker/build-images
Currently there is some bug with Docker (most likely our configuration of it) where it CPU limits commands run in the container.  When yum inside the container hits 100% CPU usage it hangs for some undetermined time and makes each package install VERY slow.  I've tried manually opening up Docker to use all CPUs and other available resources but this does not prevent any one CPU from hitting full usage.
Conveniently, podman does not have any of this problem, and since the build stage of candlepin tests don't strictly require docker, I'm doing a simple fix of using that for the builds only.
Note that this doesn't include a fix for the other build script in `docker/gating-test-images/build.sh`  and we will likely hit that problem there also.  This PR makes the job run much faster but we …
> Slow docker image builds

- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/Product.java
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitorTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- The versioned entity update logic will now clear the entity version
for an existing entity on collision when the colliding entities
have the same entity ID
> [4.1] 2123382: Added same-ID entity version collision resolution (ENT-5385)

- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/test-logging-convention.gradle
- dependencies.gradle
- spec-tests/build.gradle
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Branding.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/CertificateUtil.java
- spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateV3SpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java
- spec-tests/src/test/resources/junit-platform.properties
- Extract test logger settings into a convention file
- Enable parallel execution of spec tests
Note: We've written a fair amount of spec tests and questions are starting to arise whether the choices we are making now will affect tests running in parallel. We should start with parallel execution in order to flush out issues early.
> Enable parallel execution of spec tests

- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- Added state tracking to the CandlepinContextListener to avoid
exceptions on shutdown if initialization doesn't complete
successfully
- Reformatted string generation in cases where unrun Liquibase
changes are detected
> [M] Added minor state management to the CandlepinContextListener (ENT-5386)

- spec-tests/src/test/java/org/candlepin/spec/StatusSpecTest.java
- Spec expected "default" rules source but other tests occasionally run
before this and update it to "database"
> Fix random failures of StatusSpecTest

- client/src/main/java/org/candlepin/resource/HostedTestApi.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/SpecTest.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/ProductAttributes.java
- spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/HostedTestSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementCertificateV3SpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceConcurrentSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceFilteringSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/InactiveConsumerCleanerJobSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/JobScheduleSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
- Change test lifecycle to prevent sharing of instance variables
- Fix expectation of status endpoint spec as other tests might have
changed the result
- Merge v3 cert test that was split in the previous fix attempt
- Update beforeAll to static as that is required in PER_METHOD
lifecycle
> Fix spec parallelization issues

- src/main/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptor.java
- src/main/resources/META-INF/persistence.xml
- The CandlepinQueryInterceptor now processes CandlepinQuery (CPQ) instances in a transaction rather than individually, to work around a potential Hibernate configuration issue which will cause connections to be closed before the CPQ has been fully read
- Removed the default persistence connection release mode of "on_close"
> [M] CandlepinQueryInterceptor now processes CPQ instances in a transaction (ENT-5400)

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/PoolsClient.java
- spec-tests/src/test/java/org/candlepin/spec/HypervisorCheckInSpecTest.java
- spec/hypervisor_check_in_spec.rb
- src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java
There is a marker in hypervisor_check_in_spec to show where I stopped.
The async tests were ported and the sync ones were left. The sync ones will be removed when the sync endpoint is removed.
Also corrected an issue with the last checkin date not getting updated in the async call if there were no other changes.
> Convert hypervisor_check_in_spec part 1

- bin/deployment/update-server-xml.py
This enables gzip compression settings for tomcat, this works well on el8 & has some weirdness on el7 where only some of the data is compressed.  
To test: 
deploy with standard test data:
```
./bin/deployment deploy -gat
````
Test with the list subscriptions endpoint (or really your endpoint of choice). Using curl on el8 to get the compressed & uncompressed output & compare to the uncompressed sizes / contents.
```
curl -verbose -k -u admin:admin "https://localhost:8443/candlepin/owners/snowwhite/subscriptions" --compressed --raw -o compressed.txt
curl -verbose -k -u admin:admin "https://localhost:8443/candlepin/owners/snowwhite/subscriptions" --raw -o uncompressed.txt
```
When using the test data I saw the subscriptions endpoint for snowwhite have the payload reduced from 1.9M to 45k.
> Enable gzip compression support for el8

- api/candlepin-api-spec.yaml
- src/main/java/org/candlepin/guice/CandlepinCapabilities.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/main/java/org/candlepin/resource/StatusResource.java
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- src/test/java/org/candlepin/resource/StatusResourceTest.java
- Added support for the device_auth capability
- Added new fields to the status DTO for indicating OAuth2 device auth details (realm, url, client_id, and scope)
- Updated keycloak flows to also populate the device auth fields and capabilities
> [M] Added support for the device_auth capability and status (ENT-3599)

- docker/candlepin-base-cs8/Dockerfile
- docker/candlepin-base-cs8/setup-devel-env.sh
- docker/candlepin-base/Dockerfile
- docker/candlepin-base/setup-devel-env.sh
- docker/gai.conf
- Bundler had trouble accessing rubygems when ipv6 was used. All requests were timing-out. This fix changes the precedence so that ipv4 is used for accessing rubygems.
- Centos 7 was missing ruby-devel dependency which caused issues for some of the gems.
> ENT-5390: Fix bundle install

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClientFactory.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClients.java
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/HypervisorCheckInSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/activationkey/ActivationKeySpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceConcurrentSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceFilteringSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/pools/PoolSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/pools/PostBindBonusPoolSpecTest.java
- While porting spec tests from ruby to java, there has been a heavy use of ApiClients.trustedConsumer and ApiClients.trustedUser auth methods which are using the 'magic' headers (cp-consumer/cp-user). The ruby tests never used those, and instead use the identity cert + key and username + password for authentication. This change switches all existing java spec tests to use the ApiClients.basic(username, password) and ApiClients.ssl(consumer) which are the more realistic authentication use cases.
> [M] Eliminate trustedConsumer/trustedUser usage in spec tests

- src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- The path tree condensing algorithm was dropping nodes in some specific cases
- This code was untouched for 10 years and only after a change was made to the
hashing of content did it surface.
- Included are sets of data, where it previously did and did not work correctly,
in unit tests so that we will see any future problems sooner.
- The urls in the files should all be compressed and decompressed correctly
if the algorithm is operating properly.
> [M] 2134502: Satellite cannot enable or sync satellite-tools repo

- src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- The path tree condensing algorithm was dropping nodes in some specific cases
- This code was untouched for 10 years and only after a change was made to the hashing of content did it surface.
- Included is a set of data from the BZ where the condensation did not work.
- The urls should be compressed and decompressed correctly if the algorithm is operating properly.
> [4.1] 2134480: Satellite cannot enable or sync satellite-tools repo

- spec-tests/src/test/java/org/candlepin/spec/activationkey/ActivationKeySpecTest.java
- The test would sometimes fail because the comparison of the activation key lists was taking into account the order of the returned list, which shouldn't matter.
> [M] Fix flaky activation key list test

- bin/deployment/test_data_importer.py
The actual paths for content have the directory named as "$PID-$CID" (with a dash), and the "content_url" stored for the products did not have it. Fix it by:
- rename the "content_id" variable in the loop to "candlepin_content_id": this way it does not shadow the "content_id" loop variable
- compose "content_url" using the expected format
Fixes commit 7dff0036b805cbdba392a0139666d3ccf0a4e12a.
> test_data_importer: fix invalid content_url

- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/java/org/candlepin/resource/OwnerProductResource.java
- src/main/resources/db/changelog/20221114152236-add_delete_cascade_to_content_modified_products.xml
- src/main/resources/db/changelog/20221117125815-prime_system_locks.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/async/tasks/OrphanCleanupJobTest.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Changed the ProductManager and ContentManager to obtain pessimistic write locks before making any change or removal of products or content
- Moved several org-less content and product queries from the OwnerContentCurator or OwnerProductCurator to the ContentCurator or ProductCurator as appropriate
- Changed the output from several curator methods from lists of tuples to maps of collections to better convey exactly what was being returned and to make it easier to follow during analysis
- The OrphanCleanupJob no longer removes content that is referenced by a non-orphaned product or an environment, even in cases where the content is technically orphaned (bad content mapping)
- Added a DB-level delete cascade on Content.modifiedProductIds, as JPA is inexplicably unwilling or unable to …
> [M] 1931913: API-level product/content updates no longer occur in parallel (CANDLEPIN-440)

- src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/resources/db/changelog/20221114152236-add_delete_cascade_to_content_modified_products.xml
- src/main/resources/db/changelog/20221117125815-prime_system_locks.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/async/tasks/OrphanCleanupJobTest.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Changed the ProductManager and ContentManager to obtain pessimistic write locks before making any change or removal of products or content
- Moved several org-less content and product queries from the OwnerContentCurator or OwnerProductCurator to the ContentCurator or ProductCurator as appropriate
- Changed the output from several curator methods from lists of tuples to maps of collections to better convey exactly what was being returned and to make it easier to follow during analysis
- The OrphanCleanupJob no longer removes content that is referenced by a non-orphaned product or an environment, even in cases where the content is technically orphaned (bad content mapping)
- Added a DB-level delete cascade on Content.modifiedProductIds, as JPA is inexplicably unwilling or unable to …
> [4.1] 1931923: API-level product/content updates no longer occur in parallel (CANDLEPIN-440)

- src/test/java/org/candlepin/sync/ExporterTest.java
- Appeared to be a difference between timestamps and use of Date.now() in different places in the code
- Backed up the "start" time a second to clear it up. Passes repeatedly when run in batches of 10,000
> CANDLEPIN-442: Unit test failure from date issue

- server/src/main/java/org/candlepin/async/tasks/OrphanCleanupJob.java
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/Content.java
- server/src/main/java/org/candlepin/model/ContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/resources/db/changelog/20221114152236-add_delete_cascade_to_content_modified_products.xml
- server/src/main/resources/db/changelog/20221117125815-prime_system_locks.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/async/tasks/OrphanCleanupJobTest.java
- server/src/test/java/org/candlepin/model/ContentCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Changed the ProductManager and ContentManager to obtain pessimistic write locks before making any change or removal of products or content
- Moved several org-less content and product queries from the OwnerContentCurator or OwnerProductCurator to the ContentCurator or ProductCurator as appropriate
- Changed the output from several curator methods from lists of tuples to maps of collections to better convey exactly what was being returned and to make it easier to follow during analysis
- The OrphanCleanupJob no longer removes content that is referenced by a non-orphaned product or an environment, even in cases where the content is technically orphaned (bad content mapping)
- Added a DB-level delete cascade on Content.modifiedProductIds, as JPA is inexplicably unwilling or unable to …
> [4.0] 2142944: API-level product/content updates no longer occur in parallel (CANDLEPIN-440)

- bin/scripts/code/setup/cpdb
- bin/scripts/code/setup/cpsetup
- build.gradle
- buildSrc/src/main/groovy/PomToolkit.groovy
- candlepin.spec.tmpl
- pom.xml
- Update pom generation to generate annotation processor paths
- Update script headers to fix python version ambiguity
- Remove unuser selinux_policyver
> CANDLEPIN-209: Enable RPM build on RHEL 9

- ansible/roles/candlepin/tasks/common/cp_debugging.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- spec-tests/build.gradle
- Added a block in the cp_debugging task that forwards port 8001
- Added a check for the 'remote-debug' system property in the spec gradle task
Running `vagrant up` with ansible.roles.candlepin.defaults.cp_configure_debugging set to 'true' will now forward the port 8001 that can be attached to for remote debugging Java spec tests. I also added a check for the system property 'remote-debug' in the 'spec' gradle task that will enable the remote debugging.
I figured that we should use a different port than what is already being forwarded for Candlepin debugging (8000) so you don't have to remove the debug arguments from Tomcat and restart the service so that port 8000 is open before trying to debug a spec test.
Example of running a spec test for remote debugging:
`./gradlew clean spec …
> [M] Added remote debug configurations for Gradle

- ansible/roles/candlepin/tasks/el8/el8_ruby.yml
- ansible/roles/candlepin/tasks/el9/el9_ruby.yml
- Bundler 2.4 dropped support of our ruby version. Bundler 2.3.26 is the last version that supports it.
> Limit bundler version to 2.3.26

- bin/deployment/create_test_repos.py
- bin/deployment/test_data_importer.py
Create a `requests.Session` object to use for all the requests. This makes sure that existing connections can be cached/reuse; considering that all the connections go to the same hostname, this gives a considerable speed improvement.
> test data importers: use a `requests.Session`

- api/candlepin-api-spec.yaml
- buildSrc/src/main/resources/templates/api.mustache
- buildSrc/src/main/resources/templates/pojo.mustache
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- src/main/java/org/candlepin/exceptions/mappers/ValidationExceptionMapper.java
- src/main/java/org/candlepin/resource/OwnerContentResource.java
- src/main/java/org/candlepin/validation/CandlepinMessageInterpolator.java
- Corrected the input validation on the POST /owners/{key}/content endpoint to no longer require the content ID on creation
- Updated the input validation on content creation to throw 400s when the label, name, type, or vendor fields are not provided during content creation, rather than erroring with a 500
- Updated the ValidationExceptionMapper to separate constraint violations when building the response error message
- Updated a few older bits of code with to fit with modern practices and stylistic choices
- Updated a couple of the OpenAPI generator templates to produce slightly more readable code
> [M] CANDLEPIN-456: Fixed input validation on content creation endpoint

- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/Entitler.java
- src/main/java/org/candlepin/model/CloudProfileFacts.java
- src/main/java/org/candlepin/model/Consumer.java
- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/PoolCurator.java
- src/main/java/org/candlepin/policy/criteria/CriteriaRules.java
- src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
- src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java
- src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- src/test/java/org/candlepin/controller/EntitlerTest.java
- src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- src/test/java/org/candlepin/model/ConsumerTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- Updated the Consumer.Facts pseudo-class to contain all of the facts Candlepin uses either directly or indirectly
- Updated the CloudProfileFacts to reference Consumer.Facts rather than hard-coding its own copies of the values
- Updated several places in Candlepin code which were using hard-coded strings for facts to use the new values in Consumer.Facts
> [M] CANDLEPIN-455: Normalized consumer fact constants and usage

- src/main/java/org/candlepin/async/JobManager.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/async/JobManagerTest.java
- src/test/java/org/candlepin/util/UtilTest.java
- Updated Util.getHostname to drop the use of reflection, as this method has been blocked with new restrictions as of Java 17
- Added a new configuration for specifying the name of a node to use while setting the origin and executor for jobs within the job system
> [M] CANDLEPIN-459: Updated Util.getHostname to no longer use reflection

- src/main/java/org/candlepin/auth/CloudRegistrationAuth.java
- src/main/java/org/candlepin/auth/KeycloakAuth.java
- This is for stats purposes, to differantiate between cloud auto-registration token and generic 'keycloak' token usage.
> [M] Log different types of token auth usage

- src/main/java/org/candlepin/dto/manifest/v1/ProductDTO.java
- src/main/java/org/candlepin/model/Entitlement.java
- src/main/java/org/candlepin/service/impl/ImportProductServiceAdapter.java
- src/main/java/org/candlepin/sync/EntitlementImporter.java
- src/main/java/org/candlepin/sync/Exporter.java
- src/main/java/org/candlepin/sync/Importer.java
- src/main/java/org/candlepin/sync/ProductImporter.java
- src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- src/test/java/org/candlepin/dto/AbstractDTOTest.java
- src/test/java/org/candlepin/sync/EntitlementImporterTest.java
- src/test/java/org/candlepin/sync/ImporterTest.java
- src/test/java/org/candlepin/sync/ProductImporterTest.java
- Fixed an issue that was preventing children products of products from being normalized during import
- Improved merging and resolution logic while processing product data stored on pools for older manifest formats
- Fixed several issues regarding data storage and encapsulation in the manifest product DTO
- Refactored logic surrounding product collection during export
- Updated tests and test suites which were erroneously using import objects as mocks
> [M] CANDLEPIN-475: Updated the product importer and resolution logic

- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/AbstractHibernateObject.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/Product.java
- src/main/resources/db/changelog/20230207161633-clear_entity_versions-1.xml
- src/main/resources/db/changelog/changelog-create.xml
- src/main/resources/db/changelog/changelog-testing.xml
- src/main/resources/db/changelog/changelog-update.xml
- Added entity class guidelines and documentation to the
AbstractHibernateObject
- Changed several methods in Product and Content to no longer
reference model attributes outside of mutators and accessors
- Added entity version to the string representation of Product
and Content
- Improved output of entity version collision error message in
ProductNodeVisitor and ContentNodeVisitor
- Changed how content processes modified product IDs during
entity version calculation
- Removed XML serialization annotations from AbstractHibernateObject,
Content, and Product
- AbstractHibernateObject now returns a typed self-reference from
its mutators
- Deprecated the AbstractHibernateObject.populate method, and the
AbstractHibernateObject.DEFAULT_SORT_FIELD property
> [M] CANDLEPIN-480: Fixed product and content attribute referencing

- src/main/java/org/candlepin/model/Content.java
- Updated Content.getEntityVersion to reference the correct variable when adding modified product IDs to the hash
> [M] CANDLEPIN-480: Fixed incorrect variable reference in Content.getEntityVersion

- jenkins/candlepin-validate-text.sh
- jenkins/lint.sh
- jenkins/spec-tests.sh
- jenkins/unit-tests.sh
- jenkins/upload-on-sonarqube.sh
When Jenkins stage runs in docker, all build output is created under
root user which prevents unprivileged staages from working.
This change returns ownership of workspace to jenkins user after each
such stage.
> [M] Fix workspace ownership

- jenkins/candlepin-validate-text.sh
- jenkins/lint.sh
- jenkins/spec-tests.sh
- jenkins/unit-tests.sh
- jenkins/upload-on-sonarqube.sh
When Jenkins stage runs in docker, all build output is created under root user which prevents unprivileged staages from working.
This change returns ownership of workspace to jenkins user after each such stage.
> [4.2] Fix workspace ownership

- jenkins/candlepin-validate-text.sh
- jenkins/lint.sh
- jenkins/rspec-tests.sh
- jenkins/unit-tests.sh
- jenkins/upload-on-sonarqube.sh
When Jenkins stage runs in docker, all build output is created under root user which prevents unprivileged staages from working.
This change returns ownership of workspace to jenkins user after each such stage.
> [4.1] Fix workspace ownership

- jenkins/candlepin-validate-text.sh
- jenkins/lint.sh
- jenkins/rspec-tests.sh
- jenkins/unit-tests.sh
When Jenkins stage runs in docker, all build output is created under root user which prevents unprivileged staages from working.
This change returns ownership of workspace to jenkins user after each such stage.
> [4.0] Fix workspace ownership

- build.gradle
- jenkins/Jenkinsfile
- Undockerize stages that do not have to run in a container. Only spec test stages need to run in docker.
- Reuse junit test reports in sonar to avoid running unit tests twice.
> [4.2] CANDLEPIN-331: Jenkins: Reuse result of unit test stage

- build.gradle
- jenkins/Jenkinsfile
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Undockerize stages that do not have to run in a container. Only spec test stages need to run in docker.
- Reuse junit test reports in sonar to avoid running unit tests twice.
> [4.1] CANDLEPIN-331: Jenkins: Reuse result of unit test stage

- buildSrc/src/main/groovy/PomToolkit.groovy
- pom.xml
- Openapi-generator was upgraded to 6.3.0 in gradle, but the maven plugin needs to also be upgraded.
> [M] Upgrade maven openapi plugin to be in line with gradle

- docker/candlepin-base-cs8/Dockerfile
- docker/candlepin-base-cs9/Dockerfile
- docker/candlepin-base/Dockerfile
This allows the cp-test file in the branch to be used instead of one baked into
the docker image.
to test, build locally and then run the test command against it. See https://github.com/candlepin/candlepin/pull/3876 if you need the full instructions.
Note that once this makes it into the images on quay.io, none of the branches prior to 4.2 will run CI correctly until they have the change in PR https://github.com/candlepin/candlepin/pull/3876
> CANDLEPIN-509: [M] Link to source cp-test

- docker/candlepin-base-cs8/Dockerfile
- docker/candlepin-base/Dockerfile
This allows the cp-test file in the branch to be used instead of one baked into
the docker image.
Brought here so that images can be created and tested solely in this branch.
> CANDLEPIN-509: [4.2] Link to source cp-test

- docker/candlepin-base/Dockerfile.template
- docker/cp-test
This will allow the version of the cp-test file in the test branch
to be used. The previous means was to use the cp-test file in the
master branch that would get baked into the docker image.
The reason for the symlink to cp-test is that the location of the cp-test file was different in later branches. 
The symlink in the Dockerfile.template file matches the one in later branches to allow a uniform setup when an image is produced from this branch instead of master and then tested.
To test [from the docker directory in this branch]: 
./build-images 
take the hash output at the end of the process. Copy to the docker-compose-[postgres|mysql].yml file in place of "candlepin: image: **${REGISTRY}/candlepin-base**". 
run "./test -[p|m] -c '/usr/bin/cp-test -u'"
WE NEED TO WAIT ON THE MASTER …
> CANDLEPIN-509: [4.1] Link to cp-test file in branch

- docker/candlepin-base/Dockerfile.template
- docker/cp-test
This will allow the version of the cp-test file in the test branch
to be used. The previous means was to use the cp-test file in the
master branch that would get baked into the docker image.
See description on https://github.com/candlepin/candlepin/pull/3876 for the details that apply here as well
> CANDLEPIN-509: [4.0-SAT] Link to cp-test file in branch

- candlepin.spec.tmpl
- config/candlepin/logrotate.conf
- Remove conditional statements used for RHEL 7 or earlier since now candlepin supports RHEL 8 as the minimum.
- Remove long unneeded obsoletes directives.
- Don't depend on tomcatjss, but instead directly on pki-servlet-engine and jss. The tomcatjss dependency was a hack to work around the renaming of the tomcat package from pki-servlet-container to pki-servlet-engine on RHEL 8.1.
> [M] RPM spec file cleanup

- Vagrantfile
- ansible/roles/candlepin/tasks/el8/el8_base_deps.yml
- Switched to generic/centos8s box. The box we currently use, which got it's last update two years ago seems no longer updatable.
- Updated dnf update task to use dnf module instead of command.
> Fix vagrant up

- containers/build-images
- Due to a regression running 'build-images -c' now fails with 'Option -c requires an argument.'. This should not be the case since -c does not need an argument.
> [M] Remove argument requirement for build-images -c flag

- src/main/java/org/candlepin/model/OwnerContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/Pool.java
- src/test/java/org/candlepin/model/PoolTest.java
- Updated OwnerProductCurator.clearProductEntityVersion to use native query
The Hibernate warning messages that this PR addresses are the following:
1. HHH000502: The [product] property of the [org.candlepin.model.Pool] entity was modified, but it won't be updated because the property is immutable.
2. HHH000487: The query: [UPDATE Product SET entityVersion = NULL WHERE uuid = :product_uuid] attempts to update an immutable entity: [cp2_products]
The first error message is reproduced by running the spec tests in the RefreshPoolsSpecTest suite. I ran the same tests to validate that the changes cause the warning messages to no longer occur. The issue is that the annotation parameters `insertable = false` and `updatable = false` was marking the Pool.Product field as non updatable, but we are …
> CANDLEPIN-476: Updated Pools model to avoid immutability warning

- bin/deployment/deploy
- bin/scripts/code/setup/cpsetup
- The cpsetup and the deploy scripts will now create an additional config file in Tomcat's conf.d directory to set the com.redhat.fips property to false to disable FIPS mode in Candlepin's Tomcat instance
> [M] CANDLEPIN-538: Disabled FIPS mode for dev Tomcat setup

- src/main/java/org/candlepin/jackson/OffsetDateTimeSerializer.java
- src/main/java/org/candlepin/resource/StatusResource.java
- src/test/java/org/candlepin/jackson/OffsetDateTimeSerializerTest.java
Update JSON time serializer to follow more strict ISO-8601 derivatives
- When we specify the format as date-time for a given field, the OpenAPI spec
expects it to be an RFC-3339 date-time, which while close to the basic
ISO-8601 format, does not permit omitting the colon in the offset.
- This is handled in code with the DateTimeFormatter.ISO_OFFSET_DATE_TIME
which claims to be ISO-8601 lenient, but still has a requirement of the
colon in the zone offset.
Ensure Status output has proper UTC time
- Previously we relied on the value to come from a system set to
UTC already. This will ensure it is in UTC regardless of the system
setting.
> CANDLEPIN-536: Update JSON time serializer for ISO-8601

- gradle/wrapper/gradle-wrapper.properties
- spec-tests/build.gradle
- Extended the network timeout in the gradle-wrapper.properties to
fix the issue of retrieving the gradle zip and Java dependencies
- Updated the build.gradle for the spec tests to force the use of
UTF-8 encoding for compiling
> CANDLEPIN-541: Spec test improvements for Jenkins runs

- api/candlepin-api-spec.yaml
- src/main/java/org/candlepin/resource/AdminResource.java
- src/main/java/org/candlepin/service/impl/DefaultUserServiceAdapter.java
- src/test/java/org/candlepin/resource/AdminResourceTest.java
- src/test/java/org/candlepin/resource/UserResourceTest.java
- src/test/java/org/candlepin/service/impl/DefaultUserServiceAdapterTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Moved the default super-admin user creation from the AdminResource.init endpoint to the DefaultUserServiceAdapter's construction step
- Marked the AdminResource.init endpoint deprecated; will remove in a future release
> [M] CANDLEPIN-551: Moved default user creation to DefaultUserServiceAdapter

- buildSrc/src/main/groovy/Gettext.groovy
- buildSrc/src/main/groovy/Msgfmt.groovy
- buildSrc/src/main/groovy/PomToolkit.groovy
- pom.xml
- Added two parameters to allow specifying the input and output directories for the msgfmt Gradle task
- Added additional status output to the gettext and msgfmt tasks
- Minor refactors to the gettext task
- Updated the pom generator task to generate a pom.xml that no
longer uses the gettest Maven plugin, and instead calls back
into Gradle to generate source files
> [M] Updated the gettext and msgfmt Gradle tasks

- bin/deployment/create_test_repos.py
Create the symlinks for SCA repositories as relative rather than absolute: the result is the same, however this make it possible to relocate the generated repositories.
> test data importers: make repos symlinks relative

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerCheckinSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/imports/ImportUpdateSpecTest.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/PersonConsumerResourceCreationLiberalNameRules.java
- Added a new query parameter, cleanup_entitlements, to the consumer entitlement certificate regeneration endpoint. When set, if the consumer is operating in SCA mode, unused entitlements will be removed before certificate regeneration occurs
- Miscellaneous comment, logging, and documentation cleanup
> [M] CANDLEPIN-557: Added support for entitlement cleanup in SCA mode

- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Fixed the resolution of a consumer's content access mode to no longer consider the mode a consumer may use for manifest import or export purposes
> [M] CANDLEPIN-557: Fixed content access mode resolution for consumers

- .github/scripts/bugzilla_reference_check.py
- .github/workflows/pr_verification.yml
Created Bugzilla reference check step for PR verification. I migrated the check_pr_branch.py script that is used for the Jenkins job to the .github/scripts directory and renamed the file to bugzilla_reference_check.py to more accurately describe the functionality of the script.
> CANDLEPIN-503: Migrated bugzilla reference to Github actions

- src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- src/test/java/org/candlepin/test/TestUtil.java
Sometimes tests in ConsumerResourceIntegrationtest fail when run on a jenkins node where spec tests were previously run and left some temp files behind.
> Fix random unit test failures

- build.gradle
- candlepin.spec.tmpl
- pom.xml
- Setup maven publish for candlepin artifacts
- Update spec template to support PNC build
Example usage
```bash
bacon pnc build-config clone 10925 --buildConfigName=test2 --scmRevision=ojanus/pnc4
bacon pnc build start 10925
bacon pnc brew-push build AYLIGMPK3RQAA --tag-prefix=candlepin-1-pnc
bacon pnc brew-push status AYLIGMPK3RQAA
brew wrapper-rpm --create-build candlepin-1-rhel-9-candidate org.candlepin-candlepin-4.3.2.redhat_00005-1 "git://git.app.eng.bos.redhat.com/candlepin/candlepin.git?#4.3.2.redhat-00005" --scratch
```
> CANDLEPIN-120: Add setup for PNC build

- .github/scripts/bugzilla_reference_check.py
- .github/workflows/pr_verification.yml
Workflows triggered by PRs from public forks do not have access to repo secrets. This causes failures for jobs that require secrets to work.
- Updated bugzilla library
- Removed secret as we use it to only read public bugs
- Reordered GH jobs
> Fix Bugzilla check for PRs from public forks

- src/main/java/org/candlepin/controller/ContentManager.java
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- ContentManager.isChangedBy now respects the null-as-empty property of the five content fields where null and empty have the same value: arches, content url, GPG url, release version, and required tags
- Refresh will no longer flag content for update when the only change appears to be setting a null-as-empty field to an empty string when the local value is null
> [M] CANDLEPIN-580: Fixed missing null-as-empty check in content equality test

- src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- src/main/java/org/candlepin/controller/refresher/builders/ContentNodeBuilder.java
- src/main/java/org/candlepin/controller/refresher/builders/ProductNodeBuilder.java
- src/main/java/org/candlepin/controller/refresher/mappers/AbstractEntityMapper.java
- src/main/java/org/candlepin/controller/refresher/mappers/ContentMapper.java
- src/main/java/org/candlepin/controller/refresher/mappers/EntityMapper.java
- src/main/java/org/candlepin/controller/refresher/mappers/PoolMapper.java
- src/main/java/org/candlepin/controller/refresher/mappers/ProductMapper.java
- src/main/java/org/candlepin/controller/refresher/nodes/AbstractNode.java
- src/main/java/org/candlepin/controller/refresher/nodes/EntityNode.java
- src/main/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitor.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/OwnerProductCurator.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/test/java/org/candlepin/controller/refresher/RefreshWorkerTest.java
- src/test/java/org/candlepin/controller/refresher/builders/ContentNodeBuilderTest.java
- src/test/java/org/candlepin/controller/refresher/builders/ProductNodeBuilderTest.java
- src/test/java/org/candlepin/controller/refresher/mappers/AbstractEntityMapperTest.java
- src/test/java/org/candlepin/controller/refresher/mappers/ContentMapperTest.java
- src/test/java/org/candlepin/controller/refresher/mappers/ProductMapperTest.java
- src/test/java/org/candlepin/controller/refresher/nodes/AbstractNodeTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ContentNodeVisitorTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/policy/AutobindRulesTest.java
- src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
- src/test/java/org/candlepin/policy/PoolRulesTest.java
- Fixed an issue where a "dirty" local reference to one or more
existing entities would trigger a global org-entity remapping,
but would not fix the mapping error in the entity model
- Reduced the conditions in which the global org-entity remapping
logic would be invoked to only cases where an org has one or
more missing org-entity mappings
- Entity trees which contain one or more dirty nodes will now be
entirely rebuilt, clearing the versioning of any dirty node and
all nodes above any dirty nodes in the tree
- Versioning lookup will now be skipped for dirty nodes to avoid a
case where the rebuild process will resolve to an existing
entity, undoing the work of the rebuild step
- Extremely rare cases where entity version resolution would
result in an entity mapping back to itself will now …
> [M] CANDLEPIN-580: Fixed various remapping issues during refresh

- bin/deployment/deploy
- bin/deployment/gen_certs.sh
- src/main/java/org/candlepin/auth/SSLAuth.java
- Updated the dev environment certificate generation script to
support generating certs signed by a given CA certificate
- Added support for specifying multiple hostnames or addresses to
add to the cert's subject alt name extension
- Removed the legacy keystore generation call from the deploy
script
> [M] CANDLEPIN-565: Updated dev environment cert generation script

- bin/deployment/deploy
- config/candlepin/candlepin.conf.template
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- Uses the existing lookup for unrun liquibase change sets to determine  the need for executing the update
- Has 4 levels of action
- Defaults to bypassing the process
- Update for liquibase package use to avoid deprecated methods
> CANDLEPIN-569: Run liquibase update on startup

- .github/workflows/sonar_branch_analysis.yml
- build.gradle
- We need this for when sonarcloud compares each PR code's analysis with the analysis of its target branch. If it's not there, then the PR analysis will show sonar issues that aren't actually in the PR code itself, but only exist in the target branch's commits that weren't analysed yet.
> CANDLEPIN-505: Add Sonarcloud long-lived branch analysis GH Action

- .github/workflows/pr_verification.yml
- .github/workflows/sonar_branch_analysis.yml
- When pushing a new commit on a PR or branch, we only care about the workflow on the latest change, so cancel workflows that on outdated commits that are in progress.
> [M] Cancel outdated GH Actions workflows on new commits

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/OwnerClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Contents.java
- spec-tests/src/test/java/org/candlepin/spec/pools/RefreshPoolsSpecTest.java
- src/main/java/org/candlepin/async/tasks/RefreshPoolsForProductJob.java
- src/main/java/org/candlepin/async/tasks/RefreshPoolsJob.java
- src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- src/main/java/org/candlepin/controller/PoolManager.java
- src/main/java/org/candlepin/controller/Refresher.java
- src/main/java/org/candlepin/controller/refresher/RefreshWorker.java
- src/main/java/org/candlepin/controller/refresher/mappers/AbstractEntityMapper.java
- src/main/java/org/candlepin/controller/refresher/mappers/EntityMapper.java
- src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/async/tasks/RefreshPoolsForProductJobTest.java
- src/test/java/org/candlepin/async/tasks/RefreshPoolsJobTest.java
- src/test/java/org/candlepin/async/tasks/UndoImportsJobTest.java
- src/test/java/org/candlepin/controller/PoolManagerTest.java
- src/test/java/org/candlepin/controller/RefresherTest.java
- src/test/java/org/candlepin/controller/refresher/RefreshWorkerTest.java
- src/test/java/org/candlepin/policy/PoolRulesInstanceTest.java
- src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
- src/test/java/org/candlepin/policy/PoolRulesTest.java
- Added support for performing forced-update refresh operations, which will cause refreshed entities to be updated even in cases where an explicit change in data is not detected
- Added the "force" query parameter to the refresh pools API endpoint (PUT /owners/{owner_key}/subscriptions), which will put the refresh operation into forced-update mode
- Removed the trace-level logging of upstream subscriptions and product data from the refresh operation
> [M] CANDLEPIN-589: Added support for forced-update owner refresh

- .github/workflows/sonar_branch_analysis.yml
- Avoid errors in the long-lived branch sonar analysis around JVM heap space running out.
> [M] Increase gradle memory for sonar analysis reports

- .github/workflows/pr_verification.yml
- .github/workflows/sonar_pr_analysis.yml
Workflows triggered by PRs from forks do not have access to secrets, so jobs like sonar cannot run. Moving sonar job to a separate workflow triggered by workflow_run lets it access secrets.
> Run Sonar scan as a separate workflow

- .github/containers/Dockerfile
- .github/containers/mariadb.docker-compose.yml
- .github/containers/postgres.docker-compose.yml
- .github/containers/server.xml
- .github/workflows/pr_verification.yml
- src/main/java/org/candlepin/guice/CustomizableModules.java
I wanted to add some additional information on some the choices that were made for migrating the spec tests to Github Actions.
For the spec tests jobs, I used a matrix for the two databases (postgres and mariadb) and the two modes (standalone and hosted) to create 4 jobs after the Candlepin image build job has completed. To run the database and Candlepin container, I choose to use docker-compose instead of the Github service containers for a couple of reasons.
- I don't believe you can conditionally start the database containers running as service containers based on the job's matrix database value. So, you would have to create both a mariadb and postgres as service containers and only use one of them for the spec test that is running.
- We can add database specific environment variables …
> [M] CANDLEPIN-504: Migrated spec tests to GH Actions

- containers/candlepin-base/setup-devel-env.sh
Java 11 is the minimum for sonarcube
> CANDLEPIN-603: Update Java version in build images

- .github/workflows/pr_verification.yml
- dependencies.gradle
- spec-tests/build.gradle
- spec-tests/src/test/java/org/candlepin/spec/content/ContentVersioningSpecTest.java
- Add concurrency limit to spec tests
- Disable Gradle spec test reports
- Use lazy config in spec tests
- Fixed content versioning spec. Occasionally it failed with concurrent modification exception in test code.
> Minor spec test optimization

- .github/workflows/pr_verification.yml
- .github/workflows/sonar_pr_analysis.yml
- build.gradle
- Disable unnecessary html and csv reports
- Upload only coverage info in unit tests
- Generate test report from coverage info during sonar scan
> Fix test coverage in Sonar scan

- .github/containers/Dockerfile
- .github/containers/postgres.docker-compose.yml
- .github/workflows/pr_verification.yml
- updated postgres docker-compose health check
- updated spec test Dockerfile to use UBI 9 base image
I created a PR from a forked repository to validate that the spec tests properly run:
https://github.com/candlepin/candlepin/actions/runs/5338261121/jobs/9675387427
> [M] CANDLEPIN-610: GH actions spec tests can't push images from forks

- .github/workflows/pr_verification.yml
- settings.gradle
This is the gradle scan I mentioned some time ago. It will enable scan only on GH Actions and will let us check if there are ways we could optimize our build.
> Enable Gradle Build Scan on GH Actions

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Permissions.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Roles.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/UserUtil.java
- spec-tests/src/test/java/org/candlepin/spec/activationkey/ActivationKeySpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- src/main/java/org/candlepin/auth/SubResource.java
- src/main/java/org/candlepin/auth/UserAuth.java
- src/main/java/org/candlepin/auth/UserPrincipal.java
- src/main/java/org/candlepin/auth/permissions/ActivationKeyCreationPermission.java
- src/main/java/org/candlepin/auth/permissions/ActivationKeyManagementPermission.java
- src/main/java/org/candlepin/auth/permissions/PermissionFactory.java
- src/main/java/org/candlepin/resource/ActivationKeyResource.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/main/java/org/candlepin/service/impl/DefaultUserServiceAdapter.java
- src/main/java/org/candlepin/service/model/PermissionBlueprintInfo.java
- src/test/java/org/candlepin/auth/permissions/ActivationKeyCreationPermissionTest.java
- src/test/java/org/candlepin/auth/permissions/ActivationKeyManagementPermissionTest.java
- Relaxed the authorization requirements for activation key management operations by adding a new permission specifically for providing authorization, instead of requiring only org admin or super admin priviledges
- Updated caching of org lookups during permission building
- Updated verification on several activation key endpoints to use the standard authorization logic
- Updated permission conversion to permit permission blueprints to result in the creation of more than one explicit permission
> [M] CANDLEPIN-638: Relax auth restrictions for activation key management

- .github/scripts/i18n.sh
- When the i18n job runs in GH Actions, some non-staged files end up with their file mode changed, which causes the 'git diff' to flag them as actual changes, and ends up pushing redundant commits such as the POT-Creation-Date update. This change only runs the diff on the keys.pot file to avoid issues like that.
> [4.2] During i18n job, only check for diffs on the .pot file

- .github/scripts/i18n.sh
- When the i18n job runs in GH Actions, some non-staged files end up with their file mode changed, which causes the 'git diff' to flag them as actual changes, and ends up pushing redundant commits such as the POT-Creation-Date update. This change only runs the diff on the keys.pot file to avoid issues like that.
> [4.1] During i18n job, only check for diffs on the .pot file

- .github/scripts/i18n.sh
- When the i18n job runs in GH Actions, some non-staged files end up with their file mode changed, which causes the 'git diff' to flag them as actual changes, and ends up pushing redundant commits such as the POT-Creation-Date update. This change only runs the diff on the keys.pot file to avoid issues like that.
> [M] During i18n job, only check for diffs on the .pot file

- src/main/resources/db/changelog/20230811183400-add-indexes-certificate-cleanup.xml
- src/main/resources/db/changelog/changelog-update.xml
- When there was a lot of old data in the Content Access Certificate table, it to hours for the cleanup to process
- Indexes added to tables that have a serial id column that were not indexed like other similar tables
- Index added to consumer table for content access cert id column
> 2231503: CertificateCleanupJob execution takes a very long time; CANDLEPIN-643

- src/main/java/org/candlepin/jackson/OffsetDateTimeDeserializer.java
- src/main/java/org/candlepin/jackson/OffsetDateTimeSerializer.java
- src/test/java/org/candlepin/jackson/OffsetDateTimeDeserializerTest.java
- src/test/java/org/candlepin/jackson/OffsetDateTimeSerializerTest.java
- Reverted a change that modified the way date/time fields with timezone offset were serialized such that it no longer includes the optional colon in the timezone offset
- Updated the date/time deserializer to no longer accept arbitrary timezone IDs (such as "America/New York", or "UTC") in place of a proper timezone offset, or the zero-offset specifier ("Z")
- Added an additional test to check that an exception is thrown when a malformed timezone offset is received
> [M] CANDLEPIN-650: Reverted date/time serialization change

- src/main/java/org/candlepin/jackson/OffsetDateTimeDeserializer.java
- src/main/java/org/candlepin/jackson/OffsetDateTimeSerializer.java
- src/test/java/org/candlepin/jackson/OffsetDateTimeDeserializerTest.java
- src/test/java/org/candlepin/jackson/OffsetDateTimeSerializerTest.java
- Reverted a change that modified the way date/time fields with timezone offset were serialized such that it no longer includes the optional colon in the timezone offset
- Updated the date/time deserializer to no longer accept arbitrary timezone IDs (such as "America/New York", or "UTC") in place of a proper timezone offset, or the zero-offset specifier ("Z")
- Added an additional test to check that an exception is thrown when a malformed timezone offset is received
> [4.3.7] CANDLEPIN-650: Reverted date/time serialization change

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/StatusCodeAssertions.java
- spec-tests/src/test/java/org/candlepin/spec/SubscriptionResourceSpecTest.java
- src/main/java/org/candlepin/resource/SubscriptionResource.java
- src/main/java/org/candlepin/service/impl/ImportSubscriptionServiceAdapter.java
- src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
- Fixed a NullPointerException (NPE) that occurred when attempting to activate a subscription in standalone mode
- Moved user-facing error message generation for subscription activation out of the adapter domain
- Added a unit and spec test for verifying the correct behavior in standalone mode
> [M] CANDLEPIN-648: Fixed NPE when activating subscriptions in standalone

- .github/workflows/pr_verification.yml
During backporting GH action I need to get logs from runners with spec test. So I write this to get logs and upload them as artifacts. I think it could be useful also in main, if not just close it. Or if you want more logs to collect just write me. Now its collecting docker log, candlepin logs and tomcat logs. It collects them only when spec test fail, so we save time on successful run.
> [M] Collecting logs from spec tests runners in GH action

- .github/actions/rebase/action.yml
- .github/workflows/rerun_workflow_on_push.yml
- Create a workflow that triggers when a PR is closed, and it will rerun all workflows associated with the affected branch
- Added feature when you mark PR with label `skip CI` it will not rerun affected workflows
- **We need to start again using merge commits, otherwise it doesn't work**
> [M] CANDLEPIN-619: Re-run PR workflow when target branch gets pushed

- .github/workflows/pr_verification.yml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/DatabaseEmployed.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/NotWithMySql.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- src/main/java/org/candlepin/bind/PoolOpProcessor.java
- src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
This issue arises because the pool sorting and locking is happening in sub-sets based on key. The entitlement revoke sorts on all the pools that are attached. The difference in sort order while locking between the actions causes a deadlock when a force re-registration is done concurrently. Existing consumers that are all using the same combination (>1) of keys will have this issue if the earlier keys have "later" pool ids.
You can see the error if you comment out the new locking lines in ConsumerBindUtil.
Note that this does not solve an issue with the volume of concurrent force refresh operations that can successfully occur without lock wait timeouts.
> 2213261: [M] Ensure pool lock order for activation keys

- .github/workflows/pr_verification.yml
- dependencies.gradle
- spec-tests/build.gradle
- spec-tests/src/test/java/org/candlepin/spec/bootstrap/assertions/DatabaseEmployed.java
- spec-tests/src/test/java/org/candlepin/spec/bootstrap/assertions/NotWithMySql.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
This issue arises because the pool sorting and locking is happening in sub-sets based on key. The entitlement revoke sorts on all the pools that are attached. The difference in sort order while locking between the actions causes a deadlock when a force re-registration is done concurrently. Existing consumers that are all using the same combination (>1) of keys will have this issue if the earlier keys have "later" pool ids.
You can see the error if you comment out the new locking lines in ConsumerBindUtil.
Note that this does not solve an issue with the volume of concurrent force refresh operations that can successfully occur without lock wait timeouts.
> 2213245: [4.2] Ensure pool lock order for activation keys

- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- src/main/java/org/candlepin/auth/permissions/UsernameConsumersPermission.java
- This issue allowed a user that has no 'create consumer' permission in a certain org, to create consumers in it, if they could guess the organization key.
> [4.3.7] Disallow creating consumers in org without permission

- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- src/main/java/org/candlepin/auth/permissions/UsernameConsumersPermission.java
- src/test/java/org/candlepin/auth/permissions/UsernameConsumersPermissionTest.java
- This issue allowed a user that has no 'create consumer' permission in a certain org, to create consumers in it, if they could guess the organization key.
> [M] Disallow creating consumers in org without permission

- api/candlepin-api-spec.yaml
* OpenAPI spec file contained confusing description related to the case, when client want to delete consumer and client does not have sufficient permissions doing that.
> Fix confusing string in Spec API related to unregister

- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/hostedtest/HostedTestCloudRegistrationAdapter.java
- src/main/java/org/candlepin/hostedtest/HostedTestDataStore.java
- src/main/java/org/candlepin/hostedtest/HostedTestResource.java
- src/main/java/org/candlepin/model/AnonymousCloudConsumer.java
- src/main/java/org/candlepin/model/PoolCurator.java
- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/main/java/org/candlepin/service/model/CloudAuthenticationResult.java
- src/main/resources/db/changelog/20230803000000-create-anonymous-consumers.xml
- src/test/java/org/candlepin/auth/AnonymousCloudConsumerPrincipalTest.java
- src/test/java/org/candlepin/auth/AnonymousCloudRegistrationAuthTest.java
- src/test/java/org/candlepin/auth/permissions/AnonymousCloudConsumerPermissionTest.java
- src/test/java/org/candlepin/model/AnonymousCloudConsumerCuratorTest.java
- src/test/java/org/candlepin/model/AnonymousCloudConsumerTest.java
- src/test/java/org/candlepin/model/PoolCuratorTest.java
- src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- src/test/java/org/candlepin/resteasy/filter/VerifyAuthorizationFilterTest.java
- updated cloud offering hosted test endpoint to use multiple products
- PoolCurator.hasPoolForProduct updated to check pools for multiple products
> [F] CANDLEPIN-675: Update anon cloud consumers to store multiple SKUs

- .github/workflows/gradle_wrapper_update.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Add a workflow that periodically checks for Gradle Wrapper updates and opens a PR if update is available.
- Switch to wrapper distribution to bin for faster setup. It can be switched to full locally.
> Gradle Wrapper auto-update workflow

- bin/scripts/code/setup/cpdb
- Since Liquibase v4.23.0 it no longer reports to liquibase hub and the option was removed.
> Remove deprecated liquibase cli option

- bin/scripts/code/setup/cpdb
- Since Liquibase v4.23.0 it no longer reports to liquibase hub and the option was removed.
> [4.3] Remove deprecated liquibase cli option

- containers/release.Containerfile
Verified by building a war file and then using the release.Containerfile to build a Candlepin docker image and then running then running that docker image with a Postgres container.
> [M] Updated release.Containerfile to use latest ubi9 as base image

- .github/workflows/rerun_workflow_on_push.yml
With new feature branches we were not doing scan on push on them. So sonar was not working. 
Added rule to be able scan all feature branches on push.
> Enable sonar base scan for all feature branches

- client/src/main/java/org/candlepin/resource/HostedTestApi.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/StatusCodeAssertions.java
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/hostedtest/HostedTestCloudRegistrationAdapter.java
- src/main/java/org/candlepin/hostedtest/HostedTestDataStore.java
- src/main/java/org/candlepin/hostedtest/HostedTestResource.java
- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/main/java/org/candlepin/service/CloudRegistrationAdapter.java
- src/main/java/org/candlepin/service/exception/CloudRegistrationNotSupportedForOfferingException.java
- src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- First party (1P) offerings are not supported for the autoregv2 MVP implementation. Handle them gracefully with a meaningful error for the clients.
> [F] CANDLEPIN-707: Handle rejection for 1P offering systems

- src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java
- src/main/java/org/candlepin/service/CloudRegistrationAdapter.java
- src/main/java/org/candlepin/service/exception/CloudAccountOrgMismatchException.java
- src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
- Defines adapter interface exception in case the cloud account setup cannot be done yet due to an org key conflict upstream of Candlepin.
> [F] Add CloudAccountOrgSetupJob org mismatch case exception

- .github/containers/mariadb.docker-compose.yml
- .github/containers/postgres.docker-compose.yml
- .github/workflows/spec_tests.yml
- Removed the Github actions build_image job
- Added build section to spec Github actions docker-compose files
Instead of using a Github actions job to build an image and push to the Github container registry for non-forked PRs and then pulling the image when we are running `docker compose up`, we can use the `--build` option when running `docker compose up` and build the image and then run the container in the same command.
Also, for forked PRs we won't have to upload and download the image tar file, we can just run `docker compose up` with the `--build` option.
Build of a forked PR to verify that the changes are compatible with forked PRs: https://github.com/candlepin/candlepin/actions/runs/6856289293/job/18643172392
> [M] Build Github actions spec test containers using docker compose build

- .github/workflows/spec_tests.yml
It looks like we lost the Github actions spec test log collection functionality when we migrated the spec tests from the `pr_verification.yml` file to the `spec_test.yml` file.
The problematic commit:
https://github.com/candlepin/candlepin/commit/f6dc654e9dd5e8746d2d1685e2f29c2b9fcb0138#diff-45ec1ef1d052754056fdd7f77fdcf8a155e4fe80a9b66d7873358ae2c63a4758
> [M] Readded log collection for GH actions spec tests

- build.gradle
- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/main/java/org/candlepin/model/AbstractHibernateObject.java
- src/main/java/org/candlepin/paging/FieldComparatorFactory.java
- src/main/java/org/candlepin/paging/Page.java
- src/main/java/org/candlepin/paging/PageRequest.java
- src/main/java/org/candlepin/paging/PagingUtil.java
- src/main/java/org/candlepin/paging/PagingUtilFactory.java
- src/main/java/org/candlepin/paging/ReflectionFieldComparatorFactory.java
- src/main/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptor.java
- src/test/java/org/candlepin/paging/Pageable.java
- src/test/java/org/candlepin/paging/PagingUtilFactoryTest.java
- src/test/java/org/candlepin/paging/PagingUtilTest.java
- src/test/java/org/candlepin/paging/ReflectionFieldComparatorFactoryTest.java
- Added a new utility, PagingUtil, which provides methods to apply paging to streams and collections
- Moved AbstractHibernateObject.DEFAULT_SORT_FIELD to PageRequest to better align with the other defaults and to further separate paging logic from the database model
- Updated Page and PageRequest's void mutators to return a reference to the object for fluent-style invocation chaining
> [M] CANDLEPIN-318: Added new utility for abstract universal paging logic

- spec-tests/build.gradle
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java
- src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java
- src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
- Set Owner.displayName to make sure owner gets created.
- Add spec test to assert that the CloudAccountOrgSetupJob creates an owner when one doesn't exist.
- Update all cloud autoreg auth calls in spec tests to use no authentication (like in reality) instead of admin credentials.
> [M] CANDLEPIN-722: Fix CloudAccountOrgSetupJob owner creation error

- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- Remove a coupld of seconds from a date used in a query to avoid issue with Mysql truncating milliseconds on dates.
- Also, add missing space in translatable string.
> [M] Fix flaky CloudAccountOrgSetupJob spec test

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/CandlepinMode.java
- The import spec tests would sometimes fail with a ConcurrentModificationException when trying to setup the available test extensions map.
> [M] Fix ConcurrentModificationException in import spectests

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/CertificateAssert.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/JobStatusAssert.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/cert/X509Cert.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/OID.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementCertificateV3SpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java
- src/main/java/org/candlepin/model/Pool.java
- src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- Updated the logic for entitlement certificate generation to only include the top-level product namespace OID if the namespace is a non-null, non-blank value
- Added additional spec tests to verify the presence or non-presence of the entitlement namespace OID in the certificates
- Updated the unit tests for entitlement namespace extension generation
> [M] CANDLEPIN-736: Updated entitlement certificate namespace logic

- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
- src/test/java/org/candlepin/model/AnonymousCloudConsumerCuratorTest.java
- src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- Fix issue with checking if the relevant pools exist in Candlepin during registration with an anonymous token, which should not be checked when the owner does not even exist upstream of Candlepin. Also re-factored this method to read better.
- Make sure the CloudAccountOrgSetupJob creates anonymous owners with SCA as the current and only possible content access mode.
- Make sure the CloudAccountOrgSetupJob creates non-anonymous owners with the default content access mode and content access mode list.
- Remove CloudAccountOrgSetupJob from the list of scheduled jobs since it isn't one.
> [M] CANDLEPIN-743: Fix autoregv2 reauthentication & other flow updates

- src/main/java/org/candlepin/async/tasks/CertificateCleanupJob.java
- src/main/java/org/candlepin/model/AnonymousCloudConsumerCurator.java
- src/main/resources/db/changelog/20240101162555-update-anon-cert-foreign-key.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/async/tasks/CertificateCleanupJobTest.java
- src/test/java/org/candlepin/model/AnonymousCloudConsumerCuratorTest.java
- src/test/java/org/candlepin/model/AnonymousCloudConsumerTest.java
- Update the foreign key from cp_anonymous_cloud_consumers to cp_anonymous_certificates to not be CASCADE on delete, and make sure the CertificateCleanupJob unlinks those consumers before deleting their certs to avoid this constraint.
- Add missing foreign key from cp_anonymous_certificates to cp_cert_serial.
> [M] CANDLEPIN-758: Update/add foreign keys around cp_anonymous_certificates

- src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- In MariaDB scenarios where milliseconds are not kept in date fields a comparison to determine a date change in the start or end field fails
- The comparison now only uses dates to the second to make its determination
See the Jira card for steps to reproduce. Both hosted DB versions should pass/fail with the same code.
> CANDLEPIN-731: Comparison for pool dates fails without milliseconds

- src/main/java/org/candlepin/audit/ActivationListener.java
- src/test/java/org/candlepin/audit/ActivationListenerTest.java
- Will bypass email sending if event data is null or a subscription id is not in the data
> CANDLEPIN-739: Catch scenario with null event data

- build.gradle
- dependencies.gradle
- src/main/java/org/candlepin/cache/AnonymousCertContent.java
- src/main/java/org/candlepin/cache/AnonymousCertContentCache.java
- src/main/java/org/candlepin/cache/MultiKey.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/cache/AnonymousCertContentCacheTest.java
- src/test/java/org/candlepin/config/TestConfig.java
- src/test/java/org/candlepin/controller/ContentAccessManagerDBTest.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- Created ConsumerCertificateContentCache to cache cert content
- Added the cache to the ContentAccessManager and attempt to use the cached content when creating anonymous content access certificates
- Removed unused CloudRegistrationAdapter and PoolCurator from the ConsumerResource class
I have some concerns about needing to add an upper bound entry limit to the ConsumerCertificateContentCache to prevent the cache from consuming potentially too much memory.  I created the following jira for determining if we should limit the max number of entries:
https://issues.redhat.com/browse/CANDLEPIN-759
> [M] CANDLEPIN-733: Created anonymous certificate content cache

- src/main/java/org/candlepin/model/CertificateSerialCurator.java
- src/main/resources/db/changelog/20230811183400-add-indexes-certificate-cleanup.xml
- src/main/resources/db/changelog/20240104162911-unrevoke-subscription-certs.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/async/tasks/CertificateCleanupJobTest.java
This PR adds back the previously reverted commits for improving the speed of CertificateCleanupJob (9fef94d5f625ae24f530cd0caadae1dc5da3dbec and 7d67a8b1dff719ff12475db63af03c4911a42cc1),
while also fixes the foreign key violation against the cp_certificate table.
> [4.3] Fix CertificateCleanupJob fk violation & add back indexes (CANDLEPIN-741)

- src/main/java/org/candlepin/resource/OwnerResource.java
- Added a missing LinkedResource annotation to the /owners/{key}/environments endpoint to restore the environments listing to the resources endpoint
> [M] CANDLEPIN-772: Fixed missing environment resource

- api/candlepin-api-spec.yaml
- Renamed EnvironmentDTO.content_prefix to .contentPrefix to better match the existing field name formatting conventions
> [M] CANDLEPIN-776: Updated the content prefix field name in EnvironmentDTO

- dev-container/docker-compose.yml
- updated the Candlepin health check to use curl with insecure option
To replicate the issue run `docker compose -f ./dev-container/docker-compose.yml up -d --wait` from the root of the project directory. Using whe `--wait` option will force the command to wait for all healthy health checks, but Candlepin will fail to change to healthy despite properly starting up. 
Running the current health check by itself returns:
```
wget --tries=1 --spider https://localhost:8443/candlepin/status
Spider mode enabled. Check if remote file exists.
--2024-01-16 10:42:54--  https://localhost:8443/candlepin/status
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8443... connected.
ERROR: The certificate of ‘localhost’ is not trusted.
ERROR: The certificate of …
```
> [M] Updated Candlepin health check in dev compose file

- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- src/main/java/org/candlepin/model/EntitlementCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Updated the owner-update operation such that entitlements within the org are flagged as dirty and the last-content-update time is updated when the content prefix field is changed as part of the update
> [M] CANDLEPIN-773: Regenerate certs when org content prefix changes

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Consumers.java
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- src/main/java/org/candlepin/auth/CloudConsumerPrincipal.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- When subman uses cloud autoregistration tokens for registration it does not set the owner as a query parameter. In the case of standard autoreg tokens, the owner key is extracted from the token itself. In the case of anonymous autoreg tokens, the owner may not even exist yet, so an owner key is not included in the token at all. This change updates our tests to not set an owner query param in order to be more in line with the real scenario.
- We now extract the owner key from the newly created CloudConsumerPrincipal, instead of using the owner query param which should be empty in a realistic scenario.
> [M] Do not specify owner query param in Autoreg spec tests

- src/main/java/org/candlepin/controller/util/ContentPathBuilder.java
- src/test/java/org/candlepin/controller/util/ContentPathBuilderTest.java
- Fixed an issue which would cause full content paths to be malformed if the host contained an underscore or was otherwise detected as a non-compliant with the URI RFC
- Fixed an issue that would cause malformed content paths to trigger an unrecoverable error during path encoding. A warning will now be triggered when a malformed URI is encountered and it will be returned as-is, rather than blocking entirely.
> [M] CANDLEPIN-771: Fixed issues surrounding content path encoding

- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- When anonymous organizations are claimed, their systems are migrated to a new org, and their identity certificates are revoked. When the systems check in for the first time after the claiming, they need to have a new Identity cert generated.
> [M] CANDLEPIN-783: Generate new Identity cert for claimed systems

- src/main/java/org/candlepin/audit/Event.java
I can only assume that the jackson behavior for @XmlTransient has changed since our code was written. None of the event bodies had the eventData field when received.
I added the UUID on event creation because it makes tracking the events in the log easier. It also appears to be an oversight as the field was never set.
> CANDLEPIN-786: Remove XmlTransient tag from eventData

- api/candlepin-api-spec.yaml
- src/main/java/org/candlepin/async/tasks/ImportRecordCleanerJob.java
- src/main/java/org/candlepin/model/ImportRecordCurator.java
- src/main/java/org/candlepin/model/RoleCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/async/tasks/ImportRecordCleanerJobTest.java
- src/test/java/org/candlepin/async/tasks/UndoImportsJobTest.java
- src/test/java/org/candlepin/model/RoleTest.java
- Removed the use of CandlepinQuery in ImportRecordCurator
- Removed the use of CandlepinQuery in RoleCurator
> [M] CANDLEPIN-272: Removed cp query in ImportRecordCurator and RoleCurator 

- src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- src/test/java/org/candlepin/pki/impl/JSSPKIUtilityTest.java
- Fixed a bug in the JSS version detection logic that was
interpreting the major and minor versions together as a single
floating point value rather than individual integer values
- Fixed a bug in the JSS version detection logic that would fail
to parse the version string if it contained more than three
version components (i.e. x.y.z.a)
- Added additional logic to default to the newest known JSS
initializer when version string parsing fails for any reason
> [4.1] Fixed a bug with the JSS version detection logic

- .github/workflows/sonar.yml
- Will now fire when base branch is prepended with 'feature/'
A previous PR was pushed to main instead of my fork. This should fix it.
> Updated branch listing for sonar tests

- api/candlepin-api-spec.yaml
- src/main/java/org/candlepin/model/activationkeys/ActivationKeyCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/resource/ActivationKeyContentOverrideResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
Classes affected:
- ActivationKeyResource
- ActivationKeyCurator
- ConsumerResource
- OwnerResource
- ContentOverrideCurator
> CANDLEPIN-169: Removed CP Query from Activation Key

- client/src/main/java/org/candlepin/resource/HostedTestApi.java
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/main/java/org/candlepin/service/model/CloudAuthenticationResult.java
- src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
- src/main/java/org/candlepin/testext/hostedtest/HostedTestResource.java
- src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- Added isRegistrationOnly to CloudAuthenticationResult for cloud offering types that only require registration using a standard cloud authentication token type.
- Removed CloudRegistrationNotSupportedForOfferingException
- Removed some unused variables and white space in CloudRegistrationSpecTest
> [M] CANDLEPIN-801: Added registration only to CloudAuthenticationResult

- src/main/java/org/candlepin/model/PermissionBlueprintCurator.java
- src/test/java/org/candlepin/model/PermissionBlueprintCuratorTest.java
- Removed CP query from PermissionBlueprintCurator
- Added PermissionBlueprintCurator unit tests
In the Jira it also mentions updating the following methods, but it appears that these methods have been removed and or updated and no longer need to be updated.
- OwnerProductCurator.getOwnersByProduct
- OwnerProductCurator.getProductsByOwner
- OwnerProductCurator.getProductsByIds
- OwnerProductCurator.getProductsByIdsUsingOwnerKey
- OwnerProductCurator.getOrphanedProducts
> [F] CANDLEPIN-210: Removed CP query from PermissionBlueprintCurator

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
- spec-tests/src/test/java/org/candlepin/spec/auth/TrustedUserAuthSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/service/impl/DefaultOwnerServiceAdapter.java
- src/test/java/org/candlepin/resource/AnonymousConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerContentOverrideResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Updated createOwnerIfNeeded to create owner if it is missing for TrustedUserPrincipal.
> CANDLEPIN-802: Create Owner for TrustedUserPrincipal during consumer registration

- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/auth/permissions/ConsumerCuratorPermissionsTest.java
- src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Remove the CandlepinQuery classes from ConsumerResource and ConsumerCurator and their test classes.
> CANDLEPIN-140: Remove CandlepinQuery from ConsumerResource and ConsumerCurator

- bin/scripts/upstream_data_injector.sh
- src/main/java/org/candlepin/testext/hostedtest/HostedTestResource.java
- Updated the way JSON files are processed when injecting upstream data to support larger files and minimize likelyhood of hitting out-of-memory errors
- Restored the upstream_data_injector script to simplify the process of uploading several files in one command
> [M] Improved hosted test framework support for large JSON files

- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- removed use of CandlepinQuery from EnvironmentResourceTest
- the use of CandlepinQuery in EnvironmentResource was handled
previously
> CANDLEPIN-203: Removed CP Query from Environment

- CONTRIBUTING.md
- dev-container/candlepin-deployment.yaml
- Converted from docker-compose.yml via Kompose tool
- Uses the most recent Candlepin dev image and the newest Postres image
- The Candlepin container start does not have actual pause based on the Postgres container startup as 'podman play kube' does not have the Sidecar feature from Kubernetes yet
- The Postgres container starts quickly and does not adversely affect the Candlepin container startup
- A single command 'podman play kube candlepin-deployment.yaml' will bring everything up for use
> CANDLEPIN-804: Created kube file for candlepin-dev image

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/consumers/DeletedConsumerSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/jobs/InactiveConsumerCleanerJobSpecTest.java
- src/main/java/org/candlepin/model/DeletedConsumerCurator.java
- src/main/java/org/candlepin/resource/DeletedConsumerResource.java
- src/test/java/org/candlepin/model/DeletedConsumerCuratorTest.java
- src/test/java/org/candlepin/resource/DeletedConsumerResourceTest.java
- Created new method in DeletedConsumerCurator listAll with DeletedConsumerQueryArguments
- Updated DeletedConsumerResource method listByDate to take paging parameters and call the new curator method
- Updated candlepin-api-spec.yaml to include the paging parameters
> CANDLEPIN-234: Added paging to GET /deleted_consumers endpoint

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/resource/ContentResource.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- src/test/java/org/candlepin/resource/ContentResourceTest.java
- Created new methods in ContentCurator listAll and getContentCount to take QueryArguments
- Updated ConsumerResource method getContents to take paging parameters and use them to call the new curator methods
- Updated candlepin-api-spec.yaml to include the paging parameters
> CANDLEPIN-269: Added paging to GET /content endpoint

- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/resource/ContentResource.java
- src/main/java/org/candlepin/resource/DeletedConsumerResource.java
- src/main/java/org/candlepin/resource/JobResource.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/main/java/org/candlepin/resteasy/filter/PageRequestFilter.java
- src/test/java/org/candlepin/config/TestConfig.java
- src/test/java/org/candlepin/resteasy/filter/PageRequestFilterTest.java
- Updated the PageRequestFilter to throw a BadRequestException if a page size is specified larger than the configured max page size
- Increased the default max page size from 1000 to 3000
- Renamed the PAGING_SIZE and MAX_PAGING_SIZE constants to PAGING_DEFAULT_PAGE_SIZE and PAGING_MAX_PAGE_SIZE respectively
> [F] CANDLEPIN-819: Added enforcement of the max page size configuration

- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/main/java/org/candlepin/model/PoolCurator.java
- src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- src/test/java/org/candlepin/controller/PoolServiceFunctionalTest.java
- src/test/java/org/candlepin/model/PoolCuratorTest.java
- Updated PoolCurator to not use Hibernate Criteria in queries.
- Added missing test for PoolCurator methods.
- Removed unused code.
> CANDLEPIN-238: Updated PoolCurator to not use Hibernate Criteria

- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
- src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- Updated CloudRegistrationResource.validateCloudAuthenticationResult to not validate the cloud account ID when CloudAuthenticationResult has a true registration only value since we do not need the cloud account ID in this scenario.
Tagging @nikosmoum as I created this card and PR before he had a chance to look over the issue.
> [M] CANDLEPIN-833: Removed account ID validation when registration only

- src/main/java/org/candlepin/resource/CloudRegistrationResource.java
- src/main/java/org/candlepin/testext/hostedtest/HostedTestCloudRegistrationAdapter.java
- src/test/java/org/candlepin/resource/CloudRegistrationResourceTest.java
- Updated CloudRegistrationResource.validateCloudAuthenticationResult to only validate the owner key when CloudAuthenticationResult has a true registration only value.
Changes cherry-picked from commit 058abe56ec156550311bbdd43dcfc3e75d70e339
> [4.4.1] CANDLEPIN-833: Updated CloudAuthenticationResult validation

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- src/main/java/org/candlepin/model/OwnerCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/model/CuratorPaginationTest.java
- src/test/java/org/candlepin/model/OwnerCuratorTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Created new method in OwnerCurator listAll with OwnerQueryArguments
- Updated OwnerResource method listOwners to take paging parameters
and call the new curator method only
- Updated candlepin-api-spec.yaml to include the paging parameters
> CANDLEPIN-147: Added paging to GET /owners endpoint

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/java/org/candlepin/resource/ProductResource.java
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/resource/ProductResourceTest.java
- Created new method in ProductCurator listAll with ProductQueryArguments
- Updated ProductResource method getProducts to take paging parameters and call the new curator method
- Updated candlepin-api-spec.yaml to include the paging parameters
> CANDLEPIN-734: Added paging to GET /products endpoint

- gradle/libs.versions.toml
- spec-tests/build.gradle
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- Updated the concurrent activation key registration testing to no longer need the external awaitility library, nor need multiple runs to trigger deadlock when it's present
> [M] CANDLEPIN-829: Updated consumer activation key registration testing

- src/main/java/org/candlepin/auth/permissions/PermissionFactory.java
- src/test/java/org/candlepin/auth/permissions/PermissionFactoryTest.java
- Updated the PermissionFactory to return an empty list of permissions when there is a cache miss to retrieve an owner and the owner does not yet exist in the database instead of throwing an IllegalStateException.
> [M] CANDLEPIN-827: Removed IllegalStateException when owner does not exist

- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/util/ContentOverrideValidator.java
- src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
- Added a new configuration, candlepin.content.overrides.blocklist, to control which fields of a given content repo cannot be overridden by consumers or environments
- Retained/refactored the logic to prevent the "name" and "label" fields from being overridden, as this could cause content mapping issues
> [F] CANDLEPIN-838: Added blocklist configuration for content override fields

- CONTRIBUTING.md
- Added documentation explaining how to get the Candlepin container to start in the case that the database container does not start before the Candlepin container attempts to run the database migrations when using the podman play kube command.
For this issue, I created the following card for adding retry logic for connecting to the DB.  This would allow the Candlepin container to eventually connect to the DB container and continue running migrations.
https://issues.redhat.com/browse/CANDLEPIN-845
> [M] Added additional documentation for podman play kube health checks

- src/main/java/org/candlepin/model/ConsumerContentOverride.java
- src/main/java/org/candlepin/model/ContentOverride.java
- src/main/java/org/candlepin/model/EnvironmentContentOverride.java
- src/main/java/org/candlepin/model/activationkeys/ActivationKeyContentOverride.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/main/resources/db/changelog/20240329143555-add_environment_content_override_schema.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/ActivationKeyContentOverrideCuratorTest.java
- src/test/java/org/candlepin/model/ActivationKeyContentOverrideTest.java
- src/test/java/org/candlepin/model/ConsumerContentOverrideTest.java
- src/test/java/org/candlepin/model/ContentOverrideTest.java
- src/test/java/org/candlepin/model/EnvironmentContentOverrideTest.java
- Updated the database schema to support environment content overrides
- Added indexes to the consumer_id and the new environment_id
columns to improve content override lookup performance
- Added a constraint to the content override table to help prevent
creating overrides in invalid states
- Removed legacy constructors for content overrides and the various
subclasses
- Removed the allowance of null values on the content override
subclasses which add a "parent" entity reference
- Removed old XML annotations on the content override entities
> [F] CANDLEPIN-839: Updated schema to support environment content overrides

- src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java
- src/main/java/org/candlepin/service/model/CloudAccountData.java
- src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
- In case an org already exists in Candlepin before the CloudAccountOrgSetupJob gets to create it, it should instead make sure to set it as anonymous, if it should be marked as such.
> [M] CANDLEPIN-846: Make sure anonymous orgs are marked as such

- src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java
- src/main/java/org/candlepin/service/model/CloudAccountData.java
- src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
- In case an org already exists in Candlepin before the CloudAccountOrgSetupJob gets to create it, it should instead make sure to set it as anonymous, if it should be marked as such.
> [4.4.1] CANDLEPIN-846: Make sure anonymous orgs are marked as such

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/EntitlementClient.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- src/main/java/org/candlepin/async/tasks/RevokeEntitlementsJob.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/PoolService.java
- src/main/java/org/candlepin/guice/CandlepinModule.java
- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/EntitlementCurator.java
- src/main/java/org/candlepin/model/activationkeys/ActivationKeyCurator.java
- src/test/java/org/candlepin/TestingModules.java
- src/test/java/org/candlepin/async/tasks/RevokeEntitlementsJobTest.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/model/ActivationKeyCuratorTest.java
- src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- Created RevokeEntitlementsJob to revoke all entitlements for an owner and remove all activation key pools for an owner's activation keys.
- Created a RevokeEntitlementJob for an owner that changes from entitlement mode to SCA mode.
> [M] CANDLEPIN-832: Revoke all entitlements when owner changes to SCA mode

- .github/workflows/spec_tests.yml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/DatabaseEmployed.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/NotWithMySql.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- src/main/java/org/candlepin/bind/PoolOpProcessor.java
- src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
- This will stop a deadlock from occuring when multiple consumers are force registered concurrently
- An underlying issue with how many can be run concurrently is still subject to lock wait timeouts
> [4.3] CANDLEPIN-848 - 2213261: Ensure pool lock order for activation keys

- settings.gradle
- Switch from the soon-to-be deprecated Gradle Enterprise to Gradle Develocity, along with the necessary configuration adjustments.
Fix this warning from gradle:
WARNING: The following functionality has been deprecated and will be removed in the next major release of the Develocity Gradle plugin:
- The deprecated "gradleEnterprise.buildScan.termsOfServiceUrl" API has been replaced by "develocity.buildScan.termsOfUseUrl"
- The deprecated "gradleEnterprise.buildScan.termsOfServiceAgree" API has been replaced by "develocity.buildScan.termsOfUseAgree"
- The deprecated "gradleEnterprise.buildScan.publishAlwaysIf(condition)" API has been replaced by "develocity.buildScan.publishing.onlyIf { condition }"
- The "com.gradle.enterprise" plugin has been replaced by "com.gradle.develocity"
> [M] Upgraded gradle from enterprise to develocity

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- Updated the ContentDTO definition to include max lengths on string fields to assist the validator in catching invalid or malformed content definitions
- Fixed the output definition on the createContentBatch operation
- Added additional tests for the max length validation
> [M] Updated the API spec to include a max length for ContentDTO fields

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceContentOverrideSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentContentOverrideSpecTest.java
- src/main/java/org/candlepin/dto/api/v1/ContentOverrideTranslator.java
- src/main/java/org/candlepin/model/ConsumerContentOverride.java
- src/main/java/org/candlepin/model/ConsumerContentOverrideCurator.java
- src/main/java/org/candlepin/model/ContentOverride.java
- src/main/java/org/candlepin/model/ContentOverrideCurator.java
- src/main/java/org/candlepin/model/EnvironmentContentOverride.java
- src/main/java/org/candlepin/model/EnvironmentContentOverrideCurator.java
- src/main/java/org/candlepin/resource/ActivationKeyResource.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- src/test/java/org/candlepin/model/ActivationKeyContentOverrideCuratorTest.java
- src/test/java/org/candlepin/model/ConsumerContentOverrideCuratorTest.java
- src/test/java/org/candlepin/model/ConsumerContentOverrideTest.java
- src/test/java/org/candlepin/model/ContentOverrideTest.java
- src/test/java/org/candlepin/model/EnvironmentContentOverrideTest.java
- src/test/java/org/candlepin/resource/ActivationKeyResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerContentOverrideResourceTest.java
- src/test/java/org/candlepin/resource/EnvironmentContentOverrideResourceTest.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- src/test/java/org/candlepin/resource/RoleResourceTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Added endpoints for managing environment content overrides
- Updated consumer content override fetching to include layered overrides from any environments applicable to the consumer
- Removed .setParent from ContentOverride and its subclasses
- Updated the migration of content overrides from activation keys to consumers in ConsumerBindUtil to no longer fetch and persist each override individually (or multiple times)
- Added tests and updated testing logic where applicable
> [F] CANDLEPIN-840: Added endpoints for environment content overrides

- src/main/java/org/candlepin/service/impl/DefaultUserServiceAdapter.java
- Reduced the BCrypt cost from 12 to 4 to reduce the amount of time spent processing the auth portion of requests in dev and test environments
> [M] CANDLEPIN-849: Reduced BCrypt cost in DefaultUserServiceAdapter

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/NotWithMySql.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- Restored an annotation that was removed from the consumer resource test to verify concurrent reregistration which prevented it from running against MySQL backends
> [M] CANDLEPIN-844: Restored an annotation on the reregistration test

- .github/containers/mariadb.docker-compose.yml
- Added --innodb-print-all-deadlocks=ON to the mariadb container used to run SpecTests in GH actions to provide more information on deadlock issues.
This will help in CANDLEPIN-841 investigation. We will be able to download the logs and get more information on a deadlock if we run into the issue again.
> [M] Added innodb deadlock logging to mariadb GH actions container

- CONTRIBUTING.md
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/config/validation/ConfigurationValidatorUtil.java
- src/main/java/org/candlepin/database/DatabaseConnectionManager.java
- src/main/java/org/candlepin/database/MigrationManagementLevel.java
- src/main/java/org/candlepin/database/MigrationManager.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/test/java/org/candlepin/config/validation/ConfigurationValidatorUtilTest.java
- src/test/java/org/candlepin/database/DatabaseConnectionManagerTest.java
- src/test/java/org/candlepin/database/MigrationManagerTest.java
- src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- Moved database connection and migration logic from
CandlepinContextListener to a new DatabaseConnectionManager class and
a new MigrationManager class.
- Added database connection retry logic for when Candlepin is starting
and fails to connect to the database.
- Added max retry attempts and retry interval configurations to be used
for the database connection retry logic.
- Removed documentation in CONTRIBUTING.md regarding needing to
restart the candlepin container when using podman play kube command.
> [M] CANDLEPIN-845: Added retry logic for database connection failures

- .github/scripts/jira_target_version_check.py
- .github/workflows/jira_check.yml
- Created a Github Actions workflow and script for validating that the target branch for a PR that references a Jira that has a defined 'Target Version' field value.
I included a couple of runs that I did testing some of the possible outcomes of the Jira target version field validation.
- Example of the wrong PR target branch: https://github.com/candlepin/candlepin/actions/runs/8910712833/job/24470503727?pr=4693
- Example of multiple target versions being defined in Jira: https://github.com/candlepin/candlepin/actions/runs/8910712833/job/24470554065
- Example of a Jira issue that does not exist being in a commit message: https://github.com/candlepin/candlepin/actions/runs/8910773318/job/24470687335?pr=4693
> [M] CANDLEPIN-446: Added PR commit validation for Jira Target Version field

- spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- src/main/resources/db/changelog/20240502145033-fix_entity_namespace_type.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/resource/OwnerContentResourceTest.java
- src/test/java/org/candlepin/resource/OwnerProductResourceTest.java
- Updated the namespace column definition to be the same width as the owner key, which is the primary source for the namespace values
> [M] CANDLEPIN-853: Fixed namespace column type for layered entities

- .github/workflows/jira_check.yml
- Updated jira_check.yml to run on pull_request_target instead of pull_request so that the jira validation can access secrets for PRs from forked repos.
> [M] Updated jira_check.yml to run on pull_request_target

- src/main/java/org/candlepin/model/ContentAccessCertificateCurator.java
- src/main/java/org/candlepin/model/DistributorVersionCurator.java
- src/main/java/org/candlepin/model/ProductCertificateCurator.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/resource/DistributorVersionResource.java
- src/main/java/org/candlepin/sync/Exporter.java
- src/test/java/org/candlepin/model/ContentAccessCertificateCuratorTest.java
- src/test/java/org/candlepin/model/DistributorVersionCuratorTest.java
- src/test/java/org/candlepin/sync/ExporterTest.java
- Removed hibernate criteria from DistributorVersionCurator, ProductCertificateCurator, and ContentAccessCertificateCurator.
- Added missing java docs to curator methods.
- Added mising unit tests for ContentAccessCertificateCurator and DistributorVersionCurator.
> CANDLEPIN-820: Removed hibernate criteria from select curator classes

- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/main/java/org/candlepin/model/OwnerInfoCurator.java
- Updated OwnerInfoCurator to stop using Hibernate APIs, such as Hibernate criteria and Hibernate implementations of JPA interfaces
- Flagged all of the "secure criteria" methods in AbstractHibernateCurator as deprecated
> [M] CANDLEPIN-821: Updated OwnerInfoCurator to stop using Hibernate APIs

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Added a DISTINCT to the product UUID selection while migrating provided products to avoid failing out when multiple products are mapped to the same children
- Added conditions to the left joins of the cp_pool update statement to avoid returning multiple results from the subquery in cases where a given environment has multiple active products mapped
- Added indexes to select columns on the temporary tables to avoid unnecessary table scans during the various updates
> [M] Additional fixes for the entity layering database migration

- src/main/java/org/candlepin/model/DeletedConsumerCurator.java
- src/main/java/org/candlepin/model/EntitlementCertificateCurator.java
- src/main/java/org/candlepin/model/ExporterMetadataCurator.java
- src/main/java/org/candlepin/model/OwnerCurator.java
- src/test/java/org/candlepin/model/DeletedConsumerCuratorTest.java
- src/test/java/org/candlepin/model/EntitlementCertificateCuratorTest.java
- src/test/java/org/candlepin/model/ExporterMetadataCuratorTest.java
- src/test/java/org/candlepin/model/OwnerCuratorTest.java
- Removed hibernate criteria from DeletedConsumerCurator, EntitlementCertificateCurator, ExporterMetadataCurator, and OwnerCurator.
Note that I did not modify `OwnerCurator.getByKeySecure` method because it is used by `StoreFactory`
> CANDLEPIN-823: Removed hibernate criteria from select curator classes

- api/candlepin-api-spec.yaml
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentPrioritySpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentSpecTest.java
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- If an environment was deleted, any consumers in the environment that did not belong to any other environment were also deleted. For console.redhat.com content templates, we did not want this behavior. With deleteConsumers set to false, we left the consumers environment-less.
> [M] CANDLEPIN-856: Support environment deletion without deleting consumers

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/EnvironmentClient.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentPrioritySpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentSpecTest.java
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- Renamed the delete_consumers query parameter on the deleteEnvironment operation to retain_consumers to better reflect the behavior with respect to legacy/default behavior
- Flipped the default value of the delete_consumers parameter from true to false
- Updated the API documentation for the deleteEnvironment endpoint to include details about the new query parameter and its behavior
- Added a method overload to the EnvironmentClient to allow omitting the retain_consumers parameter
> [M] Renamed the delete_consumers query parameter on the deleteEnvironment op

- src/main/java/org/candlepin/model/CdnCurator.java
- src/main/java/org/candlepin/model/ContentOverrideCurator.java
- src/main/java/org/candlepin/model/RoleCurator.java
- src/main/java/org/candlepin/model/UserCurator.java
- Updated ContentOverrideCurator, RoleCurator, UserCurator and CdnCurator to stop using Hibernate APIs, such as Hibernate criteria and Hibernate implementations of JPA interfaces
> [M] CANDLEPIN-822: Removed hibernate criteria from select curator classes

- .github/workflows/sonar.yml
- We needed to adjust due to changes in v4, where the default behavior for downloading artifacts from forks shifted from true to false.
> [M] Updated configuration of downoald step in GH action

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Updated the entity layering script to include explicit casts in the common table expressions for recursively fetching products to avoid an issue with PostgreSQL's type inference system not having a varchar length in some cases
> [M] CANDLEPIN-865: Added explicit casts in entity layering migration

- .github/containers/Dockerfile
- CentOS Stream 8 has reached its end of life, which necessitates updating the repository URLs in our Candlepin containers to point to the CentOS Vault repositories.
> [4.2] CANDLEPIN-869: Fixed containers to transition from CS8 to Vault repos

- .github/scripts/jira_target_version_check.py
- Fixed script in CI to check Jira target version and skip commits linked to Jira when the Jira card did not contain a SAT link to a bug.
> [M] CANDLEPIN-872: Updated jira_target_version_check GH action

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Updated the casting performed by the CTEs in the entity layering migration script to be even more explicit, and directly compatible with the set of database engines Candlepin supports without the use of variables or string concatenation
- Added casts on every column in the chained, recursive CTEs, even where not strictly required; primarily for clarity, but also to ensure this same issue doesn't happen again with the other fields
- Added aliases to the cast fields for consistency and debugging purposes
- Removed the now-unused property declaration at the top of the layering migration changelog
> [M] CANDLEPIN-865: Updated explicit casts in entity layering migration

- .github/workflows/checkstyle.yml
- .github/workflows/sonar.yml
- .github/workflows/sonar_branch_analysis.yml
- .github/workflows/spec_tests.yml
- .github/workflows/unit_tests.yml
- .github/workflows/validate_translations.yml
Gradle actions will be deprecated and triggering gradle actions using arguments will be removed in v4 recommended approach for projects that include gradlew wrapper to use that.
[Deprecating gradle
](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle) [Recommended approach](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated)
> [M] Updated deprecated gradle step in CI

- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/model/dto/Content.java
- src/main/java/org/candlepin/pki/DistinguishedName.java
- src/main/java/org/candlepin/pki/certs/SCACertificateGenerator.java
- src/main/java/org/candlepin/pki/certs/X509CertificateBuilder.java
- src/test/java/org/candlepin/pki/DistinguishedNameTest.java
- src/test/java/org/candlepin/pki/certs/SCACertificateGeneratorTest.java
- src/test/java/org/candlepin/pki/certs/X509CertificateBuilderTest.java
- src/test/java/org/candlepin/util/X509HuffmanDecodeUtil.java
- Updated SCACertificateGenerator to not URL encode path separators in the organization keys or environment names used to construct content paths
- Updated X509CertificateBuilder to properly escape non-ASCII characters in the various components of the distinguishing name or subject alt name
> [M] CANDLEPIN-888: Fixed several encoding errors during certificate generation

- src/main/java/org/candlepin/pki/certs/X509CertificateBuilder.java
- src/test/java/org/candlepin/pki/DistinguishedNameTest.java
- src/test/java/org/candlepin/pki/certs/X509CertificateBuilderTest.java
- Updated the Authority Key Identifier extension generator to no longer include the issuer in the extension, as this causes some cert processors to be unable to resolve certificate chains
- Updated the Key Usage extension to be flagged as critical
> [M] CANDLEPIN-891: Updated X.509 certificate extension generation

- gradle/libs.versions.toml
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/pki/certs/AnonymousCertificateGenerator.java
- src/main/java/org/candlepin/pki/certs/SCACertificateGenerator.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- src/test/java/org/candlepin/pki/certs/AnonymousCertificateGeneratorTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Content in anonymous entitlement certificates should not be always overriden to enabled. Instead the default value from the content definition in the IT Product Service should be used, like for other (SCA/Entitlement) certs.
- Refactor OwnerContentCurator.getActiveContentByOwner() to use CTE and to avoid recursive queries.
> [M] CANDLEPIN-868: Anon Registration results in Ents with all repos Enabled

- src/main/java/org/candlepin/auth/permissions/ActivationKeyPermission.java
- src/main/java/org/candlepin/auth/permissions/AnonymousCloudConsumerPermission.java
- src/main/java/org/candlepin/auth/permissions/AsyncJobStatusPermission.java
- src/main/java/org/candlepin/auth/permissions/AttachPermission.java
- src/main/java/org/candlepin/auth/permissions/ConsumerEntitlementPermission.java
- src/main/java/org/candlepin/auth/permissions/ConsumerOrgHypervisorPermission.java
- src/main/java/org/candlepin/auth/permissions/ConsumerPermission.java
- src/main/java/org/candlepin/auth/permissions/ConsumerServiceLevelsPermission.java
- src/main/java/org/candlepin/auth/permissions/OwnerActivationKeyPermission.java
- src/main/java/org/candlepin/auth/permissions/OwnerPermission.java
- src/main/java/org/candlepin/auth/permissions/OwnerPoolsPermission.java
- src/main/java/org/candlepin/auth/permissions/Permission.java
- src/main/java/org/candlepin/auth/permissions/UserUserPermission.java
- src/main/java/org/candlepin/auth/permissions/UsernameConsumersPermission.java
- src/test/java/org/candlepin/auth/permissions/ActivationKeyPermissionTest.java
- src/test/java/org/candlepin/auth/permissions/AnonymousCloudConsumerPermissionTest.java
- src/test/java/org/candlepin/auth/permissions/OwnerActivationKeyPermissionTest.java
- Updated Permissions classes to stop using Hibernate APIs, such as Hibernate criteria and Hibernate implementations of JPA interfaces.
> [M] CANDLEPIN-902: Removed usage of Hibernate Criteria in Permissions classes

- gradle/libs.versions.toml
- Rolled back to version 3.14 of commons-lang from Apache Commons to work around an issue in Liquibase which could cause Candlepin to hang on startup on systems which do not have high entropy for the purposes of generating random data via /dev/random
> [M] CANDLEPIN-901: Rolled back to previous version of Apache Commons lang

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Added missing validCheckSum tags to the entity layering changeset to
prevent Liquibase migration errors that could occur if an environment
deployed Candlepin 4.4.2 to 4.4.9, and then attempted to deploy 4.4.10
or later
> [M] CANDLEPIN-901: Added missing validCheckSum to the entity layering changeset

- Vagrantfile
- ansible/roles/candlepin/tasks/main.yml
- Replaced Centos Stream 8 for AlmaLinux 8 for the el8 Vagrant box. This is due to the cs8 end of life changing the repository URLs and causing issues standing up the el8 Vagrant VM.
To test the changes, run `vagrant up el8`
> [M] CANDLEPIN-878: Updated Vagrant el8 to use AlmaLinux instead of CentOS

- CONTRIBUTING.md
- Removed buildr from the contributing.md file since the tool is no longer being used.
- Updated the Liquibase section in contributing.md to include steps on how to manually add changesets.
> [M] Removed buildr from contributing.md

- src/main/resources/db/changelog/20240802101300-update-anon-cert-table-cert-column.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/main/resources/db/changelog/datatypes.xml
- Updated cp_anonymous_certificate cert column to longblob as products with lots of content would cause database errors when attempting to insert the certificate into the column.
The longblob data type is also used for the cert column in the cp_ent_certificate table. Since the anonymous certificate's cert column is populated the same way that an entitlement certificate is, it makes sense to use the same type.
Verified by deploying to MySQL locally and checking the columns:
```
MariaDB [candlepin]> SHOW COLUMNS from cp_anonymous_certificates;
+------------+-------------+------+-----+---------+-------+
| Field      | Type        | Null | Key | Default | Extra |
+------------+-------------+------+-----+---------+-------+
| id         | varchar(32) | NO   | PRI | NULL    |       |
| created …
```
> [M] CANDLEPIN-907: Updated cp_anonymous_certificate cert column to longblob

- Vagrantfile
-  Increased the el8 and el9 Vagrant VM filesystem size from 10 GB to 30 GB.
Run the following command.
`vagrant up el9`
```
(14:51:33) vagrant@candlepin-el9:~/devel/candlepin (jalbrech/m/CANDLEPIN-903) $ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINTS
vda    253:0    0  20G  0 disk 
└─vda1 253:1    0  20G  0 part /
```
Output of running `df -H` inside of the Vagrant VM
```
(14:51:44) vagrant@candlepin-el9:~/devel/candlepin (jalbrech/m/CANDLEPIN-903) $ df -H
Filesystem                                                 Size  Used Avail Use% Mounted on
devtmpfs                                                   4.2M     0  4.2M   0% /dev
tmpfs                                                      2.1G   17k  2.1G   1% /dev/shm
tmpfs                                                      822M …
```
> [M] CANDLEPIN-903: Increased el8 and el9 Vagrant VM filesystem size

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Contents.java
- spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/imports/ImportSuccessSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/pools/RefreshPoolsSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/ContentQueryBuilder.java
- src/main/java/org/candlepin/resource/ContentResource.java
- src/main/java/org/candlepin/resource/OwnerContentResource.java
- src/main/java/org/candlepin/testext/manifestgen/EntityMapper.java
- src/test/java/org/candlepin/model/ContentQueryBuilderTest.java
- src/test/java/org/candlepin/resource/ContentResourceTest.java
- src/test/java/org/candlepin/resource/OwnerContentResourceTest.java
- Added the "label", "active", and "custom" filters to the query parameters of the GET /owners/{key}/content endpoint
- Added the "owner", "label", "active", and "custom" filters to the query parameters of the GET /content endpoint
- Removed the now-redundant "omit_globals" query parameter from both GET /owners/{key}/content and GET /content endpoints
- Reworked the GET /contents and GET /owner/{key}/contens endpoints to support filtering on content IDs, content labels, and the "active" and "custom" states
- Added a new query builder object for building dynamic content queries
- Updated the manifest generator test extension to create entities in a namespace rather than global to fix multiple issues with manifest generation
> [M] CANDLEPIN-913: Updated content endpoints to support improved querying

- src/main/java/org/candlepin/model/ContentCurator.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- Optimized the query backing the ContentCurator.getActiveContentByOwner method based on the shape of the data in production, and MySQL's query planner. The new query should still perform well on non-MySQL and standalone, but will no longer take 5+ seconds to prime some of its CTEs with very large data sets.
> [M] Optimized the ContentCurator.getActiveContentByOwner query

- src/main/java/org/candlepin/paging/PagingUtil.java
- Added a missing space to the error message returned when an endpoint either requires paging and no paging was specified, or the requested page size is too large
> Added a missing space to the "paging required" error message

- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceEnvironmentSpecTest.java
- src/main/java/org/candlepin/dto/api/v1/ConsumerTranslator.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- src/test/java/org/candlepin/util/UtilTest.java
- Fixed a bug that prevented the removal of all environments from a consumer via the consumer update endpoint (PUT /consumers/{uuid})
> [M] CANDLEPIN-918: Fixed bug preventing removal of consumer environments

- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/resource/OwnerResourceOwnerClaimingTest.java
- Modified `OwnerResource.claim` to check if the claimant owner exists upstream. If the claimant owner does not exist in Candlepin but exists upstream, it is now created in Candlepin before proceeding with the claim operation. This ensures that Red Hat customers can claim an anonymous organization even if the claimant organization hasn't been synced to Candlepin yet.
> [M] CANDLEPIN-922: Updated Owner claim to create owner if it exists upstream

- src/main/java/org/candlepin/async/impl/ActiveMQSessionFactory.java
- Added reconnect attempts to the server locator for the ingress session manager so that ClientSessionFactory will reconnect to another broker after a failover.
> [M] CANDLEPIN-924: Added reconnection attempts to ingress session

- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/resource/ContentResource.java
- src/main/java/org/candlepin/resource/OwnerContentResource.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- Updated the GET /content and GET /owners/.../content endpoints to translate internal model objects to DTOs in bulk to avoid performance issues associated with fetching lazily populated content fields
> [M] CANDLEPIN-923: Optimized content DTO translation

- src/main/java/org/candlepin/model/ContentOverrideCurator.java
- src/main/java/org/candlepin/resource/ActivationKeyResource.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/main/java/org/candlepin/util/ContentOverrideValidator.java
- src/test/java/org/candlepin/model/ActivationKeyContentOverrideCuratorTest.java
- src/test/java/org/candlepin/model/ConsumerContentOverrideCuratorTest.java
- src/test/java/org/candlepin/resource/ActivationKeyResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Refactored and optimized the endpoints PUT /consumers/{uuid}/content_overrides, PUT /activation_keys/{id}/content_overrides, and PUT /environments/{id}/content_overrides such that they pull all overrides in bulk instead of each individually for update.
> [M] CANDLEPIN-914: Optimized the update content overrides endpoints

- src/main/resources/db/changelog/20240920000000-update-cloud-offering-id-column-size.xml
- src/main/resources/db/changelog/changelog-update.xml
- Updated the cp_anonymous_cloud_consumers.cloud_offering_id column size from 170 to 255.
> [M] CANDLEPIN-917: Updated anon consumer cloud_offering_id column size

- src/main/java/org/candlepin/pki/huffman/PathNode.java
- src/test/java/org/candlepin/pki/huffman/PathNodeTest.java
A regression in how content paths are compressed in certs made the cert size bigger than it used to be.
> Fix Huffman content path compression regression

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Consumers.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- src/main/java/org/candlepin/controller/ConsumerManager.java
- src/main/java/org/candlepin/service/model/CloudCheckInEvent.java
- src/test/java/org/candlepin/controller/ConsumerManagerTest.java
- src/test/java/org/candlepin/resteasy/filter/ConsumerCheckInFilterTest.java
- src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
- Updated ConsumerManager.updateLastCheckIn to merge the updated
entity so that the new check-in date is populated. An IAE exception
would be thrown while creating a CloudCheckInEvent if the consumer
was not refreshed with the new last check-in date and the consumer
had a null last check-in date before the update.
- Updated CloudCheckInEvent constructor validation checks to throw
IllegalStateException instead of IllegalArgumentException for invalid
consumer state.
> [M] CANDLEPIN-928: Updated updateLastCheckIn to refresh updated consumer

- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/GuestIdCurator.java
- Queries for GuestId entities used to use an optimization where a specific guestIdLower field/column was used instead of using the LOWER SQL function. That optimization got accidentally lost during the refactor and this change brings it back.
> [M] Use guestIdLower column instead of LOWER SQL function

- containers/release.Containerfile
- Set the candlepin.hidden_resources configuration as an empty string in the development container Candlepin configurations.
1. Create the war file using `./gradlew war -Ptest_extensions=hostedtest,manifestgen`
2. Build the dev container image using the following command:
```
sudo docker build --target development -f ./containers/release.Containerfile -t testing:test . \
--build-arg WAR_FILE=./build/libs/candlepin-4.4.17.war \
--no-cache
```
3. Modify the `./dev-container/docker-compose.yml` file to use the newly created container image
4. Run `docker-compose up -d` to create the Candlepin container and the db container
5. Validate that the environment resource exists by running `curl -k https://localhost:8443/candlepin/`
> [M] Added candlepin.hidden_resources configuration to the dev image

- src/main/java/org/candlepin/model/ConsumerCloudData.java
- src/test/java/org/candlepin/model/ConsumerCloudDataTest.java
- Refactored the ConsumerCloudData class to include a `setCloudOfferingIds` method, enabling direct replacement of cloud offering IDs instead of only appending them via `addCloudOfferingIds`. This allows for flexible management of cloud offering IDs, with validation ensuring that the maximum length is not exceeded.
> [M] Updated logic for offering id in ConsumerCloudData

- src/main/java/org/candlepin/model/PoolCurator.java
- src/test/java/org/candlepin/model/PoolCuratorTest.java
- Fixed two potential null pointer exceptions (NPEs) in PoolCurator bulkDelete if either a null collection of pools or a collection of pools containing one or more null pools is passed in
> [M] CANDLEPIN-934: Fixed NPE in PoolCurator.bulkDelete

- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/test/java/org/candlepin/controller/PoolManagerTest.java
- src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- Updated AbstractHibernateCurator.lockAndLoad to no longer include null elements in its output if one or more input IDs could not be found
- Updated the output type on AHC.lockAndLoad to be a List, rather than the more generic Collection
- Updated the documentation on the two list-outputting lockAndLoad implementations to be clear and consistent regarding the inclusion of nulls when a provided ID was not found
- Replaced use of Hamcrest.assertThat in the AbstractHibernateCurator test suite with AssertJ.assertThat
> [M] CANDLEPIN-933: Updated AHC.lockAndLoad to not return null elements in collections

- src/main/java/org/candlepin/controller/ContentManager.java
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- Removed the ability for ContentManager.isChangedBy to acknowledge or flag a content as changed if the ID changed; as IDs are immutable fields
- Removed an extraneous check on the gpgUrl field that did not consider nulls and empty as equal, causing content to be considered changed when it had not actually changed
- Updated the testing in content manager to avoid using content objects as update objects, to avoid passing tests that are broken due to checks in the content object rather than isChangedBy
> [M] CANDLEPIN-938: Fixed multiple bugs in ContentManager.isChangedBy

- src/main/java/org/candlepin/model/Pool.java
- src/test/java/org/candlepin/model/PoolTest.java
- Fixed a bug in the Pool entity that can occur when checking the managed state if the manage flag had been changed to null in the backing database
> [M] CANDLEPIN-940: Fixed bug in Pool.isManaged when managed flag is null

- src/main/resources/db/changelog/20231211101743-add-pool-dirty-product-column.xml
- Fixed the format of the column name in the precondition for the liquibase task for adding the dirty_product column from camel case to snake case
> [M] CANDLEPIN-938: Fixed column name format in dirty_product precondition

- spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java
- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/java/org/candlepin/resource/OwnerContentResource.java
- src/main/java/org/candlepin/resource/OwnerProductResource.java
- src/main/resources/db/changelog/20241024154545-revert_product_content_delete_cascades.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/resource/OwnerContentResourceTest.java
- src/test/java/org/candlepin/resource/OwnerProductResourceTest.java
- Updated the product and content removal functions to no longer automatically remove references from parent products or subscriptions. Endpoints and internal functions will now, instead, fail when attempting to remove/delete a child entity that is still referenced by one or more parent entities.
- Restored a missing check that ensures products and contents being removed or updated are existing, managed entities
- Updated some tests on update and removal to verify the received errors more explicitly to avoid allowing a test pass when receiving an error from a different fail state
> [M] CANDLEPIN-938: Reverted auto-detach when removing child products and content

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/EntitlementClient.java
- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- src/main/java/org/candlepin/async/tasks/RevokeEntitlementsJob.java
- src/main/java/org/candlepin/config/ConfigProperties.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/PoolService.java
- src/main/java/org/candlepin/guice/CandlepinModule.java
- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/EntitlementCurator.java
- src/main/java/org/candlepin/model/activationkeys/ActivationKeyCurator.java
- src/test/java/org/candlepin/TestingModules.java
- src/test/java/org/candlepin/async/tasks/RevokeEntitlementsJobTest.java
- src/test/java/org/candlepin/controller/ContentAccessManagerDBTest.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/model/ActivationKeyCuratorTest.java
- src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- Created RevokeEntitlementsJob to revoke all entitlements for an owner and remove all activation key pools for an owner's activation keys.
- Created a RevokeEntitlementJob for an owner that changes from entitlement mode to SCA mode.
> [4.4.1] CANDLEPIN-832: Revoke all entitlements when owner changes to SCA mode

- spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitor.java
- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/main/java/org/candlepin/model/Branding.java
- src/main/java/org/candlepin/model/Content.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/Product.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/java/org/candlepin/model/dto/ProductData.java
- src/main/java/org/candlepin/resource/ContentResource.java
- src/main/java/org/candlepin/testext/hostedtest/HostedTestDataStore.java
- src/main/java/org/candlepin/testext/manifestgen/EntityMapper.java
- src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- src/main/resources/META-INF/persistence.xml
- src/test/java/org/candlepin/controller/PoolManagerTest.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java
- src/test/java/org/candlepin/dto/api/v1/BrandingTranslatorTest.java
- src/test/java/org/candlepin/dto/api/v1/ProductTranslatorTest.java
- src/test/java/org/candlepin/dto/manifest/v1/BrandingTranslatorTest.java
- src/test/java/org/candlepin/dto/manifest/v1/ProductTranslatorTest.java
- src/test/java/org/candlepin/dto/shim/BrandingInfoTranslatorTest.java
- src/test/java/org/candlepin/model/BrandingTest.java
- src/test/java/org/candlepin/model/ProductCuratorTest.java
- src/test/java/org/candlepin/model/ProductTest.java
- src/test/java/org/candlepin/model/dto/ProductDataTest.java
- src/test/java/org/candlepin/policy/js/pool/PoolHelperTest.java
- src/test/java/org/candlepin/test/TestUtil.java
- src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- Restored the cache annotations to the product and content entities,
and their respective collections
- Removed use of the deprecated `@fetch` annotation on the product
entity
- Enabled the setting to automatically evict entity collections when
the entity itself is evicted from cache in persistence.xml
- Updated the Branding entity to be properly immutable, following
the changes to ProductContent in an earlier commit
- Removed some extraneous or duplicate operations from
AbstractHibernateCurator
- Fixed a number of potential avenues for null pointer exceptions
in AbstractHibernateCurator and derived curators
> [M] CANDLEPIN-938: Restored L2 caching to product and content entities

- build.gradle
- Added the "async" and "paging" packages to the apiJar gradle task so that the classes are included in the candlepin-api jar.
Verified the changes by running the `./gradlew apiJar` command to produce the candlepin-api jar and then decompiled the candlepin-api jar to verify that the classes from the "async" and "paging" packages are included.
> [4.4.1] CANDLEPIN-946: Update apiJar dependency list

- src/main/resources/db/changelog/20241029000000-drop-fk-cp-owner.xml
- src/main/resources/db/changelog/changelog-update.xml
- When the satellite tried to update from version 6.15 to 6.16, we decided not to use cp2_ownerproduct/content anymore and to utilize new tables for that purpose. However, we chose to keep the original tables in case we needed to revert to the previous version. We didn’t delete the foreign keys (FK) on those tables, which prevented the deletion of custom owners due to constraint violations.
> [M] CANDLEPIN-944: Droped FK for cp2_owner_content/product on cp_owner

- src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- src/main/java/org/candlepin/model/CertificateSerialCurator.java
- src/main/java/org/candlepin/model/ConsumerContentOverrideCurator.java
- src/main/java/org/candlepin/model/ConsumerCurator.java
- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/model/ContentQueryBuilder.java
- src/main/java/org/candlepin/model/EntitlementCurator.java
- src/main/java/org/candlepin/model/EnvironmentCurator.java
- src/main/java/org/candlepin/model/PoolCurator.java
- src/main/java/org/candlepin/model/ProductCurator.java
- src/main/java/org/candlepin/model/ProductQueryBuilder.java
- src/main/java/org/candlepin/model/activationkeys/ActivationKeyCurator.java
- src/main/java/org/candlepin/testext/manifestgen/EntityMapper.java
- Updated the way query spaces are declared for all native queries to use the table names and/or entity classes as appropriate
- Updated all query space declarations to use the Hibernate API rather than the JPA query hint
> [M] CANDLEPIN-938: Updated query space declarations for native SQL queries

- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
- Manual subscription attachment via activation keys in SCA mode was initially allowed to ease the transition from Entitlement, but it was no longer needed. Auto-attachment was disabled at the Candlepin level, and Satellite 6.9+ removed subscription attachment from the UI.
> [M] 2018469: Disabled subscription attachment by Activation Key in SCA

- src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- Ignored EntityNotFoundException in ConsumerStore.lookup which can occur when a consumer is concurrently being deleted while being retrieved. By ignoring the exception we return a 404 or 410 response status code to the client instead of a 500 response status code.
This issue was discovered by a flaky spec test (ConsumerResourceSpecTest.shouldReturn404Or410WhenConcurrentRegisterIsDeletedByAnotherRequest) where a 500 response would occasionally be returned because a consumer was being retrieved by VerifyAuthorizationFilter while the consumer was concurrently being deleted.
To recreate the issue, you can run the ConsumerResourceSpecTest.shouldReturn404Or410WhenConcurrentRegisterIsDeletedByAnotherRequest test in a loop about 100 times and you will eventually run into the error. The following …
> [M] CANDLEPIN-945: Handle EntityNotFoundException in ConsumerStore.lookup

- src/main/java/org/candlepin/guice/CandlepinModule.java
- src/test/java/org/candlepin/TestingModules.java
- Updated the module configuration for ObjectMapper to ensure it is created as an eager singleton, rather than creating it on every injection
> [M] CANDLEPIN-938: Registered ObjectMapper as an eager singleton

- src/main/java/org/candlepin/auth/KeycloakConfiguration.java
- KeycloakConfiguration is now tagged as a Singleton to avoid unnecessarily instantating new instances on every request
> [M] CANDLEPIN-938: Updated KeycloakConfiguration to be a singleton

- src/main/java/org/candlepin/model/Consumer.java
- Added the cache annotation to the Consumer entity, with the READ_WRITE cache strategy
> [M] CANDLEPIN-938: Added caching to the Consumer entity

- src/main/java/org/candlepin/model/ContentCurator.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- Updated ContentCurator.getActiveContentByOwner to use Hibernate result translators instead of multiple queries and mappers to fetch active content
- getActiveContentByOwner no longer guarantees uniqueness in its output, instead leaving that responsibility up to its callers
- Removed the now-extraneous unit test for collision resolution in getActiveContentByOwner
> [M] CANDLEPIN-938: Refactored ContentCurator.getActiveContentByOwner

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- src/main/java/org/candlepin/model/CloudIdentifierFacts.java
- src/main/java/org/candlepin/model/Consumer.java
- src/main/java/org/candlepin/model/ConsumerCloudData.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/model/ConsumerCloudDataTest.java
- src/test/java/org/candlepin/model/ConsumerTest.java
- src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
- ConsumerCloudData.addCloudOfferingIds and .setCloudOfferingIds now
accept null collections and collections with null or empty values,
but will silently ignore them for the purposes of collecting and
retaining the offering IDs
- Removed use of Apache Commons StringUtil from the Util class
- Removed ConsumerCloudData.setId, .equals, and .hashCode
- Fixed a bug in the Request object which would pass through null
values to the underlying regex replace operation
> [M] CANDLEPIN-954: Relaxed constraint on null values in ConsumerCloudData

- src/main/java/org/candlepin/model/ContentCurator.java
- src/main/java/org/candlepin/resource/ContentResource.java
- src/main/java/org/candlepin/resource/OwnerContentResource.java
- src/test/java/org/candlepin/model/ContentCuratorTest.java
- Reverts commit 285644b525460623645831487905a50eac461c69 that reverted the patch for explicit bulk content translation
> [4.5] Revert "CANDLEPIN-938: Reverted explicit content bulk translation"

- src/main/java/org/candlepin/model/PoolCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- Fixed a bug that prevented the page size header from being set when fetched pools from the GET /owners/{owner_key}/pools endpoint in pages
> [4.5] CANDLEPIN-974: Restored page size header when fetching owner pools

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java
- spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- src/main/java/org/candlepin/model/CloudIdentifierFacts.java
- src/main/java/org/candlepin/model/Consumer.java
- src/main/java/org/candlepin/model/ConsumerCloudData.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/util/Util.java
- src/test/java/org/candlepin/model/ConsumerCloudDataTest.java
- src/test/java/org/candlepin/model/ConsumerTest.java
- src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
- ConsumerCloudData.addCloudOfferingIds and .setCloudOfferingIds now accept null collections and collections with null or empty values, but will silently ignore them for the purposes of collecting and retaining the offering IDs
- Removed use of Apache Commons StringUtil from the Util class
- Removed ConsumerCloudData.setId, .equals, and .hashCode
- Fixed a bug in the Request object which would pass through null values to the underlying regex replace operation
> [4.4] CANDLEPIN-954: Relaxed constraint on null values in ConsumerCloudData

- ansible/roles/candlepin/tasks/el8/el8_postgresql.yml
- ansible/roles/candlepin/tasks/el9/el9_postgresql.yml
- Added a blank address for the el8 and el9 ansible tasks to prevent an issue with the postgresql_pg_hba module and allow the Vagrant VM to be created.
The following is a workaround to an issue with postgresql.postgresql_pg_hba component in Version 3.9.0 that prevents the vagrant VM from being created.
https://github.com/ansible-collections/community.postgresql/issues/777
> [M] Added blank address for local pg_hba.conf entry

- spec-tests/src/test/java/org/candlepin/spec/AutobindDisabledForOwnerSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceEntitlementRulesTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceVirtEntitlementTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- In SCA mode, manual attachment of subscriptions was no longer needed. Auto-attachment had already been disabled at the Candlepin and Satellite (6.9+) levels. Only manifest consumers ('candlepin' or 'satellite' types) were allowed to attach entitlements to ensure manifest generation continued to function properly.
> [M] 2017774: Disallowed Manual Subscription Attachment in SCA Mode

- spec-tests/src/test/java/org/candlepin/spec/AutobindDisabledForOwnerSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceEntitlementRulesTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceVirtEntitlementTest.java
- src/test/java/org/candlepin/test/DatabaseTestFixture.java
- In SCA mode, manual attachment of subscriptions was no longer needed. Auto-attachment had already been disabled at the Candlepin and Satellite (6.9+) levels. Only manifest consumers ('candlepin' or 'satellite' types) were allowed to attach entitlements to ensure manifest generation continued to function properly.
> [4.4] 2332067: Disallowed Manual Subscription Attachment in SCA Mode

- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java
- src/main/java/org/candlepin/controller/ConsumerManager.java
- src/main/java/org/candlepin/service/model/CloudCheckInEvent.java
- src/test/java/org/candlepin/resteasy/filter/ConsumerCheckInFilterTest.java
- src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
- Removed an extraneous null/empty check on consumer cloud data while generating the cloud consumer check in event during any consumer check-in operation
> [M] CANDLEPIN-978: Removed extranous null check during consumer check in

- spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceActivationKeySpecTest.java
- src/main/java/org/candlepin/resource/ActivationKeyResource.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/test/java/org/candlepin/resource/ActivationKeyResourceTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- While SCA mode is enabled for a given organization, activation keys can no longer be created with pools, or have pools added to them
> [M] CANDLEPIN-277: Disallowed creation of AK with Pool(s) specified when on SCA

- candlepin.spec.tmpl
- Re-introduced the 'tomcat' package on all supported RHELs(RHEL8 and RHEL9) and deprecated 'pki-servlet-engine'.
> [4.3] CANDLEPIN-982: Updated RHEL dependency from pki-servlet-engine to tomcat

- candlepin.spec.tmpl
- Re-introduced the 'tomcat' package on all supported RHELs(RHEL8 and RHEL9) and deprecated 'pki-servlet-engine'.
> [4.4] CANDLEPIN-981: Updated RHEL dependency from pki-servlet-engine to tomcat

- candlepin.spec.tmpl
- Re-introduced the 'tomcat' package on all supported RHELs(RHEL8 and RHEL9) and deprecated 'pki-servlet-engine'.
> [M] CANDLEPIN-980: Updated RHEL dependency from pki-servlet-engine to tomcat

- bin/deployment/test_data_importer.py
- With the changes introduced in CANDLEPIN-277, adding pools to activation keys for SCA organizations was no longer allowed. This broke our test_data_importer.py script, as it attempted to add pools to all organizations without checking their entitlement mode. This commit updated the script to properly handle SCA organizations and avoid adding pools where not permitted.
> [M] CANDLEPIN-987: Fixed data importer

- src/main/java/org/candlepin/model/Environment.java
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/main/resources/db/changelog/20250128162900-add-last-content-update-field.xml
- src/main/resources/db/changelog/changelog-update.xml
- src/test/java/org/candlepin/model/EnvironmentTest.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- Updated environments to record the last content update timestamp whenever content was promoted or demoted to an environment, or the environment's prefix was changed. Used this timestamp to determine if the SCA certificate needed regeneration: if the last content update is newer than the certificate’s timestamp, the certificate needs to be regenerated.
> [F] CHAINSAW-356: Added last content update field to environments

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Updated the way the entity layering DB migration calculates its "best" rows in cases where collisions are expected to use window functions instead of nested aggregate queries
- Fixed a couple errors in how product attributes are queried in cases with multiple sources of a given attribute
- Fixed issues with the way custom product and content queries were flagging entities as "best", causing some entities to be omitted from the migration, or fail on partial migration
> [M] CANDLEPIN-995: Updated the entity layering migration's tiebreakers

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Updated the way the entity layering DB migration calculates its "best" rows in cases where collisions are expected to use window functions instead of nested aggregate queries
- Fixed a couple errors in how product attributes are queried in cases with multiple sources of a given attribute
- Fixed issues with the way custom product and content queries were flagging entities as "best", causing some entities to be omitted from the migration, or fail on partial migration
> [4.4] CANDLEPIN-995: Updated the entity layering migration's tiebreakers

- src/main/java/org/candlepin/exceptions/ServiceUnavailableException.java
- src/main/java/org/candlepin/exceptions/TooManyRequestsException.java
- src/main/java/org/candlepin/resteasy/filter/SecurityHoleAuthorizationFilter.java
- src/test/java/org/candlepin/exceptions/ServiceUnavailableExceptionTest.java
- src/test/java/org/candlepin/exceptions/TooManyRequestsExceptionTest.java
- Refactored the ServiceUnavailableException and the TooManyRequestsException to have the standard exception constructors.
- Added the ability to define a 'Retry-After' header for the ServiceUnavailableException.
- Added exception messages for TooManyRequestsExceptions in SecurityHoleAuthorizationFilter.
`ServiceUnavailableException` and `TooManyRequestsException` extend a `CandlepinException` and a `CandlepinException` extends a RuntimeException. This means that the headers for both the `ServiceUnavailableException` and `TooManyRequestsException` are added by the `RuntimeExceptionMapper`.
https://github.com/candlepin/candlepin/blob/main/src/main/java/org/candlepin/exceptions/mappers/RuntimeExceptionMapper.java#L67-L69
> [F] CHAINSAW-375: Refactored exceptions

- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated ConsumerResource.getEntitlementCertificateSerials to retrieve only the X509 certificate from the SCACertificateGenerator when retrieving the content access certificate serial.
> [F] CHAINSAW-358: Updated getEntitlementCertificateSerials serial retrieval

- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/main/java/org/candlepin/controller/ContentManager.java
- src/main/java/org/candlepin/controller/ProductManager.java
- src/main/java/org/candlepin/model/AbstractHibernateObject.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/main/java/org/candlepin/resource/SubscriptionResource.java
- src/test/java/org/candlepin/controller/ContentAccessManagerTest.java
- src/test/java/org/candlepin/controller/ContentManagerTest.java
- src/test/java/org/candlepin/controller/ProductManagerTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
- Removed the 'hasCertChangesSince' and 'syncOwnerLastContentUpdate' methods from the ContentAccessManager class.
> [F] CHAINSAW-361: Removed obsoleted methods from ContentAccessManager

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/CandlepinStatusAssert.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/model/ContentAccessPayload.java
- src/main/java/org/candlepin/pki/certs/SCACertificateGenerator.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated ConsumerResource.getContentAccessBody to fetch the individual components from the SCACertificateGenerator instead of retrieving the entire assembled certificate.
- Updated ConsumerResource.getContentAccessBody to return a 429 response if there is a constraint violation when persisting the SCA certificate's content access payload.
> [F] CHAINSAW-359: Updated ConsumerResource.getContentAccessBody

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Owners.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/test/java/org/candlepin/model/OwnerCuratorTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- If contentAccessModeList is not specified when creating a new org via Candlepin API, it now defaults to org_environment.
- It no longer includes entitlement by default.
- A caller can still update the owner’s contentAccessModeList to include entitlement for dev/test scenarios or other special cases.
> [M] CANDLEPIN-985: Switched default contentAccessModeList to SCA only

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Owners.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/controller/ContentAccessManager.java
- src/test/java/org/candlepin/model/OwnerCuratorTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- If contentAccessModeList is not specified when creating a new org via Candlepin API, it now defaults to org_environment.
- It no longer includes entitlement by default.
- A caller can still update the owner’s contentAccessModeList to include entitlement for dev/test scenarios or other special cases.
> [4.5] CANDLEPIN-985: Switched default contentAccessModeList to SCA only

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Response.java
- spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated ConsumerResource.exportCertificates to throw TooManyRequestsException (HTTP status code 429) when a conflict in SCA payload generation happens.
- Renamed two tests in ExportSpecTest to be more accurate.
> [F] CHAINSAW-376: Updated ConsumerResource.exportCertificates exception handling

- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated ConsumerResourceTest.validIdCertDoesNotRegenerate to not use a hard coded date that was causing the test to fail.
This test began failing today because the hard coded date is exactly 90 days from today, which is the duration where we consider an identity certificate to be expired. So, the test's tested code path is different from today forward because the tested code path checks if the ID cert is expired and the test now fails because it is considered expired.
> [M] Updated hard coded unit test date

- src/main/java/org/candlepin/async/JobManager.java
- src/main/java/org/candlepin/model/ManifestFileRecordCurator.java
- Removed duplicate logging branch logic in JobManager.
- Refactored createBlob method to use try-with-resources to properly close FileInputStream, preventing resource leaks.
> [M] CANDLEPIN-996: Fixed SAST scan issues

- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated ConsumerResourceTest.validIdCertDoesNotRegenerate to not use a hard coded date that was causing the test to fail.
> [4.4] Updated hard coded unit test date

- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated ConsumerResourceTest.validIdCertDoesNotRegenerate to not use a hard coded date that was causing the test to fail.
> [4.5] Updated hard coded unit test date

- spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
- spec-tests/src/test/java/org/candlepin/spec/pools/PoolResourceSpecTest.java
- src/main/java/org/candlepin/controller/PoolManager.java
- src/main/java/org/candlepin/model/PoolCurator.java
- src/main/java/org/candlepin/resource/OwnerResource.java
- src/main/java/org/candlepin/resource/PoolResource.java
- src/test/java/org/candlepin/model/PoolCuratorTest.java
- src/test/java/org/candlepin/resource/OwnerResourceTest.java
- src/test/java/org/candlepin/resource/PoolResourceTest.java
- Updated the list owner pools endpoint to not filter the pools twice when paging is requested.
- Updated list owner pools to return a bad request response instead of an internal server error response when an invalid order key is provided in the request.
- Moved the paging of the pools out of the PoolManager class and into the OwnerResource.listOwnerPools and PoolResource.listPools.
> [M] CANDLEPIN-999: Fixed paging for list owner pools

- .github/workflows/unit_tests.yml
Version 3 was deprecated at the beginning of the year.[1]
[1] https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> [4.3] Increased upload action version due to deprecation

- buildSrc/src/main/java/org/candlepin/gradle/SpecVersion.java
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/DefaultProperties.java
- Refactored the get() method to automatically close the InputStream acquired from loader.getResourceAsStream().
- Added a null check for when the "settings.properties" resource was not found.
> [M] CANDLEPIN-996: Additional SAST scan fixes

- CONTRIBUTING.md
- containers/logback.xml
- containers/release.Containerfile
- dev-container/candlepin-deployment.yaml
- dev-container/docker-compose.yml
- Added a ConsoleAppender to the logback.xml for the dev container image so that the Candlepin logs are output to stdout.
- Added a ConsoleAppender to the logback.xml for the dev container image to log the org.candlepin.audit.LoggingListener.AuditLog logs to stdout.
- Removed the host port for the Postgres container in dev-container/docker-compose.yml and dev-container/candlepin-deployment.yml so that the OS will choose the host port number in the port mapping.
- Updated some of the container documentation in CONTRIBUTING.md.
To test and verify the changes we can build a new development image and run the container using `podman-compose`, `docker-compose`, or `podman play kube`.
Run the following command to build the WAR file that will be used in our new image. The command includes the …
> [M] CHAINSAW-382: Updated dev container image to output Candlepin logs

- src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Updated the way the entity layering DB migration calculates its "best" rows in cases where collisions are expected to use window functions instead of nested aggregate queries
- Fixed a couple errors in how product attributes are queried in cases with multiple sources of a given attribute
- Fixed issues with the way custom product and content queries were flagging entities as "best", causing some entities to be omitted from the migration, or fail on partial migration
> [4.5] CANDLEPIN-995: Updated the entity layering migration's tiebreakers

- .github/workflows/jira_check.yml
- Due to security limitations with token usage in GitHub Actions, the Jira check was executed only for internal pull requests. This prevented workflow failures for forked PRs and ensured that sensitive tokens were not exposed.
> [M] CANDLEPIN-943: Removed JIRA target check from forks PRs

- .github/workflows/jira_check.yml
- Due to security limitations with token usage in GitHub Actions, the Jira check was executed only for internal pull requests. This prevented workflow failures for forked PRs and ensured that sensitive tokens were not exposed.
> [4.3] CANDLEPIN-943: Removed JIRA target check from forks PRs

- .github/workflows/jira_check.yml
- Due to security limitations with token usage in GitHub Actions, the Jira check was executed only for internal pull requests. This prevented workflow failures for forked PRs and ensured that sensitive tokens were not exposed.
> [4.5] CANDLEPIN-943: Removed JIRA target check from forks PRs

- src/main/java/org/candlepin/model/Consumer.java
- src/main/java/org/candlepin/model/EntitlementCurator.java
- src/main/resources/db/changelog/20250325000000-update-env-priority-column-type.xml
- src/main/resources/db/changelog/changelog-update.xml
- Updated the cp_consumer_environments.priority column from a varchar to a tinyint to prevent ordering issues when a consumer has more than 10 environments.
> [M] CANDLEPIN-990: Updated cp_consumer_environments.priority to tinyint

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/CertificateUtil.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentPrioritySpecTest.java
- src/main/java/org/candlepin/pki/huffman/Huffman.java
- src/test/java/org/candlepin/pki/huffman/HuffmanTest.java
- When 2 or more environment names contain slashes, where one environment's name is a sub path of the other, the SCA cert's Authorized Content URLs section will now only contain the path from the environment with the base path (regardless of priority of environments). Example: Given environments A and A/1 in OrgX, applied to a given consumer, only the path /OrgX/A should be present in the cert.
> [M] CANDLEPIN-1014: Fix Content URLs in SCA cert for Multi Env

- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/CertificateUtil.java
- spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentPrioritySpecTest.java
- src/main/java/org/candlepin/pki/huffman/Huffman.java
- src/test/java/org/candlepin/pki/huffman/HuffmanTest.java
- When 2 or more environment names contain slashes, where one environment's name is a sub path of the other, the SCA cert's Authorized Content URLs section will now only contain the path from the environment with the base path (regardless of priority of environments). Example: Given environments A and A/1 in OrgX, applied to a given consumer, only the path /OrgX/A should be present in the cert.
> [4.4] CANDLEPIN-1009: Fix Content URLs in SCA cert for Multi Env

- src/main/java/org/candlepin/resource/OwnerResource.java
- Added an emergency patch to prevent attempting to sort on fields of nested children in GET /owner/{key}/pools
> [M] HOTFIX: Added a check to prevent sorting on nested object fields

- src/main/java/org/candlepin/resource/OwnerResource.java
- Added an emergency patch to prevent attempting to sort on fields of nested children in GET /owner/{key}/pools
> [4.6.2] HOTFIX: Added a check to prevent sorting on nested object fields

- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- src/test/java/org/candlepin/resource/PersonConsumerResourceCreationLiberalNameRules.java
- Centralized all checks for consumer name into one method.
- Applied that method to both consumer create and update.
- Renamed tests to be more descriptive.
> [4.6.2] Add validation for name during consumer update

- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java
- src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- src/test/java/org/candlepin/resource/PersonConsumerResourceCreationLiberalNameRules.java
- Centralized all checks for consumer name into one method.
- Applied that method to both consumer create and update.
- Renamed tests to be more descriptive.
> [M] Add validation for name during consumer update

- src/main/java/org/candlepin/async/tasks/InactiveConsumerCleanerJob.java
- src/test/java/org/candlepin/async/tasks/InactiveConsumerCleanerJobTest.java
- Restored the explicit certificate deletion during inactive consumer cleanup that was erroneously removed in a previous commit
> [M] CANDLEPIN-1028: Restored cert deletion during inactive consumer cleanup

- src/main/java/org/candlepin/resource/EnvironmentResource.java
- src/test/java/org/candlepin/resource/EnvironmentContentOverrideResourceTest.java
- src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
- src/test/java/org/candlepin/test/TestEventSink.java
- Environment deletion will now generate bulk consumer deletion events when consumers are cleaned up as a result of an environment being removed
> [M] CANDLEPIN-1028: Added event generation to environment deletion

- src/main/java/org/candlepin/database/MigrationManager.java
- src/main/java/org/candlepin/guice/CandlepinContextListener.java
- src/main/java/org/candlepin/liquibase/LiquibaseConnectionGenerator.java
- src/test/java/org/candlepin/database/MigrationManagerTest.java
- src/test/java/org/candlepin/liquibase/LiquibaseConnectionGeneratorTest.java
- Updated the migration manager to use try-with-resources for its database connection to ensure it's closed when the migration operation is completed
- Renamed and moved the not-generic "DatabaseConnectionManager" to the Liquibase-specific "LiquibaseConnectionGenerator"
> [4.5] CANDLEPIN-1041: Fixed dangling Liquibase connections

- api/candlepin-api-spec.yaml
- spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/ExportUtil.java
- spec-tests/src/test/java/org/candlepin/spec/content/ContentAccessSpecTest.java
- src/main/java/org/candlepin/pki/certs/AnonymousCertificateGenerator.java
- src/main/java/org/candlepin/resource/ConsumerResource.java
- src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Updated the handling of concurrent content payload exceptions such that content access payload generation is retried at least once before returning returning a 429 to the user
- Refactored several methods in ConsumerResource surrounding content access certificate and payload generation
- Fixed a bug causing serial filtering to exclude matching certificates rather than include while fetching anonymous consumer certificates
> [M] CANDLEPIN-1059: Reduced 429s while fetching content access payloads
