candlepin/candlepin

- gutterball/src/main/java/org/candlepin/gutterball/curator/ComplianceSnapshotCurator.java
- gutterball/src/main/java/org/candlepin/gutterball/curator/ConsumerStateCurator.java
ConsumerStateCurator is no longer needed by the
ComplianceSnapshotCurator.
Also fixed some checkstyle issues.
> Removed unused object reference

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
Deadlocks are occurring in certain situations where we do a mass bind involving modifier entitlements, followed by several simultaneous requests to list entitlements. Each list call attempts
to regenerate entitlement certs, which do not technically need to be
regenerated at this point.
Allow the caller to specify that they wish to skip regeneration of any dirty
entitlements.
This is a short term fix, we may with to pursue something better longterm, but
this is a quick gain for hosted scenarios.
> Add option to skip dirty certificate regeneration on list entitlements.

- common/src/main/java/org/candlepin/common/filter/ServletLogger.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/VirtConsumerMap.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/GuestIdResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
virt-who checkins are easily blowing past the 60 second timeout that will occur with both virt-who or subscription-manager. Approx 150 hypervisors each with 15 guests is about enough to do it, in my system this was taking around 50s. 
Problem boiled down to looking up the host consumer record for every hypervisor record, and then two more queries to lookup the guest consumer and it's latest host for each guest ID on each hypervisor.
Fixed by batching up the requests and passing them in memory, so we lookup hypervisor consumers for all hypervisors in the checkin, and similarly the guest and host consumers for all guest IDs. These three large queries vs ~4500 small queries results in a close to 10x performance improvement. (50 -> 7s on my system with the sample data mentioned above)
Added a …
> Virt-Who Checkin Performance Improvements

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
Slight increase in logging for consumer updated and binds. These do not
necessarily have to be permanent but will hopefully help identify slow portions
of bind, and give some insight into what's happening in consumer updates where
we're lock wait timing out.
> Update logging to debug issues with lock wait timeouts.

- server/src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
- The tests in the ContentOverrideValidatorTest which test the
contents of collections are no longer dependent on the order
of the contents of the collections.
> ContentOverrideValidatorTest is no longer order-dependent

- gutterball/src/main/java/org/candlepin/gutterball/report/ComplianceTransformerIterator.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerStatusReport.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerStatusReportDefaultResult.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerTrendReport.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerTrendReportDefaultResult.java
- gutterball/src/main/java/org/candlepin/gutterball/report/dto/ConsumerStatusComplianceDto.java
- gutterball/src/main/java/org/candlepin/gutterball/report/dto/ConsumerTrendComplianceDto.java
- gutterball/src/test/java/org/candlepin/gutterball/TestUtils.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ConsumerStatusReportTest.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ConsumerTrendReportTest.java
By default, reports will return as little data as possible
to help with performance. This will allow
> Use minimized DTO for report defaults

- buildfile
Candlepin proper uses SLF4J, but some of the third-party libraries
(e.g. Hibernate) use Log4J instead.  Since Candlepin does not configure
Log4J, the Hibernate logging messages get lost.  By providing a bridge
between Log4J and SLF4J, we can record logging messages from Log4J.
To test:
1. Add "log4j.logger.org.hibernate.SQL=DEBUG" to /etc/candlepin/candlepin.conf.  If you are using autoconf, you can do this easily be editing custom.yaml to look something like
```yaml
candlepin.conf:
custom_logging:
"org.hibernate.SQL": "DEBUG"
```
2. Deploy the current master and import test data.  Note that Hibernate does not log any SQL.
3. Deploy this branch and import test data.  Hibernate will now display SQL.
> Provide bridge to adapt Log4J to SLF4J.

- gutterball/src/main/java/org/candlepin/gutterball/model/Status.java
- gutterball/src/main/java/org/candlepin/gutterball/resource/StatusResource.java
- gutterball/src/test/java/org/candlepin/gutterball/resource/StatusResourceTest.java
Version/Release version was coming from the config file. We were all setup to pull from version.properties so this PR does that instead.
> GB: Return correct gutterball version info

- server/bin/update-server-xml.py
There was a typo in the config stanza, 'sslEnabledProtocol'
vs 'sslEnabledProcotols', the former is ignored.
> 1153375: make dev deploys disable sslv3 by default

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/CheckIn.java
- server/src/main/java/org/candlepin/model/CheckInCurator.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CleanupCheckInsJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/resources/db/changelog/20150123105016-add-consumer-checkin-table.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/CheckInCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
Problems surface in deployments with extremely high load. Because we update the consumer's row every time they authenticate, any request running long can cause other requests to wait longer than mysql's 50 second limit trying to get the lock to update that row.
To work around this I introduced a new table for consumer check-in times. The Consumer's last checkin time is calculated as the max in the table for that consumer.
A job is included to run periodically (every 8 hours by default) and clean out all but the most recent row for each consumer. In a really big deployment, this could be well into the millions. Multiple attempts were made to delete all but the most recent row for each consumer, none would scale to that level and work on all dbs. Instead we query checkins to be deleted in …
> Eliminate Lock Contention on Consumer Last Check-In Time

- server/src/main/resources/db/changelog/20150123105016-add-consumer-checkin-table.xml
All DBMSes appear to create an index on a primary key, Oracle actually errors
out if you try to create another. (Postgres and MySQL do not)
> Fix broken db upgrade on Oracle.

- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerStatusReport.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerTrendReport.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ConsumerStatusReportTest.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ConsumerTrendReportTest.java
- changed 'custom' to 'custom_results' to avoid confusion with custom products (asked about it a couple of times)
- added actual report parameters for include/exclude parameters.
- updated description for consumer status report 'status' parameter
> Some updates to the GB reports params

- gutterball/gutterball.spec
This was only working as candlepin was expected to be there already, but in
installers it was possible for gutterball to install before tomcat arrived
leading to warnings and permissions problems.
Verification, before, if I setup this repo:
[candlepin]
name=candlepin
baseurl=http://download.devel.redhat.com/brewroot/repos/candlepin-1-rhel-6-build/latest/x86_64
And yum install gutterball, tomcat is not in the list of packages to be installed, and you get a pile of errors:
warning: user tomcat does not exist - using root
warning: group tomcat does not exist - using root
With new build including this dep change everything functions correctly and tomcat ends up installed.
> 1190040: Add tomcat dependency for gutterball.

- server/src/main/resources/db/changelog/20150123105016-add-consumer-checkin-table.xml
This option (when set to true) is unsupported on postgres and will cause an
error, *if* you're using liquibase 2.x. The issue does not surface if you are
running liquibase 3.x.
Set to false to match all existing use of addForeignKeyConstraint element.
WARNING: This will not apply clean on an existing db with the old changeset due to checksum change. I believe this is ok only developers have this deployed, who will need to regen db clean or do a little hacking if they hit the issue.
> 1194997: Don't use referencesUniqueColumn true.

- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
Attributes and provided products were not being properly copied to unmapped
guest pools on creation, resulting in breakage of the main VDC use-case.
Some cleanup will take place in the multi-org branch.
> Fix unmapped guest pools with derived product data.

- gutterball/src/main/java/org/candlepin/gutterball/config/ConfigProperties.java
- gutterball/src/main/java/org/candlepin/gutterball/receiver/EventReceiver.java
- gutterball/src/test/java/org/candlepin/gutterball/receiver/EventRecieverTests.java
If gutterball fails to connect to the event bus on startup,
pause and retry a configured amount of times before failing
completely.
Both the number of times to retry and the time between retries
are configurable.
> 1200358: Wait for successful message bus connection on startup

- server/spec/ueber_cert_spec.rb
- server/src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
This can happen for ubercert consumers in Satellite at the very least, it seems
to be happening very rarely for real systems, and the cause of this is
currently unknown. None the less we should allow them to be deleted.
> Fix NPE deleting consumer without identity cert.

- tasks/checkstyle.rake
Checkstyle was previously aborting as soon as it detected a problem.  This patch changes it so that it checks all projects and reports the results at the end.
> Run Checkstyle on all projects before failing.

- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/main/resources/db/changelog/20150316122833-add-entitlement-end-date-override.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/resource/util/InstalledProductStatusCalculatorTest.java
In the past both pools and entitlements had a start/end date. This was removed
as the data was redundant at the time, however the Entitlement getEndDate() and
setEndDate() methods remained for API compatability, and just returned the
pool's values.
With the addition of 24h unmapped guest entitlements, we actually want to have
entitlements with a different end date than the pool. This was implemented by
stamping the correct date in the cert, but not available anywhere else in the
code causing issues with things like installed product validity date ranges.
Fixed by adding an entitlement end date override. getEndDate() will return this
value if it's set, otherwise resort to the pools. Compliance code was already
properly set up to use the entitlement end date due to the original …
> 1199443: Add entitlement end date override.

- server/src/main/java/org/candlepin/sync/ProductImporter.java
- server/src/main/resources/db/changelog/20150311151612-force-all-content-metadataexpire-to-0.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/sync/ProductImporterTest.java
Imports only run in standalone, thus it's safe to assume that on import
we can force metadata expire to 0, allowing clients to immediately see
changes to published content.
On upgrade we'll flip all content to 0. This should be safe as these
tables are currently empty in production, thus this should only affect
standalone servers.
> 1200142: Force content metadata expire to 0 in standalone.

- server/src/main/resources/db/changelog/20150211111319-add-last-guest-update-table.xml
Script would fail if you had a host that had reported more than one guest ID.
Discovered much simpler query as all the data we need is technically already in
the cp_consumer_guests table, no need for the join.
> Fix SQL in guest ID checkin time upgrade script.

- server/src/main/java/org/candlepin/sync/ProductImporter.java
- server/src/test/java/org/candlepin/sync/ProductImporterTest.java
We just implemented this at 0 in commit
15653851a7bfcb14d9d86a7aec8ac974403be89c, however it has been discovered that
somehow the client plugin is interpreting 0 as unset and just ignoring the
setting entirely, which would result in the default timeout being used. (which
is not 0)
Instead we're setting for 1 second which should have the same effect.
> 1200142: Force metadata expire to 1 in standalone.

- gutterball/deps/el7.txt
Tested and found to contain the symlink, and allow gb to run on EL7 system experiencing the bug.
> 1207810: Add missing symlink for gutterball and c3p0.

- common/src/main/java/org/candlepin/common/filter/LoggingFilter.java
- common/src/main/java/org/candlepin/common/filter/ServletLogger.java
Previously the components of a request and/or response were spread
across multiple log statements.  One at INFO level would log the verb
and requested URL (or the response code) and one at DEBUG level would
log the headers and body.  Splitting what should logically be a single
unit across multiple statements made reading the logs harder than
necessary.
This patch consolidates an entire request and/or response into a single
statement.  If the logger is set to INFO, it writes a short statement
with the verb and URL combination (or response code).  If the logger is
set to DEBUG, it skips the aforementioned INFO statement and writes a
longer statement with the headers and body.
From this:
```
2015-02-04 11:50:09,849 [req=840fd586-b40b-4ef6-b3e6-0587c17d4e07, org=] INFO …
```
> Consolidate request and response logging into one log statement.

- server/spec/environment_spec.rb
- server/src/main/java/org/candlepin/model/EnvironmentContentCurator.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- EnvironmentResource will now throw a ConflictException if an API
user attempts to promote content that has already been promoted.
- Added spec tests to verify the above behavior
> 1207822: EnvironmentResource fix for duplicate content IDs

- gutterball/src/main/java/org/candlepin/gutterball/config/ConfigProperties.java
- gutterball/src/main/java/org/candlepin/gutterball/receiver/EventReceiver.java
- gutterball/src/main/java/org/candlepin/gutterball/servlet/GutterballContextListener.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
1) Establish QPID connection in a separate thread to avoid delay in bringing up the gutterball report API and stalling deployment of candlepin.
2) Properly close the gutterball context: shut down qpid connection
3) Adjusted the default retry configuration values for connecting to qpid (1h was way too long)
> Address several gutterball startup/shutdown issues

- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/resources/db/changelog/20150401140006-add-pool-type-to-db.xml
- server/src/test/java/org/candlepin/model/PoolTest.java
- Pool.getType now only reports UNMAPPED_GUEST iff the pool has both
the "pool_derived" and "unmapped_guests_only" attribute.
- Pool type DB migration queries and pool tests have been updated to
reflect the change to Pool.getType.
>  Updated the method used to determine pool types

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Submitted as a pull request, but more like experimental theatre.
The criteria is to ensure identical REST output while removing stack-trace logging for non-fatal conditions. This required removing a few thrown exceptions and then adjusting the code stack back to the resource.
All suggestions are welcome.
> 1204962: remove throw/catch/eat of runtime exception in bind

- common/pom.xml
- gutterball/pom.xml
- server/pom.xml
- tasks/pom.rake
Previously the code was only adding "Buildr::Artifact" instances to the
POM files, but sub-projects are of the type "JarTask".  What we
really needed to do was filter out instances of "Rake::FileTask".  Note
that Buildr::Artifact is descended from Rake::FileTask so we need to do
an exact match on the class type using instance_of.
> Add Candlepin sub-projects as dependencies in POM files.

- gutterball/src/main/resources/db/changelog/2014-12-03-15-39-add-event-status.xml
When upgrading from gutterball-1.0.7-1, a changeset was
breaking DB upgrades because it was modified after
gutterball-1.0.7-1 was released.
The changeset modification was not critical and could
be skipped, so this commit will allow liquibase to
accept the new md5 checksum produced due to the
changeset file modification.
> 1217058: Fixed broken changeset affecting upgrade

- server/spec/job_status_spec.rb
- server/src/main/java/org/candlepin/auth/ConsumerPrincipal.java
- server/src/main/java/org/candlepin/auth/UserPrincipal.java
- server/src/main/java/org/candlepin/auth/permissions/CheckJobStatusPermission.java
- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitleByProductsJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/main/java/org/candlepin/resteasy/interceptor/AuthInterceptor.java
- server/src/main/resources/db/changelog/20150424150412-add-owner-id-to-jobstatus.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/auth/ConsumerPrincipalTest.java
- server/src/test/java/org/candlepin/model/JobCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
Allow JobStatus to be fetched by a regular user
or consumer if they have the appropriate permission
to do so.
Permissions will be applied such that:
* a super admin can view any job status
* a user can view a job status if they have some level of access
to an org (no matter who started the job)
* a consumer can only view the status of jobs they have started
> Apply permissions while getting Job Status

- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
Previously this scenario was blocked by rule. Seems that a product
without a support_level attribute should be usable by anyone, not
just those without a service level assignment.
> 1123560: Allow consumer with service level to autobind to pool without

- server/src/main/resources/db/changelog/20150211111319-add-last-guest-update-table.xml
- Added a pair of validCheckSums to the changeset for populating the
last guest update table. These represent the current, valid, checksum
and a checksum for the version that was merged on Feb. 25, 2015.
> Added valid checksums to the last guest update table changeset

- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
Eliminate a db lookup for the exact same SKU product being run twice per content set when generating entitlement certificates, leading to substantial performance improvements.
Also includes a more minor fix to stop filtering the content twice. This only saves a second or so but it was the next highest hit and completely unnecessary.
Using test SKU with ~2600 content sets, bind time was 10.8 seconds. After these changes we're down to 2.2s.
The latter patch is getting a bit messy because the V1 / V3 code split is messy and really needs a refactor. Going to attempt to do this on 2.0 / per-org products branch and limit changes to this 0.9.x stream, so went with the messy but fast approach here.
> 5x Bind Improvement for Large SKUs

- server/spec/environment_spec.rb
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- Fixed a bug in EnvironmentResource that was causing a 500 error
when an invalid content ID was provided
- The demotion logic has been slightly modified such that an invalid
content ID will now cause a 404 to be thrown without performing
any demotions
> 1227930: Deleting invalid content Ids causes error 500

- gutterball/src/main/java/org/candlepin/gutterball/curator/ComplianceSnapshotCurator.java
- gutterball/src/main/java/org/candlepin/gutterball/report/StatusTrendReport.java
- gutterball/src/test/java/org/candlepin/gutterball/TestUtils.java
- gutterball/src/test/java/org/candlepin/gutterball/curator/ComplianceSnapshotCuratorTest.java
- gutterball/src/test/java/org/candlepin/gutterball/report/StatusTrendReportTest.java
- gutterball/src/test/resources/logback-test.xml
- Adding "product_name=<value>" to the status trend report query will
now allow filtering on consumers who have installed the specified
product, so long as there's at least one compliance record indicating
the product's status (compliant, partial or non)
> Added product name filtering to the status trend report

- server/bin/cmv
- The default usage message now displays the commands in addition
to the options
- Fixed a grammar issue in the verify command's output
> Fixed cmv usage output omitting commands

- docker/jenkins-scripts/smoke-test.sh
- Docker containers are no longer linked by container ID, as this was
not supported in Docker 1.3. Instead, the DB container has a unique
name generated for it, which is used to link to the container under
test
> Fixed linking issues in Jenkins smoke-test script

- server/client/ruby/candlepin_api.rb
- server/spec/product_resource_spec.rb
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/test/java/org/candlepin/model/OwnerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
- Added a new/fixed an old API call to ProductResource to lookup owners
for a given product or list thereof
- The refresh pools operation can now be triggered on a per-org basis by
specifying changed products
- Added new methods to candlepin_api.rb: get_owners_with_products and
refresh_pools_for_orgs_with_product
- Updated and added spec tests
> Added per-org/product pool refreshing and by-product owner lookups

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
Big performance optimization for distributors which can have many entitlements
but no installed products. Looking up the consumer would then result in a huge
chunk of serialization to the compliance rules to calculate data we then did
nothing with.
No installed products = skip adding data to installed products.
> Do not calculate compliance status if there are no installed products.

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/spec/entitlement_resource_spec.rb
- server/spec/entitlement_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/EntitlementFilterBuilder.java
- server/src/main/java/org/candlepin/model/PoolFilterBuilder.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/EntitlementResource.java
- server/src/main/resources/logback.xml
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
Affected API calls:
GET /consumers/:uuid/entitlements
GET /entitlements
Caller can now specify an 'attribute' query parameter to filter
results by pool/product attributes.
Caller can now specify a 'matches' query parameter to filter
entitlements by an entitlement pool's:
- product name/id
- contract number
- order number
- provided product name/id
>  Added filter options to Consumer/Entitlement resource ent lookups

- docker/build_container.sh
- docker/rebuild.sh
- Scripts no longer auto-elevate to root if not already run as root, as Docker has problems with the way this was done
- rebuild.sh no longer needs to be run from its containing directory
> Reverted automatic permission elevation

- server/spec/virt_spec.rb
- Added a delay to the virt guest auto-healing spec test to resolve
an issue where checkins can be resolved out-of-order on MySQL when
migrating a guest from one host to another within an interval too
small for MySQL's timestamp field
> Added a delay to solve precision problem with tests on MySQL

- server/client/ruby/candlepin_api.rb
- server/spec/entitlement_resource_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
Appropriate aliases were not in place for for the filter builder in EntitlementCurator.listAll(...)
Test the filters using the following as an example:
curl -k -u admin:admin 'https://localhost:8443/candlepin/entitlements?matches=awesomeos*' 
curl -k -u admin:admin 'https://localhost:8443/candlepin/entitlements?attribute=cores:2'
> Fixed broken filters when listing all entitlements

- docker/README.mkd
- docker/candlepin-rhel6-base/startup.sh
Instead of YUM_REPO, you can specify a RPM_URL instead which points to a single
Candlepin rpm to install. Should work for newer 2.0 builds.
> Allow installing a single candlepin rpm in Docker base containers.

- server/bin/import_products.rb
- server/client/ruby/candlepin_api.rb
- server/spec/product_cert_spec.rb
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ProductCertificateCurator.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- Added the lock method to AbstractHibernateCurator, which
will set the locking mode on the provided entity for the
remainder of the transaction
- Fixed an issue with adding content to products while
looking up that product on MySQL
- Updated candlepin_api.rb to use the newer org-specific
call to retrieve product certificates; import_products
and various spec tests have also been updated accordingly
> Added additional locking functionality to curators

- docker/candlepin-base/setup-devel-env.sh
- docker/candlepin-base/setup-supervisord.sh
- docker/candlepin-mysql/setup-mysql.sh
- docker/candlepin-oracle/launch-oracle.sh
- docker/candlepin-oracle/setup-oracle.sh
- docker/candlepin-postgresql/setup-postgresql.sh
- docker/candlepin-rhel6-base/setup-supervisor.sh
- docker/candlepin-rhel6-base/startup.sh
- docker/candlepin-rhel6/startup.sh
- docker/candlepin-rhel7-base/setup-supervisor.sh
- docker/candlepin-rhel7-base/startup.sh
- docker/candlepin-rhel7/startup.sh
- docker/jenkins-scripts/smoke-test.sh
- docker/rebuild.sh
- Added "set -e" to scripts which don't explicitly track command/sub-script results
- Updated output in a few places
- The Jenkins smoke test will now output the server context on failure
> Setup scripts will now abort on any error

- docker/jenkins-scripts/smoke-test.sh
- The Jenkins smoke test script no longer specifies the log driver
when running the target container, as this requires Docker 1.6,
which is not currently available on RHEL (and was specifying the
default driver anyway)
> Removed the log driver specification from the smoke test

- server/bin/test_data.json
- server/spec/derived_product_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
In the case of a distributor, derived products were not being
considered as entitled products. This would cause any content
specifying modified products to not be included in the
distributor's entitlement certificate, preventing content
sync downstream.
Candlepin now considers all derived products as entitled products
for a distributor. Standard rules governing inclusion of modifier
content still apply, but in the case of a distributor, modified
products specified on content can now be a derived/derived provided
product.
This means that in order for modifier content to be included in
the entitlement cert, the consumer must be entitled to the
modified product in one of the following ways:
- consumer currently has an entitlement providing the modified product
- the pool from which the …
> Include derived modifier content in distributor ent cert

- server/spec/consumer_resource_spec.rb
- Reduced the precision required in the consumer_resource_spec tests
to prevent the test from failing on MySQL where timestamp precision
is lower
Not sure if the milliseconds were important or explicitly put there, so this "correction" may not be the best way to go about resolving the issue.
> Reduced required precision in check-in spec test

- buildfile
- common/src/main/java/org/candlepin/common/config/MapConfiguration.java
- server/src/main/java/org/candlepin/guice/I18nProvider.java
The Java 1.7 ConcurrentHashMap#keySet() returns a Set<K> while the Java
1.8 version returns ConcurrentHashMap.KeySetView<K>.  Since Java allows an
overridden method to return a sub-type of the parent method's return
type, no compilation are raised.  When we run the code on Java 1.7,
however, it immediately fails since the ConcurrentHashMap.KeySetView
class is not available.
One solution is to compile against a 1.7 bootstrap classpath, but since
1.7 is not packaged for recent versions of Fedora, we will work around
the issue by upcasting ConcurrentHashMaps to just Maps.
See https://gist.github.com/AlainODea/1375759b8720a3f9f094 for a
detailed explanation.
> Fix cross-compile issue with ConcurrentHashMap.

- gutterball/src/main/resources/db/changelog/2015-06-02-10-26-compliance-status-products.xml
- server/src/main/resources/db/changelog/20140408160212-add-pool-source-sub-table.xml
- server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml
- server/src/main/resources/db/changelog/20150401140006-add-pool-type-to-db.xml
- Added preconditions to custom change tasks, and any reliant task,
to prevent them from running during offline/sql output mode
This update is primarily to help IT with their internal workflow that requires examining/processing the SQL statements to be run. This won't provide a 100% accurate representation (as the custom tasks tend to run quite a few statements), but it does allow updateSQL to run.
> Added preconditions to custom change tasks

- server/spec/export_spec.rb
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/sync/EntitlementImporter.java
- server/src/test/java/org/candlepin/sync/EntitlementImporterTest.java
Provided products were not being imported at all due to looking at the wrong
collection in the entitlement importer. (derived provided products were fine)
Updated code to look at the correct collection, removed unused checks for the
wrong collection (as these should never be populated now).
Added extensive comments to hopefully help clarify this unfortunate hack done
during 2.0 development to maintain JSON compatability over the API and in
manifests. This allows us to not break clients, and to keep manifest import
working both from old servers to new, and from new to old.
> Fix provided product import.

- server/spec/entitlement_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
Since we joining on content, we need to make sure we have a distinct root
entity when querying with the matches filter.
Attach one of the stackable ram subsciptions from the test data. I used ram-2gb-stackable -- "RAM Limiting Package (2GB stackable)"
Then run the curl command below, and expect a singe result.
```bash
curl -k -u admin:admin "https://localhost:8443/candlepin/consumers/:consumer_uuid/entitlements?matches=*ram*"
```
> Fixed duplicate results when using Entitlement matches filter

- server/spec/import_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/EntitlementResource.java
- server/src/main/java/org/candlepin/sync/EntitlementImporter.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/test/java/org/candlepin/policy/js/compliance/hash/ComplianceStatusHasherTest.java
We implemented some fixes to let old manifests import the main product ID from
a legacy manifest, but derived product ID was missed. Because this is the key
piece of data we check to trigger derived product behaviour, we ended up with
no derived product data importing or taking effect.
Implement the same hack required for product ID.
> Fix derived product import with 0.9 manifests.

- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
When virt-who created new HypervisorCheckIn job using new async API, it
couldn't check state of that job because it was not allowed. This commit
fixes the issue and virt-who can check state of job it created.
> Fix InsufficientPermission error when checking HypervisorCheckIn Job

- docker/candlepin-rhel6-base/startup.sh
- docker/candlepin-rhel7-base/startup.sh
- server/code/setup/cpsetup
Addition of set -e introduced problems in the startup.sh script, as the cpsetup
command does error out on EL7 because the service it not yet running, thus we
can't check status and initialize. Previously this would fail and continue in
the script, starting supervisor.
Instead we'll keep the set -e, but add a new cpsetup option that skips service
stop/restart/init, and eliminates the failed command during startup.
Also added wget calls to fetch the latest cpsetup and cpdb for this base
container used for rpm installation tests. This isn't used by the more official
tagged containers with a build in them, only for the base image that doesn't
yet have cp installed.
> Fix EL7 docker rpm container test.

- server/spec/product_resource_spec.rb
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resteasy/interceptor/AuthInterceptor.java
- server/src/main/resources/logback.xml
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
- When using @Verify with both an owner and a product, the
lookup on the product will be owner-specific
- Added @Verify to most requests in ProductResource and
OwnerProductResource
- ProductResource.getProductCertificate now throws an exception along
with the other org-agnostic write operations
Note that this change introduces its own set of oddities. Particularly, to ensure the proper permission is checked, a @Verify must be present on both an owner (that occurs in the argument list before the product) and the product; and due to the ordering, a user must meet both verify criteria to perform the action. As such, the @Verify tags may need to be adjusted to have the proper explicit permissions for this update.
> Updated @Verify to use owner when checking products

- docker/jenkins-scripts/smoke-test.sh
3 seconds isn't always enough for postgres to come up, causing the candlepin container to fail fast if it's got the candlepin rpm pre-installed. (a discrepancy fixed in the job itself on jenkins)
Added some more info for debugging purposes.
Fixes failures if run on Python 2.7.9+ where SSL certs are checked by default.
> Fixes for the docker rpm smoke tests on jenkins.

- docker/jenkins-scripts/smoke-test.sh
ssl module is already imported and exists on the older Python we're targetting.
The actual error surfaces as an AttributeError.
> Fix docker rpm smoke-test script AttributeError.

- docker/jenkins-scripts/smoke-test.sh
- Added the -t (or --time) option for specifying the maximum wait time
to wait for a response from Candlepin
- Added the -l (or --log-lines) option for specifying the number of
lines to output from the container log if an error occurs or a
response is not received within the allowed wait time
- Cleaned up the remaining time message and sleep logic to only wait
the lower of time remaining and 10s, and only output when there
is still time remaining
- Corrected server container ID output
- Added SSL unexpected EOF error to the expected list
> Several improvements/fixes in the Jenkins smoke test script

- docker/candlepin-rhel6-base/setup-supervisor.sh
- docker/candlepin-rhel7-base/setup-supervisor.sh
- Added a specific requirement for the meld3 package for installing
supervisord via pip to work around an issue with the latest
versions of meld3 causing dependency issues
Issue and workaround discussed here:
https://github.com/Supervisor/meld3/issues/21
> Added a specific install for meld3 in the RHEL RPM docker containers

- server/bin/concurrent_reg_autobind_test.rb
- server/spec/consumer_resource_activation_key_spec.rb
- server/spec/spec_helper.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- When the CandlepinPoolManager triggers an EntitlementRefusedException while
entitling by products due to entitlements not being available, it will
retry the operation. This works around a synchronization issue that can
occur when a pool is selected for consumption, but is locked and consumed
by another request/thread before it can be consumed.
> 1247242: CPM will attempt to retry entitlements under certain conditions

- server/bin/test_data.json
- server/src/main/resources/db/changelog/20150729082417-content-unique-owner-label.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
You will need to regenerate the database if the test data was previously loaded
as the older data violates this constraint
> 1246636: Content labels need unique key per owner

- server/spec/rules_import_spec.rb
- server/src/main/java/org/candlepin/model/RulesCurator.java
- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/resource/RulesResource.java
- server/src/main/java/org/candlepin/resource/StatusResource.java
- server/src/main/java/org/candlepin/sync/RulesImporter.java
- server/src/test/java/org/candlepin/resource/StatusResourceTest.java
- server/src/test/java/org/candlepin/sync/RulesImporterTest.java
This looks like it might be the largest chunk of processing our app does in
prod. Client makes ample use of this, but IT also uses it as a health check.
First step drops querying of rules version and source, instead we set these on
the provider singleton whenever we recompile rules. (i.e. they changed) The two
places they can change (rules upload and import) are updated to immediately
recompile rather than wait for someone to attempt to use them.
Ideally we'd have dropped all db connectivity from the class, but unfortunately
we need to know if the db loses it's connection, so IT can drop the node from
rotation automatically. Instead, we'll reduce the query dramatically and just
query the updated timestamp.
A nice future enhancement would be to catch db errors (all of them somewhere)
and …
> Reduce database chatter in GET /status.

- gutterball/bin/qpid/README.md
- gutterball/bin/qpid/configure-qpid.sh
Based on information discovered in
http://projects.theforeman.org/issues/11285
QPid requires a package to be installed to persist items to disk.  The old implementation was "qpid-cpp-server-store" and the newer one is "qpid-cpp-server-linearstore".  You need one of them or else everything vanishes once the service is restarted.
> Update required Qpid packages.

- buildfile
Eliminates the numerous warnings Buildr has been printing during compilation.
> Turn off compiler linting.  Too noisy.

- docker/build_container.sh
- docker/candlepin-base/cp-test
- docker/candlepin-oracle/build.sh
- docker/container_version.sh
- Version checking now uses /bin/sh as the base command, rather than cd
- Added a linter option to cp-test
> Docker build script updates

- server/client/ruby/candlepin_api.rb
- server/spec/guestid_resource_spec.rb
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/GuestIdResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
The lookup for the host to have most recently reported every guest UUID in a
virt-who checkin was showing up as a major performance bottleneck, exposing the
fact that there are virt-who deployments of far larger size than anything we
anticipated.
When reporting thousands of guest IDs into orgs with tens of thousands already
there, the performance very rapidly degrades beyond 60 second timeouts and
continues to scale up linearly as new guest IDs are added.
The check was done during virt-who checkins to detect migration, revoke
entitlements restricted to the previous host, and auto-heal if necessary.
We realized however that (a) most guest IDs never become registered consumers,
and (b) this behavior is causing bugs in revoking entitlements that the guest
systems are still attempting to use. …
> Push migration detection from virt-who checkin to system checkin.

- server/spec/rules_import_spec.rb
- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/resource/RulesResource.java
The cached rules data needs to be forced past the date checking to ensure
proper version use.
The spec test also required a sleep so that the rpm rules and the test update
rules do not have the same time in mysql.
> Forced refresh on the add/delete rules operations

- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/ExpiredPoolsJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/ImportRecordJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/JobCleaner.java
- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/StatisticHistoryTask.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UnpauseJob.java
Override logExecutionTime in the few jobs that run every 5 seconds to keep those quieter, everything else we log how long it ran for.
> Log execution time of all jobs by default.

- server/bin/import_products.rb
- server/bin/test_data.json
- server/spec/storage_band_spec.rb
- server/src/main/java/org/candlepin/model/Status.java
- server/src/main/java/org/candlepin/policy/js/compliance/StatusReasonMessageGenerator.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
- server/src/main/resources/rules/rules.js
Implemented storage band counting. Each entitlement
will equate to 1TB of coverage and marketing products
will use the multiplier such that sub quantity purchased
* multiplier will yeild pool quantity (total capacity in TB).
For example:
pool_quanity = sub_qty_bought * (storage_band_attr * multiplier)
= 1 * (1 * 256)
= 256
The resulting pool will have a quantity of 256, which can
cover 256TB of storage.
The rules will calculate a system's coverage based on a
band.storage.usage fact.
Consider a system is using 128TB:
- a quantity of 128 entitlements will cover the system (green).
- a quantity < 128 entitlements will partially cover the
system (yellow)
- no entitlements (red)
Marketing Product (requirements)
---------------------------------
The marketing product should define a multiplier …
> Storage band implementation

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/resources/logback.xml
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Refresh pools, and anything making use of the function, will no
longer remove any generate ueber certs
- Partial information for ueber certs or consumers will no longer
cause 500 errors when generating or retrieving ueber certs
> 1259248: Fixed issue with refresh pools removing ueber certs

- server/client/ruby/candlepin_api.rb
- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/HypervisorId.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/resources/db/changelog/20150915094638-add-reporter-id-to-hypervisor-id.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
While an owner can have multiple hypervisor - guest mapping reporters, Assumption is that at a given time, only one reporter reports hypervisor mappings for a particular hypervisor of an owner. This PR ensures that we:
* persist if reporter id is available in the request, else ignore.
* update if reporter id changed for the hypervisor
* warn if a hypervisor's reporter changed.
* dont warn if a reporter id was not set in the first place ( to avoid excessive warnings when this version first hits production )
> Persist reporter id for Hypervisor checkins

- server/bin/performance-dataloader.rb
- server/client/ruby/candlepin_api.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/PoolFilterBuilder.java
When using match parameters while listing available pools
hibernate would return a partially initialized list of
pool objects when matching on a collection of sub objects.
For example, if the match filter matched on 1 of 4 provided
products, only the matched provided product would be loaded
in the Pool's collection. Only a hibernate refresh would
bring the remainder in after the initial lookup.
This patch changes the query to use correlated subqueries
instead of left outer joins, which works around the partial
collection issue.
I tried implementing a unit test for the curator but
wasn't able to reproduce. I have a hunch that HSQLDB
may be dealing with joins a little differently than
postgres. A spec test easily reproduced this issue.
https://bugzilla.redhat.com/show_bug.cgi?id=1256926
>  1256926: Fixed Pool match filter query

- apicrawl/src/main/java/org/candlepin/util/apicrawl/ApiCrawler.java
- common/src/main/java/org/candlepin/common/config/Configuration.java
- project_conf/checks.xml
- server/src/main/java/org/candlepin/auth/Access.java
- server/src/main/java/org/candlepin/guice/I18nProvider.java
- server/src/main/java/org/candlepin/policy/js/entitlement/Enforcer.java
- tasks/checkstyle.rake
Users may need to start Eclipse with the `-clean` option if the were
using an old version of the Eclipse Checkstyle plugin.
Testing:
1. Run `buildr checkstyle`.  You should see some output about what is being checked but not see any errors.
2. Run `buildr eclipse`.
3. If you do not have the Eclipse Checkstyle plugin installed, it can be installed from `Help -> Eclipse Marketplace...` and then search for "checkstyle".
4. Go to `Project -> Clean...` and clean all your Candlepin projects.
5. If you see any errors complaining about classes that can't be found, close Eclipse, then run `eclipse -clean`
6. Go to a random file and type something like `if(true) { System.out.printline("hello");}`
7. A checkstyle warning should pop up immediately complaining about missing space between the if …
> Update to Checkstyle 6.9

- docker/candlepin-base/cp-test
- docker/rebuild.sh
- cp-test now runs checkstyle from $CP_HOME rather than the individual
project directory
- Re-added the note about the insecure registry
> Updated cp-test to run the linter from the top-level CP directory

- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerStatusReport.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ConsumerTrendReport.java
- gutterball/src/main/java/org/candlepin/gutterball/report/ParameterDescriptor.java
- gutterball/src/main/java/org/candlepin/gutterball/report/Report.java
- gutterball/src/main/java/org/candlepin/gutterball/report/StatusTrendReport.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ConsumerStatusReportTest.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ConsumerTrendReportTest.java
- gutterball/src/test/java/org/candlepin/gutterball/report/ParameterDescriptorTest.java
- gutterball/src/test/java/org/candlepin/gutterball/report/StatusTrendReportTest.java
- The .mustBeDate method on ParameterDescriptor will now accept a collection
of strings to use while validating input dates. Multiple calls to
.mustBeDate are destructive and do not persist previously provided formats.
- ConsumerStatusReport now accepts the date format in any of the following
formats: yyyy-MM-dd'T'HH:mm:ss.SSSZ, yyyy-MM-dd HH:mm:ss.SSSZ,
yyyy-MM-dd'T'HH:mm:ss or yyyy-MM-dd HH:mm:ss
> Added multiple formats to GB's date/time parser

- server/src/main/java/org/candlepin/audit/HornetqContextListener.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
Throttling and paging feature for our auditing HornetQ infrastructure.
Simultaneously with this branch I am also issuing PR with documentation so make sure to take a look at that as well: https://github.com/candlepin/candlepinproject.org/pull/60
To test these changes you can use stress test that is available in the following branch. Just cherry-pick commit with name "Auditing stress test"  https://github.com/nguyenfilip/candlepin/tree/auditing-stress
> Adding configuration options for HornetQ to prevent server overload

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionServiceAdapter.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- getAttribute, getProductContent and getDependentProductIds will now
set their collections if it is null at the time it is called
- Product.toString no longer causes NPEs if it is called before the
product has an owner set
- Added additional logging to ProductCurator
- CandlepinPoolManager now sets the owner of a product even when it
already exists
Not entirely sure if this will prove useful long-term. I feel like I recall some code that explicitly looked for a null value to perform certain actions. If so, and if the old code proves to be a better solution, this commit may need to be reverted/discarded.
> Added correction to the output of some getters in Product; few misc bug fixes

- server/src/main/java/org/candlepin/liquibase/PerOrgProductsUpgradeTask.java
- server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml
- The per-org products upgrade task now verifies that it actually
migrated a given product before using it in further queries
- All of the constraints and foreign keys are added as a separate step
in the 2.0 migration, performed after all the data has been migrated
- When running on MySQL or MariaDB, the foreign key checks are disabled
during the migration
> Updated the per-org products migration for performance with lots of data

- server/spec/unbind_spec.rb
When writing this test, I did not use the new candlepin_scenarios.rb methods that ensure proper operation of tests while running in hosted mode. This PR updates that test to do so.
> Updates test to remove by pool id to use the new hosted methods

- gutterball/src/main/resources/db/changelog/2015-10-20-13-20-change-event-entity-json-column-types.xml
- Updated the entitydata.type property definition in the event entity
changeset to now use "mediumtext" for mysql and hsqldb, but "text"
for everything else. This fixes several unit test failures stemming
from various side-effects of not having a default type.
> Updated property definition in Gutterball Event changeset

- buildfile
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UniqueByOwnerJob.java
- server/src/test/java/org/candlepin/model/JobCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
I plan on submitting this as a PR to master as well.
> Limit the number of binds per consumer that can run concurrently.

- server/spec/candlepin_scenarios.rb
Fix to timing issue [1] where entitlement_certificate_v3_spec.'encoded many content urls' has been failing sometimes on [2]. The problem was that async refresh_pool interleaved with delete_owner (our Ruby cleanup method) and refresh_pool created a new pool that caused [2].  You can see the interleaved threads [3].
The refresh_pool async call that caused this was entitlement_certificate_v3_spec.refresh_upstream_subscription. This can be deduced when enabling 'logging' of refresh pools with async param [4]
[1] https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/candlepin-pullrequest-spectests-hosted/34/
[2] ERROR: update or delete on table "cp_owner" violates foreign key constraint "fk_pool_owner" on table "cp_pool"  Detail: Key (id)=(2c91809a51642b0e0151642ba7b1011a) is still …
> Resolving a timing issue in hosted spec tests

- server/client/ruby/candlepin_api.rb
- server/spec/authorization_spec.rb
- server/spec/consumer_resource_spec.rb
- server/spec/filter_response_spec.rb
- server/spec/owner_resource_spec.rb
- server/spec/system_admin_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
* simplest solution for this BZ is to simply enforce that the user mentions at least one search critera
* currently none of the consumers call this API without any search criteria ( please confirm )
* This PR does NOT address the problem where using a single criteria can match hundreds of thousands of consumers, but I don't think enforcing a default page limit is a good idea, as it may break existing consumers.
* if this implementation plan is acceptable, we could change [python-rhsm](https://github.com/candlepin/python-rhsm/blob/5426aca93722f562cae7d6245999d6e874d80f04/src/rhsm/connection.py#L1013) to not let owner be optional.
> 1283401:  500 status (or an empty reply) when getting all consumers

- common/src/main/java/org/candlepin/common/jackson/DynamicPropertyFilter.java
- common/src/test/java/org/candlepin/common/jackson/DynamicPropertyFilterTest.java
Making DynamicPropertyFilter thread safe and adding a few unit tests for it since they were missing. Because this class wasn't thread safe a user could hit serialization server side error when invoking 
```
consumers/<UUID>/entitlements?exclude=certificates.key&exclude=certificates.cert
```
> 1287609: Fixing race condition

- server/spec/consumer_resource_spec.rb
- server/spec/owner_product_resource_spec.rb
- server/src/main/java/org/candlepin/jackson/DateSerializer.java
- server/src/main/java/org/candlepin/resteasy/JsonProvider.java
- server/src/test/java/org/candlepin/resteasy/JsonProviderTest.java
MySQL does not support milliseconds on time stamps. This has caused numerous issues with our spec tests. This PR removes milliseconds of Date objects on serialization. The dates are serialized to ISO 8601 format less the fractional seconds. This is done on serialization by a custom date serializer to ensure no dates are missed. This change fixes the broken unbind test in master (against MySQL) as well as includes fixes for two spec tests that required milliseconds.
I have checked python-rhsm, nothing there seems to be relying on the presence of milliseconds and as the new format is still ISO 8601 compliant seems to be well tolerated by pythons built-in time/datetime/timedelta functionality. As this would affect all clients and is not configurable it would definitely be worth it to have a …
> Truncate timestamps on serialization

- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Improving performance of bind() operation by introducing Hibernate batching and adding a new method to Consumer currator that retrieves information related to the Consumer more eagerly in lower amount of queries
> Data eager loading in ConsumerResource.bin

- server/spec/one_sub_pool_per_stack_spec.rb
- Added an additional delay in the one_sub_pool_per_stack_spec test
'should remove guest entitlement when guest is migrated' to help
alleviate some periodic failures when testing on MySQL
> Added a delay in the guest entitlement spec tests

- buildfile
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UniqueByOwnerJob.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/JobCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UniqueByOwnerJobTest.java
This PR should eliminate the possibility of deadlock on cp_consumer during a bind by pool.  It can, however, cause lock wait timeouts especially in hosted mode.  If several bind by pool jobs are all created at once, the compliance checking portion of CandlepinPoolManager.getStatus can easily result in some of the jobs not being able to acquire a lock in time.
The additional commits add a mechanism to throttle the number of concurrent Entitler jobs and to dispense with compliance checking on distributors.
> 1274074: Fix deadlock during highly concurrent entitlement jobs.

- server/bin/test_data.json
- server/spec/consumer_resource_dev_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/entitlement/AbstractEntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/StatusReasonMessageGeneratorTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/PreEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/test/TestUtil.java
This patch backports the developer subscription feature from the
master branch. This is a net new commit since the code in master
was added in a bunch of different commits and the merge was not
very smooth.
In hosted mode, a developer subscription will be granted to any
consumer during autobind that will cover all of the consumer's
installed products. An owner must have and active entitlement and
a match must be made on the dev_sku specified by the consumer
in order for the entitlement to be granted. The developer
entitlement comes from a special pool that is created
for that consumer only and will be deleted along with the
entitlement on manual removal or expiry. Multiple runs of the
auto-attach process that detect a change in coverage, will cause
the entitlement/pool to be removed and a …
> Port Developer Subscriptions from master to 0.9.51

- server/src/main/java/org/candlepin/jackson/DateSerializer.java
This sets the timezone to be used for our serialization format to UTC.
> Sets timezone to UTC for date time serialization

- server/src/test/java/org/candlepin/resteasy/JsonProviderTest.java
This PR updates the test for date serialization to include the now expected UTC timezone.
> Adds the UTC timezone to the date serialization test.

- server/spec/consumer_resource_spec.rb
The test was ammeded to show that the incoming JSON will get properly parsed
whether it contains milliseconds in its time format or not.
> Test milliseconds or not

- bin/bash_functions
- gutterball/bin/deploy
- server/bin/deploy
- Specifying -d <name> on the command line for either Candlepin or
Gutterball will now use the given name when performing any
database operations
> Added an option to specify the db name in the deploy scripts

- server/spec/consumer_resource_dev_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/policy/js/entitlement/AbstractEntitlementRules.java
Since we were deleting the dev pool before the derived products
were loaded (lazy), we couldn't look them up when addressing
modified entitlements.
Moved the dev pool deletion to the end of the remove entitlement
process to be sure we were done with it.
> 1292877: Do not delete dev pool before we are done with it

- server/spec/consumer_resource_dev_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Since there should only ever be one dev pool per
consumer, look up the existing pool by dev_pool and
requires_consumer attributes, ignoring the dev_sku
fact. Otherwise, a change in the dev_sku fact will
result in multiple dev pools.
[BZ] https://bugzilla.redhat.com/show_bug.cgi?id=1295452
> 1295452: Look up dev sku by consumer only

- server/bin/import_products.rb
- server/bin/test_data.json
- server/spec/storage_band_spec.rb
- server/src/main/java/org/candlepin/model/Status.java
- server/src/main/java/org/candlepin/policy/js/compliance/StatusReasonMessageGenerator.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
- server/src/main/resources/rules/rules.js
Implemented storage band counting. Each entitlement
will equate to 1TB of coverage and marketing products
will use the multiplier such that sub quantity purchased
* multiplier will yeild pool quantity (total capacity in TB).
For example:
pool_quanity = sub_qty_bought * (storage_band_attr * multiplier)
= 1 * (1 * 256)
= 256
The resulting pool will have a quantity of 256, which can
cover 256TB of storage.
The rules will calculate a system's coverage based on a
band.storage.usage fact.
Consider a system is using 128TB:
- a quantity of 128 entitlements will cover the system (green).
- a quantity < 128 entitlements will partially cover the
system (yellow)
- no entitlements (red)
Marketing Product (requirements)
---------------------------------
The marketing product should define a multiplier …
> Storage Band Implementation Backport to candlepin-0.9.52

- docker/candlepin-base/cp-test
If the current deploy script does not appear to have a -h flag, it will not be passed into the deploy script.
> cp-test no longer sends -h to older Candlepin deploy scripts

- buildfile
- common/pom.xml
- gutterball/pom.xml
- server/pom.xml
- server/spec/rules_import_spec.rb
- Added a delay to the rules upload function in the spec tests to
work around a time resolution issue on databases like MySQL which
don't store/use milliseconds
> Fixed the rules import spec tests on MySQL (0.9.51)

- buildfile
- common/pom.xml
- gutterball/pom.xml
- server/pom.xml
- server/spec/rules_import_spec.rb
- Added a delay to the rules upload function in the spec tests to
work around a time resolution issue on databases like MySQL which
don't store/use milliseconds
> Fixed the rules import spec tests on MySQL (0.9.52)

- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Auto-attach for a developer consumer was taking approx
2 minutes due to the query used to check if a development
pool existed for the consumer.
This patch improves the query time by adding an owner filter
to the Pools query.
https://bugzilla.redhat.com/show_bug.cgi?id=1300705
> 1300705: Fix perf issue finding dev pools (0951)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/test/TestUtil.java
- Refresh pools, and anything making use of the function, will no
longer remove any generate ueber certs
- Partial information for ueber certs or consumers will no longer
cause 500 errors when generating or retrieving ueber certs
> 1259248: Fixed issue with refresh pools removing ueber certs (0.9.52)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Changes made to a stack derived pool will no longer cause null
pointer exceptions during manifest import or pool refresh
> 1301812: Fixed an issue with event generation for stack derived pools (0.9.49)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Changes made to a stack derived pool will no longer cause null
pointer exceptions during manifest import or pool refresh
> 1301812: Fixed an issue with event generation for stack derived pools (CP2)

- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Auto-attach for a developer consumer was taking approx
2 minutes due to the query used to check if a development
pool existed for the consumer.
This patch improves the query time by adding an owner filter
to the Pools query.
**Testing Note**
This bug was only reproducible with a lot of pools already existing. I've tested this already against a large data set and since it takes a while to get set up, I'd suggest just doing a functionality check to verify this PR.
> 1300705: Fix perf issue finding dev pools

- buildfile
- server/src/main/java/org/candlepin/util/DERUtil.java
- server/src/main/java/org/candlepin/util/X509CRLEntryStream.java
- server/src/main/java/org/candlepin/util/X509CRLStreamWriter.java
- server/src/test/java/org/candlepin/util/X509CRLEntryStreamTest.java
- server/src/test/java/org/candlepin/util/X509CRLStreamWriterTest.java
Empty CRLs are missing the revokedCertificates sequence which creates a
difficult situation for the streaming code since it has to consume part
of the stream in order to determine if the list is empty or not.  If the
list isn't empty, then we've consumed part of the ASN1 that we actually
needed.  This state is especially problematic for the
X509CRLStreamWriter because it relies on X509CRLEntryStream to leave the
stream in a known state.
> Add special case code to handle empty CRLs.

- server/src/main/java/org/candlepin/util/CrlFileUtil.java
- server/src/main/java/org/candlepin/util/X509CRLEntryStream.java
- server/src/main/java/org/candlepin/util/X509CRLStreamWriter.java
- server/src/test/java/org/candlepin/util/CrlFileUtilTest.java
- server/src/test/java/org/candlepin/util/X509CRLStreamWriterTest.java
The AuthorityKeyIdentifier is an extension that identifies the public
key of the key pair used to sign the CRL.  If users change keys, in the
old implementation the AuthorityKeyIdentifier would not be updated to
reflect the new key pair.  This patch corrects that oversight.
> Allow X509CRLStreamWriter to change AuthorityKeyIdentifier extension.

- docker/candlepin-base/cp-test
- teepipe now lives in /tmp and is referenced as such by all commands,
fixing issues with running unit and spec tests
> Fixed incorrect pathing with the teepipe

- server/bin/bind-performance.rb
- server/bin/bulk-crl-test.rb
- server/bin/concurrency-bonuspool-test.rb
- server/bin/concurrency-test.rb
- server/bin/concurrent_reg_autobind_test.rb
- server/bin/generate-export.rb
- server/bin/performance-dataloader.rb
- server/client/ruby/candlepin_api.rb
- server/client/ruby/hostedtest_api.rb
- server/spec/candlepin_scenarios.rb
- server/spec/consumer_resource_dev_spec.rb
- server/spec/derived_product_import_spec.rb
- server/spec/subscription_resource_spec.rb
* fix scripts that were using older client versions
* bin scripts should now use HostedTest resources
* I have only fixed scripts that were using create_subscription. there may be other scripts still broken, no idea what is used and what is stale.
*  found that spec tests are still being written using create_subscription. Throw an error if that happens.
* move hosted test methods from candlepin scenarios to hostedtest_api so scripts can use them.
> Fix server/bin scripts that have been broken since candlepin 2.0

- server/candlepin.spec.tmpl
The spec file was missing a requires on the JDBC driver which `cpdb` needs.
> Add missing RPM requires.

- gutterball/src/main/java/org/candlepin/gutterball/util/cron/CronSchedule.java
Replaced the comment explaining the accepted format for the cron scheduler, with a similar comment using only ascii characters. (The new comment was provided by Ceiu).
This is needed to update the strings for translation with zanata.
> Remove non-ascii characters from CronSchedule

- server/src/main/java/org/candlepin/util/X509CRLStreamWriter.java
- server/src/test/java/org/candlepin/util/X509CRLStreamWriterTest.java
Add the BouncyCastle provider in the unit test.
> Remove some unnecessary code from the CRL streaming writer.

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/CertificateSerialCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/ProductEntitlements.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/util/ContentOverrideValidator.java
- server/src/test/java/org/candlepin/auth/SSLCertTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/test/CertificateSerialCuratorTest.java
- server/src/test/java/org/candlepin/model/test/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/model/test/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/test/OwnerResourceTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- server/src/test/java/org/candlepin/test/TestUtil.java
- server/src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
To make the unit tests pass, one of the commits ignores SSLCertTest.validCertificateShouldPassVerification test
After local run of rspec tests I can see the following failures
```
Failures:
1) Authorization allows trusted consumer clients
Failure/Error: trusted_cp.list_entitlements()
RestClient::Unauthorized:
401 Unauthorized
2) Authorization allows in trused users
Failure/Error: trusted_user_cp.list_consumers :owner => owner1['key']
RestClient::Unauthorized:
401 Unauthorized
3) OAuth lets a caller act as a user
Failure/Error: res.code.should == '200'
expected: "200"
got: "401" (using ==)
4) OAuth trusts the provided username
Failure/Error: res.code.should == '200'
expected: "200"
got: "401" (using ==)
5) OAuth lets a caller act as a consumer
Failure/Error: res.code.should == '200' …
```
> Backport of Batch Revoke to 9.23

- tasks/gettext.rake
'builder gettext:extract" uses xgettext to extract string
catalogs, and sans '--from-code=utf-8', it assumes source
files are encoded as plain ASCII. If a file includes (valid)
utf-8 that is not also plain ASCII, xgettext fails with an
error like:
xgettext: Non-ASCII comment at or before
gutterball/src/main/java/org/candlepin/gutterball/util/cron/CronSchedule.java:39.
Please specify the source encoding through --from-code.
> Specify 'utf-8' as txt encoding for source files.

- apicrawl/src/main/java/org/candlepin/util/apicrawl/ApiCrawler.java
- apicrawl/src/main/java/org/candlepin/util/apicrawl/ApiDoclet.java
- buildfile
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
The API crawler had several problems: resource classes not listed in
RootResource were not getting scanned and overloaded methods were not
being documented correctly.
This patch uses Scannotation to search for classes providing a REST
resource instead of relying on listing in the RootResource.
This patch should produce a "candlepin_methods.json" that no longer causes the Jekyll builder to throw warnings.
> Fix apicrawler

- project_conf/checks.xml
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
The '1=1' stipulation is to reject searches performed on non-marketing
product SKUs.  Originally the stipulation was "true='true'" which worked
on PostgreSQL but not on MySQL.
> Correct error in SKU search SQL seen in MySQL.

- server/bin/data_generator.rb
When parsing safe ints, the value wasn't being
returned from the function causing nil option
values.
The script was broken if any int param value
was set.
> Fixed broken option parsing

- server/spec/ueber_cert_spec.rb
- server/src/main/java/org/candlepin/model/UeberCertificateGenerator.java
RFC 5280 states in section 4.1.2.5:
CAs conforming to this profile MUST always encode certificate
validity dates through the year 2049 as UTCTime; certificate validity
dates in 2050 or later MUST be encoded as GeneralizedTime.
Conforming applications MUST be able to process validity dates that
are encoded in either UTCTime or GeneralizedTime.
But currently, python-rhsm is parsing certificates with either M2Crypto
or a custom C binding (certificate.c) to OpenSSL's x509v3 (so that we can access
the raw octets in the custom X509 extensions used in version 3 entitlement
certificates).  Both M2Crypto and our binding contain code that automatically
converts the Not After time into a UTCTime.  The conversion "succeeds" but the
value of the resultant object is something like "Bad time value" …
> 1242310: Do not issue ueber certs that expire after 2050.

- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/guice/CandlepinRequestScope.java
- server/src/main/java/org/candlepin/guice/CandlepinRequestScoped.java
- server/src/main/java/org/candlepin/pinsetter/core/GuiceJobFactory.java
- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/policy/js/JsRunnerRequestCache.java
- server/src/main/java/org/candlepin/policy/js/JsRunnerRequestCacheProvider.java
- server/src/main/java/org/candlepin/servlet/filter/CandlepinScopeFilter.java
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/guice/TestingRequestScope.java
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- server/src/test/java/org/candlepin/policy/EnforcerTest.java
- server/src/test/java/org/candlepin/policy/js/JsRunnerProviderTest.java
- server/src/test/java/org/candlepin/policy/js/activationkey/ActivationKeyRulesTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/EntitlementRulesTestFixture.java
- server/src/test/java/org/candlepin/policy/js/override/OverrideRulesTests.java
- server/src/test/java/org/candlepin/policy/js/quantity/QuantityRulesTest.java
- server/src/test/java/org/candlepin/resource/util/InstalledProductStatusCalculatorTest.java
- server/src/test/java/org/candlepin/servlet/filter/CandlepinScopeFilterTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- server/src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
In our configuration, Google Guice creates a new instance of JsRunner for every Inject annotation. it means that  JsRunner is being constructed ~36 times during every request. In each of these constructions, the provider JsRunnerProvider is checking to the database if cp_rules.updated changed. This brings significant overhead. 
This PR introduces request scoped caching of cp_rules.updated value. The JsRunnerProvider now uses request scoped bean JsRunnerRequestCache in order to cache the value of cp_rules.updated for the duration of the request.
We cannot cache the value longer. The reason is that in the clustered environment, any cluster node of Candlepin can updated the cp_rules table. We don't have any clustered in-memory cache, hence synchronization on database level seems to be …
> Request scope caching of cp_rules.updated 

- server/src/main/java/org/candlepin/util/X509CRLStreamWriter.java
- server/src/test/java/org/candlepin/util/X509CRLStreamWriterTest.java
Due to the way the streaming process works, when X509CRLStreamWriter is
asked to modify an empty CRL, it uses a different method than it would
normally.  This different method was failing to update the nextUpdate
field on the generated CRL.
> Set nextUpdate correctly when modifying an empty CRL.

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTask.java
- server/src/main/java/org/candlepin/pki/PKIUtility.java
- server/src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/sync/ImporterTest.java
Although it's not the original intention, the nextUpdate value on a CRL
is frequently used to mean the expiration date for the CRL.  Previously,
Candlepin was setting nextUpdate to be one day away.  This patch makes
the number of days away configurable so that users can provide a little
more breathing room in case CRL generation fails or is delayed.
See http://security.stackexchange.com/a/55784
> Allow configurable delta for nextUpdate on the CRL.

- server/spec/candlepin_scenarios.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitleByProductsJob.java
The job was being created with a List<String> for target pools,
but on execution, it was being casted to a HashSet.
Always cast to a Collection here, as that's what is passed
by the job creation's static method.
> 1320711: Fixed class cast exception in EntitleByProductsJob

- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/ConsumerComplianceJob.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/ConsumerComplianceJobTest.java
If a consumer was updated or deleted before the job was run
an OptimisticLockException was thrown and the job would fail.
Losing a compliance can be problematic as the consumer
status would be out of date.
The OLE would occur if the consumer was updated/deleted after
it was looked up and before it was locked.
This PR locks the consumer isntance on lookup, eliminating the
gap between fetch and lock.
If the Consumer does not exist, the job will now finish
successfully with an appropriate result message stating that
the targeted consumer could no longer be found.
> Fixed Optimistic Lock issue with ConsumerComplianceJob

- server/src/main/java/org/candlepin/model/Content.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/test/java/org/candlepin/model/ContentTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- Products and Content will now check their lock state when checking
for equality or generating hash codes. This should prevent an issue
where an entity could become locked or unlocked by merging or
diverging from another entity in a different lock state.
> Products and Content now check the lock state when checking equality

- server/spec/one_sub_pool_per_stack_spec.rb
Apparently two seconds was not enough. spec test still failed some times , look at build 246 in jenkins for example.
> Increase sleep time for one sub pool per stack spec

- docker/candlepin-base/Dockerfile
- docker/candlepin-base/cp-test
- docker/candlepin-postgresql/Dockerfile
- The rspec tests may now be filtered from the cp-test command by adding
the filter string with the -r option
- Updated usage text for cp-test
> Updated how rspec filters are specified

- server/src/main/java/org/candlepin/model/Pool.java
- Added the @JsonIgnore annotation to getComplianceType and
isUnmappedGuestPool as these methods were never intended to
be exposed to JSON serialization
> Added @JsonIgnore to getComplianceType and isUnmappedGuestPool

- buildfile
- docker/candlepin-base/cp-test
- Unit test as many times as needed using `cp-test -uuuu`
- This helps to catch non-deterministic unit tests
- create buildr lint task to checkstyle, rubocop, and rpmlint
- add jenkins buildr task to do misc. validation
- add -b option to cp-test to execute arbitrary buildr task
- now you can run arbitrary buildr commands like:
- `cp-test -b test:PoolManagerTest`
- `cp-test -b jenkins`
if accepted, we will need to :
> unit test thrice to catch non deterministic tests

- server/src/main/resources/db/changelog/20160419110701-oracle-add-indexes-for-foreign-keys.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- whenever you create a foreign key, mysql automatically creates an index, oracle doesnt.
- we should have indexes on all foreign keys : [why?](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:292016138754)
- also, if you dont have an index, oracle will lock the entire table of the foreign entity, instead of just the foreign entity.
- this PR helps the spec test failures in oracle tests
> Add missing foreign key indexes in oracle

- server/spec/product_resource_spec.rb
- server/src/main/java/org/candlepin/auth/Verify.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/resource/ContentResource.java
- server/src/main/java/org/candlepin/resource/OwnerContentResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resteasy/filter/EntityStore.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/main/java/org/candlepin/resteasy/filter/VerifyAuthorizationFilter.java
- server/src/test/java/org/candlepin/resource/ContentResourceTest.java
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
- server/src/test/java/org/candlepin/test/VerifyAuthorizationFilterFactory.java
- ProductResource has been updated such that it can be used to fetch
products and product certificates by UUID
- Usage of @Verify on OwnerProductResource and OwnerContentResource
has been updated such that @Verify does not appear on either
product or content references
- VerifyAuthorizationFilter has been updated to lookup products by
UUID rather than ambiguous RHID
- StoreFactory no longer accepts an owner on any of its lookup
operations
- EntityStore.getOwner has been brought back for looking up the
owner of a given entity object
> Updated CP's auth interceptors and product resources to use UUIDs

- server/src/main/java/org/candlepin/resource/ActivationKeyResource.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/ContentResource.java
- server/src/main/java/org/candlepin/resource/EntitlementResource.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/resource/GuestIdResource.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/main/java/org/candlepin/resource/OwnerContentResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resource/RoleResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/java/org/candlepin/resteasy/ResourceLocatorMap.java
Also add warning when a @Consumes is set to the */* media type but
actually reads the request body.  Currently, Candlepin only consumes
JSON so methods should be specific about that instead of using the
wildcard type as a shortcut.
> Add missing @Consumes annotations.

- buildfile
- common/pom.xml
- gutterball/pom.xml
- server/pom.xml
- Candlepin now uses commons-io 1.4 and httpclient 4.3.2
> Updated component versions for commons-io and httpclient

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/resteasy/filter/AuthenticationFilter.java
- server/src/test/java/org/candlepin/resteasy/filter/AuthenticationFilterTest.java
Candlepin shouldn't send WWW-Authenticate when the client communicates using
insecure channel, instead Candlepin should send back 403 Forbidden
> Authenticate over SSL only

- buildfile
Since qpid-client version 0.32 the qpid-client respects extension X509v3
Subject Alternative Name
> 1330263: Subject Alternative Name not respected

- buildfile
Since qpid-client version 0.32 the qpid-client respects extension X509v3
Subject Alternative Name.
> 1330262: Subject Alternative Name not respected

- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Guest lists reported as null are treated as if they were empty lists.
> 1332635: Treat null guest lists as empty guest lists on hypervisor checkin

- server/candlepin.spec.tmpl
- server/conf/logrotate.conf
There is a precedent to this solution in [spacewalk](https://github.com/spacewalkproject/spacewalk/blob/master/backend/spacewalk-backend.spec#L357).
Please try the following steps both in master and my branch to observe the difference:
Easiest steps I can think of, to test:
1. build a source rpm using tito:
`tito build --rpm --test`
2. copy over the **source** rpm to your RHEL6 and RHEL7 vms.
3. rebuild the rpm on each vm using the source rpm(there might be some dependencies you may have to install for this step to work):
`rpmbuild --rebuild mycandlepin.src.rpm`
4. extract the rpm that was created in the step above:
`rpm2cpio mycandlepin.noarch.rpm  | cpio -dium`
5. verify that the appropriate logrotate conf is installed:
on RHEL6: 
> 
cat etc/logrotate.d/candlepin  | grep "su tomcat" …
> 1330246: Candlepin logrotate error on RHEL6.7

- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
This is a smaller, more immediate patch to a much bigger issue involving auditing on operations that cascade to other model objects. For this PR, only the details in the BZ were addressed due to the massive scope of the underlying issue which will be fixed in another PR to come.
> 1306628: Added additional logging to environment deletion

- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
This is the forward port of the fix for bz 1332635. There is really nothing much different here about the fix than there was in candlepin version 0.9.54. The async logic did not have the same flaw as the synchronous logic did.
> 1332637: Treat null guest lists as empty guest lists

- docker/candlepin-base/cp-test
Our script that pulls Github PR branches was using 'git pull' which may leave
untracked files and local changes in the working copy. That may result in errors
during checkouts. It is safer to fetch+reset and then clean the working copy.
> Clean working copy before checkout

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/JobCuratorTest.java
- server/src/test/java/org/candlepin/util/X509CRLStreamWriterTest.java
- Fixed an issue in the JobCuratorTest which allowed two jobs to have the
same time for the purposes of ordering
- Fixed an issue in the ConsumerCuratorTest where the update date could
end up identical unintentionally
- Added a tolerance of three milliseconds to the time check in
X509CRLStreamWriterTest to account for minor slowdowns or scheduling
issues during testing
> Fixed periodic failures in some unit tests

- docker/candlepin-base/cp-test
- docker/candlepin-base/setup-devel-env.sh
This can be tested building candlepin-base, then using the new image to test an old build of Candlepin:
```
cd devel/candlepin/docker
mkdir artifacts
sudo ./candlepin-base/build.sh
sudo docker run -Pti --rm -v $PWD/artifacts/:/artifacts/ candlepin/candlepin-base cp-test -u
sudo docker run -Pti --rm -v $PWD/artifacts/:/artifacts/ candlepin/candlepin-base cp-test -u -c candlepin-0.9.51-HOTFIX
```
> Docker containers now use rvm for Ruby management

- docker/candlepin-base/cp-test
This can be tested by building the candlepin-base image, then running unit tests against it with filters, without filters, with varying number of unit test runs
```
cd devel/candlepin/docker
mkdir artifacts
sudo ./candlepin-base/build.sh
sudo docker run -Pti --rm -v $PWD/artifacts/:/artifacts/ candlepin/candlepin-base cp-test -u
sudo docker run -Pti --rm -v $PWD/artifacts/:/artifacts/ candlepin/candlepin-base cp-test -u JobCuratorTest
sudo docker run -Pti --rm -v $PWD/artifacts/:/artifacts/ candlepin/candlepin-base cp-test -uuu ConsumerCuratorTest
```
> Added filtering to the unit test parameter in cp-test

- server/src/main/java/org/candlepin/model/Environment.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
This is a smaller, more immediate patch to a much bigger issue involving auditing on operations that cascade to other model objects. For this PR, only the details in the BZ were addressed due to the massive scope of the underlying issue which will be fixed in another PR to come.
> 1306628: Added additional logging to environment deletion (0.9.54)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/CertificateSerialCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/model/EntitlementCertificateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/sync/ExporterTest.java
- Added a limit to the number of pools the expired pools query will fetch
per "block." The cleanup expired pools operation will now fetch and
cleanup pools in blocks of 2048 (by default) rather than fetching
every known pool and running out of memory
- Hibernate queries which make use of the IN operator no longer create
new lists when the source collection is not a List instance
- Several redundant blocks of code were removed in favour of the updated
in-operator handling
- Added explicit handling of iterable entitlement IDs when regenerating
certificates; it is now performed with a bulk update rather than
loading the entire entitlement set one-by-one
- Retrieval of modifier products by a query instead of using iteration over
overlapping entitlements (which consumes a lot of memory)
- …
> 1331793: Improved performace of expired pool cleanup task

- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
Because of repeatable read isolation semantics, we sometimes
got stale data even after locking an entity. This caused
overconsumption.
> 1336054: Overconsumption Fix

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- During pool refresh, any owners other than the owner for which pools
are being refreshed are removed from incoming products and content.
This should address an issue where we could receive transient owners
on an entity, and currently does not impact equality checks.
> CandlepinPoolManager now removes extraneous product owners during refresh

- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
Refresh pools hasn't been cleaning up stack derived pools. This happened
when entitlements were deleted in batch during
refreshPoolsWithRegeneration method.
The underlying issue here is with collection Pool.entitlements. Because
this collection has cascade set to PERSIST, one must be very careful
when deleting entitlement to also remove it from the collection.
Otherwise, Hibernate will un-schedule the deletion.
> 1337906: Stack derived pool cleanup

- common/src/main/java/org/candlepin/common/jackson/DynamicPropertyFilter.java
- common/src/test/java/org/candlepin/common/jackson/DynamicPropertyFilterTest.java
Making DynamicPropertyFilter thread safe and adding a few unit tests for
it since they were missing. Because this class wasn't thread safe a user
could hit serialization server side errors because requests were
colliding on the List that is being modified inside the filter.
> 1338846: Fixing property filter race condition

- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
Refresh pools hasn't been cleaning up stack derived pools. This happened
when entitlements were deleted in batch during
refreshPoolsWithRegeneration method.
The underlying issue here is with collection Pool.entitlements. Because
this collection has cascade set to PERSIST, one must be very careful
when deleting entitlement to also remove it from the collection.
Otherwise, Hibernate will un-schedule the deletion.
> 1345845: Stack derived pool cleanup

- server/src/main/java/org/candlepin/model/Product.java
Upon concurrent ProductResource.removeContent requests we were getting
unique constraint violation errors for table "cp_product_content_pkey".
The reason for this is that productContent collection is a
ElementCollection and when such collection is declared as List, then
Hibernate has no way of tracking changes to this collection and then
updating database correctly (List may contain duplicates). Hibernate's
strategy in this case is to (upon every merge) delete everything from
the collection table and then insert in memory entities from that
collection back. In concurrent situations this resulted same rows
being inserted duplicitly.
Besides this solution it's also possible to use OrderColumn annotation,
but that would require schema changes.
> 1344402: Unique product content violation

- server/src/main/java/org/candlepin/model/Product.java
Upon concurrent ProductResource.removeContent requests we were getting
unique constraint violation errors for table "cp_product_content_pkey".
The reason for this is that productContent collection is a
ElementCollection and when such collection is declared as List, then
Hibernate has no way of tracking changes to this collection and then
updating database correctly (List may contain duplicates). Hibernate's
strategy in this case is to (upon every merge) delete everything from
the collection table and then insert in memory entities from that
collection back. In concurrent situations this resulted same rows
being inserted duplicitly.
Besides this solution it's also possible to use OrderColumn annotation,
but that would require schema changes.
> 1345918: Unique product content violation

- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EnvironmentContent.java
- server/src/main/java/org/candlepin/model/dto/EnvironmentContent.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/util/RdbmsExceptionTranslator.java
Under concurrent demotion requests, we were getting StaleStateException
from hibernate indicating that a request is trying to delete already
deleted instance. Also, the demotion of content was using one
transaction per content demotion, so request could demote some content,
then throw exception and never get into the part of the code that is
responsible for regeneration of environment certs.
In this commit I introduce RdbmsExceptionTraslator that can help to
determine a reason for a Hibernate Exception. Also I use batch
operation for database operation (demotion of content) to mitigate a
possibility of partial demotion.
> 1345765 - Concurrent content demotions cause 400

- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/guice/DefaultConfig.java
- server/src/main/java/org/candlepin/pinsetter/tasks/ExportJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/service/ExportExtensionAdapter.java
- server/src/main/java/org/candlepin/service/impl/DefaultExportExtensionAdapter.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/sync/ExporterTest.java
Added a ManifestExtensionAdapter interface that allows implementations
to add files to an export. The default implementation does nothing.
> Allow manifest exports to be extended

- server/src/main/resources/db/changelog/20160614113932-add-owner-and-type-constraint-export-metadata.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
in 0.9.54, there is a rare chance ( not reproducable ) that two concurrent reports can result in two records in the cp_export_metadata table for the same "type" . Given the current code, this prevents any future manifest activity ( delete / import / refresh ) because our query expects there to be a unique owner and type  ( user / system ) combination for every record.
we are adding a constraint that prevents this situation in the reported branch. in candlepin 2.0, we shall lock the owner and more.
more details in the bz!
> 1338950: prevent successful concurrent imports

- server/src/main/java/org/candlepin/guice/AMQPBusPubProvider.java
Candlepin should use SASL mechanism ANONYMOUS when communicating with
Qpid.
> 1314904: SASL mechanism ANONYMOUS

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- server/src/test/resources/logback-test.xml
- PoolCurator.findExpiredPools now uses left joins and null checks
when comparing entitlements and attributes, fixing an issue where
pools without entitlements or attributes would not be found
- CandlepinPoolManager.cleanupExpiredPools now uses a transaction for
each block of pools rather than the entire cleanup operation
- Added AbstractHibernateCurator.evictAll for performing bulk eviction
on entity collections
> Updated query backing the PoolCurator.listExpiredPools method

- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/util/RdbmsExceptionTranslator.java
Similar to 1345765. This method was designed in the past to throw 409 in
case when a content has already been promoted to an environment. This
wasn't working sometimes under concurrent access. Also the method allows
to pass in a set of content ids to promote but it is possible that
method just partially promotes a subset of those ids.
Adding transactionality and exception handling.
> 1345766: Concurrent content promotion cause 400

- buildfile
Point to a different gettext dependency. Eases up running spec tests locally (specs for 0.9.49 are not supported in Jenkins anymore).
Buildfile in master points to this new gettext artifact as well. @awood I think it  just hasn't been done in 0.9.49, correct?
> GETTEXT dependency

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/Content.java
- server/src/main/java/org/candlepin/model/Product.java
ConsumerResource.getConsumer() was taking a long time because compliance
check needs to check the whole object graph down to the
Content.modifiedProductIds collection. We observed number of queries run
for some consumers - even thousands. Batching alleviates the issue.
> 1357036: N+1 fix for Content.modifiedProductIds

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Skipping derived pools from listExpiredPools leads to a few edge cases ( derived pools that dont have source entitlements are skipped )
- Batching deletion also complicates things as often we delete pools in intermediate steps that are already in the current batch, so the second attempt to delete them errors out.
- This PR appears to be the safest way to delete all pools that should be deleted.
- I have tested this against deletion of 100000 pools over a weekend.
> fix deletePools - delete derived pools

- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/resource/RulesResource.java
When RulesResource methods were run in quick succession, it was possible
that rules compliation might have been skipped. Adding a 'force' flag to
compileRules. The reasoning is that RulesResource.upload or
RulesResource.delete should always result in recompilation of the rules.
> 1358742: UniqueTag cannot be cast to Function

- server/src/main/java/org/candlepin/model/CheckIn.java
- server/src/main/java/org/candlepin/model/GuestIdsCheckIn.java
- server/src/main/resources/db/changelog/20160711104547-remove-fk-checkins.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
Removing foreign key constraints on checkin tables to mitigate a
posisibility of lock waits during GET requests.
When a long running request acquires X lock on a consumer, then any
other requests by the consumer (even GET) will get blocked. This is
because we update consumer checkin tables that have foreign key to
consumer table. This behavior is specific to Postgres 9.2, newer
Postgres has a new feature that is less strict to updates to foreign
tables.
> 1350771: ExclusiveLock held by Candlepin

- server/spec/one_sub_pool_per_stack_spec.rb
- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/resource/RulesResource.java
- server/src/main/resources/db/changelog/20160720104426-remove-bad-ueber-cert-data.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
An old bug that caused the ueber cert pools
to be deleted was fixed but did not correct
the state of any owners that were affected.
All required ueber objects (sub, product,
content, consumer) were not cleaned up.
Subsequent attempts to get or create a new
debug cert would fail because the data was
in a new state.
This patch adds a new liquibase changeset to
clean up the data. This patch plus the old
bug fix should make sure that this doesn't
happen again.
**Before starting, make sure that you have a manifest handy! You will have to import it in one of the steps below!!!**
1) Check out the branch that first introduced the bug and deploy.
```bash
$ git co -b ueber-broken 64b74191499e60de17162f56e10a090c74de5b87
$ bin/deploy -gt
```
2) Generate the debug cert for the 'admin' owner.
```bash …
```
> 1354633: Cleanup stray ueber objects

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/GuestId.java
- server/src/main/java/org/candlepin/model/GuestIdCurator.java
- server/src/main/java/org/candlepin/model/HypervisorId.java
- server/src/main/java/org/candlepin/model/PoolAttribute.java
- server/src/main/java/org/candlepin/policy/criteria/CriteriaRules.java
- server/src/main/resources/db/changelog/20160714130753-add_lower_columns.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/ConsumerContentOverrideCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorSearchTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/GuestIdCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Changing strategy for case insensitive searches. In the past we
used ignoreCase() and lower() to perform case insensitive search.
That strategy was performing poorly in the absence of an database
index. Adding such index was not possible in database agnostic way
so the new strategy is to use columns suffixed '_lower'. These
columns have index created and they contain only lower case data.
> 1350455: Improve performance of case insensitive search

- server/src/main/java/org/candlepin/model/UeberCertificateGenerator.java
- server/src/main/resources/db/changelog/20160722162105-remove-bad-ueber-cert-data.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
An old bug that caused the ueber cert pools
to be deleted was fixed but did not correct
the state of any owners that were affected.
All required ueber objects (sub, product,
content, consumer) were not cleaned up.
Subsequent attempts to get or create a new
debug cert would fail because the data was
in a new state.
This patch adds a new liquibase changeset to
clean up the data. This patch plus the old
bug fix should make sure that this doesn't
happen again.
**Before starting, make sure that you have a manifest handy! You will have to import it in one of the steps below!!!**
1) Check out the branch that first introduced the bug and deploy.
```bash
$ git co -b ueber-broken 64b74191499e60de17162f56e10a090c74de5b87
$ bin/deploy -gt
```
2) Generate the debug cert for the 'admin' owner.
```bash …
```
> 1354633: Cleanup stray ueber objects (CP 2.0)

- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/Content.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductAttribute.java
- server/src/main/java/org/candlepin/model/ProductContent.java
- server/src/test/java/org/candlepin/model/ContentTest.java
- server/src/test/java/org/candlepin/model/ProductTest.java
- The existing hashCode implementations for Product and Content entities
(as well as related join- and sub-objects) has been moved to the new
getEntityVersion method
- The new hashCode implementation for Product and Content now use the
Red Hat ID for the entity
- Improved equality and hashcode testing in Product and Content
> Refactored hashCode implementations in certain high-traffic entities

- server/src/main/java/org/candlepin/policy/js/compliance/StatusReasonMessageGenerator.java
- Reverted the accidental truncation of the compliance status reason
message for unmapped guests.
> 1362701: Reverted accidental truncation of compliance status message

- server/src/main/resources/db/changelog/20160714130753-add_lower_columns.xml
Oracle accepts index name lengths only up to
32 characters.
> Oracle index name length

- Gemfile
With the latest version of activesupport, there is an error on RHEL7 machines using ruby 2.0 while running a bundle update:
```
candlepin@jmolet-cp1 [10:23:16 AM] [~/candlepin] [master *]
-> % bundle update
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
<... snip .. >
Installing activesupport 5.0.0 (was 4.2.6)
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.0.0), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.
```
With this fix it'll keep activesupport below 5.0 which requires ruby 2.2.2:
```
candlepin@jmolet-cp1 [10:26:05 AM] [~/candlepin] [master *]
-> % bundle update
Fetching …
```
> updating activesupport to have a version compatible with rhel7

- server/spec/candlepin_scenarios.rb
- server/spec/import_excess_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
Fixes in processPoolUpdate which is part of import code path.
Defensively checking to determine if the pool has already been deleted.
In such cases, we need to skip processing updates for it.
> 1361537: Import manifest fail with excess entitlement (2.0)

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Changed corresponding HQL query to take into account pools endDate, and also pools entitlements endDateOverride.
> 1344100: servicelevels returned by candlepin should exclude values from expired pools

- gutterball/src/main/java/org/candlepin/gutterball/receiver/EventReceiver.java
Gutterball now uses ANONYMOUS SALS to communicate with Qpid.
> 1359049: ANONYMOUS SASL mechanism

- buildfile
- gutterball/pom.xml
- server/pom.xml
- server/src/main/java/org/candlepin/cache/CacheContextListener.java
- server/src/main/java/org/candlepin/cache/CandlepinCache.java
- server/src/main/java/org/candlepin/cache/JCacheManagerProvider.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/resources/META-INF/persistence.xml
- server/src/main/resources/ehcache-stats.xml
- server/src/main/resources/ehcache.xml
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
Integration of EHCache as 2LC and JCache. This PR depends on #1331 
This is only integration of the caches, together with a possibility to configure statistics over JMX in candlepin.conf:
```
cache.jmx.statistics=true
jpa.config.hibernate.generate_statistics=true
jpa.config.hibernate.use_structured_entries=true
jpa.config.net.sf.ehcache.configurationResourceName=ehcache-stats.xml
```
This PR doesn't introduce any caching.
> Integrate EHCache as 2LC and JCache

- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
Saving repeated lookups to database. Only caches over one REST query.
> Cache host consumers on curator

- server/client/ruby/candlepin.rb
Provided products must be specified with productId not id.
providedProducts nad derivedProvidedProducts are specified to use ProvidedProduct class!
```
@JsonProperty("providedProducts")
@JsonProperty("derivedProvidedProducts")
```
The ruby client mentions :derived_products but that collection is not on Pool at all.
> Ruby Client - Create Pool bug

- server/spec/one_sub_pool_per_stack_spec.rb
- server/spec/virt_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
Fixes in processPoolUpdate which is part of import code path.
Defensively checking to determine if the pool has already been deleted.
In such cases, we need to skip processing updates for it.
> 1361491: Import manifest fail with excess entitlement (0.9.54)

- server/src/main/java/org/candlepin/model/Role.java
@mstead I left the Cacheable on Role by accident. Shouldn't be there though as in cluster environment Role can get stale
> Role shouldn't be cached

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/resources/db/changelog/20160714130753-add_lower_columns.xml
Intent of this PR is to revert part of #1300.
Initially in 62d36c29640c50ea14779d22f6b5559c6f78bfd9 I have changed
implementation of case insensitive search to improve performance while querying.
However cp_consumer_facts table usually contains a lot of data and the migration
step thus takes a lot of time. This commit reverts the changes for the
cp_consumer_facts_lower that were introduced in the above mentioned commit
> Revert of cp_consumer_facts_lower

- server/bin/manifest_from_csv.rb
convenience utility created to facilitate katello csv testing. Help message is self explanatory:
* Usage:
Usage: manifest_manipulator [OPTIONS]
Options:
-i, --input [FILE]               The input csv with product ids, qty and date
-o, --output [FILE]              The folder to create the manifest in. (Default = /tmp).
-k, --key [OWNER_KEY]            the owner to bind from
-p, --product-column N           the product column index. (Default = 0
-q, --quantity-column N          the quantity coulumn index. (Default = 1)
-d, --date-column N              the date column index. (Default = 2
-h, --help                       Display help and exit
* Demo:
[vrjain@localhost bin]$ ./manifest_from_csv.rb -i test.csv  -k admin -o test
Created consumer: id = ff80808156667b5d015666cda2a302f6, uuid = …
> Added utility to create manifest from csv

- buildfile
- pom.xml
It looks like the class files that our in our official builds do not
have debug symbols in them.  No debug symbols saves some space but also
means that Support can't install a Satellite instance and then attach to
a running Candlepin with jdwp.
I have a suspicion that MEAD sets debug=false in an environment
configuration somewhere because the debug symbols are added when I
compile locally.  Setting the values explicitly should ensure the
symbols are left in.
> Ensure debug symbols make it into compiled code.

- server/client/ruby/candlepin_api.rb
- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/healing_spec.rb
- server/spec/hypervisor_check_in_spec.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/controller/AutobindDisabledForOwnerException.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/main/resources/db/changelog/20160907121757-add-autobind-disabled-column-to-owner.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/model/OwnerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/PersonConsumerResourceCreationLiberalNameRules.java
- server/src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
**Reviewers please test the scenarios listed [here](https://docs.google.com/document/d/1i0SJB2zX6QWXXa_YMEC1AIktth_44Ml5tBYLykTQWnI/edit)!**
Added autobindDisabled field/column to Owner
* Added the field to the Owner object
* Added utility method to consider null value when
asking if autobind is disabled for the Owner.
* Added a change set that adds the new column to
the cp_owner table.
Add ability to update Owner.autobindDisable via API
* PUT owners/:key will now update the autobindDisable
field on the targeted Owner.
Throw exception on autobind if disabled on owner
* Allows for determining precise impact points and
allows for customizing the resulting behavior.
* In most cases this results in a BadRequestException
thrown by the caller.
Block hypervisor checkins when autobind is …
> Disable autobind at Owner level (candlepin-0.9.54)

- server/spec/content_versioning_spec.rb
- server/spec/owner_product_resource_spec.rb
- server/spec/product_versioning_spec.rb
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/test/java/org/candlepin/controller/ContentManagerTest.java
- server/src/test/java/org/candlepin/controller/ProductManagerTest.java
- Product and Content entities are now treated as immutable objects
by their respective managers. Every chage made to either of these
types of entities will now result in new entities being created,
even in instances when fewer than two owners are using the entity.
- Updated unit and spec tests accordingly, and added missing tests
for verifying the new behavior
> Removed in-place updating for product and content

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
If there are more than one guest on the same hypervisor that checkin or autobind at near the same time it is possible for the hypervisor to end up with more than one of an entitlement necessary to cover the guests.
I was able to replicate this by autobinding multiple guests at the same time. When done with 2 guests the hypervisor ends up with 2 of the same entitlement.
The solution to this is to lock the hypervisor consumer earlier in the transaction to ensure only one autobind modifies the entitlements of the hypervisor at any time.
The performance implications seem to be minimal with a failure rate of 7% when auto attaching 500 guests (that are on the same hypervisor) at the same time. (For reference the failure rate is around 10% in my tests on 0.9.54-HOTFIX currently).
> Fix potential double entitlement issue by locking earlier in the transaction (0.9.54)

- docker/candlepin-base/cp-test
- docker/candlepin-base/setup-devel-env.sh
- Added the -j argument to cp-test for specifying a Java
version to use for building and running Candlepin
- The candlepin-base container now automatically installs
Java 1.6, 1.7 and 1.8, as well as the current version
(which happens to be 1.8 at the moment)
> Added an argument for specifying the Java version in cp-test

- server/client/ruby/candlepin_api.rb
- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/healing_spec.rb
- server/spec/hypervisor_check_in_spec.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/controller/AutobindDisabledForOwnerException.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/main/resources/db/changelog/20160907121757-add-autobind-disabled-column-to-owner.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/model/OwnerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/PersonConsumerResourceCreationLiberalNameRules.java
- server/src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
**Reviewers please test the scenarios listed [here](https://docs.google.com/document/d/1i0SJB2zX6QWXXa_YMEC1AIktth_44Ml5tBYLykTQWnI/edit)!**
Added autobindDisabled field/column to Owner
* Added the field to the Owner object
* Added utility method to consider null value when
asking if autobind is disabled for the Owner.
* Added a change set that adds the new column to
the cp_owner table.
Add ability to update Owner.autobindDisable via API
* PUT owners/:key will now update the autobindDisable
field on the targeted Owner.
Throw exception on autobind if disabled on owner
* Allows for determining precise impact points and
allows for customizing the resulting behavior.
* In most cases this results in a BadRequestException
thrown by the caller.
Block hypervisor checkins when autobind is …
> Disable autobind at Owner level (2.0)

- buildfile
> Add debug symbols to Java projects and not the top project.

- server/spec/owner_product_resource_spec.rb
Fixing random spec test failure. The attributes will get their 'updated' field
changed because now every time we change anything on a product, we expect new
version to be created
> 1387104: Product update changes 'updated' field

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
This is the same fix as in #1333 except against master.
> Lock the hypervisor consumer earlier to avoid over entitlement (2.x)

- .gitignore
- Vagrantfile
Add the .vagrant directory to the .gitignore & disable the localhost port-forwarding now that the hostmanager plugin will automatically update your hosts file with candlepin.example.com
> Disable vagrant port forward

- server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml
Candlepins with jpa.config.hibernate.hbm2ddl.auto=validate break when
NumericBooleanType is mapped to smallint.
Note that this change will require dropping your database and recreating it!
> Change mapping of NumericBooleanType to Integer

- server/src/main/resources/db/changelog/20161025100925-remove-unique-content-name-constraint.xml
> 1388201: Add check to insure constraint has not already been dropped

- server/src/main/resources/db/changelog/20161025100925-remove-unique-content-name-constraint.xml
> 1392107: Add check to insure constraint has not already been dropped

- server/src/main/resources/db/changelog/20161025100925-remove-unique-content-name-constraint.xml
> 1392114: Add check to insure constraint has not already been dropped

- server/src/main/resources/db/changelog/20161025100925-remove-unique-content-name-constraint.xml
> 1392108: Add check to insure constraint has not already been dropped

- server/src/main/resources/db/changelog/20161025100925-remove-unique-content-name-constraint.xml
To test:
1. Check out this branch.
2. Delete the line `<include file="db/changelog/20161025100925-remove-unique-content-name-constraint.xml"/>` from `changelog-create.xml` (It's the second to last line).
3. Run `bin/deploy -g`
4. `psql -U candlepin candlepin`
5. `select count (*) from pg_constraint where conname='cp_content_label_key';` should be 1.
6. Run `alter table cp_content drop constraint cp_content_label_key;`
7. `git checkout` changelog-create.xml (Revert your changes).
8. (optional) Edit `20161025100925-remove-unique-content-name-constraint.xml` and comment out the constraint.  Run `bin/deploy` and get an error.  Revert the change. …
> 1392111: Add check to insure constraint has not already been dropped

- server/src/main/java/org/candlepin/model/Content.java
- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/java/org/candlepin/model/ProductAttribute.java
- server/src/main/resources/META-INF/persistence.xml
Disable the hibernate 2nd level cache as it is competing for memory with the JSR-107 cache and does not appear to be providing significant speedup.
> Disable the Hibernate 2nd level cache and remove annotations

- Vagrantfile
- vagrant/README.md
- vagrant/roles/candlepin-root/defaults/main.yml
- vagrant/roles/candlepin-root/tasks/main.yml
To use this all you need to do is uncomment the setup_yourkit var (ensuring it is set to True) and uncomment the yourkit_library var. The latter must be set to the location of the libyjpagent.so file on your system that you would like to have installed in the remote tomcat.
After doing the above, start the virtual machine and provision as you normally would (using vagrant).
> Add ansible automation to optionally setup yourkit profiling

- server/spec/ueber_cert_spec.rb
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/model/UeberCertificateGenerator.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/model/UeberCertGeneratorTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java
- Addressed transaction issues that would allow partial
cert generation (combos of consumer, pool, prod, content).
- Lock the target Owner on cert generation so that checks
for an existing cert will succeed and result in a single
cert per owner.
- Added another changeset to delete all the ueber certificates
since already affected candlepin instances may have invalid
DB state due to this bug.
**Steps To Test This PR**
1. Deploy the latest version of candlepin 0954.
2. Follow steps to test in the BZ [1391922](https://bugzilla.redhat.com/show_bug.cgi?id=1391922) to reproduce.
**NOTE:** You may have to run the script a couple of times in order to get the bug to occur. See the BZ for more details. I had to run it twice, and counts are reflected in the DB query.
```bash
$ …
```
> 1391922: Fixed concurrent ueber cert generation issues (0.9.54)

- server/spec/ueber_cert_spec.rb
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/model/UeberCertificateGenerator.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java
- Addressed transaction issues that would allow partial
cert generation (combos of consumer, pool, prod, content).
- Lock the target Owner on cert generation so that checks
for an existing cert will succeed and result in a single
cert per owner.
- Added another changeset to delete all the ueber certificates
since already affected candlepin instances may have invalid
DB state due to this bug.
1. Deploy the latest version of candlepin 2.0
2. Follow steps to test in the BZ [1391923](https://bugzilla.redhat.com/show_bug.cgi?id=1391923) to reproduce.
**NOTE:** You may have to run the script a couple of times in order to get the bug to occur. See the BZ for more details. I had to run it twice, and counts are reflected in the DB query.
```bash
$ ./concurrent_ueber_cert.sh -o brewery
Creating …
```
> 1391923: Fixed concurrent ueber cert generation issues (2.0)

- Gemfile
- Gemfile.lock
- docker/candlepin-base/cp-test
- docker/candlepin-base/setup-supervisord.sh
- gutterball/bin/qpid/configure-qpid.sh
- server/bin/deploy
- server/erb/candlepin.conf.erb
- server/spec/candlepin_scenarios.rb
- server/spec/qpid_spec.rb
New -q switch for deploy script that will recreate queue 'allmsg' which is a
special queue for testing purposes. -a switch will also cause autoconf
to enable AMQP in candlepin config.
Docker image candlepin-base now installs qpid and starts it using supervisord.
cp-test script has new -q switch that uses guterrball configure-qpid.sh
script, to setup qpid (generate SSL keys, create event exchange) etc.
I also had to modify configure-qpid.sh to be aware of supervisorctl
You can now write spec tests that assert Qpid queue. There is a new
CandlepinQpid helper class.
> Qpid Spec Test Support

- profiles.yaml
- server/code/setup/cpsetup
- server/src/main/java/org/candlepin/hibernate/Oracle10gDialectFollowOnLockingOff.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
For some reason or other, against Oracle,
setting the LockMode on the query does not
seem to work.
As a workaround, look up the Owner by key,
and do a refresh with a LockMode.
> Fix issue locking Owner on Oracle

- server/client/ruby/candlepin_api.rb
- server/spec/owner_content_resource_spec.rb
- server/spec/owner_product_resource_spec.rb
- server/src/main/java/org/candlepin/auth/permissions/OwnerPermission.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/resource/OwnerContentResource.java
- server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java
- server/src/test/java/org/candlepin/resource/OwnerContentResourceTest.java
- Fixed a crash that could occur when paging requests for products or content
by owner while not sorting by a owner id or content/product uuid
- Updated OwnerContentCurator to use the CandlepinQuery for its collection-based
queries
> Fixed a crash when paging certain requests

- server/spec/candlepin_scenarios.rb
- server/spec/qpid_spec.rb
- server/src/main/java/org/candlepin/audit/QpidQmf.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/resource/StatusResource.java
- server/src/test/java/org/candlepin/audit/QpidQmfTest.java
- server/src/test/java/org/candlepin/resource/StatusResourceTest.java
Qpid can be in three states that Candlepin needs to distinguish. First state is
'Qpid down' which is when connection to the Qpid is not available. Second state
is 'Flow Stopped'. That situation occurs when one of the queues bound to the
event exchange is flow stopped (see Flow Control in Qpid docs). Last is normal
happy 'connected' state in which Qpid is available.
> Broker Status

- common/src/main/java/org/candlepin/common/exceptions/SuspendedException.java
- server/spec/suspend_mode_spec.rb
- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- server/src/main/java/org/candlepin/controller/ModeChangeListener.java
- server/src/main/java/org/candlepin/controller/ModeManager.java
- server/src/main/java/org/candlepin/controller/ModeManagerImpl.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/CandlepinModeChange.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterTriggerListener.java
- server/src/main/java/org/candlepin/resource/StatusResource.java
- server/src/main/java/org/candlepin/resteasy/filter/CandlepinSuspendModeFilter.java
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
- server/src/test/java/org/candlepin/controller/ModeManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
- server/src/test/java/org/candlepin/resource/StatusResourceTest.java
Candlepin can enter Suspend Mode. In this mode Candlepin will only respond to Status Resource requests and pause all Pinsetter Jobs.
It is expected that as soon as Candlepin enters Suspend Mode, no more new requests or jobs are started.
It is still possible that some of the ongoing requests and jobs succeed.
> Suspend mode

- server/src/main/java/org/candlepin/model/Pool.java
Loading entitlements forces a pool load. Because this is done with a left join on pool which triggers the exported calculation an extraordinary amount of time is spent in the entitlement fetch (500ms for medium/large database). Under large amounts of load this is having a cascading effect of slowing down everything.  
The risk with this is that areas of code that rely on the exported count will trigger additional calls to the databse. Where pools are acted on in bulk there is additional risk (manifest import specifically).
> 1399768: Make pool exported count calculation lazy

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/controller/ImportResult.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- Fixed a bug that would count existing products or contents as
updated during import or refresh, even if the operation did not
result in a net change to the entity
> Fixed a bug that would treat unchanged entities as updated

- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/util/CrlFileUtil.java
Futhermore, use EntityManager's flush instead of Session's flush so that
a missing transaction will cause a TransactionRequiredException to be
thrown instead of Session's flush which just fails silently.
> 1399356: No transaction in syncCRLWithDB caused immediate rollback

- server/src/main/java/org/candlepin/resource/AdminResource.java
- server/src/test/java/org/candlepin/resource/AdminResourceTest.java
In theory one should be able to see this api work by a curl something like the following:
`curl -ik -u admin:admin --request DELETE "https://localhost:8443/candlepin/admin/cache/product"`
You should be able to see the cache be cleared in jconsole by enabling statistics for ehcache by following the instructions found here: http://www.candlepinproject.org/docs/candlepin/caching.html
> Add API to clear productfullcache

- server/client/ruby/candlepin_api.rb
- server/spec/activation_key_spec.rb
- server/spec/environment_spec.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptor.java
- server/src/test/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptorTest.java
- CandlepinQueryInterceptor now uses its own session for streaming the
query results
- Added additional spec tests for testing streaming certain entities
> CandlepinQueryInterceptor now uses a separate session for cursors

- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
Every time the HornetQ session is aquired, EventSinkImpl
logs it. This can litter the logs which is unnecessary.
Reduced level to DEBUG so that the log info can still be
available.
> Reduce log level aquiring HornetQ session

- server/spec/consumer_bonus_pool_provided_spec.rb
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
The problem is in method PoolHelper.copyProvidedProducts. The method is used to
copy the original pool to a bonus pool. The method
expects the original pool (the one being copied) to be stored in the database.
It is trying to find its provided products in the database. That fails, because
the original pool is not yet there.
Adding more defensive code into that method. First I will check whether the
pool is already persisted (Pool.id != null). When it is not persisted, I will
copy the provided products directly from the original instance.
> 1394401: List of provided products empty on Bonus Pools

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Need clearer error message when register with system name exceeding max characters.
-throwing new exceptions with clear description + adding new constant to Consumer
-adding unit test
**Change from previous fix:** I cherry-picked commit from cp-0.9.23 and then changed generating of consumer name w.r.t @crog comment in /candlepin/candlepin/pull/1356. Another difference is that changing buildfile was not necessery, because buildfile has already corrected version of org.xnap.commons.i18n.
> 1371009:  clearer error message (for master)

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
1371009:Need clearer error message when register with system name exceeding max characters.
-throwing new exceptions with clear description + adding new constant to Consumer
-adding unit test
**Change from previous fix**: I cherry-picked commit from cp-0.9.23 and then changed generating of consumer name w.r.t @crog comment in /candlepin/candlepin/pull/1356. Another difference is that changing buildfile was not necessery, because buildfile has already corrected version of org.xnap.commons.i18n.
> 1371009: clearer error message (for 0.9.54)

- server/src/main/java/org/candlepin/jackson/StringTrimmingConverter.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/test/java/org/candlepin/jackson/StringTrimmingConverterTest.java
This is primarily intended to address ppc64 virt uuids that end with a
null byte, but in principle we do not want any facts to end in null
bytes or even whitespace.
> 1405125: Remove null byte from end of any fact value.

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Fixing typo in error message.
Previous message: Name of the consumer should be shorter than 255 characters.
Fixed message : Name of the consumer should be shorter than 256 characters.
> 1371009: clearer error message (fixed typo) for cp-0.9.51

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Fixing typo in error message.
Previous message: Name of the consumer should be shorter than 255 characters.
Fixed message : Name of the consumer should be shorter than 256 characters.
> 1371009: clearer error message (fixed typo) for cp-0.9.54

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Fixing typo in error message.
Previous message: Name of the consumer should be shorter than 255 characters.
Fixed message : Name of the consumer should be shorter than 256 characters.
> 1371009: clearer error message (fixed typo) for master

- docker/candlepin-base/setup-devel-env.sh
- The setup-devel-env script now installs qpid-proton-c and
qpid-proton-c-devel, which are now used by some of the new qpid
spec tests
> Updated the environment setup to include qpid-proton

- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/test/java/org/candlepin/audit/AMQPBusPublisherTest.java
- server/src/test/java/org/candlepin/audit/EventFactoryTest.java
- server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
Removed the useage of ProductCachedSerializationModule in
EventFactory while serializing pools since we use the
HATEOS JSON version of Pool when serializing for Events.
Removing this serializer produces the exact same JSON
data. No need to hydrate provided products as it is
never, and has never, been included.
On revoke entitlement, do not remove entitlements
from their pool's collection. Since the collection
is Extra lazy, hibernate will query the ents each
time an entitlement is removed from a Pool's collection.
By doing this, we are no longer maintaining runtime
consistency b/w Pools and Entitlements. The biggest
concern with doing this is that we may run into a
hibernate unscheduling problem. For example a missed
delete. To minimize this risk, this PR removes the cascades
on the …
> Batch Revoke Performance Fix (v3)

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/GuestIdResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
* while we discuss guest migration, reverting the guest migration implementation to what is currently in 0.9.54.
* this is a selective revert of [this](https://github.com/candlepin/candlepin/pull/1166/commits/ec77d7f09b30fef175b560775d45fadd4219646e) commit.
> Revert check for guest migration

- server/spec/candlepin_scenarios.rb
- server/spec/import_and_undo_exports_in_parallel_spec.rb
- server/spec/import_update_single_pool_spec.rb
- server/spec/spec_helper.rb
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/sync/ImporterTest.java
I wrote spec for this bug, which run (sync) importManifest (with updated manifest on brandings) and undoManifest in parralel.
When I experimented with mentioned spec I've never got same error like in bugzilla. It is becase we don't store subsrciption in DB anymore, but BZ should be covered by this fix.
I got different errors and deadlocks, so I locked owner at begining of both methods.
Fix's broken some unit tests so I changed those as well and made them little bit readable.
Note: For clarity, I moved ImportUpdateExporter from import_update_single_pool_spec to others exporters in candlepin_scenarios
> 1314042: bug caused by import and undo manifest run in parallel

- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- Fixed the query responsible for migrating activation keys to no
longer reference a dummy ID on the join table for activation key
products
> Fixed a bug that broke CP2 migration with activation keys

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/util/AttributeValidator.java
- server/src/main/java/org/candlepin/util/FactValidator.java
- server/src/main/java/org/candlepin/util/PropertyValidationException.java
- server/src/main/java/org/candlepin/util/PropertyValidator.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- server/src/test/java/org/candlepin/util/AttributeValidatorTest.java
- server/src/test/java/org/candlepin/util/FactValidatorTest.java
- server/src/test/java/org/candlepin/util/PropertyValidatorTest.java
- Added the new PropertyValidator class and its subclasses
AttributeValidator and FactValidator, which provide implementations
for validating attributes and facts, respectively
- Updated the ProductCurator and ConsumerCurator to use the new
PropertyValidator instances in place of their old private validation
methods
- ConsumerValidator no longer massages inbound fact data, but will
now, instead, throw PropertyValidationExceptions when it encounters
malformed or otherwise unmanagable data
- ConsumerResource now provides the massaging and filtering
functionality previously performed in the ConsumerCurator
> 1416823: Abstracted out property validation to new validator framework (0.9.49)

- server/client/ruby/candlepin_api.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/PoolResource.java
- server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorFilterTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/model/PoolTest.java
- server/src/test/java/org/candlepin/policy/CriteriaRulesTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
Either future only or active and future together.
To test this function you will need to use the two new query parameters 'add_future' and 'only_future' in conjunction with the 'activeon' parameter.
'activeon' determines what 'now' is for the other parameters. When not passed in, the current date will be used. If add_future is set to true, then you will get back any pool whose starting date is after the 'activeon' date in addition to those that the method previously returned. If only_future is set to true, then you will only get back the future date pools.
You may not use both add_future and only_future at the same time. It will return a bad request exception.
> 1414426: Ability to get future pools by owner

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/util/AttributeValidator.java
- server/src/main/java/org/candlepin/util/FactValidator.java
- server/src/main/java/org/candlepin/util/PropertyValidationException.java
- server/src/main/java/org/candlepin/util/PropertyValidator.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- server/src/test/java/org/candlepin/util/AttributeValidatorTest.java
- server/src/test/java/org/candlepin/util/FactValidatorTest.java
- server/src/test/java/org/candlepin/util/PropertyValidatorTest.java
- Added the new PropertyValidator class and its subclasses
AttributeValidator and FactValidator, which provide implementations
for validating attributes and facts, respectively
- Updated the ProductCurator and ConsumerCurator to use the new
PropertyValidator instances in place of their old private validation
methods
- ConsumerValidator no longer massages inbound fact data, but will
now, instead, throw PropertyValidationExceptions when it encounters
malformed or otherwise unmanagable data
- ConsumerResource now provides the massaging and filtering
functionality previously performed in the ConsumerCurator
> 1416825: Abstracted out property validation to new validator framework (0.9.54)

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/util/AttributeValidator.java
- server/src/main/java/org/candlepin/util/FactValidator.java
- server/src/main/java/org/candlepin/util/PropertyValidationException.java
- server/src/main/java/org/candlepin/util/PropertyValidator.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerTest.java
- server/src/test/java/org/candlepin/model/ProductCuratorTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- server/src/test/java/org/candlepin/util/AttributeValidatorTest.java
- server/src/test/java/org/candlepin/util/FactValidatorTest.java
- server/src/test/java/org/candlepin/util/PropertyValidatorTest.java
- Added the new PropertyValidator class and its subclasses
AttributeValidator and FactValidator, which provide implementations
for validating attributes and facts, respectively
- Updated the ProductCurator and ConsumerCurator to use the new
PropertyValidator instances in place of their old private validation
methods
- ConsumerValidator no longer massages inbound fact data, but will
now, instead, throw PropertyValidationExceptions when it encounters
malformed or otherwise unmanagable data
- ConsumerResource now provides the massaging and filtering
functionality previously performed in the ConsumerCurator
> 1416825: Abstracted out property validation to new validator framework

- server/client/ruby/candlepin_api.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/ConsumerTypeCurator.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerTypeValidator.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- This feature should be similar like listConsumer API, so it should return equal count of consumers.
- Feature was firstly implemented SQL, then with JPQL and at the end with hibernate criteria.
Perfromance test didn't show significant difference between these implementation. Hibernate criteria
was used because secureCriteria are used in listConsumer method and to use JPQL we would have to make more effort.
- Unit test added and refactored in ConsumerCuratorTest to test DB layer and OwnerResourceTest to test business layer.
Some older portion of code in OwnerResourceTest was refactored as well.
Notice methods which only passthrough collections.  These are only helpers for better readability and less verbosity.
Consider these 2 approaches:
```java
1)
List<String> typeLabels = null; …
```
> Pinhead counting feature

- server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml
- server/src/main/resources/db/changelog/20170125112728-cleanup-uebercerts-round3-2-0.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
This PR addresses 2 issues:
**1. When migrating the DB from 0.9.54 to 2.0 a checksum error occurs.**
The changeset causing the issue has been updated to validate all checksums that it encounters. It doesn't matter if the checksum is off here as it is only a cleanup task and contains no schema updates.
**2. Liquibase property definitions do not override existing ones that exist in a changelog.**
Re-run the cleanup as a precaution to make sure that the appropriate queries are run on migration.
**Testing Notes**
This PR will be tested in 2 stages -- checksum issue and the cleanup.
**Checksum Issue Testing**
1. Deploy candlepin 0.9.54 with test data
2. Deploy candlepin's current master branch (without recreating the DB) and the checksum issue should occur.
3. Apply this patch and redeploy …
> Candlepin 2.0 ueber cert cleanup 3 + checksum fix

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/ProvidedProduct.java
Fixes a bug in async hypervisor checkin when the job requires a provided product to be serialized.
to test, deploy master, checkout this branch, and run:
buildr rspec:hypervisor_check_in_spec.rb:"Hypervisor Checkin should complete succesfully when a guest"
> Fix ProvidedProduct serialization

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/ConsumerTypeCurator.java
- server/src/main/java/org/candlepin/model/activationkeys/ActivationKey.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptor.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorSearchTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- A handful of methods in ConsumerCurator have been updated to return
CandlepinQuery objects rather than returning Pages or Lists
- Affected resource methods have been updated to pass CandlepinQuery
objects received from the ConsumerCurator from their endpoints
> Made some optimizations to ConsumerCurator

- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
Ueber pools/entitlements should never get cleaned up unless the Owner is deleted.
**Pre-req:** Grab a manifest you have lying around, or ask me and I'll get you one.
```bash
$ bin/deploy -g
$ ./cpc create_owner testorg
$ ./cpc generate_ueber_cert testorg
$ ./cpc import testorg <path_to_manifest_file>
```
Verify the uber cert data is correct:
```sql
SELECT 
-- NO SUBS FOR 2.0
-- Certificates
(SELECT Count(*)
FROM   cp_ent_certificate ec
INNER JOIN cp_entitlement e
ON e.id = ec.entitlement_id
INNER JOIN cp_pool p
ON e.pool_id = p.id
INNER JOIN cp2_products prod
ON prod.uuid = p.product_uuid
WHERE  prod.NAME LIKE '%_ueber_product') AS UEBER_ENT_CERTS,
-- Entitlements
(SELECT Count(*)
FROM   cp_entitlement e
INNER JOIN cp_pool p
ON e.pool_id = p.id
INNER JOIN cp2_products prod
ON prod.uuid = …
```
> 1420455: No ueber pool deletion on manifest cleanup

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/model/CuratorPaginationTest.java
- server/src/test/java/org/candlepin/model/DeletedConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/GuestIdCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerAccessControlTest.java
- server/src/test/java/org/candlepin/model/ProductCertificateCuratorTest.java
- server/src/test/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptorTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultUserServiceAdapterTest.java
- server/src/test/java/org/candlepin/test/CacheTestFixture.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Moved the transaction for CandlepinPoolManager.entitleByProducts
to after the retry logic, which will allow many paths to release
pool locks between attempts when retrying
> Moved transaction around autobind to after retry logic

- server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java
- Reverted the use of cursors in the heal entire org job when
pulling consumers for a given org.
> Reverted the use of cursors in the heal entire org job

- server/src/main/java/org/candlepin/util/X509Util.java
Add background javadoc as to why engineering products must have numeric
product ids.
> add background javadoc for X509 PROD_FILTER_PREDICATE

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
ExpiredPoolJob now batch deletes expired pools and
entitlements. This drastically reduces the time it
takes to delete large numbers of expired pools.
Ping me for a test database with a lot of expired pools/ents and a git patch to apply over the top of this commit that provide a simple way to trigger the job.
Load the database by running:
```bash
$ ./restorecp-949.sh
```
Apply the support patch with:
```bash
$ git apply 0001-Support-for-testing-expired-pool-job.patch
```
Deploy candlepin WITHOUT recreating the DB
```bash
$ bin/deploy
```
Validate the expired pools/entitlement counts with the following query:
```sql
candlepin=# select
( select count(*) from cp_entitlement e, cp_pool p where e.pool_id = p.id and p.enddate < NOW() ) as expired_ents,
( select count(*) from cp_pool p where …
```
> 1428828: Use batch delete when deleting expired pools

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
ExpiredPoolJob now batch deletes expired pools and
entitlements. This drastically reduces the time it
takes to delete large numbers of expired pools.
Also fixed a broken unit test that was pre-existing.
ExpiredPoolJob now batch deletes expired pools and
entitlements. This drastically reduces the time it
takes to delete large numbers of expired pools.
Ping me for a test database with a lot of expired pools/ents and a git patch to apply over the top of this commit that provide a simple way to trigger the job.
Load the database by running:
```bash
$ ./restorecp-949.sh
```
Apply the support patch with:
```bash
$ git apply 0001-Support-for-testing-expired-pool-job.patch
```
Deploy candlepin WITHOUT recreating the DB
```bash
$ bin/deploy
```
Validate the expired pools/entitlement counts with …
> 1428827: Use batch delete when deleting expired pools

- Vagrantfile
So, I'm not a huge fan of using NFS. So I'd like to be able to just use rsync. This PR allows me (and anyone else who'd rather just `vagrant rsync`) to do that without affecting everyone else.
> Vagrant: skip NFS if CANDLEPIN_VAGRANT_NO_NFS set

- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- Certain ID-fetching queries now only fetch distinct results, reducing
the size of the following object-fetching queries and reducing the
probability of hitting the packet size limit on some databases
> Certain queries now only pull distinct values

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_host_guest_spec.rb
- server/spec/consumer_resource_spec.rb
- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/main/java/org/candlepin/policy/js/quantity/QuantityRules.java
- server/src/main/resources/rules/rules.js
While maintaining the ability to use it as input when creating
and updating consumers.
> Remove guestIds from the consumer json output

- server/src/main/resources/db/changelog/20170323142254-add-revoked-column-to-cert-serial.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
This PR simply adds the cp_cert_serial.revoked column and defaults the value to 'false'.
This is in prep for rolling out removing the @Formula currently on the field.
> Add revoked column to cp_cert_serial table

- server/spec/qpid_spec.rb
- server/src/main/java/org/candlepin/audit/HornetqContextListener.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
Candlepin will now enter suspend mode if Qpid is unavailable.
For this to occur the startup Qpid check must be disabled by setting `candlepin.amqp.qmf.startup_check_enabled` to `false`.
> Entering suspend mode on startup

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Don't load pools into memory, instead, use a query to update the
affected entitlements DB-side.
One way to see the effects:
- set `hibernate.show_sql` to `true` in `persistence.xml`.
- observe queries made in `buildr rspec:content_resource_spec`
> 1435807: Optimize cert regen from content update

- server/candlepin.spec.tmpl
Updating the liquibase version in the spec file as we are now using features from 3.0.0 in our changesets.
> Update required liquibase version

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
The tests for this PR will fail until our docker mysql images are updated to set the transaction isolation level to READ-COMMITTED.
The PR from the branch docker-refactor includes those changes.
> 1428145: Do not deadlock on simultaneous hypervisor checkin

- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Don't load pools into memory, instead, use a query to update the
affected entitlements DB-side.
Analogous to #1531 (this one targets 2.0).
One way to see the effects:
- set `hibernate.show_sql` to `true` in `persistence.xml`
- run `buildr rspec:owner_content_resource_spec`
> 1436258: Optimize cert regen from content update

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
Added the manifest extension params to the synchronous
export API.
Testing this is a little hackish since the default implementation of the ExportExtensionAdapter does nothing. After checking out this PR's branch, modify the DefaultExportExtensionAdapter.java to look like below. During an export, any provided ext params will be put in a file in the 'extensions' dir of the manifest zip.
```java
/**
* Copyright (c) 2009 - 2016 Red Hat, Inc.
*
* This software is licensed to you under the GNU General Public License,
* version 2 (GPLv2). There is NO WARRANTY for this software, express or
* implied, including the implied warranties of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
* along with this software; if not, see
* …
```
> 1440936: Support manifest ext params in deprecated API

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
Added the manifest extension params to the synchronous
export API.
Testing this is a little hackish since the default implementation of the ExportExtensionAdapter does nothing. After checking out this PR's branch, modify the DefaultExportExtensionAdapter.java to look like below. During an export, any provided ext params will be put in a file in the 'extensions' dir of the manifest zip.
```java
/**
* Copyright (c) 2009 - 2016 Red Hat, Inc.
*
* This software is licensed to you under the GNU General Public License,
* version 2 (GPLv2). There is NO WARRANTY for this software, express or
* implied, including the implied warranties of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
* along with this software; if not, see
* …
```
> 1440945: Support manifest ext params in deprecated API

- server/src/main/java/org/candlepin/controller/CdnManager.java
- server/src/main/java/org/candlepin/model/CdnCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/CdnManagerTest.java
When a Cdn is deleted and is associated with a pool,
we need to update the pool reference. Otherwise, hibernate
will throw an exception.
> Update Pool.cdn reference on Cdn deletion

- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
This change removes the check to always include the version of a
given content or product that was created during the initial migration
to versioned products & content. This removal means that the
initial versions created during the migration will never be matched
for deduplication. The first refresh for a given product or content will
always create a new entity. The existing orphan cleanup job will
clean up the initially migrated data.
The plus side is that we are not performing the null check for every item in the SQL query
and that we do not always return 2 entities that must be field wise
compared for the existing entities once a new version has been imported.
> Remove null version inclusion on getProductsByVersions and getContentByVersions

- server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml
- server/src/main/resources/db/changelog/20170214115606-uber-cert-rewrite.xml
- Added an index to cp2_products.product_id and cp2_content.content_id.
These should help improve overall performance, as many of our queries
still do RHID-oriented lookups rather than using the UUID.
- Added an index to cp_pool_products.product_id, which should
significantly improve migration times
> Added indexes to various tables (CP 2.0)

- server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml
- server/src/main/resources/db/changelog/20170214115606-uber-cert-rewrite.xml
- Added an index to cp2_products.product_id and cp2_content.content_id.
These should help improve overall performance, as many of our queries
still do RHID-oriented lookups rather than using the UUID.
- Added an index to cp_pool_products.product_id, which should
significantly improve migration times
> Added indexes to various tables (master)

- server/src/main/java/org/candlepin/resource/ActivationKeyResource.java
Fetching the pools for an activation key was
being scoped to a Super Admin. Loosened this
permission to anyone with access to the AK.
> 1445010: Fix permission issue on getting pools for an AK

- server/src/main/java/org/candlepin/resource/ActivationKeyResource.java
Fetching the pools for an activation key was
being scoped to a Super Admin. Loosened this
permission to anyone with access to the AK.
> 1445012: Fix permission issue on getting pools for an AK

- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTask.java
- server/src/main/java/org/candlepin/resource/AdminResource.java
- server/src/test/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTaskTest.java
- Added support for a skip_existing query parameter/option for
the populate hosted DB task which will skip fetching and updating
product information for products which already exist in the local
database
- When the hosted DB population job runs, it will now verify that the
products it requested were fetched; for each product it determines
was omitted, a warning will be printed. Additionally, the final
job status now includes the number of "unresolved references" hit.
> Added the skip_existing option to the populate hosted DB task

- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTask.java
- server/src/main/java/org/candlepin/resource/AdminResource.java
- server/src/test/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTaskTest.java
- Added support for a skip_existing query parameter/option for
the populate hosted DB task which will skip fetching and updating
product information for products which already exist in the local
database
- When the hosted DB population job runs, it will now verify that the
products it requested were fetched; for each product it determines
was omitted, a warning will be printed. Additionally, the final
job status now includes the number of "unresolved references" hit.
> Added the skip_existing option to the populate hosted DB task (0.9.51)

- server/spec/consumer_resource_host_guest_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/UeberCertificateGenerator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Several methods used for applying database/entity locks have been
generalized and refactored; extraneous methods have been removed
- Fixed a bug that could allow a temporary service level change to
be permanently applied
- Fixed a bug that prevented consumers from being refreshed when
the lockAndLoad method was called
> Consolidated and refactored the database locking methods

- server/spec/identity_spec.rb
- server/src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java
Prior to this patch, identity certificates were adding a distinguished name with the consumer name (generally the hostname) as a URI.  This behavior is obviously incorrect, but the question of what the correct behavior should be isn't immediately obvious.
I discuss my reasoning in the [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1395747), but in short, I elected to add both the subject field as a distinguished name and the consumer name as a distinguished name to the subject alternative names extension.  An identity certificate's subject alternative name extension will now look something like this:
```
X509v3 Subject Alternative Name: 
DirName:/CN=048d9b62-7665-4878-966b-6434d6b80a67, DirName:/CN=consumer-Fo7o5y9a
```
when viewed with `openssl x509 -in CERT_FILE -noout -text`.
This …
> 1395747: Fix incorrect semantics in entitlement certificate SANs.

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTask.java
- server/src/test/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTaskTest.java
Product lookups via the adapter take a long time on hosted,
and seems to cause c3p0 to close the DB connection due to
an idle connection timeout. This patch performs batch product
adapter lookups in order to shorten the idle time while
updating the product records.
> [0.9.51] Batch product fetching from adapters when populating hosted db.

- server/client/ruby/candlepin_api.rb
- server/spec/candlepin_scenarios.rb
- server/spec/multi_org_spec.rb
- server/spec/spec_helper.rb
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
If share org is deleted, then the share consumer is removed from master org
If REST call comes to delete master org while there is a share, then it will
fail with a message unless the force query parameter is used.
> Updates for owner delete

- server/spec/virt_spec.rb
- server/src/main/resources/rules/rules.js
This is an implementation of this design [1]. The work to prioritize the host specific and virt-only pools over others is done entirely by the rules.
[1]: https://docs.google.com/document/d/1fM19-FFxUAkt3T2kf_g1ZbjFUZBl5oA_LzlrN5WZtLs/edit#
> 1440909: Choose host_specific/virt_only pools first 

- server/client/ruby/hostedtest_api.rb
- server/spec/candlepin_scenarios.rb
- server/spec/import_cleanup_spec.rb
- server/spec/import_environment_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/dto/Subscription.java
- server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/resource/PoolResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Fixed a crash that could occur when creating a custom pool without
a source subscription that would require creation of derived pools
- Derived or bonus pools are no longer created for custom pools
without source subscription IDs
- Added a spec test for verifying that custom pools are not removed
during an import or refresh, so long as they were not created with
a source subscription
- Added a check to refresh to not remove pools that lack an upstream
pool ID in standalone mode. This temporary fix should avoid an issue
where pools created through the API were getting deleted during
refresh.
- Derived/children pools are now properly cleaned up during batch
deletion.
> 1452330: Added refresh behavior from Candlepin 0.9.x (2.0)

- server/spec/candlepin_scenarios.rb
- server/spec/import_cleanup_spec.rb
- server/spec/import_environment_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/dto/Subscription.java
- server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/resource/PoolResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Fixed a crash that could occur when creating a custom pool without
a source subscription that would require creation of derived pools
- Derived or bonus pools are no longer created for custom pools
without source subscription IDs
- Added a spec test for verifying that custom pools are not removed
during an import or refresh, so long as they were not created with
a source subscription
- Added a check to refresh to not remove pools that lack an upstream
pool ID in standalone mode. This temporary fix should avoid an issue
where pools created through the API were getting deleted during
refresh.
- Derived/children pools are now properly cleaned up during batch
deletion.
> 1452330: Added refresh behavior from Candlepin 0.9.x (master)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
HQL didnt help here, there was a bug that always resulted in a weird error "References to collections must be define a SQL alias" 
This happens due to the left outer join with products in the inner class fwiw.
resorting to native query here.
There was also a unit test in PoolManagerTest that did not make sense to me, please take a second look, I think what I did makes sense. we were ensuring a method isnt called before, but that method is only used in tests a.t.m.
> Mark modifying ents as dirty if not already

- docker/candlepin-base/cp-test
- When the -q flag is specified to setup Qpid, cp_test will now
verify the qpid directory exists in the active project before
attempting to run the setup tasks
> cp_test now checks for Qpid when attempting to configure it

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
in 731188f, when I split addOrUpdateEntitlements , I mistakingly coded to regenerate *all* the entitlements of a consumer, instead of just the one that we are now updating. this commit undoes that mistake.
> Undo excessive regen added by mistake in 731188f

- bin/bash_functions
- docker/candlepin-base/setup-db.sh
- server/bin/deploy
This is a fix for the deploy script that was broken by the extra quotes in bash_functions.
> Removes the extra quotes added mistakenly in the docker refactor

- server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml
- server/src/main/resources/db/changelog/20170220102027-add-id-column-for-productcontent.xml
- tasks/liquibase.rake
- Fixed a Liquibase migration task that would fail when attempting
to update a database that already contained product content
when run against MySQL
- Updated the Liquibase buildr task to use a newer version of the
XML validator
- Added a valid checksum to the ueber cert cleanup task to avoid
issues with certain migrations
> Fixed an issue with migrating a database with product content

- server/bin/test_data.json
- server/spec/candlepin_scenarios.rb
- server/spec/cert_revocation_spec.rb
- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/service/impl/DefaultContentAccessCertServiceAdapter.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/main/resources/db/changelog/20170612091842-default-content-access-list.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/OwnerManagerTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
If no list exists, then it is set to the default list and
the mode is also set to the default value ['entitlement']
Ensure that the org's content access mode is defined when the
org is created or updated
Update the mode list and mode columns to not null and default.
> 1448897: Enforce default content access mode list

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UniqueByEntityJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UnpauseJob.java
- server/src/test/java/org/candlepin/model/JobCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UnpauseJobTest.java
https://bugzilla.redhat.com/show_bug.cgi?id=1457905
When listing jobs, if the job class was deleted and is not
found, hibernate would through an exception when building
up the JobStatus object.
This was addressed by changing the JobStatus.jobClass field
to be a String instead of a class. This way hibernate will
not try and create a Class object from the class string.
Callers of JobStatus.getJobClass will now have to instantiate
the Class directly and handle cases where the class is not found.
1. Deploy 0.9.54 in **hosted** mode with test data.
2. Run the populate hosted DB Job
```bash
$ curl -k -u admin:admin https://localhost:8443/candlepin/admin/pophosteddb
{
"id" : "populated_hosted_db-9baf8b43-a96e-449b-a32d-7fbd909c7dd9",
"state" : "CREATED",
"startTime" : null,
"finishTime" : null, …
```
> (2.0) 1457905: Fix failure listing Jobs when class not found

- server/src/main/java/org/candlepin/pinsetter/tasks/JobCleaner.java
Since JobCleaner runs every 12h by default and
nothing is currently overriding it, there is no
reason not to log it.
> (2.0) Re-enable JobCleaner logging

- server/src/main/java/org/candlepin/pinsetter/tasks/JobCleaner.java
Since JobCleaner runs ever 12h by default and
nothing is currently overriding it, there is no
reason not to log it.
> Re-enable JobCleaner logging

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterTriggerListener.java
Adds some debug logging showing trigger information for the misfired quartz job.
Honestly, there isn't an easy way to test this. I had to hack some candlepin code to make it happen on my dev box. I don't think it is worth spending the time to verify this PR and a code review is enough.
> (2.0) Added logging for quartz job misfires

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UniqueByEntityJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UnpauseJob.java
- server/src/test/java/org/candlepin/model/JobCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UnpauseJobTest.java
https://bugzilla.redhat.com/show_bug.cgi?id=1457902
When listing jobs, if the job class was deleted and is not
found, hibernate would through an exception when building
up the JobStatus object.
This was addressed by changing the JobStatus.jobClass field
to be a String instead of a class. This way hibernate will
not try and create a Class object from the class string.
Callers of JobStatus.getJobClass will now have to instantiate
the Class directly and handle cases where the class is not found.
1. Deploy 0.9.54 in **hosted** mode with test data.
2. Run the populate hosted DB Job
```bash
$ curl -k -u admin:admin https://localhost:8443/candlepin/admin/pophosteddb
{
"id" : "populated_hosted_db-9baf8b43-a96e-449b-a32d-7fbd909c7dd9",
"state" : "CREATED",
"startTime" : null,
"finishTime" : null, …
```
> (2.1) 1457902: Fix failure listing Jobs when class not found

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterTriggerListener.java
Adds some debug logging showing trigger information for the misfired quartz job.
Honestly, there isn't an easy way to test this. I had to hack some candlepin code to make it happen on my dev box. I don't think it is worth spending the time to verify this PR and a code review is enough.
> (2.1) Added logging for quartz job misfires

- server/src/main/resources/rules/rules.js
Detects guestIds as non-existent in the context. This condition
occurs when newer rules versions are run in 0.9.54 because of
inclusion in manifests. This will delay the need to make a
major revision bump.
> 1461472: Update rules to run against 0.9 versions

- server/spec/consumer_resource_host_guest_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/OwnerContentCurator.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/UeberCertificateGenerator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/model/OwnerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Several methods used for applying database/entity locks have been
generalized and refactored; extraneous methods have been removed
- Fixed a bug that could allow a temporary service level change to
be permanently applied
- Fixed a bug that prevented consumers from being refreshed when
the lockAndLoad method was called
> Consolidated and refactored the database locking methods (2.0)

- server/src/main/resources/rules/rules.js
Rules changes during the Uber Cert re-write broke ueber cert
generation after the rules were imported into an older candlepin.
This patch reverts those changes to maintain backwards compatibility.
The rules version has been updated to 5.24.1 to avoid versioning
conflicts with candlepin 2.1.
1. Deploy candlepin from master - clean database with test data.
2. Create a distributor -- no need to attach any subs, we only need the rules.
```bash
$ curl -k -u admin:admin -X POST -H "Content-Type: application/json" -d '{"type":{"label":"candlepin"}, "name":"my_distributor", "facts":{}, "installedProducts":[], "contentTags":[]}' https://localhost:8443/candlepin/consumers?owner=admin
```
3. Export a manifest using the distributor you just created.
```bash
$ curl -k -u admin:admin …
```
> 1466966: Fixed broken rules when importing into old candlepin (2.0)

- server/src/main/resources/rules/rules.js
Rules changes during the Uber Cert re-write broke ueber cert
generation after the rules were imported into an older candlepin.
This patch reverts those changes to maintain backwards compatibility.
1. Deploy candlepin from master - clean database with test data.
2. Create a distributor -- no need to attach any subs, we only need the rules.
```bash
$ curl -k -u admin:admin -X POST -H "Content-Type: application/json" -d '{"type":{"label":"candlepin"}, "name":"my_distributor", "facts":{}, "installedProducts":[], "contentTags":[]}' https://localhost:8443/candlepin/consumers?owner=admin
```
3. Export a manifest using the distributor you just created.
```bash
$ curl -k -u admin:admin https://localhost:8443/candlepin/consumers/:uuid/export > manifest1.zip
```
4. Deploy this patch (without …
> 1467888: Fixed broken rules when importing into old candlepin (2.1)

- server/spec/import_spec.rb
- server/spec/rules_import_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- Pools for custom subscriptions will no longer be deleted on manifest
delete/undo import
- The Per-org products migration has been updated/fixed to also migrate
subscription information from the subscription table to the pool table
- Bonus pools now inherit upstream pool and customer data from their
source pool
> 1452694: Candlepin no longer deletes pools for custom subscriptions (2.0)

- server/bin/cmv
- server/client/ruby/candlepin_api.rb
- server/spec/spec_helper.rb
> Updated CMV to store and verify activation keys (0.9.51)

- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/EntitlementRulesTestFixture.java
- server/src/test/java/org/candlepin/policy/js/pool/PoolHelperTest.java
- PoolHelper.copyProvidedProducts (used by clonePool) now pulls products
in a batch, rather than individually
> Optimized the clonePool optimization in PoolHelper

- buildfile
- checks/pom.xml
- common/pom.xml
- server/pom.xml
- tasks/pom.rake
The new version of Buildr added attributes to its POM plugin that we did
not have in our POM plugin.  When the IDEA plugin attempted to access
these attributes, an exception was thrown.  This patch adds in those
attributes and writes them, if defined, into the POM file the same way
that Buildr would itself.
> Fix custom pom plugin to be compatible with new Buildr version.

- server/bin/cmv
- server/client/ruby/candlepin_api.rb
- server/spec/spec_helper.rb
> Updated CMV to store and verify activation keys (0.9.54)

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterTriggerListener.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterTriggerListenerTest.java
If you want to see the misfire happen do the following:
Alter ConfigProperties.java such that org.quartz.threadPool.threadCount = 1
Then add a sleep to the job you want to try out. I did ManifestCleanerJob.java
```
public void toExecute(JobExecutionContext arg0) throws JobExecutionException {
File baseDir = new File(config.getString(ConfigProperties.SYNC_WORK_DIR));
int maxAgeInMinutes = config.getInt(ConfigProperties.MANIFEST_CLEANER_JOB_MAX_AGE_IN_MINUTES);
try { Thread.sleep(10000); } catch (InterruptedException ie) { };
```
You will need to flood the API with requests to run the job. Here is a the bash I used:
```
#!/bin/bash
for it in `seq 1 150`;
do
curl -k -u admin:admin -X POST https://localhost:8443/candlepin/jobs/schedule/ManifestCleanerJob
done
```
About 30 seconds after the …
> Account for misfires in job status

- server/spec/import_spec.rb
- server/spec/rules_import_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/JsRunnerProvider.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- Pools for custom subscriptions will no longer be deleted on manifest
delete/undo import
- The Per-org products migration has been updated/fixed to also migrate
subscription information from the subscription table to the pool table
- Bonus pools now inherit upstream pool and customer data from their
source pool
> 1452694: Candlepin no longer deletes pools for custom subscriptions (2.1/master)

- server/selinux/candlepin.te
I have had no luck reproducing the actual SELinux denial, but you can test that the module works like so:
* `cd server/selinux`
* `dnf install selinux-policy-devel`
* `make NAME=targeted -f /usr/share/selinux/devel/Makefile` will build `candlepin.pp`
* `sudo semodule -s targeted -i candlepin.pp` which will install the module
* `ls -Z /var/log/candlepin` if you don't have a Candlepin policy already installed will likely show the context as `var_log_t`
* `sudo restorecon -R /var/log/candlepin`
* `ls -Z /var/log/candlepin` will show the new context
* `sudo semodule -r candlepin` will remove the module
You can find more information on the `logging_log_file` directive [here](https://debian-handbook.info/browse/stable/sect.selinux.html#example.te.interface).
> 1473255: Fix SELinux error when logrotate runs on candlepin logs

- server/bin/cmv
- server/bin/generate_consumers.rb
- The CMV tool now validates consumer entitlements for an org
- CMV no longer checks any field named "updated," as these are
universally problematic timestamp fields that are expected to change
during a migration anyway
- Added a utility script, generate_consumers.rb, for generating
consumers and consuming pools in a Candlepin deployment
> [2.0] Added entitlement validation to CMV

- server/bin/cmv
- server/bin/generate_consumers.rb
- The CMV tool now validates consumer entitlements for an org
- CMV no longer checks any field named "updated," as these are
universally problematic timestamp fields that are expected to change
during a migration anyway
- Added a utility script, generate_consumers.rb, for generating
consumers and consuming pools in a Candlepin deployment
> [0.9.51] Added entitlement validation to CMV

- server/bin/cmv
- server/bin/generate_consumers.rb
- The CMV tool now validates consumer entitlements for an org
- CMV no longer checks any field named "updated," as these are
universally problematic timestamp fields that are expected to change
during a migration anyway
- Added a utility script, generate_consumers.rb, for generating
consumers and consuming pools in a Candlepin deployment
> [master] Added entitlement validation to CMV

- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTask.java
- server/src/test/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTaskTest.java
- Products referenced by activation keys will now be fetched while
running the populated-hosted-db task
> The populate-hosted-db task now fetches activation key products

- docker/.env
Jenkins slaves have been updated (that work is in the rhsm-ansible repo), this should be all that is needed candlepin side.  This probably needs to be cherrypicked into the HOTFIX and other (?) branches, which @kahowell has written a nice script to do that.
> updating docker registry to new engineering host

- server/spec/virt_spec.rb
- server/src/main/resources/rules/rules.js
This is a change to the rules that allows virtualized systems to
reliably receive entitlements from host_specific and/or virt_only
pools before the consumption of quantity from physical pools.
There is one case that this change could make a bit worse.
In the case that there are not enough host_specific and/or
virt-only pools available to cover the products on the guest
system, the guest will be given entitlements from all available
virtual pools that provide at least one product in addition to
receiving an entitlement from as many physical pools as necessary
to cover the products installed.
If the available physical pools included one that would provide
all the installed products on the guest, all the entitlements
from the virtual pools would be redundant.
Adds a spec test for host pool …
> Forward port of 1440909 to master

- server/src/main/java/org/candlepin/model/IdentityCertificate.java
- server/src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
This consumer backreference caused hibernate to load another copy of the consumer from the database whenever the IdentityCertificate was loaded. For example, a consumer loads the identity which reloads the consumer.
> Remove an unused backreference from IdentityCertificate

- server/src/main/java/org/candlepin/model/IdentityCertificate.java
- server/src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java
This consumer backreference caused hibernate to load another copy of the consumer from the database whenever the IdentityCertificate was loaded even though lazy was specified. For example, a consumer loads the identity which reloads the consumer.
Back-port of #1686
> Remove an unused backreference from IdentityCertificate.

- server/src/main/java/org/candlepin/model/Owner.java
In order to prevent unnecessary queries for upstream consumer every time an organization is loaded mark the relationship as lazy.
> Make UpstreamConsumer lazy load

- bin/bash_functions
candlepin's mysql deployment requires READ-COMMITTED isolation level, otherwise some spec tests fail and the developers are left with no clue why. This warning should help with that, and is fired only if the current isolation level is not as expected.
> Warn devs about transaction isolation level on mysql

- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/test/java/org/candlepin/pinsetter/tasks/BaseJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTaskTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/ImportJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/JobCleanerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/RefreshPoolsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/RegenEntitlementCertsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/SweepBarJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UnpauseJobTest.java
When the @CandlepinScopedRequest annotation was removed from the cache it
caused the JsRunnerRequestCacheProvider to always return a new instance.
This meant that the rules version was queried many times instead of once in a given request.
In the KingPinJob was updated to properly enter & exit the scope CandlepinRequestScope
> 1482937: Fix regression in scoping of JsRunnerRequestCache

- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/test/java/org/candlepin/pinsetter/tasks/BaseJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTaskTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/ImportJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/JobCleanerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/RefreshPoolsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/RegenEntitlementCertsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/SweepBarJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UnpauseJobTest.java
When the @CandlepinScopedRequest annotation was removed from the cache it
caused the JsRunnerRequestCacheProvider to always return a new instance.
This meant that the rules version was queried many times instead of once in a given request.
This is a backport of 1482937 & https://github.com/candlepin/candlepin/pull/1701
> 1484438: Fix regression in scoping of JsRunnerRequestCache

- server/client/ruby/candlepin_api.rb
- server/client/ruby/hostedtest_api.rb
- server/spec/autobind_spec.rb
- server/spec/import_environment_spec.rb
- server/spec/instance_spec.rb
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/HostedVirtLimitEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
Fix custom pool lookup for bonus pool
the absence of source subscription is not a reliable way to determine if a pool is a custom pool,
since that behaviour varies with the candlepin verion. More reliable is the presence or absence of
an upstream pool id.
CandlepinPoolManager.isManaged is now the single method to determine if a pool is custom, and checks
both source subscription and upstream pool id.
> Fix custom pool lookup for bonus pool - 2.1

- server/client/ruby/candlepin_api.rb
- server/client/ruby/hostedtest_api.rb
- server/spec/autobind_spec.rb
- server/spec/import_environment_spec.rb
- server/spec/instance_spec.rb
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/policy/PoolRulesTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/HostedVirtLimitEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
Fix custom pool lookup for bonus pool
the absence of source subscription is not a reliable way to determine if a pool is a custom pool,
since that behaviour varies with the candlepin verion. More reliable is the presence or absence of
an upstream pool id.
CandlepinPoolManager.isManaged is now the single method to determine if a pool is custom, and checks
both source subscription and upstream pool id.
> Fix custom pool lookup for bonus pool

- server/spec/autobind_disabled_for_owner_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
Allow registration with autobind enabled key when owner
has disabled autobind.
When the disable owner's autobind feature was implemented
we blocked registration in this case, but this was in the end
not desirable.
> 1419016: Fix registration issue when owner's autobind is disabled.

- server/spec/autobind_disabled_for_owner_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
Allow registration with autobind enabled key when owner
has disabled autobind.
When the disable owner's autobind feature was implemented
we blocked registration in this case, but this was in the end
not desirable.
> 1487374: Fix registration issue when owner's autobind is disabled.

- server/spec/autobind_disabled_for_owner_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/test/java/org/candlepin/resource/util/ConsumerBindUtilTest.java
Allow registration with autobind enabled key when owner
has disabled autobind.
When the disable owner's autobind feature was implemented
we blocked registration in this case, but this was in the end
not desirable.
> 1487375: Fix registration issue when owner's autobind is disabled.

- server/spec/virt_spec.rb
- server/src/main/resources/rules/rules.js
This is a change to the rules that allows virtualized systems to
reliably receive entitlements from host_specific and/or virt_only
pools before the consumption of quantity from physical pools.
There is one case that this change could make a bit worse.
In the case that there are not enough host_specific and/or
virt-only pools available to cover the products on the guest
system, the guest will be given entitlements from all available
virtual pools that provide at least one product in addition to
receiving an entitlement from as many physical pools as necessary
to cover the products installed.
If the available physical pools included one that would provide
all the installed products on the guest, all the entitlements
from the virtual pools would be redundant.
Adds a spec test for host pool …
> 1440910: Choose host_specific/virt_only pools first (forward port to 2.0 of 1440909)

- server/bin/import_test_data.rb
Looks like the input test data script had code to create activation keys but exits before that step. This script fixes that issue.
> Create activation keys in test data

- common/src/main/java/org/candlepin/common/exceptions/ResourceMovedException.java
- server/client/ruby/candlepin_api.rb
- server/spec/import_spec.rb
- server/spec/multi_org_spec.rb
- server/spec/owner_resource_spec.rb
- server/spec/pool_resource_spec.rb
- server/spec/subscription_resource_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/PoolResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/resources/db/changelog/20170816084513-add-createdByShare-and-hasSharedAncestor.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
I'd like to call out the following items this PR does, one should consider before merging:
* discontinues the following APIs and provides replacements if they did not exist already
* PUT owner/subscriptions
* GET subscriptions/{id}
* GET subscriptions/{id}/cert
* SHARED is no longer a pool type, instead we have two new fields 
* createdByShare ( to identify a pool that was created because of a share)
* hasSharedAncestor ( to identify shared pools and their descendants )
* The rest API "DELETE pool/{id}" now deletes child pools of the pool id provided.
* This is necessary if it is to replace "DELETE subscription/{id}"
* CPM.deletePools no longer  sends out events for revoking entitlements when the pool is deleted.
* This was already the implementation in CPM.deletePool, and I think we …
> ambiguous subscription resources

- docker/candlepin-base/cp-test
beefing up the artifact saving for the Jenkins jobs to help with debugging errors.
> adding tomcat logs to the artifacts saved during cp-test

- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/owner_product_resource_spec.rb
- server/spec/product_resource_spec.rb
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Updated select rspec tests to use "skip" over "pending"
- Updated a few rspec tests to use "skip" instead of "pending" when
Candlepin is running in standalone mode
Fixed an issue with some PoolCurator tests and functionality
- Fixed a compilation error and failure in PoolCuratorTest
> [M] Test Failure Fixes

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/main/java/org/candlepin/util/Traceable.java
- server/src/main/java/org/candlepin/util/TraceableParam.java
- Added the new Traceable and TraceableParam annotations, to denote
large, complex or messy methods likely to be hotspots to be
explicitly measured in profiling tools
- Tagged a handful of methods with the new annotations:
- CandlepinPoolManager.refreshWithRegeneration
- CandlepinPoolManager.deletePools
- CandlepinPoolManager.revokeEntitlements
- ContentManager.importContent
- KingpinJob.execute
- ProductManager.importProducts
> [2.1] Added the new Traceable and TraceableParam annotations

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/main/java/org/candlepin/util/Traceable.java
- server/src/main/java/org/candlepin/util/TraceableParam.java
- Added the new Traceable and TraceableParam annotations, to denote
large, complex or messy methods likely to be hotspots to be
explicitly measured in profiling tools
- Tagged a handful of methods with the new annotations:
- CandlepinPoolManager.refreshWithRegeneration
- CandlepinPoolManager.deletePools
- CandlepinPoolManager.revokeEntitlements
- ContentManager.importContent
- KingpinJob.execute
- ProductManager.importProducts
> [M] Added the new Traceable and TraceableParam annotations

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/policy/js/pool/StackedSubPoolValueAccumulator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- PoolManager.deletePools no longer calls out to revokeEntitlements
as part of its operation
- Several optimizations were made to deletePools to minimize the
number of queries peformed and the number of entities it fetches
- Added new ID-based query methods to PoolCurator and EntitlementCurator
- Added a new utility method for partitioning blocks by the in-operator
block size to AbstractHibernateCurator
- Added a new utility method to Pool for properly checking if a pool
has a product attribute
> Made several optimizations to PoolManager.deletePools

- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- server/src/main/resources/db/changelog/20170919110500-fixupstreampoolmigration.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- The per-org migration task no longer migrates upstream subscription
info to all related pools, but instead only updates the master pool
for a given subscription
> [M] 1488508: Restricted upstream info migration to master pools

- server/src/main/resources/db/changelog/20140317115036-index-facts-consumerid.xml
- Added a valid checksum to the consumer ID fact index changeset
to fix an issue where Liquibase would detect an a mismatch when
the changeset was actually valid
> [2.0] Added a valid checksum to a problematic Liquibase changeset

- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- server/src/main/resources/db/changelog/20170919110500-fixupstreampoolmigration.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- The per-org migration task no longer migrates upstream subscription
info to all related pools, but instead only updates the master pool
for a given subscription
> [2.1] 1488508: Restricted upstream info migration to master pools

- server/src/main/resources/db/changelog/20140317115036-index-facts-consumerid.xml
- Added a valid checksum to the consumer ID fact index changeset
to fix an issue where Liquibase would detect an a mismatch when
the changeset was actually valid
> [M] Added a valid checksum to a problematic Liquibase changeset

- server/src/main/resources/db/changelog/20140317115036-index-facts-consumerid.xml
- Added a valid checksum to the consumer ID fact index changeset
to fix an issue where Liquibase would detect an a mismatch when
the changeset was actually valid
> [2.1] Added a valid checksum to a problematic Liquibase changeset

- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- server/src/main/resources/db/changelog/20170919110500-fixupstreampoolmigration.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- The per-org migration task no longer migrates upstream subscription
info to all related pools, but instead only updates the master pool
for a given subscription
> [2.0] 1488508: Restricted upstream info migration to master pools

- server/bin/qpid/README.md
- server/bin/qpid/configure-qpid.sh
- server/spec/candlepin_scenarios.rb
- server/spec/qpid_spec.rb
- Updated the qpid rspec tests to wait for messages and status
changes rather than using static sleep timers
- Updated the CandlepinQpid wrapper object to make use of
blocking calls, timeout configuration and configurable addresses
and cert/key files
> [M] Updated qpid rspec tests

- server/bin/qpid/README.md
- server/bin/qpid/configure-qpid.sh
- server/spec/candlepin_scenarios.rb
- server/spec/qpid_spec.rb
- Updated the qpid rspec tests to wait for messages and status
changes rather than using static sleep timers
- Updated the CandlepinQpid wrapper object to make use of
blocking calls, timeout configuration and configurable addresses
and cert/key files
> [2.1] Updated qpid rspec tests

- server/spec/pool_resource_spec.rb
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/audit/EventFilter.java
- Removed the old/previous pool from pool deleted events, as they
were unused by event consumers and very expensive to serialize
> [M] Pool deleted events no longer contain old pool entities

- server/spec/pool_resource_spec.rb
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/audit/EventFilter.java
- Removed the old/previous pool from pool deleted events, as they
were unused by event consumers and very expensive to serialize
> [2.1] Pool deleted events no longer contain old pool entities

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
This patch ensures that for a given owner only one HypervisorUpdateJob
will be run at a time. The next job (for the given owner) to execute will
be the job with oldest created date that is not in a Failed, Cancelled, or
Finished state.
You can test this PR by adding a sleep and some logging to the HypervisorUpdateJob.toExecute method as follows:
```java
log.debug("BEGINNING SLEEPING FOR 2 min");
Thread.sleep(120000);
log.debug("DONE SLEEPING EXECUTING");
```
After that change, you need only deploy CP and submit a bunch of async hypervisor check ins (such as repeatedly executing the following):
```shell
curl -ik -u admin:admin --request POST "https://localhost:8443/candlepin/hypervisors/admin" -d @async_hypervisor_report.json --header "Content-type: text/plain"
```
The file referenced …
> 1497248: Execute HypervisorUpdateJobs in the order they were received

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
This patch ensures that for a given owner only one HypervisorUpdateJob
will be run at a time. The next job (for the given owner) to execute will
be the job with oldest created date that is not in a Failed, Cancelled, or
Finished state.
see #1728 for testing instructions
> 1497707: Execute HypervisorUpdateJobs in the order they were received

- server/client/ruby/candlepin_api.rb
- server/spec/authorization_spec.rb
- server/spec/consumer_checkin_spec.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/auth/UpdateConsumerCheckIn.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resteasy/filter/AuthenticationFilter.java
- server/src/main/java/org/candlepin/resteasy/filter/ConsumerCheckInFilter.java
- server/src/test/java/org/candlepin/resteasy/filter/ConsumerCheckInFilterTest.java
This patch adds a ConsumerCheckInFilter that updates a consumer's
check-in time only if the REST resource called has the
UpdateConsumerCheckIn annotation.
The following methods have been annotated:
* ConsumerResource.updateConsumer (PUT /consumers/{uuid})
* ConsumerResource.regenerateEntitlementCertificates (PUT
/consumers/{uuid}/certificates)
* ConsumerResource.getEntitlementCertificates (GET
/consumers/{uuid}/certificates)
* ConsumerResource.getEntitlementCertificateSerials (GET
/consumers/{uuid}/certificates/serials)
* HypervisorResource.hypervisorUpdate (POST /hypervisors)
* HypervisorResource.hypervisorUpdateAsync (POST /hypervisors/{owner})
which should cover the cases of rhsmcertd check-ins, consumer refreshes,
and hypervisor check-ins.
> 1482949: Limit consumer check-in time updates to specific calls

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
Jobs are tracked in both cp_job and in the Quartz tables.  Prior to this
patch, when Pinsetter shutdown, it deleted job detail information from
the Quartz tables but did not alter the job in cp_job.  Upon startup,
the UnpauseJob would attempt to restart the job found in cp_job but no
correlating record would be found in the Quartz tables.
This patch adds a line to mark a job as canceled in the cp_job table as
the job is purged from the Quartz tables.  It also invokes a JobCurator
method that removes orphaned jobs on start up although this measure is
primarily preventative.
> 1497288: Mark jobs canceled when shutting down

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
Jobs are tracked in both cp_job and in the Quartz tables.  Prior to this
patch, when Pinsetter shutdown, it deleted job detail information from
the Quartz tables but did not alter the job in cp_job.  Upon startup,
the UnpauseJob would attempt to restart the job found in cp_job but no
correlating record would be found in the Quartz tables.
This patch adds a line to mark a job as canceled in the cp_job table as
the job is purged from the Quartz tables.  It also invokes a JobCurator
method that removes orphaned jobs on start up although this measure is
primarily preventative.
> 1498905: Mark jobs canceled when shutting down

- server/spec/autobind_disabled_for_owner_spec.rb
- Updated an autobind spec test to use use "skip" rather than "pending"
when checking if the test is running in hosted mode. This will
prevent the test from still running and failing with an error when
running in standalone mode.
> [2.1] Updated an autobind test to use "skip" instead of "pending"

- server/spec/content_access_spec.rb
- server/src/main/java/org/candlepin/service/impl/DefaultContentAccessCertServiceAdapter.java
The URLs that are contructed at the CDN use the environment name instead
of the environment id.
> 1498215: Use the environment name in the certificate

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/liquibase/FixDuplicatePoolsLiquibaseWrapper.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/SourceSubscription.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/resources/db/changelog/20171011093538-add-sourcesub-id-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
- Updated getPoolsBySubscriptionIds to pull pool IDs directly from
the cp2_pool_source_sub table, then lookup pools from there
- Deleting consumers no longer triggers consumer status recalcuation
nor dependent entitlement regeneration
- Added an index on the cp2_pool_source_sub.subscription_id column
to help speed up subscription ID based lookups
> [2.1] Optimized fetching/deleting pools by subscription IDs

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/liquibase/FixDuplicatePoolsLiquibaseWrapper.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/SourceSubscription.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/resources/db/changelog/20171011093538-add-sourcesub-id-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
- Updated getPoolsBySubscriptionIds to pull pool IDs directly from
the cp2_pool_source_sub table, then lookup pools from there
- Deleting consumers no longer triggers consumer status recalcuation
nor dependent entitlement regeneration
- Added an index on the cp2_pool_source_sub.subscription_id column
to help speed up subscription ID based lookups
> [2.0] 1500846: Optimized fetching/deleting pools by subscription IDs

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/liquibase/FixDuplicatePoolsLiquibaseWrapper.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/SourceSubscription.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/EnvironmentResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- server/src/main/resources/db/changelog/20171011093538-add-sourcesub-id-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
- Updated getPoolsBySubscriptionIds to pull pool IDs directly from
the cp2_pool_source_sub table, then lookup pools from there
- Deleting consumers no longer triggers consumer status recalcuation
nor dependent entitlement regeneration
- Added an index on the cp2_pool_source_sub.subscription_id column
to help speed up subscription ID based lookups
> [M] Optimized fetching/deleting pools by subscription IDs

- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/resources/db/changelog/20171010164730-add-cp-consumer-username-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
In addition to liquibase changes to add the index I have
deleted useless and deprecated @Index and @ForeignKey hibernate
annotations from Consumer since they are DDL specific.
> 1487758 Added index on cp_consumer.username field

- docker/docker-compose-build.yml
- docker/docker-compose-mysql.yml
- docker/docker-compose-oracle.yml
- docker/docker-compose-postgres.yml
If this makes the tests pass, we should do this for the other HOTFIX
branches as well. Our test infrastructure uses an MTU lower than 1500,
but when docker-compose creates networks they get an MTU of 1500, thus
problems.
> Override docker network MTU

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceVirtEntitlementTest.java
ConsumerResource.bind should NEVER be provided with a POST body. While technically that change would be backwards compatible,  there are older clients which erroneously provide an empty string  as a post body and hence result in a serialization error.
ref: BZ: 1502807
> [2.0] 1502807: bind with an empty string as POST body

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceVirtEntitlementTest.java
ConsumerResource.bind should NEVER be provided with a POST body. While technically that change would be backwards compatible,  there are older clients which erroneously provide an empty string  as a post body and hence result in a serialization error.
ref: BZ: 1502807
> [2.1] 1503298: bind with an empty string as POST body

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- Fixed an exception that could occur in CPM.deletePools when attempting
to delete pools which had entitlements which had derived pools
- PoolCurator.getPoolIdsForSourceEntitlements now returns pool IDs
like it should have been doing, rather than entitlement IDs.
> [2.0] 1502817: Fixed an issue with CPM.deletePools

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceEntitlementRulesTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceVirtEntitlementTest.java
ConsumerResource.bind should NEVER be provided with a POST body. While technically that change would be backwards compatible,  there are older clients which erroneously provide an empty string  as a post body and hence result in a serialization error.
ref: BZ: 1502807
> [M] 1503299: bind with an empty string as POST body

- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/policy/js/pool/StackedSubPoolValueAccumulator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- PoolManager.deletePools no longer calls out to revokeEntitlements
as part of its operation
- Several optimizations were made to deletePools to minimize the
number of queries peformed and the number of entities it fetches
- Added new ID-based query methods to PoolCurator and EntitlementCurator
- Added a new utility method for partitioning blocks by the in-operator
block size to AbstractHibernateCurator
- Added a new utility method to Pool for properly checking if a pool
has a product attribute
> [2.1] Made several optimizations to PoolManager.deletePools

- server/src/main/java/org/candlepin/resource/SubscriptionResource.java
- Fixed an error that could occur when calling the deleteSubscription
endpoint in the SubscriptionResource to delete a subscription which
had more than one associated pool
> [2.1] 1503694: Fixed an error that could occur while deleting subscriptions

- server/src/main/resources/db/changelog/20170220102027-add-id-column-for-productcontent.xml
- server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml
- server/src/main/resources/db/changelog/20170816084513-add-createdByShare-and-hasSharedAncestor.xml
- server/src/main/resources/db/changelog/20170919110500-fixupstreampoolmigration.xml
- server/src/main/resources/db/changelog/20171010164730-add-cp-consumer-username-index.xml
- server/src/main/resources/db/changelog/20171011093538-add-sourcesub-id-index.xml
- tasks/liquibase.rake
Using a schema version newer than what is packaged in the Liquibase jar
file will cause Liquibase to attempt to access the new schema over http.
In disconnected installations, the lack of network connectivity will
cause the request to fail and Liquibase will fail to run in turn.
Notes on testing:
1.  To test this item, you will need to be running Liquibase 3.1 and not 3.5 (which is the current version in Fedora). You can grab the old Liquibase RPM from the Satellite 6 repository and downgrade.
1.  You will need to turn off your machine's network connectivity.
1.  Run a bin/deploy -g. Liquibase will run and will fail because some of the changeset files are referencing the 3.5 schema. The failure occurs when trying to run the 20170220102027-add-id-column-for-productcontent.xml changeset.
> 1504710: Do not use schema version past what is available in RHEL 7.

- server/src/main/resources/db/changelog/20170220102027-add-id-column-for-productcontent.xml
- server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml
- server/src/main/resources/db/changelog/20170919110500-fixupstreampoolmigration.xml
- server/src/main/resources/db/changelog/20171011093538-add-sourcesub-id-index.xml
- tasks/liquibase.rake
Using a schema version newer than what is packaged in the Liquibase jar
file will cause Liquibase to attempt to access the new schema over http.
In disconnected installations, the lack of network connectivity will
cause the request to fail and Liquibase will fail to run in turn.
Notes on testing:
1. To test this item, you will need to be running Liquibase 3.1 and not 3.5 (which is the current version in Fedora).  You can grab the old Liquibase RPM from the Satellite 6 repository and downgrade.
2. You will need to turn off your machine's network connectivity.
3. Run a `bin/deploy -g`.  Liquibase will run and will fail because some of the changeset files are referencing the 3.5 schema.  The failure occurs when trying to run the `20170220102027-add-id-column-for-productcontent.xml` …
> [2.1] 1503164: Do not use schema version past what is available in RHEL 7.

- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/policy/js/pool/StackedSubPoolValueAccumulator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- PoolManager.deletePools no longer calls out to revokeEntitlements
as part of its operation
- Several optimizations were made to deletePools to minimize the
number of queries peformed and the number of entities it fetches
- Added new ID-based query methods to PoolCurator and EntitlementCurator
- Added a new utility method for partitioning blocks by the in-operator
block size to AbstractHibernateCurator
- Added a new utility method to Pool for properly checking if a pool
has a product attribute
> [M] Made several optimizations to PoolManager.deletePools

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/main/java/org/candlepin/policy/js/pool/StackedSubPoolValueAccumulator.java
- server/src/main/resources/db/changelog/20171023140857-add-modified-prods-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- Made additional optimizations to how marking dependent entitlements
is performed, significantly reducing execution time in cases where
many entitlements owned by many different consumers are updated
- Added the ProductCurator.hydratePoolProvidedProducts method, which
hydrates a pool's provided and derived provided products and the
product cache
- Updated CandlepinPoolManager.deletePools to use the new bulk pool
hydration method to substantially reduce serialization time while
passing pools and entitlements to the rules engine
- Modified CandlepinPoolManager.processPoolUpdates to bulk its
merge and flush operations, entitlement fetching and pool
existence checking
- Added a check to skip stacked pool updating for a consumer
when there are no stacked pools to update
> [2.1] 1506012: Optimized pool serialization and dependent entitlement lookup

- common/src/main/java/org/candlepin/common/config/PropertyConverter.java
- common/src/test/java/org/candlepin/common/config/MapConfigurationTest.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/model/Status.java
- server/src/main/java/org/candlepin/resource/StatusResource.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- server/src/test/java/org/candlepin/resource/StatusResourceTest.java
Using the key "candlepin.hidden_capabilities", users can set a
comma-delimited list of capabilities that will *not* be shown in the
response to /status call.
> [2.0] Add a setting to allow users to mask capabilities.

- common/src/main/java/org/candlepin/common/config/PropertyConverter.java
- common/src/test/java/org/candlepin/common/config/MapConfigurationTest.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/model/Status.java
- server/src/main/java/org/candlepin/resource/StatusResource.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- server/src/test/java/org/candlepin/resource/StatusResourceTest.java
Using the key "candlepin.hidden_capabilities", users can set a
comma-delimited list of capabilities that will *not* be shown in the
response to /status call.
> [2.1] Add a setting to allow users to mask capabilities.

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/SweepBarJob.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/SweepBarJobTest.java
Transactionalize delete jobs - Missing annotations were causing deletes not to occur
Batch lookups by id - List exceeding the limit
> [2.1] Job Cleaner

- common/src/main/java/org/candlepin/common/config/PropertyConverter.java
- common/src/test/java/org/candlepin/common/config/MapConfigurationTest.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/model/Status.java
- server/src/main/java/org/candlepin/resource/StatusResource.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- server/src/test/java/org/candlepin/resource/StatusResourceTest.java
Using the key "candlepin.hidden_capabilities", users can set a
comma-delimited list of capabilities that will *not* be shown in the
response to /status call.
> [M] Add a setting to allow users to mask capabilities.

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/SweepBarJob.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/SweepBarJobTest.java
Transactionalize delete jobs - Missing annotations were causing deletes not to occur
Batch lookups by id - List exceeding the limit
> [M] Job Cleaner

- server/src/main/java/org/candlepin/model/JobCurator.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java
- server/src/main/java/org/candlepin/pinsetter/tasks/SweepBarJob.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
- Moved job ID partitioning to the curators, as the jobs themselves
should not be concerned with partitioning a collection due to
query/database limitations
> [M] Moved job ID partitioning to the curators

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/main/java/org/candlepin/model/ProductCurator.java
- server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- server/src/main/java/org/candlepin/policy/js/pool/StackedSubPoolValueAccumulator.java
- server/src/main/resources/db/changelog/20171023140857-add-modified-prods-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- Made additional optimizations to how marking dependent entitlements
is performed, significantly reducing execution time in cases where
many entitlements owned by many different consumers are updated
- Added the ProductCurator.hydratePoolProvidedProducts method, which
hydrates a pool's provided and derived provided products and the
product cache
- Updated CandlepinPoolManager.deletePools to use the new bulk pool
hydration method to substantially reduce serialization time while
passing pools and entitlements to the rules engine
- Modified CandlepinPoolManager.processPoolUpdates to bulk its
merge and flush operations, entitlement fetching and pool
existence checking
- Added a check to skip stacked pool updating for a consumer
when there are no stacked pools to update
- Added a method for …
> [M] 1506014: Optimized pool serialization and dependent entitlement lookup

- server/src/main/java/org/candlepin/audit/Event.java
- server/src/main/java/org/candlepin/audit/EventBuilder.java
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- server/src/main/java/org/candlepin/audit/LoggingListener.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/EventCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- Removed the oldEntity field from the Event class, also
removed setOldEntity/getOldEntity from EventBuilder and EventFactory.
- Made setEventData on EventBuilder public to be used instead
of setOldEntity when building Events. This method will probably be
re-used similarly when newEntity will be removed in the future and
will be used when creating CREATED/DELETED events. It will be
overloaded for creating MODIFIED events (which currently need both
old/new entity).
- Removed a couple of unused methods (consumerModified, ownerMigrated)
> Event Simplification: Removed oldEntity from Events

- server/spec/autobind_spec.rb
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/resources/rules/rules.js
- Fixed an issue with the hasSharedAncestor property not being
serialized, preventing the rules from deprioritizing shared
pools during pool selection
> [M] Fixed an issue with shared pools not being deprioritized

- server/src/main/java/org/candlepin/audit/ActivationListener.java
- server/src/main/java/org/candlepin/audit/Event.java
- server/src/main/java/org/candlepin/audit/EventBuilder.java
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/test/java/org/candlepin/audit/ActivationListenerTest.java
- server/src/test/java/org/candlepin/audit/EventBuilderTest.java
- server/src/test/java/org/candlepin/audit/EventFactoryTest.java
This change is a precursor to removing newEntity.
- Added json blob field 'eventData' to Events which
holds a minimal dictionary of data, specific to events
'pool.created' and 'compliance.created', which are
the only data consumed currently from those on newEntity.
- ActivationListener now uses the new eventData field to
retrieve the subscriptionId for 'pool.created' events.
> Event Simplification: Added eventData to Events

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
- OwnerResource.updatePool now properly completes/merges the inbound
pool object using data from the existing pool before passing it
to the rules or refresh operations
- PoolRules now removes the VIRT_ONLY attribute from a pool if its
product no longer carries the restriction during enrichment
> [M] 1500843: Fixed several issues with OwnerResource.updatePool

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
Batched up job deletion in the scheduler to improve performance
of CancelJobJob when there are a lot of stale quartz jobs to
cancel.
> [M] Improve performance of CancelJobJob

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
Batched up job deletion in the scheduler to improve performance
of CancelJobJob when there are a lot of stale quartz jobs to
cancel.
> [2.0] Improve performance of CancelJobJob

- server/src/main/java/org/candlepin/audit/Event.java
- server/src/main/java/org/candlepin/audit/EventBuilder.java
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/audit/LoggingListener.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/audit/EventBuilderTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/EventCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- Removed the newEntity field from Events
- EventBuilder's setEventData should now be used
for both created and deleted entities where
setNewEntity/setOldentity was used before.
- Overloaded setEventData as a utility to accept
both an old and a new entity for modification events.
- Removed verbose mode from LoggingListener and
the verbose mode property since it is no longer used.
- Added the eventData field to the normal audit log output.
> Event Simplification: Removed newEntity field

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CancelJobJobTest.java
Batched up job deletion in the scheduler to improve performance
of CancelJobJob when there are a lot of stale quartz jobs to
cancel.
> [2.1] Improve performance of CancelJobJob

- server/code/setup/cpdb
- server/code/setup/cpsetup
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationValidationLiquibaseWrapper.java
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationValidationTask.java
- server/src/main/resources/db/changelog/20171108140157-perorgproducts-migration-validation.xml
- server/src/main/resources/db/changelog/changelog-validate.xml
- Added a new set of liquibase tasks which perform database
validation rather than modification. These are part of the new
changelog-validate.xml file and are not included in any of the
existing changelog collections.
- Updated cpdb to have a --validate option, which runs the new
validation set of Liquibase tasks
- Added --verbose to cpdb, which sets the logging level in
Liquibase to "debug"
- Added the PerOrgProductsMigrationValidationTask and Liquibase
wrapper
- Minor whitespace and spelling corrections throughout cpdb and
cpsetup
> [M] Added a per-org products migration validation Liquibase task

- server/code/setup/cpdb
- server/code/setup/cpsetup
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationValidationLiquibaseWrapper.java
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationValidationTask.java
- server/src/main/resources/db/changelog/20171108140157-perorgproducts-migration-validation.xml
- server/src/main/resources/db/changelog/changelog-validate.xml
- Added a new set of liquibase tasks which perform database
validation rather than modification. These are part of the new
changelog-validate.xml file and are not included in any of the
existing changelog collections.
- Updated cpdb to have a --validate option, which runs the new
validation set of Liquibase tasks
- Added --verbose to cpdb, which sets the logging level in
Liquibase to "debug"
- Added the PerOrgProductsMigrationValidationTask and Liquibase
wrapper
- Minor whitespace and spelling corrections throughout cpdb and
cpsetup
> [2.1] Added a per-org products migration validation Liquibase task

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
To test PR:
* pause scheduler by making REST request:
POST https://localhost:8443/candlepin/jobs/scheduler ( request body: "false" )
* make any async job request :
curl -X PUT  -k -u admin:admin  "https://localhost:8443/candlepin/owners/admin/subscriptions" 
then use following sql to verify appropriate priorities:
> candlepin=# select distinct priority, trigger_group from qrtz_triggers;
priority | trigger_group 
----------+---------------
5 | async group
7 | cron group
> [2.1] Prioritize cron jobs over async jobs

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
To test PR:
* pause scheduler by making REST request:
POST https://localhost:8443/candlepin/jobs/scheduler ( request body: "false" )
* make any async job request :
curl -X PUT  -k -u admin:admin  "https://localhost:8443/candlepin/owners/admin/subscriptions" 
then use following sql to verify appropriate priorities:
> candlepin=# select distinct priority, trigger_group from qrtz_triggers;
priority | trigger_group 
----------+---------------
5 | async group
7 | cron group
@
> [M] Prioritize cron jobs over async jobs

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
To test PR:
* pause scheduler by making REST request:
POST https://localhost:8443/candlepin/jobs/scheduler ( request body: "false" )
* make any async job request :
curl -X PUT  -k -u admin:admin  "https://localhost:8443/candlepin/owners/admin/subscriptions" 
then use following sql to verify appropriate priorities:
> candlepin=# select distinct priority, trigger_group from qrtz_triggers;
priority | trigger_group 
----------+---------------
5 | async group
7 | cron group
> [2.0] Prioritize cron jobs over async jobs

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
Pause and un pause scheduler, never pause all jobs. cause when we do, quartz pauses the thread group itself. Later it does not resume the async thread group correctly, and as a result no async jobs will run.
To test this PR, please test that:
* candlepin is able to schedule async jobs even when it is suspended and those jobs resume and run to completion once candlepin resumes to normal mode. ( as long as tomcat was not shut down inbetween those steps )
* cron jobs pause when candlepin moves to suspend mode and resume when candlepin resumes to normal mode.
* any scheduled async or cron jobs are cancelled when tomcat is shutdown while candlepin was in suspended mode.
> [M] 1510082: mode change breaks pinsetter

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
Pause and un pause scheduler, never pause all jobs. cause when we do, quartz pauses the thread group itself. Later it does not resume the async thread group correctly, and as a result no async jobs will run.
To test this PR, please test that:
*   candlepin is able to schedule async jobs even when it is suspended and those jobs resume and run to completion once candlepin resumes to normal mode. ( as long as tomcat was not shut down inbetween those steps )
*   cron jobs pause when candlepin moves to suspend mode and resume when candlepin resumes to normal mode.
*   any scheduled async or cron jobs are cancelled when tomcat is shutdown while candlepin was in suspended mode.
> [2.1] 1511615: mode change breaks pinsetter

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
* Certain cron jobs are getting stuck in BLOCKED state and requires a manual update via SQL.
* This API destroys current trigger and recreates it with a clean state.
* If we need the job to run immediately, we should continue to use the exsisting jobs/{}/schedule API.
> [2.0] 1512879: Force re-trigger cron jobs

- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/resource/JobResource.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
* Certain cron jobs are getting stuck in BLOCKED state and requires a manual update via SQL.
* This API destroys current trigger and recreates it with a clean state.
* If we need the job to run immediately, we should continue to use the exsisting jobs/{}/schedule API.
> [2.1] 1512884: Force re-trigger cron jobs

- bin/bash_functions
Newer versions of PostgreSQL print out informational messages when psql
is invoked.  For example, if a user has "\pset pager off" set in their
.psqlrc file, the psql command will print a notice about this setting to
stdout.  This notice causes the conditional we use to check to see
whether the candlepin database exists or not to fail.  Consequently, the
database is not dropped and the subsequent createdb command fails since
the database already exists.  The -q option suppresses these
informational messages.
> Add -q option when checking for database existence.

- server/bin/cmv
- server/bin/manifest_manipulator.rb
I was having trouble getting this utility to generate a manifest which could be imported to Candlepin. It looks like the script is supporting an older version of the rubyzip gem and once I updated the script to support the version which I had installed, things started working for me.
```
[vagrant@centos7-devel candlepin]$ gem list rubyzip
*** LOCAL GEMS ***
rubyzip (1.2.1)
```
Before:
```
[vagrant@centos7-devel candlepin]$ ./server/bin/manifest_manipulator.rb 
/home/vagrant/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- zip/zip (LoadError)
from /home/vagrant/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from ./server/bin/manifest_manipulator.rb:5:in `<main>' …
```
> Update rubyzip usage in manifest_manipulator.rb

- server/client/ruby/hostedtest_api.rb
- server/spec/client_v1_size_spec.rb
- server/spec/owner_content_resource_spec.rb
- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
1514483: entitlements are regenerated on content change of provided products
* a previous commit had changed subscription resolution to no longer resolve product or content,
this change undoes that so we can test this.
* added the spec test to test that refresh after content and product change does indeed regenerate ent
> [2.1] 1514483: entitlements are regenerated on content change of provided products

- server/client/ruby/hostedtest_api.rb
- server/spec/client_v1_size_spec.rb
- server/spec/owner_content_resource_spec.rb
- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
1514472: entitlements are regenerated on content change of provided products
* a previous commit had changed subscription resolution to no longer resolve product or content,
this change undoes that so we can test this.
* added the spec test to test that refresh after content and product change does indeed regenerate ent
>  [2.0] 1514472: entitlements are regenerated on content change of provided products

- server/client/ruby/hostedtest_api.rb
- server/spec/client_v1_size_spec.rb
- server/spec/owner_content_resource_spec.rb
- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
1514484: entitlements are regenerated on content change of provided products
* a previous commit had changed subscription resolution to no longer resolve product or content,
this change undoes that so we can test this.
* added the spec test to test that refresh after content and product change does indeed regenerate ent
> [M] 1514484: entitlements are regenerated on content change of provided products

- common/po/zanata.xml
> Update zanata URL (2.1)

- common/po/zanata.xml
Also set the version to candlepin-2.0-HOTFIX
> Update zanata URL (2.0)

- common/po/zanata.xml
> Update zanata URL (0.9.54)

- common/po/zanata.xml
Also set the version to candlepin-0.9.51-HOTFIX
> Update zanata URL (0.9.51)

- common/po/zanata.xml
Also set version to candlepin-0.9.49-HOTFIX
> Update zanata URL (0.9.49)

- server/code/setup/cpdb
- server/code/setup/cpsetup
- server/src/main/java/org/candlepin/liquibase/CustomTaskLogger.java
- server/src/main/java/org/candlepin/liquibase/LiquibaseCustomTask.java
- server/src/main/java/org/candlepin/liquibase/LiquibaseCustomTaskLogger.java
- server/src/main/java/org/candlepin/liquibase/LiquibaseCustomTaskWrapper.java
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationValidationLiquibaseWrapper.java
- server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationValidationTask.java
- server/src/main/resources/db/changelog/20171108140157-perorgproducts-migration-validation.xml
- server/src/main/resources/db/changelog/changelog-validate.xml
- Added a new set of liquibase tasks which perform database
validation rather than modification. These are part of the new
changelog-validate.xml file and are not included in any of the
existing changelog collections.
- Updated cpdb to have a --validate option, which runs the new
validation set of Liquibase tasks
- Added --verbose to cpdb, which sets the logging level in
Liquibase to "debug"
- Added the PerOrgProductsMigrationValidationTask and Liquibase
wrapper
- Minor whitespace and spelling corrections throughout cpdb and
cpsetup
> [0.9.54] 1519900: Added a per-org products migration validation Liquibase task

- server/src/main/resources/db/changelog/20171108140157-perorgproducts-migration-validation.xml
- The per-org products migration validation Liquibase task now always
runs, even if it has previously passed, so long as the preconditions
succeed
- Improved the output message when the precondition fails and causes
the validation task to not be run
> [M] Forward port of Liquibase migration validation improvements

- server/src/main/resources/db/changelog/20171108140157-perorgproducts-migration-validation.xml
- The per-org products migration validation Liquibase task now always
runs, even if it has previously passed, so long as the preconditions
succeed
- Improved the output message when the precondition fails and causes
the validation task to not be run
> [2.1] Forward port of Liquibase migration validation improvements

- server/src/main/java/org/candlepin/model/Consumer.java
Joining on the cp_key_pair table can take hundreds of milliseconds in
tables with many rows.  The KeyPair object is not even used in most
cases, so switching it to lazy loading will shave some time off our
queries at the expense of an additional query in the cases where we
actually need the KeyPair.
> 1515093: Set the KeyPair object to lazy load.

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- PoolCurator.listBySourceEntitlements now de-duplicates pools and entitlements
before returning or recursing
- Some debug statements in CandlepinPoolManager are now trace statements, as
their output was only useful in exceptional cases
> [2.1] 1499001: Fixed parameter limit issues with PoolCurator.listBySourceEntitlements

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolCuratorTest.java
- PoolCurator.listBySourceEntitlements now de-duplicates pools and entitlements
before returning or recursing
- Some debug statements in CandlepinPoolManager are now trace statements, as
their output was only useful in exceptional cases
> [M] 1499003: Fixed parameter limit issues with PoolCurator.listBySourceEntitlements

- server/src/main/java/org/candlepin/model/Owner.java
- Owner.autobindDisabled now accepts null values again, to work
around an issue with pre-existing data not having a value set
for this field
> [DTOs] Fixed an issue with the Owner.autobindDisabled not allowing nulls

- server/client/ruby/candlepin_api.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
found during DTO work, insignificant validations, committed separately to have an independent conversation
* in the create share consumer case if you don't provide and empty collection for installed products, we get an NPE. fixed now.
* today if you provide an id-cert in the POST register request, candlepin accepts it. this should not be allowed, each consumer should have a unique id cert generated by candlepin.
* today non-share consumers are allowed to specify recipient owners which does not make sense.
* we also accept entitlement count and persist it for some reason, intuitively that does not make sense.
> Misc. validations on consumer registration. 

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
* To verify the fix, run updatedNameRegeneratesIdCert unit test before and after the fix.
* The current test is not ideal because it relies on the object being manipulated in the method, improved it in dtos branch.
> mark changesMade on name change in performConsumerUpdates

- server/src/main/resources/db/changelog/20130425102131-distributor-capabilities.xml
- server/src/main/resources/db/changelog/20130501152202-add-content-arch.xml
- server/src/main/resources/db/changelog/20161109145238-add-owner-environment-content-access.xml
- server/src/main/resources/db/changelog/20170202093945-add-ueber-cert-to-owner.xml
- server/src/main/resources/db/changelog/20170206114359-convert-quanity-consumed-exported-to-columns.xml
- server/src/main/resources/db/changelog/20170227140343-convert-consumer-entitlement-count-to-column.xml
- server/src/main/resources/db/changelog/20170301083925-update-revoked-cert-serial-data.xml
- server/src/main/resources/db/changelog/20171017062314-add-target-index-on-job-table.xml
- server/src/main/resources/db/changelog/20171020150559-add-index-to-cp-consumer-content-tags.xml
- server/src/main/resources/db/changelog/datatypes.xml
- Several Liquibase change sets have been updated to address errors
which occurred when running against Oracle databases
- Optimized a few queries to work faster and/or require less
separation between the database plaforms
- Removed an unneeded rollback task in the update-revoked-cert-serial
task
> [M] Fixed several Oracle-related SQL errors in Liquibase tasks

- server/spec/environment_spec.rb
- server/src/main/java/org/candlepin/model/dto/EnvironmentContent.java
We depend on the database value of null, true, or false, to determine
whether the environment has overridden the default value. When the
DTO was added in Candlepin 2.x it was set to true by default and thus
the environment was always overriding the value from the engineering
product.
> [2.1] 1533211: Set the default enabled value for Environment Content to Null

- server/spec/environment_spec.rb
- server/src/main/java/org/candlepin/model/dto/EnvironmentContent.java
We depend on the database value of null, true, or false, to determine
whether the environment has overridden the default value. When the
DTO was added in Candlepin 2.x it was set to true by default and thus
the environment was always overriding the value from the engineering
product.
https://bugzilla.redhat.com/show_bug.cgi?id=1533212
> [M] 1533212: Set the default enabled value for Environment Content to Null

- server/spec/derived_product_spec.rb
- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
When a regular consumer binds to an entitlement providing product
modifiers, candlepin matches on product/provided products to
determine if the modified content should be added to the
entitlement certificate.
However, when a distributor binds to the same entitlement, candlepin
will also try to match on the derived product and derived
provided products.
This patch addresses a bug where candlepin was not considering
derived products when checking to see which modifier entitlements
to regenerate when pools/entitlements are deleted.
> [2.2] 1514515: Correctly update distributor's modified product content

- server/spec/derived_product_spec.rb
- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
When a regular consumer binds to an entitlement providing product
modifiers, candlepin matches on product/provided products to
determine if the modified content should be added to the
entitlement certificate.
However, when a distributor binds to the same entitlement, candlepin
will also try to match on the derived product and derived
provided products.
This patch addresses a bug where candlepin was not considering
derived products when checking to see which modifier entitlements
to regenerate when pools/entitlements are deleted.
> [M] 1514517: Correctly update distributor's modified product content

- server/src/main/resources/db/changelog/20180110092945-cleanup-uebercerts-round4-premigration.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
Since pre-org migration is now stricter,
we need to clean up ueber certs while the data is in
pre migrated format. the SQL here is identical to
round 3 in 0.9.54
> [2.1] 1531107: Round 4 of ueber data cleanup.

- server/src/main/resources/db/changelog/20180110092945-cleanup-uebercerts-round4-premigration.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
Since pre-org migration is now stricter,
we need to clean up ueber certs while the data is in
pre migrated format. the sql here is identical to
round 3 in 0.9.54
the scenario that breaks: upgrade from 0.9.54.X where X < 18 to 2.1, master, 2.2.
for testing steps, please use comments in #1459 
reviewer: please verify upgrade from 0.9.54.17 to 0.9.54-HOTFIX as well, and  confirm my finding that we don't have an issue there.
> [M] 1531106: Round 4 of ueber data cleanup.

- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionServiceAdapter.java
* discovered this during DTO work. we dont get uuids from the adapters, so the adapters were changed to reflect that
* to expose why that is a problem, adding an optimization in detecting content changes
> [m] Clear uuids in HostedTestSubscriptionServiceAdapter

- server/src/main/java/org/candlepin/controller/ContentManager.java
- server/src/main/java/org/candlepin/controller/ProductManager.java
- server/src/main/java/org/candlepin/dto/api/v1/OwnerDTO.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionServiceAdapter.java
what was changed and why:
* addContentToUpstreamSubscriptions was removed, which breaks two tests in entitlement_certificate_v3_spec.rb because the upstream subscriptions were not being updated with the new content, as is currently done in master. this PR adds it back.
* we added a ProductContentDTO comparator in ProductManager but never used it, fixed in this PR.
* ProductManager simply uses ContentManager.isChangedBy. uuid comparision for content is now skipped ( as it is in master ) which fixes the spec tests in refresh_pools_spec.rb
* to verify it was broken, compare results in target branch and PR branch : 
* deploy in hosted mode
* buildr rspec:refresh_pools:"regenerates entitlements when"
> [DTO] Fixed content detection in products

- .gitignore
- Gemfile
- Gemfile.lock
- server/bin/qpid_watch.py
- server/spec/candlepin_scenarios.rb
- server/spec/qpid_spec.rb
- vagrant/README.md
- vagrant/roles/candlepin-root/tasks/main.yml
- vagrant/roles/candlepin-user/tasks/main.yml
Also includes a script that uses the python proton bindings so that developers can easily spy on the queue and watch events flow through.  Theoretically, this script might be enough to spec test with, but I have difficulty with it starting too slow to catch events in the spec test.  We'd have to start it, have it not block, and then watch for the event coming through.
I thought it would just be easier to have the vagrant image rely on the qpid_proton provided via Yum while developers can do a `bundle install`
This PR also returns the Qpid version to 0.17.0 which is what Jenkins wants.  Developers should just use `bundle install --without=proton` to avoid the issue altogether.  Theoretically, it would be possible to segregate the two tests that actually require the qpid_proton library and …
> Do not use the rubygems provide proton bindings on Vagrant.

- server/src/main/resources/db/changelog/20171017062314-add-target-index-on-job-table.xml
Using a version that's not packaged in the Liquibase jar file results in
Liquibase trying to download the schema.  That breaks offline
installations.
> 1501846: Fix usage of incorrect Liquibase schema version

- server/src/main/java/org/candlepin/dto/api/v1/ConsumerDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/EnvironmentDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/UpstreamConsumerDTO.java
- server/src/test/java/org/candlepin/dto/AbstractDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ActivationKeyDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/BrandingDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CapabilityDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CdnDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CertificateDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/CertificateSerialDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ConsumerDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ConsumerInstalledProductDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ConsumerTypeDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ContentDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/EntitlementDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/EnvironmentDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/GuestIdDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/HypervisorIdDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/JobStatusDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/OwnerDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/PoolDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/ProductDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/UpstreamConsumerDTOTest.java
- Fixed equals/hashcode/populate methods in ConsumerDTO, EnvironmentDTO, UpstreamConsumerDTO.
- Fixed a lot of DTO unit tests that were silently ignored due to missing fields during setup. Also fixed the inheritDoc annotation.
> Various DTO fixes in equals/hashcode/populate methods and ignored tests.

- server/bin/gen_fake_report.py
- server/client/ruby/candlepin_api.rb
- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/VirtConsumerMap.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/EntitlementResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/dto/HypervisorUpdateResultUuids.java
- server/src/main/java/org/candlepin/resource/util/GuestMigration.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
This is essentially a forward port of bz 1531628.
The biggest difference here is this version of the fix reuses existing guest id entries where applicable to ensure a guest is only mapped to one host (for a given organization).
Note: I will remove the lock wait repro script and squash the commits post-review.
> 1531627: Reduce possibility of lock waits on Async Hypervisor Check in

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/controller/SuspendModeTransitioner.java
- server/src/test/java/org/candlepin/controller/SuspendModeTransitionerTest.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
Previously, the class responsible for attempting to reconnect to Qpid
would begin with a small interval between attempts and then gradually
grow that interval so that reconnect attempts would grow farther and
farther apart.
This commit removes that functionality and replaces it with a constant
interval between reconnection attempts.  The previous algorithm provided
little tangible benefit and added additional code and configuration
complexity.
> Qpid reconnect attempts now have a constant interval.

- common/po/fr.po
- common/po/ja.po
- common/po/ko.po
- common/po/zh_CN.po
We had several translations that incorrectly escaped single quotes.  I
corrected the translations, pushed them to Zanata, and then pulled them
back.  Zanata apparently performs some clean-up (deleting trailing
whitespace, etc) so I made the pull to avoid conflicts in the future.
> Pull corrected translations from Zanata.

- common/src/main/java/org/candlepin/common/resteasy/filter/PageRequestFilter.java
- common/src/main/java/org/candlepin/common/validation/CandlepinMessageInterpolator.java
- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/consumer_resource_dev_spec.rb
- server/spec/derived_product_spec.rb
- server/spec/healing_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/policy/js/activationkey/ActivationKeyRules.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/ConsumerTypeResource.java
- server/src/main/java/org/candlepin/resource/EntitlementResource.java
- server/src/main/java/org/candlepin/resource/EventResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/PoolResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/main/java/org/candlepin/util/ServiceLevelValidator.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Single quotes need to be escaped with single quotes in po files. This is
an unusual escape sequence and it is not obvious to translators that the
translated key also needs to use two single quotes.  Double quotes are
escaped with a backslash.
Besides, quoting these strings in single quotes was grammatically
incorrect in the first place.
> Correct incorrect punctuation in user messages.

- server/src/main/java/org/candlepin/guice/DefaultConfig.java
- server/src/main/java/org/candlepin/pki/PKIUtility.java
- server/src/main/java/org/candlepin/pki/SubjectKeyIdentifierWriter.java
- server/src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java
- server/src/main/java/org/candlepin/pki/impl/DefaultSubjectKeyIdentifierWriter.java
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/sync/ImporterTest.java
Hosted-mode Candlepin instances can have special requirements around the
SubjectKeyIdentifier extension written into certificates.  This
extension point was removed in the process of upgrading to a newer
release of BouncyCastle.
> Add SubjectKeyIdentifierWriter extension point back into Candlepin.

- common/src/main/java/org/candlepin/common/filter/LoggingFilter.java
- common/src/test/java/org/candlepin/common/jackson/DynamicPropertyFilterTest.java
- server/src/main/java/org/candlepin/hibernate/ResultDataUserType.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ImportRecord.java
- server/src/main/java/org/candlepin/model/dto/PoolIdAndErrors.java
- server/src/main/java/org/candlepin/model/dto/PoolIdAndQuantity.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsForProductJob.java
- server/src/main/java/org/candlepin/sync/ExportResult.java
This PR is the first half of the effort to stop storing serialized objects in cp_job's resultData column.  The idea is that once this is merged we can modify the ResultDataUserType so that it can load either serialized objects (for legacy records) **or** UTF8 JSON stored in the column as bytes.  Storing the JSON in a `bytea` column seems a little hacky but it's backwards compatible and won't require a DB migration.  The DB migration would be tricky since migrating it will require writing a custom task in Java that deserializes the data from the column, re-serializes the data as JSON, and then writes it to the column of type `text`.
I'm filing this partly to avoid bit-rot while I'm working on something else this week and also to get opinions on whether this solution is acceptable to the …
> Custom UserType for job result data

- server/src/main/java/org/candlepin/audit/QpidConnection.java
- server/src/main/java/org/candlepin/audit/QpidQmf.java
- server/src/main/java/org/candlepin/audit/QpidStatus.java
- server/src/main/java/org/candlepin/controller/QpidStatusListener.java
- server/src/main/java/org/candlepin/controller/QpidStatusMonitor.java
- server/src/main/java/org/candlepin/controller/SuspendModeTransitioner.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/test/java/org/candlepin/controller/QpidStatusMonitorTest.java
- server/src/test/java/org/candlepin/controller/SuspendModeTransitionerTest.java
- server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
https://bugzilla.redhat.com/show_bug.cgi?id=1546236
Whenever the QpidConnection needed to be rebuilt, the existing
connection was being disregarded and a new one created. The old
connections were not getting cleaned up causing candlepin to
exhaust all connections available to Qpid.
This was primarily surfacing when HornetQ would try to resend
failed messages but the Qpid queue was in FLOW_STOPPED. In
this case, QpidConnection would be marked as stale because of the
exception, and would create a new connection to Qpid, leaving
the other around. In the case of FLOW_STOPPED, a new connection
isn't required - we just need to wait for the queue to catch up.
Since the exceptions thrown by Qpid for the various failure
cases, we could never tell exactly when to recreate the connection
or when the …
> 1546236: Properly handle connections when they are recreated

- server/src/main/java/org/candlepin/dto/StandardTranslator.java
- server/src/main/java/org/candlepin/dto/api/v1/PoolQuantityTranslator.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ConsumerDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ContentDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ContentTranslator.java
- server/src/main/java/org/candlepin/dto/manifest/v1/EntitlementDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ProductDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ProductTranslator.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/dto/manifest/v1/ContentDTOTest.java
- server/src/test/java/org/candlepin/dto/manifest/v1/ContentTranslatorTest.java
- server/src/test/java/org/candlepin/dto/manifest/v1/ProductDTOTest.java
- server/src/test/java/org/candlepin/dto/manifest/v1/ProductTranslatorTest.java
- ContentDTO was also added as a dependent of ProductDTO.
- Import and export endpoints do NOT use ProductDTO yet (this will be addressed in another task).
- Added comments with lists of fields we no longer export on ProductDTO, EntitlementDTO, ConsumerDTO and their nested DTOs.
> Implemented ProductDTO for manifest import/export.

- server/src/main/resources/db/changelog/20170206133825-add-share-consumer-type.xml
- Added a pre-condition check to the Liquibase task to add a share
consumer. This will prevent a failure that could occur in the
event a consumer type named "share" already exists.
> [M] 1558060: Added precondition check to add-share-consumer task

- server/src/main/resources/db/changelog/20161109145238-add-owner-environment-content-access.xml
- server/src/main/resources/db/changelog/20170301083925-update-revoked-cert-serial-data.xml
During investigation, I discovered that between 2.1.12 and master, we renamed a primary key and a unique key, which poses risk if we later try to reference either of those objects, but I think this is somewhat unlikely.
I considered adding a changeset to drop and re-create them to ensure they have the same names regardless of whether a user is on a fresh install, or has upgraded from 2.1.12, but I feel it's better to spend effort on testing the upgrade paths, given the low risk, but I can be convinced to open up a separate PR to do so.
I left some comments in the problematic changeset, so that if we do find problems later on, it'll be easier to discover.
Hints for Testing
-----------------
Assuming you have a local postgresql DB set up per the developer instructions from …
> 1552777: Add liquibase checksums for 2.1 upgrade

- server/src/main/resources/db/changelog/20170206133825-add-share-consumer-type.xml
- Added a pre-condition check to the Liquibase task to add a share
consumer. This will prevent a failure that could occur in the
event a consumer type named "share" already exists.
> [2.1] 1558065: Added precondition check to add-share-consumer task

- common/src/main/java/org/candlepin/common/resteasy/filter/PageRequestFilter.java
- common/src/main/java/org/candlepin/common/validation/CandlepinMessageInterpolator.java
- server/spec/autobind_disabled_for_owner_spec.rb
- server/spec/consumer_resource_dev_spec.rb
- server/spec/derived_product_spec.rb
- server/spec/healing_spec.rb
- server/src/main/java/org/candlepin/controller/Entitler.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/policy/js/activationkey/ActivationKeyRules.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/ConsumerTypeResource.java
- server/src/main/java/org/candlepin/resource/EntitlementResource.java
- server/src/main/java/org/candlepin/resource/EventResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/PoolResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
- server/src/main/java/org/candlepin/util/ServiceLevelValidator.java
- server/src/test/java/org/candlepin/controller/EntitlerTest.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Single quotes need to be escaped with single quotes in po files. This is
an unusual escape sequence and it is not obvious to translators that the
translated key also needs to use two single quotes.  Double quotes are
escaped with a backslash.
Besides, quoting these strings in single quotes was grammatically
incorrect in the first place.
> [2.1] Correct incorrect punctuation in user messages.

- server/src/main/java/org/candlepin/liquibase/FixDuplicatePoolsLiquibaseWrapper.java
- server/src/main/java/org/candlepin/liquibase/FixDuplicatePoolsTask.java
We can change the FixDuplicatePools class name without an issue since
the actual changelog XML only references the
FixDuplicatePoolsLiquibaseWrapper class name.
> Unify custom tasks under the LiquibaseCustomTask interfaces.

- server/src/main/java/org/candlepin/dto/api/v1/JobStatusDTO.java
- server/src/main/java/org/candlepin/hibernate/ResultDataUserType.java
- server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java
- server/src/main/resources/META-INF/persistence.xml
- server/src/test/java/org/candlepin/hibernate/ResultDataUserTypeTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java
Testing:
* Deploy Candlepin from master
* Run `buildr rspec:import` 3 or 4 times to get some rows in `cp_job`
* Deploy this branch
* Run `buildr rspec:import` 3 or 4 times to get some more rows in `cp_job`
* Connect to the database and take a look at the `resultdata` column.  My preferred tool for doing this is JetBrain's DataGrip because it will show the data as characters if it can.  `psql` will always encode the data in hex, but if the data in the column starts with `\x7b22` that's ASCII for `{"` which means it's JSON.
* Run `client/ruby/cpc get_job JOB_ID` for a job id with JSON result data and a job with serialized object result data.
* There shouldn't be any detectable behavior differences in how the results are returned and displayed.
* Note that reading the serialized object data …
> Serialize job results as JSON

- server/src/main/java/org/candlepin/dto/api/v1/HypervisorIdTranslator.java
- server/src/main/java/org/candlepin/model/Consumer.java
- server/src/main/java/org/candlepin/resource/ActivationKeyResource.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/ContentResource.java
- server/src/main/java/org/candlepin/resource/GuestIdResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/main/java/org/candlepin/resource/util/GuestMigration.java
- server/src/main/java/org/candlepin/util/ContentOverrideValidator.java
- server/src/test/java/org/candlepin/model/ConsumerTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/ContentResourceTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
- server/src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
- The following endpoints were optimized to do data assignment from DTO to entity (as opposed to from entity to entity) where possible, and also do data validation before data assignment:
ConsumerResource.create
ConsumerResource.updateConsumer
OwnerResource.createOwner
OwnerResource.updateOwner
OwnerResource.createActivationKey
OwnerResource.createEnv
OwnerResource.createPool
OwnerResource.updatePool
- Updated a few forgotten endpoints in ProductResource & ContentResource to use OwnerDTO and ContentDTO instead of the equivalent model entities.
- Refactored a few tests in ContentResourceTest that are testing deprecated endpoints.
> Optimized DTO usage in API endpoints

- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
This enables the testing of the true hosted behavior where the entire
subscription definition comes in via the adapter. Prior to this change, product data is loaded from 
Candlepin via the resolver before being put into the HostedTestSubscriptionServiceAdapter in 
memory cache. This change enables setting things exactly as passed in the request JSON.
> Enable a bypass of resolving custom products when adding subscriptions to the test adapters

- server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
- server/src/main/java/org/candlepin/audit/EventReceiver.java
- server/src/main/java/org/candlepin/audit/EventSource.java
- server/src/main/java/org/candlepin/audit/ListenerWrapper.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/test/java/org/candlepin/audit/EventReceiverTest.java
- server/src/test/java/org/candlepin/audit/EventSourceTest.java
- server/src/test/java/org/candlepin/audit/ListenerWrapperTest.java
Before this patch, resend message on error wasn't working
all the time, which could sometimes lead to lost messages
that wouldn't make it to Qpid.
This patch moves from having one ClientSession receiving
messages for all queues, to using a ClientSession per
queue/listener.
Prior to this patch, client sessions were set to
auto-acknowledge and auto-commit messages. This is no
longer the case. Each listener's ListenerWrapper now
manages its session by committing on success and rolling
back on failure.
Another important change is that as soon as a listener
recieves a message, that message should be immediately
acknowledged so that the session can keep track of the
number of times a message was sent (despite success or
failure). This is key to allowing retry on error to
function correctly.
All …
> 1550190: Fixed Artemis resend on error to prevent lost messages

- server/src/main/java/org/candlepin/audit/Event.java
- server/src/main/java/org/candlepin/audit/EventBuilder.java
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/dto/api/v1/EventDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/EventTranslator.java
- server/src/main/java/org/candlepin/model/EventCurator.java
- server/src/main/resources/db/changelog/20180329144902-change-cp-event-dot-consumer-id-to-consumer-uuid.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/audit/EventFactoryTest.java
- server/src/test/java/org/candlepin/audit/ListenerWrapperTest.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/dto/api/v1/EventDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/EventTranslatorTest.java
- Renamed Event.consumerId to consumerUuid, as the consumer ID isn't
usable outside of Candlepin, and event consumers are expecting the UUID
- Renamed the cp_event.consumerid column to consumer_uuid in accordance
with the field name change
> [M] 1562097: Renamed Event.consumerId to consumerUuid

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Will affect libvirt scenarios
Uses the system_uuid, when available, to match an existing
consumer to a new hypervisor or an existing hypervisor to a new consumer.
Will work when the system_uuid on the hypervisor is used
as the submitted hypervisor id.
> 1365248: Reconcile registered consumers and hypevisors

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/ConsumerTypeDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/GuestIdDTO.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- server/src/test/java/org/candlepin/test/TestUtil.java
- Return the removed ConsumerTypeDTO constructor which accepts a
label to address an issue where an exception is thrown when a
consumer type is sent as a label
- Removed an additional DTO constructor that slipped through the
previous removal pass
> [M] 1563436: Restore ConsumerTypeDTO constructor for legacy consumer JSON

- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- server/src/main/java/org/candlepin/hibernate/EmptyStringInterceptor.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterJobListener.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
- The CancelJobJob no longer outputs messages regarding job cancelation
when there are no jobs to cancel
- The JobStatus object now better handles empty result messages to avoid
extra warnings in logs
- Changed the CancelJobJob's execution time logging to appear if
Candlepin's log mode is set to TRACE
> [M] 1563367: Reduced log noise associated with the CancelJobJob

- server/src/main/java/org/candlepin/resource/OwnerResource.java
- Fixed a bug that caused the errors that occurred during owner
creation to be lacking the owner key in the error message
- OwnerResource.createOwner now checks that the owner key is set
before attempting to create the owner
- OwnerResource.createOwner now checks that the default service
level is not set before attempting to create the owner
> [M] Improved error output surrounding owner creation and service levels

- server/src/main/java/org/candlepin/dto/StandardTranslator.java
- server/src/main/java/org/candlepin/dto/manifest/v1/DistributorVersionDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/DistributorVersionTranslator.java
- server/src/main/java/org/candlepin/sync/DistributorVersionExporter.java
- server/src/main/java/org/candlepin/sync/DistributorVersionImporter.java
- server/src/main/java/org/candlepin/sync/Importer.java
- server/src/test/java/org/candlepin/dto/manifest/v1/DistributorVersionDTOTest.java
- server/src/test/java/org/candlepin/dto/manifest/v1/DistributorVersionTranslatorTest.java
- server/src/test/java/org/candlepin/sync/ExporterTest.java
- DistributorVersionDTO is used instead of DistributorVersion when importing/exporting a manifest.
> [M] Implemented DistributorVersionDTO for manifest import/export.

- server/spec/cert_revocation_spec.rb
- server/src/main/java/org/candlepin/model/CertificateSerial.java
- server/src/main/java/org/candlepin/model/CertificateSerialCurator.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/util/CrlFileUtil.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/test/java/org/candlepin/model/CertificateSerialCuratorTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/util/UtilTest.java
- Heavily optimized the CrlFileUtil.syncCRLWithDB method, reducing
overall memory load and substantially reducing method runtime
- Rewrote several methods in CertificateSerialCurator to return
certificate serials (the actual serials as long integers) rather
than full CertificateSerial instances
- Rewrote several tests in CertificateSerialCuratorTest in
accordance with the changes to the curator
- Corrected a handful of utility methods and tests
> [M] 1566244: Speculative Fix For Failing CertificateRevocationListTask

- server/spec/cert_revocation_spec.rb
- server/src/main/java/org/candlepin/model/CertificateSerial.java
- server/src/main/java/org/candlepin/model/CertificateSerialCurator.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/util/CrlFileUtil.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/test/java/org/candlepin/model/CertificateSerialCuratorTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/util/UtilTest.java
(cherry-pick from master)
- Heavily optimized the CrlFileUtil.syncCRLWithDB method, reducing
overall memory load and substantially reducing method runtime
- CrlFileUtil.syncCRLWithDB now cleans up serials after successful
synchronization
- Rewrote several methods in CertificateSerialCurator to return
certificate serials (the actual serials as long integers) rather
than full CertificateSerial instances
- Rewrote several tests in CertificateSerialCuratorTest in
accordance with the changes to the curator
- Corrected a handful of utility methods and tests
> 1566244: Speculative Fix For Failing CertificateRevocationListTask

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
The beauty of SLF4J style interpolation is that if the log level is
higher that the method requires, it will not call toString on the object
and therefore saves some time.  By calling toString on the object before
it is passed in as a parameter, we lose those gains.
---
Also drop a call to a very simple utility method that is getting hit a lot and demote the log level of the pool messages anyway.
> Remove toString call where it is not necessary.

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/Branding.java
- server/src/main/java/org/candlepin/model/SourceSubscription.java
* When a product changes in a manifest resulting in entitlement revocation and subsequent deletion of entitlement derived pools,
some pools that are deleted subsequently were attempted to being updated. This branch skips those deleted pools
* Some product changes resulted in creating brandings on a product, and when that pool was being locked, created an error since
Hibernate had not flushed the brandings yet
*  sudo systemctl stop tomcat
* dropdb -U candlepin  candlepin
* createdb -U candlepin  candlepin
* import db
* psql -U candlepin -d candlepin -f candlepin_dump.sql 
* git checkout candlepin-2.1-HOTFIX
* ./server/bin/deploy 
*  fetch list of candlepin owners, so we can verify candlepin is working and we can use the owner key for later.
* import manifest from bug
* curl -X POST …
> [2.1] 1571354: Manifest import no longer fails when product changes

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/Branding.java
- server/src/main/java/org/candlepin/model/SourceSubscription.java
* When a product changes in a manifest resulting in entitlement revocation and subsequent deletion of entitlement derived pools,
some pools that are deleted subsequently were attempted to being updated. This branch skips those deleted pools
* Some product changes resulted in creating brandings on a product, and when that pool was being locked, created an error since
Hibernate had not flushed the brandings yet
*  sudo systemctl stop tomcat
* dropdb -U candlepin  candlepin
* createdb -U candlepin  candlepin
* import db
* psql -U candlepin -d candlepin -f candlepin_dump.sql 
* git checkout master
* ./server/bin/deploy 
*  fetch list of candlepin owners, so we can verify candlepin is working and we can use the owner key for later.
* import manifest from bug
* curl -X POST --header …
> [M] 1569611: Manifest import no longer fails when product changes

- server/spec/consumer_resource_host_guest_spec.rb
- server/spec/consumer_resource_spec.rb
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
Pool filtering behaviour based on SLAs has changed and currently:
- A pool is not filtered if any of these is true:
* The pool's SLA is null or empty, or in the exempt list.
* The consumer does not have any existing entitlements.
* The consumer has existing entitlements and one of them has a product that matches the pool SLA.
- A pool is filtered if the pool SLA is non-null, non-exempt,
and the consumer has one or more existing entitlements, but none of their SLAs matches the pool's SLA.
- Pools that are not filtered, will get prioritized (+700) if all of the following are true:
* the pool's SLA is non-null, non-empty and not in the exempt list.
* at least one of the following is non-null and non-empty: SLA override, consumer's SLA, owner's default SLA.
* the pool's SLA matches either the …
> [Intent] Dont filter pools based on SLA on auto-attach, but prioritize

- server/src/main/java/org/candlepin/bind/BindChain.java
- server/src/main/java/org/candlepin/bind/CheckBonusPoolQuantitiesOp.java
- server/src/main/java/org/candlepin/bind/PoolOperationCallback.java
- server/src/main/java/org/candlepin/bind/PostBindBonusPoolsOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/model/Pool.java
- server/src/main/java/org/candlepin/policy/js/entitlement/Enforcer.java
- server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/main/java/org/candlepin/policy/js/pool/StackedSubPoolValueAccumulator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/PoolTest.java
- server/src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/HostedVirtLimitEntitlementRulesTest.java
- server/src/test/java/org/candlepin/policy/js/entitlement/PostEntitlementRulesTest.java
- server/src/test/java/org/candlepin/policy/js/pool/PoolHelperTest.java
- server/src/test/java/org/candlepin/test/EnforcerForTesting.java
Today, all bind time pool operations are performed via a bind chain that passes around a shared bind context. The preProcess method performs most of the heavy weight operations, but does not perform any database operations untill the execute method is executed after the locks are placed.
In this PR, I have:
* created a DelayedPoolOp to capture the operations to perform once the locks are placed.
* split PostBindBonusPoolsOp into PostBindBonusPoolsOp and CheckBonusPoolsQuantitiesOp.
* Currently only PostBindBonusPoolsOp is lock-less in it's preProcessing. A following PR would tackle CheckBonusPoolsQuantitiesOp.
* PostBindBonusPoolsOp temporarily assigns the pools and entitlements in its preProcess step so pools and entitlements can be associated to create stack derived pools and keep the …
> [m] Lock less binds phase 2

- server/src/main/java/org/candlepin/audit/QpidConnection.java
- server/src/test/java/org/candlepin/audit/QpidConnectionTest.java
When QpidQMF reports that qpid is in FLOW_STOPPED, the connection should
remain open. When the state is reported as CONNECTED, there is no need to
open a connection since it is already open.
Also added some tests around QpidConnection since none existed prior to
to this PR.
**To Test**
Follow the steps outlined in the BZ: 
https://bugzilla.redhat.com/show_bug.cgi?id=1578967
> 1578967: Fixed edge case that was causing Qpid connections to remain open

- server/spec/filter_response_spec.rb
- server/src/main/java/org/candlepin/dto/CandlepinDTO.java
- Added the missing @JsonFilter annotation to the CandlepinDTO
class. This will re-enable the include/exclude filtering on DTOs
> [2.4] 1582204: Added missing JsonFilter annotation to the DTOs

- server/spec/filter_response_spec.rb
- server/src/main/java/org/candlepin/dto/CandlepinDTO.java
- Added the missing @JsonFilter annotation to the CandlepinDTO
class. This will re-enable the include/exclude filtering on DTOs
> [2.3] 1582607: Added missing JsonFilter annotation to the DTOs

- server/src/main/java/org/candlepin/model/Owner.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/util/ResolverUtil.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/auth/permissions/OwnerCuratorPermissionsTest.java
- OwnerCurator.getByKey now uses session.bySimpleNaturalId to fetch an owner, and the old version of that method is renamed to getByKeySecure.
- Added explicit access check in ConsumerResource.create API due to it being marked as @SecurityHole.
- Deleted two @SecurityHole annotations that were in conflict with @Verify annotations (these are mutually exclusive).
- Deleted a couple of unused methods from ResolverUtil.
> ENT-432 Converted Owner.key to a hibernate @NaturalId

- server/src/main/resources/db/changelog/20130425102131-distributor-capabilities.xml
- server/src/main/resources/db/changelog/20130501152202-add-content-arch.xml
- server/src/main/resources/db/changelog/20130722140547-add-cdn-table.xml
- server/src/main/resources/db/changelog/20130912153356-create-import-upstream-consumer.xml
- server/src/main/resources/db/changelog/20131002150608-consumer-content-override.xml
- server/src/main/resources/db/changelog/20140210083318-add-hypervisorid.xml
- server/src/main/resources/db/changelog/20140306150357-constrain-one-subpool-per-stack.xml
- server/src/main/resources/db/changelog/20140313155734-create-branding.xml
- server/src/main/resources/db/changelog/20140317115036-index-facts-consumerid.xml
- server/src/main/resources/db/changelog/20140408160212-add-pool-source-sub-table.xml
- server/src/main/resources/db/changelog/20150123105016-add-consumer-checkin-table.xml
- server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml
- server/src/main/resources/db/changelog/20150211111319-add-last-guest-update-table.xml
- server/src/main/resources/db/changelog/20150316122833-add-entitlement-end-date-override.xml
- server/src/main/resources/db/changelog/20150820140403-revert-to-lastcheckin-column.xml
- server/src/main/resources/db/changelog/20160419092221-add-db-file-storage.xml
- server/src/main/resources/db/changelog/20161013145834-add-content-access-cert-column-to-consumer.xml
- server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml
- server/src/main/resources/db/changelog/20161109145238-add-owner-environment-content-access.xml
- server/src/main/resources/db/changelog/20170125112728-cleanup-uebercerts-round3-2-0.xml
- server/src/main/resources/db/changelog/20170202093945-add-ueber-cert-to-owner.xml
- server/src/main/resources/db/changelog/20170206114359-convert-quanity-consumed-exported-to-columns.xml
- server/src/main/resources/db/changelog/20170220102027-add-id-column-for-productcontent.xml
- server/src/main/resources/db/changelog/20170224113816-add-productshare-table.xml
- server/src/main/resources/db/changelog/20170227140343-convert-consumer-entitlement-count-to-column.xml
- server/src/main/resources/db/changelog/20170301083925-update-revoked-cert-serial-data.xml
- server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml
- server/src/main/resources/db/changelog/20171020150559-add-index-to-cp-consumer-content-tags.xml
See #2008. I ran those scripts against candlepin-2.2.3-1:
server/bin/check_liquibase_checksums --base candlepin-2.2.3-1 --fix
Use of the script catches and fixes any `validCheckSum` which does not
match the current checksum, and also catches and fixes any changeset
which has a different checksum between HEAD and candlepin-2.2.3-1 but
does not have `validCheckSum` specified (it should).
Some of those caught are for deployment against Oracle databases,
which we test far less often.
Then I ran similarly against candlepin-0.9.54-HOTFIX, but no changes
resulted.
I did a little bit of cleanup afterwards (mainly removing stale
comments).
Obsoletes #1986.
> [M] 1572669: Update liquibase checksums

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
Updating the status of a large number of consumers (roughly 10000) could
run the JVM out of memory due to all the consumers referenced in the
consumerStackedEnts map.  During status calculation, the consumer
facts are accessed and during those accesses, the Hibernate proxy object
is replaced by the actual map of facts.  The consumerStackedEnts map
would accordingly grow as each status was calculated.
This patch detaches several model objects as soon as we stop needing
them and most importantly, it detaches all the consumers in the
consumerStackedEnts map.  The consumers are then fetched again, the
status is updated, and then immediately detached to keep the persistence
context at roughly a constant size.
> [M] 1584259: Detach consumers from persistence context to avoid OOM - ENT-583

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
Updating the status of a large number of consumers (roughly 10000) could
run the JVM out of memory due to all the consumers referenced in the
consumerStackedEnts map.  During status calculation, the consumer
facts are accessed and during those accesses, the Hibernate proxy object
is replaced by the actual map of facts.  The consumerStackedEnts map
would accordingly grow as each status was calculated.
This patch detaches several model objects as soon as we stop needing
them and most importantly, it detaches all the consumers in the
consumerStackedEnts map.  The consumers are then fetched again, the
status is updated, and then immediately detached to keep the persistence
context at roughly a constant size.
> [2.1] 1584256: Detach consumers from persistence context to avoid OOM - ENT-583

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
Updating the status of a large number of consumers (roughly 10000) could
run the JVM out of memory due to all the consumers referenced in the
consumerStackedEnts map.  During status calculation, the consumer facts
are accessed and during those accesses, the Hibernate proxy object is
replaced by the actual map of facts.  The consumerStackedEnts map would
accordingly grow as each status was calculated.
This patch detaches several model objects as soon as we stop needing
them and most importantly, it detaches all the consumers in the
consumerStackedEnts map.  The consumers are then fetched again, receive
an updated status, and are then immediately detached to keep the
persistence context at roughly a constant size.
> [2.4] 1584258: Detach consumers from persistence context to avoid OOM - ENT-583

- server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
* globally, connection TTL set to 24 hours
* infinite number of reconnect attempts
> [M] 1570064: Two changes to make ActiveMQ clients more resilient (ENT-469):

- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- server/src/main/java/org/candlepin/audit/HornetqContextListener.java
* globally, connection TTL set to 24 hours
* infinite number of reconnect attempts
> [2.1] 1571425: Two changes to make HornetQ clients more resilient (ENT-469):

- server/src/main/java/org/candlepin/audit/HornetqContextListener.java
- server/src/main/java/org/candlepin/audit/HornetqEventDispatcher.java
* globally, connection TTL set to 24 hours
* infinite number of reconnect attempts
> [0.9.54]1571423: Two changes to make HornetQ clients more resilient (ENT-469):

- server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
- server/src/main/java/org/candlepin/audit/EventSinkImpl.java
* globally, connection TTL set to 24 hours
* infinite number of reconnect attempts
> [2.4] 1571426: Two changes to make ActiveMQ clients more resilient (ENT-469):

- server/src/main/java/org/candlepin/resource/StatusResource.java
- StatusResource now sets the timeUTC field of the StatusDTO object
before returning it.
> [M] 1588202: Fixed status endpoint not setting the timeUTC field

- buildfile
- server/pom.xml
BZ 1566200 occurs because of an issue with the postgres JDBC driver which causes some of the operations that liquibase executes against Postgres 9.6 to fail.
cpdb sets the classpath when running liquibase to the RPM installed version of the driver which causes the breakage.
The postgres driver will be updated for RHEL 7.5.z and 7.6 ( https://bugzilla.redhat.com/show_bug.cgi?id=1566200#c2 ) which will address the installer issue.
Candlepin runs on its own version of the driver which is included in the WAR. Although it is very old, it does not cause any issues during normal operation against postgres 9.6.
This PR updates the version of the driver to the latest ONLY in the master branch since it is really outdated, however, this in no way addresses the BZ. We will have to wait for the driver …
> [M] Upgraded postgresql-jdbc driver to the latest ENT-521

- server/spec/import_excess_spec.rb
Because of the lack of DATETIME precision in MySQL, it appears
this this test will fail randomly when an export and re-import
occur at just the right moment causing a 409 MANIFEST_SAME conflict
due to matching time.
**NOTE**
Once this PR runs through the tests and we don't see the failure in other PRs against master, I'll create the PRs for 2.4 and 2.5
> [M] ENT-600 Add a sleep to fix failing spec test against mysql

- server/spec/job_status_spec.rb
- server/src/main/java/org/candlepin/auth/ConsumerPrincipal.java
- server/src/main/java/org/candlepin/auth/UserPrincipal.java
- server/src/main/java/org/candlepin/auth/permissions/JobStatusPermission.java
The permissions for JobResource were previously modified to allow a consumer to check
the status of a job it started.  This scenario was introduced so that the virt-who
process on a registered system could query for the job status. To assist the virt-who
choreography, the consumer will be allowed to cancel its own jobs.
> 1510920: Allow consumer to cancel jobs started by consumer

- server/spec/import_excess_spec.rb
Because of the lack of DATETIME precision in MySQL, it appears
this this test will fail randomly when an export and re-import
occur at just the right moment causing a 409 MANIFEST_SAME conflict
due to matching time.
> [2.4] Add a sleep to fix failing spec test against mysql

- server/spec/import_excess_spec.rb
Because of the lack of DATETIME precision in MySQL, it appears
this this test will fail randomly when an export and re-import
occur at just the right moment causing a 409 MANIFEST_SAME conflict
due to matching time.
> [2.1] Add a sleep to fix failing spec test against mysql

- server/spec/import_excess_spec.rb
Because of the lack of DATETIME precision in MySQL, it appears
this this test will fail randomly when an export and re-import
occur at just the right moment causing a 409 MANIFEST_SAME conflict
due to matching time.
> [2.3] Add a sleep to fix failing spec test against mysql

- server/src/main/resources/logback.xml
- server/src/test/resources/logback-test.xml
After a hibernate upgrade, the log file is not getting
polluted with deprecation warnings due to our use of
the old Criteria API. This patch disables those warnings
so that the log file doesn't grow when deployed in production.
The warnings have also been silenced when running unit tests
as well so that the log file isn't polluted.
> [M] ENT-617 Silence all hibernate deprecation warnings

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Concurrent attempts to unregister a system will no longer
fail hard when concurrent registrations occur. If a Consumer
record is deleted before a lock is aquired, a GoneException
is thrown resulting in a 410 response.
**Testing**
This can be tested if you run the new spec test against the base branch and watch it fail.
> [M] ENT-595 1582510: Properly handle concurrent unregister requests

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Concurrent attempts to unregister a system will no longer
fail hard when concurrent registrations occur. If a Consumer
record is deleted before a lock is aquired, a GoneException
is thrown resulting in a 410 response.
**Testing**
This can be tested if you run the new spec test against the base branch and watch it fail.
> [2.1 ENT-595] 1584716: Properly handle concurrent unregister requests

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Concurrent attempts to unregister a system will no longer
fail hard when concurrent registrations occur. If a Consumer
record is deleted before a lock is aquired, a GoneException
is thrown resulting in a 410 response.
**Testing**
This can be tested if you run the new spec test against the base branch and watch it fail.
> [2.4] ENT-595 1584715: Properly handle concurrent unregister requests

- server/src/main/java/org/candlepin/pki/SubjectKeyIdentifierWriter.java
- server/src/main/java/org/candlepin/pki/impl/DefaultSubjectKeyIdentifierWriter.java
- server/src/test/java/org/candlepin/pki/SubjectKeyIdentifierWriterTest.java
- add toOctetString default method
- keeps IT from having to use BouncyCastle directly
- moved getSubjectKeyidentifier to the interface
> ENT-616: Update SubjectKeyIdentifierWriter for isolation [m]

- server/src/main/java/org/candlepin/pki/SubjectKeyIdentifierWriter.java
- server/src/main/java/org/candlepin/policy/js/compliance/hash/Hasher.java
Compliance hashes do not need to be cryptographically secure, so using
SHA-256 is overkill.  Murmur3 is slightly faster and results in modest
performance improvement (roughly 10%).
---
Running ExpiredPoolsJob on a DB with about 10,500 consumers that need status recalculations goes from 195s to 181s on my machine (give or take).
> Switch hashing algorithms from SHA-256 to Murmur3 for compliance hash

- server/spec/job_status_spec.rb
This test was originally just scheduling a job and then attempting to
cancel it.  Unfortunately, if the job ran fast enough, it would be
complete before the cancellation attempt landed and Candlepin would
return a 400 error.  This patch fixes the issue by pausing the
scheduler, scheduling a job, and then attempts to cancel it.  The patch
is based on a similar test elsewhere in the spec file.
> Fix issue with intermittent rspec test failure.

- server/src/main/java/org/candlepin/dto/api/v1/ComplianceStatusTranslator.java
Using parallelStream incurs a lot of overhead around thread
synchronization.  In this case, these collections are likely to be on
the order of a hundred or so elements and the actual operation itself is
going to be very fast.  The additional overhead of parallelStream will
end up degrading performance.  If we expect these lists of compliant
products, partially compliant products, and partial stacks to get very
large, parallelizing this would be worth reconsidering.
See https://stackoverflow.com/a/20375622/6124862 and
https://www.ibm.com/developerworks/library/j-java-streams-5-brian-goetz/index.html
(specifically the "NQ model" section)
> Remove use of parallelStream when not necessary.

- server/src/main/java/org/candlepin/model/Product.java
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Added the new product attribute constants in the Product class.
- Ported the algorithm to javascript ES5 in the rules' get_pool_priority method.
- Added a new namespace in rules.js for purely testing purposes.
- Used the new namespace to write unit tests ported from gitlab's test-data.json scenarios that exercise the method get_pool_priority directly.
- Bumped the minor version of rules.js.
> ENT-716 Implemented syspurpose prioritization:

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/PoolManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/Branding.java
- server/src/main/java/org/candlepin/model/SourceSubscription.java
Cherry-picked and then resolved conflicts.
* When a product changes in a manfiest resulting in entitlement revocation and subsequent deletion of entitlement derived pools,
some pools that are deleted subsequently were attempted to being updated. This branch skips those deleted pools
* Some product changes resulted in creating brandings on a product, and when that pool was being locked, created an error since
Hibernate had not flushed the brandings yet
> [2.4] 1618391: Manifest import no longer fails when product changes ENT-787

- server/selinux/candlepin.te
Recent/upcoming selinux-policy disallows this by default.
> [0.9.54] 1616420: selinux - allow tomcat to connect to postgres ENT-791

- server/bin/deploy
- server/bin/gen-certs
> [M] Updated gen-certs for compatibility with Tomcat 8.5+

- server/bin/deploy
- server/bin/gen-certs
> [0.9.54] Updated gen-certs for compatibility with Tomcat 8.5+

- server/bin/deploy
- server/bin/gen-certs
> [2.1] Updated gen-certs for compatibility with Tomcat 8.5+

- server/bin/deploy
- server/bin/gen-certs
> [2.2] Updated gen-certs for compatibility with Tomcat 8.5+

- server/bin/deploy
- server/bin/gen-certs
> [2.3] Updated gen-certs for compatibility with Tomcat 8.5+

- server/src/main/java/org/candlepin/dto/CandlepinDTO.java
- server/src/main/java/org/candlepin/dto/manifest/v1/ConsumerDTO.java
- server/src/main/java/org/candlepin/model/AbstractHibernateObject.java
- server/src/main/java/org/candlepin/model/ImportUpstreamConsumer.java
- server/src/main/java/org/candlepin/model/dto/CandlepinDTO.java
- server/src/main/java/org/candlepin/model/dto/Subscription.java
- server/src/main/java/org/candlepin/resteasy/JsonProvider.java
- server/src/test/java/org/candlepin/model/PoolTest.java
- Removed all @JsonIgnoreProperties(ignoreUnknown) annotations from DTOs/models.
- Configured the API json provider's ObjectMapper to not fail during deserialization when unknown properties are encountered.
> ENT-113 Replace @JsonIgnoreProperties with ObjectMapper config:

- server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
Unnecessary since this version of Artemis does not timeout invm
connections.
Note that to test this, it's best to deploy a version with the value of
the connection-ttl-override set lower in order to speed up reproduction
of the original issue. For example, `60000L` will show an issue in a
minute. `60000L` was the default value for non-invm connections anyway.
(See https://github.com/candlepin/candlepin/blob/40ad86a3b7de87de2cd9b9dc38f9d5b4439b8616/server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java#L141)
Before: "AMQ119014" appears in logs; after: no such error in logs.
> [M] 1624446: Do not set connection-ttl-override ENT-823

- server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java
Unnecessary since this version of Artemis does not timeout invm
connections.
Note that to test this, it's best to deploy a version with the value of
the connection-ttl-override set lower in order to speed up reproduction
of the original issue. For example, `60000L` will show an issue in a
minute. `60000L` was the default value for non-invm connections anyway.
(See https://github.com/candlepin/candlepin/blob/40ad86a3b7de87de2cd9b9dc38f9d5b4439b8616/server/src/main/java/org/candlepin/audit/ActiveMQContextListener.java#L141)
Before: "AMQ119014" appears in logs; after: no such error in logs.
> [2.4] 1624447: Do not set connection-ttl-override ENT-823

- server/candlepin.spec.tmpl
See note about epoch at https://fedora-java.github.io/howto/latest/#_jvm
> [2.4] 1628595: Update epoch on Java requirement [ ENT-881 ]

- server/candlepin.spec.tmpl
See note about epoch at https://fedora-java.github.io/howto/latest/#_jvm
> [M] 1628594: Update epoch on Java requirement [ ENT-881 ]

- common/src/main/java/org/candlepin/common/resteasy/filter/LinkHeaderResponseFilter.java
- common/src/main/java/org/candlepin/common/resteasy/filter/LinkTooLongException.java
- LinkHeaderResponseFilter no longer adds link headers if any link
would be larger than 1024 characters; but instead issues a
warning with the offending link
> [2.4] 1632764: Added limits to the size of link headers (ENT-893)

- common/src/main/java/org/candlepin/common/resteasy/filter/LinkHeaderResponseFilter.java
- common/src/main/java/org/candlepin/common/resteasy/filter/LinkTooLongException.java
- LinkHeaderResponseFilter no longer adds link headers if any link
would be larger than 1024 characters; but instead issues a
warning with the offending link
> [M] 1632761: Added limits to the size of link headers (ENT-893)

- server/bin/deploy
- server/bin/update-server-xml.py
- Updated the update-server-xml.py script such that it generates
non-deprecated server configuration which does not function
when running Tomcat on Fedora 28
- update-server.xml.py now accepts a "--tomcat-version" option, to
specify the version of Tomcat to target, changing the generated
configuration accordingly
- Updated the is_different method to check attributes and children
- Attributes are now added to the node by the node editors themselves
rather than the methods provided by the AbstractBaseEditor
- Deploy script updated in accordance with the above changes
- JBoss setup and configuration removed from the deploy script
> [M] Updated the update-server-xml script for changes required in F28

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Fixed an issue where consumer instances could become desync'd
during CPM.deletePools while recalculating compliance status
for consumers in some cases, leading to an EntityExistsException
> [2.1] 1634040: Fixed an issue with object desync during pool cleanup

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Fixed an issue where consumer instances could become desync'd
during CPM.deletePools while recalculating compliance status
for consumers in some cases, leading to an EntityExistsException
> [M] Fixed an issue with object desync during pool cleanup

- server/spec/system_purpose_compliance_spec.rb
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/resources/rules/rules.js
If a consumer does not specify a syspurpose attribute (role, usage,
etc.), do not mark them partially compliant if they attach to a pool
that provides that attribute.
This commit also fixes a Jackson error that I discovered while writing
the test cases.  Jackson was attempting to deserialize compliance reason
JSON to a Map<String, String> when the JSON had arrays as the values
instead.
> 1640215: Fix incorrect partial compliance status on consumers

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Fixed an issue with changes to system purpose not causing the
syspurpose compliance status hash to be updated, events
generated, nor system purpose status to be retained.
> [M] 1634451: Fixed an issue with syspurpose changes not updating status (ENT-908)

- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Fixed an issue with changes to system purpose not causing the
syspurpose compliance status hash to be updated, events
generated, nor system purpose status to be retained.
> [2.5] 1645673: Fixed an issue with syspurpose changes not updating status

- README.md
- server/build.gradle
Enable running the rspec tests.
This assumes that the ruby environment is set up separately and 'rspec' can be run from the command line. 
Supports specifying the spec file name using the -- spec option. 
Supports specifying the test name using the --test option.
> Add support for running rspec tests via Gradle

- server/src/main/java/org/candlepin/audit/ActivationListener.java
- server/src/main/java/org/candlepin/audit/Event.java
- server/src/main/java/org/candlepin/audit/EventBuilder.java
- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/main/java/org/candlepin/auth/Principal.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/hibernate/ResultDataUserType.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/sync/SyncUtils.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/audit/AMQPBusPublisherTest.java
- server/src/test/java/org/candlepin/audit/ActivationListenerTest.java
- server/src/test/java/org/candlepin/audit/EventBuilderTest.java
- server/src/test/java/org/candlepin/audit/EventFactoryTest.java
- server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/util/UtilTest.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
* Changed all ObjectMapper instance references to static ones
* Changed SyncUtils to a singleton to make sure the ObjectMapper its
wrapping is reused instead of recreated
> ENT-884 Reuse Objectmappers when possible:

- server/spec/entitlement_certificate_spec.rb
- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/model/EntitlementCertificate.java
- server/src/main/java/org/candlepin/model/EntitlementCertificateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/service/EntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/model/EntitlementCertificateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed an issue that could cause StaleStateExceptions to occur when
regenerating certificates for the same consumer multiple times in
parallel
> [2.3] 1633829: Fixed StaleStateException during dirty entitlement regeneration (ENT-913)

- server/spec/entitlement_certificate_spec.rb
- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/model/EntitlementCertificate.java
- server/src/main/java/org/candlepin/model/EntitlementCertificateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/service/EntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/model/EntitlementCertificateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed an issue that could cause StaleStateExceptions to occur when
regenerating certificates for the same consumer multiple times in
parallel
> [M] 1633829: Fixed StaleStateException during dirty entitlement regeneration

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
This is a patch of #2131 for the 2.5-HOTFIX branch.
> [2.5] 1642621: Remove service level checking for consumers [ENT-929]

- server/spec/consumer_resource_spec.rb
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
This is a patch of https://github.com/candlepin/candlepin/pull/2131 for the 2.3-HOTFIX branch.
> [2.3] 1642624: Remove service level checking for consumers [ENT-929]

- server/src/main/java/org/candlepin/dto/api/v1/ActivationKeyDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/EventDTO.java
- Now using ?includes=pools.poolId or ?includes=pools.quantity on the
GET /owners/{owner_key}/activation_keys API will only show the requested subfield,
instead of the whole pools field.
- Also similarly fixed: using ?include=principal.name or
?include=principal.type on the GET /owners/{owner_key}/events API.
- By extending `CandlepinDTO`, which has a `@JsonFilter("DTOFilter")` on it, like all other
DTO classes, forces jackson to serialize properties of these classes using filters (even though
the `DTOFilter` does not exist, the default filter (`DynamicPropertyFilter`) will be used).
> 1588101: dynamicly filter activation key's pools subfields [ENT-972]

- server/selinux/candlepin.te
In our Katello deployment we have recently moved the candlepin CA cert and key to live under /etc/candlepin/certs and I noticed that when using selinux the app just doesn't work - /candlepin/status gives a 404
I found some denials in audit.log:
```
[root@nightly-test certs]# audit2allow -a
#============= tomcat_t ==============
allow tomcat_t candlepin_etc_certs_ca_cert_r_t:file { getattr open read };
allow tomcat_t cgroup_t:dir search;
allow tomcat_t cgroup_t:file { getattr open read };
```
I applied these and everything seems to work fine, and I think I've translated these in the proper way to the policy in this repo.
> Allow tomcat to read the candlepin CA cert

- server/spec/entitlement_certificate_spec.rb
- server/src/main/java/org/candlepin/bind/HandleCertificatesOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/Entitlement.java
- server/src/main/java/org/candlepin/model/EntitlementCertificate.java
- server/src/main/java/org/candlepin/model/EntitlementCertificateCurator.java
- server/src/main/java/org/candlepin/model/EntitlementCurator.java
- server/src/main/java/org/candlepin/service/EntitlementCertServiceAdapter.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/model/EntitlementCertificateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
**NOTE:** This PR re-applies a patch that was reverted in order to release some system purpose fixes. The code was already reviewed and this PR was created just to ensure that the tests all pass before merging.
**Description**
- Fixed an issue that could cause StaleStateExceptions to occur when
regenerating certificates for the same consumer multiple times in
parallel
> [2.3] RE-APPLY 1633829: Fixed StaleStateException during dirty entitlement regeneration

- server/src/main/java/org/candlepin/audit/EventSource.java
- server/src/main/java/org/candlepin/audit/QpidConnection.java
- server/src/main/java/org/candlepin/audit/QpidQmf.java
- server/src/main/java/org/candlepin/audit/QpidStatus.java
- server/src/main/java/org/candlepin/controller/SuspendModeTransitioner.java
- server/src/main/java/org/candlepin/model/CandlepinModeChange.java
- server/src/test/java/org/candlepin/audit/EventSourceTest.java
- server/src/test/java/org/candlepin/audit/QpidConnectionTest.java
- server/src/test/java/org/candlepin/controller/SuspendModeTransitionerTest.java
When Qpid's 'event' exchange does not exist, or the exchange does not
have at least 1 binding, candlepin will enter suspend mode until these
issues have been addressed.
**NOTE:** All commands should be run from the _server_ directory under your candlepin checkout.
1. Deploy candlepin with AMQP (Qpid)  support and test data
```bash
$ bin/deploy -gtaq
```
2. Make note of the current message count after deployment.
```bash
$ sudo qpid-stat --ssl-certificate=bin/qpid/keys/candlepin.crt --ssl-key bin/qpid/keys/candlepin.key -b amqps://localhost:5671 -q allmsg
```
3. Delete the  event exchange and immediately attempt to register your system.
**Note:** The system registration command should execute successfully. If you get a suspend mode error then you'll need to re-add the exchange and binding …
> [2.5] ( ENT-894 ) 1658289: Enter suspend mode when Qpid queue loses exchange and/or binding

- server/src/main/resources/rules/rules.js
Set the system purpose defaults in the rules file in order
to be backwards compatible with older candlepins when the
updated rules is brought in via a manifest import/refresh.
> [2.3] 1660532: Maintain backwards compatibility in rules for system purpose ( ENT-1023 )

- server/src/main/resources/rules/rules.js
Set the system purpose defaults in the rules file in order
to be backwards compatible with older candlepins when the
updated rules is brought in via a manifest import/refresh.
> [M] 1660533: Maintain backwards compatibility in rules for system purpose ( ENT-1023 )

- server/src/main/java/org/candlepin/audit/EventSource.java
- server/src/main/java/org/candlepin/audit/QpidConnection.java
- server/src/main/java/org/candlepin/audit/QpidQmf.java
- server/src/main/java/org/candlepin/audit/QpidStatus.java
- server/src/main/java/org/candlepin/controller/SuspendModeTransitioner.java
- server/src/main/java/org/candlepin/model/CandlepinModeChange.java
- server/src/test/java/org/candlepin/audit/EventSourceTest.java
- server/src/test/java/org/candlepin/audit/QpidConnectionTest.java
- server/src/test/java/org/candlepin/controller/SuspendModeTransitionerTest.java
When Qpid's 'event' exchange does not exist, or the exchange does not
have at least 1 binding, candlepin will enter suspend mode until these
issues have been addressed.
**NOTE:** All commands should be run from the _server_ directory under your candlepin checkout.
1. Deploy candlepin with AMQP (Qpid)  support and test data
```bash
$ bin/deploy -gtaq
```
2. Make note of the current message count after deployment.
```bash
$ sudo qpid-stat --ssl-certificate=bin/qpid/keys/candlepin.crt --ssl-key bin/qpid/keys/candlepin.key -b amqps://localhost:5671 -q allmsg
```
3. Delete the  event exchange and immediately attempt to register your system.
**Note:** The system registration command should execute successfully. If you get a suspend mode error then you'll need to re-add the exchange and binding …
> [M] ( ENT-894 ) 1658291: Enter suspend mode when Qpid queue loses exchange and/or binding

- docker/candlepin-base/setup-devel-env.sh
The images did not build with Ruby 2.0.0 and the older version of gem.
> Update Ruby version in Docker images.

- server/spec/autobind_spec.rb
- server/spec/system_purpose_compliance_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusTranslator.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
- server/src/main/java/org/candlepin/policy/js/compliance/hash/ComplianceStatusHasher.java
- server/src/test/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusTranslatorTest.java
- Now the syspurpose status states will be 'matched', 'mismatched' and
'not specified', instead of 'valid', 'invalid' and 'partial'
- Scenarios of mixed SLAs/Usages that would previously fall under the
'partial' category, will now be 'matched'. Scenarios of multiple
addons that are not all satisfied, that would previously fall under
the 'partial' category, will now be 'mismatched'
- Also, an additional reason will not be added for each pool that has a
mismatched sla or usage. Only one general mismatch reason is sent now
> 1660878: changed the possible syspurpose status states [ENT-1026]

- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/model/CertificateSerialCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTask.java
- server/src/main/java/org/candlepin/util/CrlFileUtil.java
- server/src/test/java/org/candlepin/model/CertificateSerialCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTaskTest.java
- server/src/test/java/org/candlepin/util/CrlFileUtilTest.java
Using a HashSet instead of an ArrayList to store the serials improves
the performance of .contains when checking if an entry in the CRL file
should be removed due to expiry.
Batch lookup/process fetched serials to keep the memory footprint down
and to allow garbage collection of the serials earlier. The number of
records per batch can be configured via the candlepin config file.
NOTE: Due to the way the CRL generation framework works, when batching
the serial processing, we end up re-scanning the crl num_serials/batch_size times.
This isn't ideal, but we will make due until we make the move to generating
a plain text serial file.
1. Deploy candlepin from the master branch.
2. Stop tomcat, drop the candlepin DB and replace it with one loaded with millions of cert serials:
```bash
$ wget …
```
> 1620226: Perform CRL generation without exceeding memory and maxing CPU

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/JobMessage.java
- server/src/main/java/org/candlepin/async/JobMessageDispatcher.java
- server/src/main/java/org/candlepin/async/impl/ActiveMQSessionFactory.java
- server/src/main/java/org/candlepin/async/impl/ArtemisJobMessageDispatcher.java
- server/src/main/java/org/candlepin/audit/EventSource.java
- server/src/main/java/org/candlepin/audit/MessageReceiver.java
- Added a new interface, JobMessageDispatcher, to allow for multiple
implementations of the message sending backend without needing to
modify JobManager itself
- Moved the AMQP broker connection management out of the JobManager
and into the new ArtemisJobMessageDispatcher class
> [F] Moved the amqp management  and message sending out of JobManager [ENT-1090]

- bin/bash_functions
- buildfile
- docker/candlepin-base/setup-devel-env.sh
- docker/docker-compose-mysql.yml
- docker/mysql.cnf
- profiles.yaml
- server/pom.xml
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/config/DatabaseConfigFactory.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
This commit leaves Liquibase still using the MySQL JDBC connector because the `mariadb-java-client` RPM isn't packaged in EPEL.  We can still use the JAR file in the deployed WAR though.
> Use MariaDB JDBC connector. [ENT-986]

- server/src/main/resources/db/changelog/20181116110941-virt-fact-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
Postgres allows the condition to better focus the index.
MySql does not, so the index will need to be broader.
> 1556930: Index to make hypervisor uuid lookup faster

- server/src/main/java/org/candlepin/auth/ConsumerAuth.java
- server/src/main/java/org/candlepin/auth/SSLAuth.java
- server/src/main/java/org/candlepin/auth/TrustedConsumerAuth.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/auth/SSLAuthTest.java
- Remove unnecessary deleted consumer check from ConsumerAuth.createPrincipal. This check is done by ConsumerStore.lookup
- Refactor ConsumerStore.lookup so that the deleted consumer check is run only when the consumer was not found
> 1482942: Remove unnecessary deleted consumer checks

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Fixed several queries which would fail when presented with large
collections of inputs
- Reduced the chunk size of the cleanupExpiredPools operation to
avoid hitting additional query size limits elsewhere
> [M] 1668463: Fix problems with CPM.deletePools with large datasets

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Fixed several queries which would fail when presented with large
collections of inputs
- Reduced the chunk size of the cleanupExpiredPools operation to
avoid hitting additional query size limits elsewhere
> [2.5] 1668462: Fix problems with CPM.deletePools with large datasets

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/PoolCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Fixed several queries which would fail when presented with large
collections of inputs
- Reduced the chunk size of the cleanupExpiredPools operation to
avoid hitting additional query size limits elsewhere
> [2.4] 1668454: Fix problems with CPM.deletePools with large datasets

- buildSrc/src/main/groovy/Rspec.groovy
- server/build.gradle
In order to optimize compile time move the Rspec custom task class to buildSrc so that it will be compiled once & then cached between build runs.
> [gradle] Move the rspec custom task to buildSrc

- server/bin/update-server-xml.py
- server/conf/logrotate.conf
- server/src/main/java/org/candlepin/audit/LoggingListener.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/resources/logback.xml
Candlepin root logger now  logs to the syslog. All log files (access.log, audit.log, candlepin.log and error.log) are rotated daily. Old log files are rotated in a format "${filename}.log-${YYYY-MM-dd}.gz"
- Configure Candlepin to log into the syslog
- Replace logrotate with Logback rolling for audit.log, candlepin.log and error.log
- Remove unused property AUDIT_LOG_FILE from ConfigProperties
- Fix rotation of Tomcat's access.log
> 1520502: Move to syslog/journald[ENT-397]

- server/client/ruby/candlepin_api.rb
- server/spec/owner_resource_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeAttributesDTO.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Created new API /owners/{owner_key}/consumers_system_purpose used
to retrieve an aggregate of all the syspurpose attributes that the
owner's consumers have specified.
> [M] 1623491: Get syspurpose attributes an owner's consumers [ENT-821]

- server/code/setup/cpsetup
Credentials passed as an argument take precedence. When no credentials are passed then environment variables are checked. When environment variables are missing, script fallbacks to hardcoded default values.
- Allow passing a db name as an environment variable CANDLEPING_DB_NAME
- Allow passing a db user as an environment variable CANDLEPIN_DB_USER
- Allow passing a db password as an environment variable CANDLEPING_DB_PASSWORD
> Allow passing credentials to cpsetup via environment variables[ENT-940]

- server/spec/autobind_spec.rb
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Pool priority (and consequently, syspurpose attribute matches) will
now have a higher impact than a virt_only match when breaking ties
during auto-attach.
- Syspurpose attributes will now always have a higher impact than
all other attributes (requires_host,virt_only,ram,cores,sockets,
cpu,vcpu) during auto-attach prioritization scoring.
- A match of the usage attribute will now have a higher impact than
not having a role, when the consumer has not specified any role
(1669185).
- Added helpful debug logging in the auto-attach rules code.
> [M] 1667238,1655703: Increase syspurpose impact on auto-attach; ENT-1137,ENT-1073

- server/spec/autobind_spec.rb
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Pool priority (and consequently, syspurpose attribute matches) will
now have a higher impact than a virt_only match when breaking ties
during auto-attach.
- Syspurpose attributes will now always have a higher impact than
all other attributes (requires_host,virt_only,ram,cores,sockets,
cpu,vcpu) during auto-attach prioritization scoring.
- A match of the usage attribute will now have a higher impact than
not having a role, when the consumer has not specified any role
(1673329).
- Added helpful debug logging in the auto-attach rules code.
> [2.3] 1669199,1656876: Increase syspurpose impact on auto-attach; ENT-1137,ENT-1073

- server/spec/autobind_spec.rb
- server/spec/system_purpose_compliance_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusTranslator.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
- server/src/main/java/org/candlepin/policy/js/compliance/hash/ComplianceStatusHasher.java
- server/src/test/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusTranslatorTest.java
- Now the syspurpose status states will be 'matched', 'mismatched' and
'not specified', instead of 'valid', 'invalid' and 'partial'
- Scenarios of mixed SLAs/Usages that would previously fall under the
'partial' category, will now be 'matched'. Scenarios of multiple
addons that are not all satisfied, that would previously fall under
the 'partial' category, will now be 'mismatched'
- Also, an additional reason will not be added for each pool that has a
mismatched sla or usage. Only one general mismatch reason is sent now
> [2.3] 1674415: changed the possible syspurpose status states

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed a couple bugs with AbstractHibernateCurator.lockAndLoad
not properly handling entities which have been deleted or
created, but not yet flushed
- lockAndLoad now throws an exception if provided an entity which
is immutable
- Removed the JPA criteria query building in favor of Hibernate's
native MultiIdentifierLoadAccess entity fetching
- Updated several unit tests in accordance with the above changes,
and added new tests for the created and deleted cases
> [M] Addressed issues surrounding locking with unmanaged entities

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed a couple bugs with AbstractHibernateCurator.lockAndLoad
not properly handling entities which have been deleted or
created, but not yet flushed
- lockAndLoad now throws an exception if provided an entity which
is immutable
- Removed the JPA criteria query building in favor of Hibernate's
native MultiIdentifierLoadAccess entity fetching
- Updated several unit tests in accordance with the above changes,
and added new tests for the created and deleted cases
> [2.4] 1679287: Addressed issues surrounding locking with unmanaged entities

- server/bin/cp_connectors.py
- server/bin/org_migrator.py
- Added the new organization migration utility, which can export
a single org's data to an archive to be re-imported later or
migrated to another database
- Added the cp_connectors utility, which provides simple setup
of various backends for communicating with Candlepin
More work is eventually needed here, but this gets us most of the way there.
> [M] Added the org_migrator utility (ENT-1110)

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed a couple bugs with AbstractHibernateCurator.lockAndLoad
not properly handling entities which have been deleted or
created, but not yet flushed
- lockAndLoad now throws an exception if provided an entity which
is immutable
- Removed the JPA criteria query building in favor of Hibernate's
native MultiIdentifierLoadAccess entity fetching
- Updated several unit tests in accordance with the above changes,
and added new tests for the created and deleted cases
> [2.3] 1679286: Addressed issues surrounding locking with unmanaged entities

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Fixed a couple bugs with AbstractHibernateCurator.lockAndLoad
not properly handling entities which have been deleted or
created, but not yet flushed
- lockAndLoad now throws an exception if provided an entity which
is immutable
- Removed the JPA criteria query building in favor of Hibernate's
native MultiIdentifierLoadAccess entity fetching
- Updated several unit tests in accordance with the above changes,
and added new tests for the created and deleted cases
> [2.5] 1679289: Addressed issues surrounding locking with unmanaged entities

- server/spec/autobind_spec.rb
- server/spec/system_purpose_compliance_spec.rb
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusTranslator.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
- server/src/main/java/org/candlepin/policy/js/compliance/hash/ComplianceStatusHasher.java
- server/src/test/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/SystemPurposeComplianceStatusTranslatorTest.java
- Now the syspurpose status states will be 'matched', 'mismatched' and
'not specified', instead of 'valid', 'invalid' and 'partial'
- Scenarios of mixed SLAs/Usages that would previously fall under the
'partial' category, will now be 'matched'. Scenarios of multiple
addons that are not all satisfied, that would previously fall under
the 'partial' category, will now be 'mismatched'
- Also, an additional reason will not be added for each pool that has a
mismatched sla or usage. Only one general mismatch reason is sent now
> [2.5] 1674419: changed the possible syspurpose status states

- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/resteasy/filter/EntityStore.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Added input partioning to ConsumerCurator.getConsumers, .findByUuids,
and .findByUuidsAndOwner. This will avoid hitting the query
parameter limit with large consumer sets.
> [M] 1601517: Added input partitioning to select ConsumerCurator methods

- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/resteasy/filter/EntityStore.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Added input partioning to ConsumerCurator.getConsumers, .findByUuids,
and .findByUuidsAndOwner. This will avoid hitting the query
parameter limit with large consumer sets.
> [2.5] 1674544: Added input partitioning to select ConsumerCurator methods

- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/resteasy/filter/EntityStore.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Added input partioning to ConsumerCurator.getConsumers, .findByUuids,
and .findByUuidsAndOwner. This will avoid hitting the query
parameter limit with large consumer sets.
> [2.4] 1674546: Added input partitioning to select ConsumerCurator methods

- server/src/main/java/org/candlepin/jackson/DateSerializer.java
- server/src/test/java/org/candlepin/resteasy/JsonProviderTest.java
- Replace SimpleDateFormat, which is not thread-safe and was shared
between threads, with DateTimeFormatter, which is thread-safe.
> [M] 1679597: Synchronize java.util.Date serializations; ENT-1183

- server/src/main/java/org/candlepin/jackson/DateSerializer.java
- server/src/test/java/org/candlepin/resteasy/JsonProviderTest.java
- Replace SimpleDateFormat, which is not thread-safe and was shared
between threads, with DateTimeFormatter, which is thread-safe.
> [2.5] 1683305: Synchronize java.util.Date serializations; ENT-1183

- server/src/main/java/org/candlepin/jackson/DateSerializer.java
- server/src/test/java/org/candlepin/resteasy/JsonProviderTest.java
- Replace SimpleDateFormat, which is not thread-safe and was shared
between threads, with DateTimeFormatter, which is thread-safe.
> [2.3] 1683304: Synchronize java.util.Date serializations; ENT-1183

- server/src/main/java/org/candlepin/pki/impl/ProviderBasedPKIUtility.java
Simply converting Candlepin to issue 4098 bit (up from 2046) keys
doesn't present any problems that I see. The major issue (that I can
see) is that once a key is generated for a client, that's the key
Candlepin is going to use for the foreseeable future. Clients will have
to re-register if they want a larger key. There's nothing we can do
about that though.  The CRL generation code has specific allowances for
changing the key size, but that would only be relevant if Candlepin
restarted with a brand new server key.
Starting to issue 4096 bit keys to new clients seems like about the
extent of what we can do for future-proofing without the user tearing up
a bunch of existing stuff in their deployment.
---
I want to test this **irrespective** of the crypto policy settings.  4096-bit keys are …
> 1650992: Change default key size to 4096 bits.

- server/src/main/java/org/candlepin/audit/EventFactory.java
- server/src/test/java/org/candlepin/audit/EventFactoryTest.java
This is very useful for Katello because we report system purpsose status (matched/mismatched/not specified) on each field. With this additional data we can figure that out. And since it should be identical fields to the /consumers/:uuid/purpose_compliance API we can parse both with the same code in case we need to process compliance status outside of an event which could happen.
I haven't tested this!
> Expose useful data on System Purpose Compliance event

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/temp/TestJob1.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/resources/db/changelog/20190222103500-add-async-job-exec-source.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- Implement construction of job from job key
- Update job state during execution(QUEUED->RUNNING->COMPLETED/FAILED)
- Handle job execution transactions
- Setup MDC for job logging
- Update TestJob1 so that it can sleep/fail according to the given parameters
- Add job_exec_source column to the cp2_async_jobs table
> Execute Jobs When Message Is Received From Artemis[ENT-1089]

- project_conf/checks.xml
- project_conf/suppression.xml
Checkstyle DTDs on puppycrawl site were deprecated some time ago and are now removed.
- Change configuration DTD link to "https://checkstyle.org/dtds/configuration_1_3.dtd"
- Change suppressions DTD link to "https://checkstyle.org/dtds/suppressions_1_2.dtd"
For more information see the following issues:
- https://github.com/checkstyle/checkstyle/issues/1571
- https://github.com/checkstyle/checkstyle/issues/6478
> Update Checkstyle DTDs links.

- project_conf/checks.xml
- project_conf/suppression.xml
Checkstyle DTDs on puppycrawl site were deprecated some time ago and are now removed.
- Change configuration DTD link to "https://checkstyle.org/dtds/configuration_1_3.dtd"
- Change suppressions DTD link to "https://checkstyle.org/dtds/suppressions_1_2.dtd"
For more information see the following issues:
- https://github.com/checkstyle/checkstyle/issues/1571
- https://github.com/checkstyle/checkstyle/issues/6478
> Update Checkstyle DTDs links[2.5]

- project_conf/checks.xml
Checkstyle DTDs on puppycrawl site were deprecated some time ago and are now removed.
- Change configuration DTD link to "https://checkstyle.org/dtds/configuration_1_3.dtd"
- Change suppressions DTD link to "https://checkstyle.org/dtds/suppressions_1_2.dtd"
For more information see the following issues:
- https://github.com/checkstyle/checkstyle/issues/1571
- https://github.com/checkstyle/checkstyle/issues/6478
> Update Checkstyle DTDs links[2.3]

- server/src/main/java/org/candlepin/pki/PKIUtility.java
Simply converting Candlepin to issue 4098 bit (up from 2046) keys
doesn't present any problems that I see. The major issue (that I can
see) is that once a key is generated for a client, that's the key
Candlepin is going to use for the foreseeable future. Clients will have
to re-register if they want a larger key. There's nothing we can do
about that though.  The CRL generation code has specific allowances for
changing the key size, but that would only be relevant if Candlepin
restarted with a brand new server key.
Starting to issue 4096 bit keys to new clients seems like about the
extent of what we can do for future-proofing without the user tearing up
a bunch of existing stuff in their deployment.
> [2.3] 1664789: Change default key size to 4096 bits.

- server/src/main/java/org/candlepin/pki/impl/ProviderBasedPKIUtility.java
Simply converting Candlepin to issue 4098 bit (up from 2046) keys
doesn't present any problems that I see. The major issue (that I can
see) is that once a key is generated for a client, that's the key
Candlepin is going to use for the foreseeable future. Clients will have
to re-register if they want a larger key. There's nothing we can do
about that though.  The CRL generation code has specific allowances for
changing the key size, but that would only be relevant if Candlepin
restarted with a brand new server key.
Starting to issue 4096 bit keys to new clients seems like about the
extent of what we can do for future-proofing without the user tearing up
a bunch of existing stuff in their deployment.
> [2.5] 1664788: Change default key size to 4096 bits.

- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Now during auto-attach, syspurpose attribute mismatches will
have a lower impact, as to only be significant when breaking
ties between otherwise similar pools. Auto-attach will choose
the pool which covers the most syspurpose attributes, even if
that pool comes with other non-specified syspurpose attributes.
> [M] 1687535: Better syspurpose matches during auto-attach; ENT-1213

- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Now during auto-attach, syspurpose attribute mismatches will
have a lower impact, as to only be significant when breaking
ties between otherwise similar pools. Auto-attach will choose
the pool which covers the most syspurpose attributes, even if
that pool comes with other non-specified syspurpose attributes.
> [2.3] 1687779: Better syspurpose matches during auto-attach; ENT-1213

- server/spec/owner_resource_spec.rb
- server/spec/system_purpose_compliance_spec.rb
- server/src/main/java/org/candlepin/bind/ComplianceOp.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/pinsetter/tasks/ActiveEntitlementJob.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Now the syspurpose status is calculated & persisted during
consumer creation.
- Now the syspurpose status is calculated & persisted correctly
during a bind operation (consumed entitlements are filtered by
their valid date).
- Now the syspurpose status will not be recalculated & persisted
during a status call with specified on_date.
- Removed redundant db call when filtering entitlements
with a specified date for the syspurpose status calculation.
- Do not calculate syspurpose status for distributors.
> Syspurose Status filter on date fixes

- server/spec/content_access_spec.rb
- server/spec/import_spec.rb
> Added additional tests to verify import functionality

- server/spec/content_access_spec.rb
- server/spec/import_spec.rb
> [M] Added additional tests to verify import functionality

- server/spec/content_access_spec.rb
- server/spec/import_spec.rb
> [2.5] Added additional tests to verify import functionality

- server/spec/content_access_spec.rb
- server/spec/import_spec.rb
> [2.4] Added additional tests to verify import functionality

- buildfile
- server/spec/content_access_spec.rb
- server/spec/import_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
> [2.4.8] Added additional tests to verify import functionality

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- RevocationOp no longer uses lockAndLoad to both lock and refresh
pools, instead only using lock and leaving pools in their current
state
- Added additional trace output during refresh
- Removed an extraneous output line from the class
DefaultEntitlementCertServiceAdapter
> [2.3] 1644707: RevocationOp no longer refreshes pools while locking (ENT-1221)

- server/bin/deploy
- server/bin/liquibase.sh
- server/candlepin.spec.tmpl
- server/code/setup/cpdb
- Add custom script for running CP-provided Liquibase
- Update deploy and cpdb to use the new script instead of locally installed Liquibase
- Remove postgresql-jdbc from candlepin.spec.tmpl
> Update deploy and cpdb to use CP-provided Liquibase[ENT-1209]

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- RevocationOp no longer uses lockAndLoad to both lock and refresh
pools, instead only using lock and leaving pools in their current
state
- Added additional trace output during refresh
- Removed an extraneous output line from the class
DefaultEntitlementCertServiceAdapter
> [2.4] 1679287: RevocationOp no longer refreshes pools while locking

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Entitlement revocation no longer uses lockAndLoad to both lock and
refresh pools, instead only using lock and leaving pools in their
current state
- Added additional trace output during refresh
- Removed an extraneous output line from the class
DefaultEntitlementCertServiceAdapter
> [2.5] 1679289: Entitlement revocation no longer refreshes pools while locking

- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Entitlement revocation no longer uses lockAndLoad to both lock and
refresh pools, instead only using lock and leaving pools in their
current state
- Added additional trace output during refresh
- Removed an extraneous output line from the class
DefaultEntitlementCertServiceAdapter
> [M] 1644707: Entitlement revocation no longer refreshes pools while locking

- server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1591315
* This BZ bug report was originaly opened against sub-man and most
of issues were really related to sub-man. These issues were
fixed in: https://github.com/candlepin/subscription-manager/pull/2056
* It was necessary to fix only one case in candlepin server.
* When system is registererd with activation key,  auto-attch is false
and subscriptions attached that cover installed products but all
pools associated with the key are exhausted/consumed, then no
exception should not be raised, when golden ticket is used.
> 1591315: Less confusing warnings, when golden ticket is used; ENT-671

- server/src/main/resources/db/changelog/20190401093722-add-content-override-index.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- Added an index on the key_id column in the table cp_content_override
to reduce query time when fetching activation key details
> [2.5] 1694728: Added index on column key_id in cp_content_override

- server/src/main/java/org/candlepin/async/JobBuilder.java
- server/src/main/java/org/candlepin/async/JobException.java
- server/src/main/java/org/candlepin/async/JobExecutionException.java
- server/src/main/java/org/candlepin/async/JobInitializationException.java
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/JobMessage.java
- server/src/main/java/org/candlepin/async/JobMessageDispatchException.java
- server/src/main/java/org/candlepin/async/JobMessageDispatcher.java
- server/src/main/java/org/candlepin/async/JobMessageReceiver.java
- server/src/main/java/org/candlepin/async/JobStateManagementException.java
- server/src/main/java/org/candlepin/async/impl/ArtemisJobMessageDispatcher.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/async/JobMessageReceiverTest.java
- The JobManager will now retry jobs that fail during execution
if they have been configured to run more than once and the
failure is not flagged as a terminal failure
- Executed jobs now have their run attempt counter and start
and end times properly set
- Updated log and exception output messages to improve clarity
and conform to existing message formats
- Renamed PreJobExecutionException to JobInitializationException
- JobInitializationException and JobExecutionException are now
both subclasses of JobException
- JobExecutionException can now be flagged as a "terminal"
exception, indicating that it should not be retried, even if
the job has been configured to retry and has not yet exceeded
its attempt limit
- Removed some of the exception handling from JobMessageReciever,
as this is now …
> [F] Added support for retry-on-failure to the async job system

- server/bin/create_test_repos.py
- server/bin/data_generator.rb
- server/bin/deploy
- server/bin/test_data.json
* Repositories are created according definition of 'content' in
test_data.json
* Added definitions of dummy packages to test_data.json
- Dummy packages are empty packages without any content (no files)
- No dependencies on anything
- Easy to test on any platform (RHEL, CentOS 6/7, Fedora, ...)
* Product certificate is created from temporary product using REST API
- Temporary product contains only one contet and ID of temporary
product is the same as ID of content
- Certitifate for temporary product is downloaded
- Temporary product is removed
* Python script for creating testing repos also contains functions
for creating GPG keys and signing keys, but it is not used ATM
* It requires more packages on the system running candlepin (https://github.com/candlepin/ansible-role-candlepin will be …
> Added ability to create testing yum/dnf repositories.

- server/client/ruby/hostedtest_api.rb
- server/spec/client_v1_size_spec.rb
- server/spec/entitlement_certificate_v3_spec.rb
- server/spec/pool_resource_spec.rb
- server/spec/refresh_pools_spec.rb
- server/spec/spec_helper.rb
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
- server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionServiceAdapter.java
- The HostedTestSubscriptionResource and ServiceAdapter are now
completely isolated from the locally managed products and
content
- Updated the hosted test API to allow for directly updating
products, content and subscriptions independently from their
downstream counterparts
- Updated several spec tests to utilize the separation between
up and downstream product/content definitions
> [2.3] Improved hosted test adapter separation

- server/candlepin.spec.tmpl
I was testing the new 2.6 build RPM and saw that candlepin would stop responding after running for only a few minutes. I suspected I needed to migrate the db and tried cpdb --update and found:
```
Error running command: /usr/share/candlepin/liquibase.sh --driver=org.postgresql.Driver --classpath=/var/lib/tomcat/webapps/candlepin/WEB-INF/lib/postgresql-42.2.2.jar:/var/lib/tomcat/webapps/candlepin/WEB-INF/classes/ --changeLogFile=db/changelog/changelog-update.xml --u
rl=jdbc:postgresql:candlepin --username=$DBUSERNAME --logLevel=severe migrate -Dcommunity=False                                                                                                                                                                                 
Status code: 32512 …
```
> Install liquibase.sh via RPM

- server/src/main/java/org/candlepin/bind/BindContext.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
> [2.3] 1679286: Removed AHC.lockAndLoad to address quirks with refresh (ENT-1245)

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/tasks/ExportJob.java
- server/src/main/java/org/candlepin/audit/Event.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/java/org/candlepin/sync/Exporter.java
- server/src/main/java/org/candlepin/util/Util.java
- server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/sync/ExporterTest.java
- server/src/test/java/org/candlepin/util/UtilTest.java
Cleanup of some dead code and minor issues I found during ENT-849. Please review [ENT-849](https://github.com/candlepin/candlepin/pull/2309) first.
- Fix JavaDoc issues with missing qualifiers
- Remove dead code from Exporter
- Make Util.fromJson generic
- Remove redundant casts
- Remove dead code from Util
> Cleanup after ENT-849

- server/bin/create_test_repos.py
- server/bin/import_test_data.rb
- server/bin/test_data.json
* When some content_id is shared with some product, then modificated
duplicity of the content is created. ID of content is:
str(product_id) + str(content_id)
* No temporary products and product certificates are installed
* Modificated a little bit some names of products without any content.
It helps with testing.
* Definition of content is automatically modified as is illustrated in this snippet:
```json
{
"contents": [
{
"name": "${product_id}-never-enabled-content",
"id": "${product_id} + 100",
"label": "${product_id}-never-enabled-content",
"type": "yum",
"vendor": "test-vendor",
"content_url": "/foo/path/never_enabled/${product_id}",
"gpg_url": "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-candlepin",
"metadata_expire": 600,
"packages": ["tricky-frog", "slow-eagle", "white-lion"]
},
], …
```
> Do not share one content with several products.

- build.gradle
This fixes an issue where the ivy style structure is more strict and does not work for the JSS libraries in the repository.
> Convert to maven style repo reference

- buildfile
- server/pom.xml
- server/src/main/java/org/candlepin/async/JobDataMap.java
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/JobMessageReceiver.java
- server/src/main/java/org/candlepin/async/temp/TestJob1.java
- server/src/main/java/org/candlepin/audit/ArtemisMessageSourceReceiverFactory.java
- server/src/main/java/org/candlepin/audit/MessageReceiver.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java
- server/src/test/java/org/candlepin/TestingModules.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
- Added basic support for scheduling jobs using a cron-like
scheduling expression
- Updated the job configuration variables and expressions
- Added support for job whitelists and blacklists
- Added support for per-job configuration, currently supporting
scheduling and disabling jobs
- Updated how the AMQP consumer filter expression is built; it
will now use the whitelist, blacklist and job enabled flags
to build the appropriate expression for the node
- JobManager now listens for mode change events and will pause
and/or resume as appropriate (currently this only stops
scheduled jobs from being executed)
- Updated the ManagerState and JobState enums to be declarative
of their valid state transitions
- Bumped Quartz to version 2.2.2
> [F] Added basic support for scheduling jobs (ENT-857)

- server/src/main/java/org/candlepin/bind/BindContext.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/controller/RevocationOp.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
usages
- Entitlement revocation was moved to after pool update, merging and
flushing of changes
- Branding synchronization no …
> [2.4] 1679287: Removed AHC.lockAndLoadById(s) to address quirks with refresh

- server/src/main/java/org/candlepin/jackson/DateSerializer.java
- server/src/test/java/org/candlepin/resteasy/JsonProviderTest.java
- Replace SimpleDateFormat, which is not thread-safe and was shared
between threads, with DateTimeFormatter, which is thread-safe.
> [2.4] 1704720: Synchronize java.util.Date serializations; ENT-1294

- server/src/main/java/org/candlepin/bind/BindContext.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
usages
- Entitlement revocation was moved to after pool update, merging and
flushing of changes
- Branding synchronization no …
> [M] 1644707: Removed AHC.lockAndLoadById(s) to address quirks with refresh

- server/src/main/java/org/candlepin/bind/BindContext.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
usages
- Entitlement revocation was moved to after pool update, merging and
flushing of changes
- Branding synchronization no …
> [2.6] 1707522: Removed AHC.lockAndLoadById(s) to address quirks with refresh

- server/src/main/java/org/candlepin/bind/BindContext.java
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/controller/OwnerManager.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java
- server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
usages
- Entitlement revocation was moved to after pool update, merging and
flushing of changes
- Branding synchronization no …
> [2.5] 1679289: Removed AHC.lockAndLoadById(s) to address quirks with refresh

- server/src/main/java/org/candlepin/config/DatabaseConfigFactory.java
Based on test of hypervisor check in with with 17K hosts and 6 guests each.
Was able to execute with a block setting of 30K. Using half that for caution.
> 1694809: Reduce in operator block size

- server/client/ruby/candlepin_api.rb
- server/spec/activation_key_spec.rb
- This was already fixed
- Added SPEC test to verify this behavior
> 1461188: Creating an ActivationKey with "contentOverrides": null results in a 400 status[ENT-1130]

- server/client/ruby/candlepin_api.rb
- server/spec/hypervisor_heartbeat_spec.rb
- server/src/main/java/org/candlepin/guice/CandlepinCapabilities.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorHeartbeatUpdateJob.java
- server/src/main/java/org/candlepin/resource/HypervisorResource.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- Create a new endpoint POST /hypervisors/heartbeat/{owner}
- The new endpoint updates last checkin date of all consumers for the given reporter_id
> 1709723: last check-in date is not updated for hypervisors reported by virt-who (candlepin changes) [ENT-1049]

- server/spec/autobind_spec.rb
- server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- server/src/main/resources/rules/rules.js
- server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- server/src/test/java/org/candlepin/policy/SystemPurposeComplianceRulesTest.java
- During auto-attach and syspurpose status calculations, syspurpose
attribute values are now compared with case insensitivity.
> 1664481: match syspurpose attributes case insensitively [ENT-1284]

- buildfile
Fixes build error when LANG and LC_* area are unset:
```
2019-05-20 12:11:06.034  FINE: Stdout: 
2019-05-20 12:11:06.034  FINE: Stderr: 
Buildr aborted!
ArgumentError : invalid byte sequence in US-ASCII
/home/candlepin/candlepin/buildfile:76:in `<top (required)>'
/home/candlepin/.gem/ruby/gems/buildr-1.5.3/lib/buildr/core/application.rb:423:in `raw_load_buildfile'
/home/candlepin/.gem/ruby/gems/buildr-1.5.3/lib/buildr/core/application.rb:224:in `block in load_buildfile'
/home/candlepin/.gem/ruby/gems/buildr-1.5.3/lib/buildr/core/application.rb:219:in `load_buildfile'
(See full trace by running task with --trace)
```
We can work around this by always setting LANG with this command. However if yall want to fix this at the source here it is.
> setting default encoding to UTF_8 during buildtime

- server/client/ruby/candlepin_api.rb
- server/spec/candlepin_scenarios.rb
- server/src/main/java/org/candlepin/async/JobConfig.java
- server/src/main/java/org/candlepin/async/JobConfigValidationException.java
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/tasks/ExportJob.java
- server/src/main/java/org/candlepin/async/temp/AsyncJobResource.java
- server/src/main/java/org/candlepin/auth/ConsumerPrincipal.java
- server/src/main/java/org/candlepin/auth/JobPrincipal.java
- server/src/main/java/org/candlepin/auth/UserPrincipal.java
- server/src/main/java/org/candlepin/auth/permissions/AsyncJobStatusPermission.java
- server/src/main/java/org/candlepin/auth/permissions/JobStatusPermission.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/java/org/candlepin/resource/ConsumerResource.java
- server/src/main/java/org/candlepin/resteasy/filter/StoreFactory.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
- ConsumerResource now uses the async/Artemis ExportJob task
instead of the old Pinsetter version
- Added the AsyncJobStatusPermission to handle support for
checking permissions on async jobs
- Updated the temp AsyncJobResource to use the DTOs and
new permissions
- Added (temporary?) methods to the spec tests for fetching
async jobs by ID
- Async job execution now uses the new JobPrincipal rather
than a system principal or empty user principal
- Renamed JobBuilder to JobConfig to better match its actual usage
- JobConfig now has a .validate method which will check its
settings and verify the minimum required fields are set
- ExportJob has been updated to use the new JobConfig and validator
- ExportJob.createJobConfig now returns a JobConfig to be filled
in rather than taking six …
> [F] Updated ConsumerResource to use the new async ExportJob task (ENT-1265)

- server/spec/import_spec.rb
- server/src/main/java/org/candlepin/async/ImportConflictJobException.java
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/tasks/ExportJob.java
- server/src/main/java/org/candlepin/async/tasks/ImportJob.java
- server/src/main/java/org/candlepin/controller/ManifestManager.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/async/tasks/ImportJobTest.java
- server/src/test/java/org/candlepin/controller/ManifestManagerTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- server/src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java
- server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
* Now the ImportJob is using the new artemis messaging framework.
* Made sure that in case of an ImportJob failure due to conflicts,
the result data returned include the list of conflicts.
* Removed some unused constructor arguments from OwnerResource.
> [F] ENT-847: Port ImportJob To The New Messaging Framework

- build.gradle
This fixes the deprecation warning for gradle 6 compatibility.
> Update nebula.lint version.

- server/src/main/java/org/candlepin/model/ConsumerCapability.java
- server/src/main/java/org/candlepin/model/ConsumerContentOverride.java
- server/src/main/java/org/candlepin/model/ConsumerInstalledProduct.java
- server/src/main/java/org/candlepin/model/DistributorVersionCapability.java
- server/src/main/java/org/candlepin/model/EntitlementCertificate.java
- server/src/main/java/org/candlepin/model/Environment.java
- server/src/main/java/org/candlepin/model/GuestId.java
- server/src/main/java/org/candlepin/model/HypervisorId.java
- server/src/main/java/org/candlepin/model/ImportUpstreamConsumer.java
- server/src/main/java/org/candlepin/model/PermissionBlueprint.java
- server/src/main/java/org/candlepin/model/Role.java
- server/src/main/java/org/candlepin/model/UpstreamConsumer.java
Candlepin now uses liquibase to generate the database schema. Because of this the ForeignKey and Index annotations are no longer necessary on the model objects. In addition the Hibernate.annotations.ForeignKey & Index annotations have been deprecated.
Rather than converting to the new JPA style annotations this change removes them entirely as they are not providing additional value on top of the liquibase schema generation.
> Remove Deprecated and unused annotations.

- server/client/ruby/candlepin_api.rb
- server/spec/product_resource_spec.rb
- server/spec/refresh_pools_spec.rb
- server/src/main/java/org/candlepin/async/tasks/RefreshPoolsJob.java
- server/src/main/java/org/candlepin/async/temp/AsyncJobResource.java
- server/src/main/java/org/candlepin/controller/Refresher.java
- server/src/main/java/org/candlepin/dto/api/v1/AsyncJobStatusDTO.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsJob.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/main/java/org/candlepin/resource/ProductResource.java
- server/src/test/java/org/candlepin/async/tasks/RefreshPoolsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/RefreshPoolsJobTest.java
- server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/resource/ProductResourceTest.java
* Now the RefreshPoolsJob is using the new artemis messaging
framework.
* Updated OwnerResource.refreshPools() &
ProductResource.refreshPoolsForProduct() to use the new job.
* Exposed the 'statusPath' field on AsyncJobStatusDTO.
* Added new 'getStatusAndDeleteIfFinished' endpoint to the temp
async job resource.
* Updated the spec test api to expect new job states.
* Removed redundant field from Refresher.
> [F] ENT-846: Port RefreshPoolsJob To The New Messaging Framework

- server/spec/entitlement_certificate_v3_spec.rb
- server/spec/environment_cert_v3_spec.rb
- server/src/main/java/org/candlepin/model/dto/TinySubscription.java
- server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
- server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- syspurpose attributes are now part of the entitlement certificates.
- Bumped certificate version from 3.3 to 3.4.
> [M] 1717903: syspurpose attributes now part of certificates [ENT-1369]

- server/build.gradle
- This was lost after the merging of master back into the new job
framework branch, due to it being simultaneously bumped in the
buildfile in one branch, and the switch from buildr to gradle
in the other.
> [F] Quartz should be bumped to version 2.2.2

- common/src/main/java/org/candlepin/common/filter/LoggingFilter.java
- server/spec/import_spec.rb
- server/src/main/java/org/candlepin/async/JobExecutionContext.java
- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/tasks/ExportJob.java
- server/src/main/java/org/candlepin/async/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/async/tasks/ImportJob.java
- server/src/main/java/org/candlepin/async/tasks/RefreshPoolsJob.java
- server/src/main/java/org/candlepin/async/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/auth/permissions/AsyncJobStatusPermission.java
- server/src/main/java/org/candlepin/dto/api/v1/AsyncJobStatusTranslator.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/main/java/org/candlepin/model/OwnerCurator.java
- server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java
- server/src/main/java/org/candlepin/resource/OwnerResource.java
- server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/async/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/dto/api/v1/AsyncJobStatusTranslatorTest.java
- server/src/test/java/org/candlepin/model/OwnerCuratorTest.java
- Ported the UndoImportsJob to the Artemis job system
- Added a new owner-specific lockAndLoad variant that can
lock and load an owner entity by key
- Added a constant to LoggingFilter to specify the key
used in the packaged logback.xml configuration for
referencing the org/owner key
- Updated all async tests to use the new
LoggingFilter.OWNER_KEY constant when setting the
owner key in the job metadata
> [F] Ported the UndoImportsJob to the Artemis job system (ENT-854)

- server/bin/deploy
- server/src/main/root/META-INF/context.xml
* Tomcat doesn't allow to use symbolic links be default due to
security reasons. It is necessary to allow it in configuration
file META-INF/context.xml
* Improved a little bit deploy script
> Improved deploy script to allow usage of symlinks by tomcat

- buildfile
- server/pom.xml
- server/src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- Now, when creating a JSS provider on deployment, we also create
a JSS CryptoManager, which initializes the NSS db.
- Downgraded JSS to 4.4.6 to be in line with the jars/libraries
distributed in RHEL 7. This means with this fix, candlepin is
not compatible with RHEL 8, which ships with JSS 4.5.x.
- Added https://barnabycourt.fedorapeople.org/repo/candlepin as
a new, temporary, artifact repository for our builds, which holds
the jss 4.4.6 dependency for now.
Co-authored-by: Alexander Scheel <ascheel@redhat.com>
> [2.5] 1720288: Initialize the NSS db when loading a JSS provider [ENT-1388]

- buildfile
- server/pom.xml
- server/src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- Now, when creating a JSS provider on deployment, we also create
a JSS CryptoManager, which initializes the NSS db.
- Downgraded JSS to 4.4.6 to be in line with the jars/libraries
distributed in RHEL 7. This means with this fix, candlepin is
not compatible with RHEL 8, which ships with JSS 4.5.x.
- Added https://barnabycourt.fedorapeople.org/repo/candlepin as
a new, temporary, artifact repository for our builds, which holds
the jss 4.4.6 dependency for now.
Co-authored-by: Alexander Scheel <ascheel@redhat.com>
> [2.6] 1724115: Initialize the NSS db when loading a JSS provider [ENT-1388]

- build.gradle
- buildfile
- server/build.gradle
- server/pom.xml
- server/src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- Now, when creating a JSS provider on deployment, we also create
a JSS CryptoManager, which initializes the NSS db.
- Downgraded JSS to 4.4.6 to be in line with the jars/libraries
distributed in RHEL 7. This means with this fix, candlepin is
not compatible with RHEL 8, which ships with JSS 4.5.x.
- Added https://barnabycourt.fedorapeople.org/repo/candlepin as
a new, temporary, artifact repository for our builds, which holds
the jss 4.4.6 dependency for now.
Co-authored-by: Alexander Scheel <ascheel@redhat.com>
> [M] 1723799: Initialize the NSS db when loading a JSS provider [ENT-1388]

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/JobMessageDispatcher.java
- server/src/main/java/org/candlepin/async/impl/ArtemisJobMessageDispatcher.java
- server/src/main/java/org/candlepin/model/AsyncJobStatus.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- Added a synchronization operation between the database and
messaging bus to ensure job messages aren't committed until
the active transaction which would persist the backing job
is complete
- Added an additional check to ensure a job class is registered
for a given job key
> [F] Added synchronization between the database and messaging bus

- docker/gating-test-images/README.mkd
- docker/gating-test-images/build.sh
- The caller (jenkins node) will be responsible for turning
SELinux enforcing off.
> Remove SELinux checks on gating-test docker image building

- server/src/main/java/org/candlepin/async/JobConstraints.java
- server/src/main/java/org/candlepin/async/impl/UniqueByArgConstraint.java
- server/src/main/java/org/candlepin/async/tasks/ExportJob.java
- server/src/main/java/org/candlepin/async/tasks/HypervisorHeartbeatUpdateJob.java
- server/src/main/java/org/candlepin/async/tasks/HypervisorUpdateJob.java
- server/src/main/java/org/candlepin/async/tasks/ImportJob.java
- server/src/main/java/org/candlepin/async/tasks/RefreshPoolsJob.java
- server/src/main/java/org/candlepin/async/tasks/UndoImportsJob.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/async/impl/UniqueByArgConstraintTest.java
- The UniqueByArgConstraint now accepts more than one parameter
for restriction job scheduling based on job arguments
- Updated several jobs to use the new method name and syntax for
adding the unique-by-arg constraint
> [F] Added support for multiple parameters in the UniqueByArgConstraint

- server/src/main/java/org/candlepin/async/JobManager.java
- server/src/main/java/org/candlepin/async/tasks/ManifestCleanerJob.java
- server/src/main/java/org/candlepin/audit/ArtemisMessageSourceReceiverFactory.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/async/tasks/BaseJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ImportJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ManifestCleanerJobTest.java
- server/src/test/java/org/candlepin/async/tasks/RefreshPoolsForProductJobTest.java
- server/src/test/java/org/candlepin/async/tasks/RefreshPoolsJobTest.java
- Ported the ManifestCleanerJob to the Artemis job system
- Refactored some job configuration constants and methods to
standardize how per-job configuration is done
- Updated several Artemis job tests to no longer reference
Pinsetter classes
- Fixed a few problems in the JobManager tests involving
scheduling
> [F] Ported the ManifestCleanerJob to the Artemis job system (ENT-859)

- server/spec/content_versioning_spec.rb
- server/spec/job_schedule_spec.rb
- server/spec/product_versioning_spec.rb
- server/src/main/java/org/candlepin/async/tasks/ImportRecordCleanerJob.java
- server/src/main/java/org/candlepin/config/ConfigProperties.java
- server/src/main/java/org/candlepin/guice/CandlepinModule.java
- server/src/test/java/org/candlepin/async/tasks/ImportRecordCleanerJobTest.java
- Ported the ImportRecordJob to the Artemis job system
as the ImportRecordCleanerJob
> [F] Port ImportRecordJob to the new job framework (ENT-865)

- server/src/test/java/org/candlepin/async/JobManagerTest.java
- server/src/test/java/org/candlepin/async/JobMessageReceiverTest.java
- server/src/test/java/org/candlepin/async/impl/UniqueByArgConstraintTest.java
- server/src/test/java/org/candlepin/async/tasks/ActiveEntitlementJobTest.java
- server/src/test/java/org/candlepin/async/tasks/BaseJobTest.java
- server/src/test/java/org/candlepin/async/tasks/CRLUpdateJobTest.java
- server/src/test/java/org/candlepin/async/tasks/EntitleByProductsJobTest.java
- server/src/test/java/org/candlepin/async/tasks/EntitlerJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ExpiredPoolsCleanupJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- server/src/test/java/org/candlepin/async/tasks/HealEntireOrgJobTest.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorHeartbeatUpdateJobTest.java
- server/src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ImportJobTest.java
- server/src/test/java/org/candlepin/async/tasks/ImportRecordCleanerJobTest.java
- server/src/test/java/org/candlepin/async/tasks/JobCleanerTest.java
- server/src/test/java/org/candlepin/async/tasks/ManifestCleanerJobTest.java
- server/src/test/java/org/candlepin/async/tasks/OrphanCleanupJobTest.java
- server/src/test/java/org/candlepin/async/tasks/RefreshPoolsForProductJobTest.java
- server/src/test/java/org/candlepin/async/tasks/RefreshPoolsJobTest.java
- server/src/test/java/org/candlepin/async/tasks/RegenEnvEntitlementCertsJobTest.java
- server/src/test/java/org/candlepin/async/tasks/UndoImportsJobTest.java
- server/src/test/java/org/candlepin/async/tasks/UnmappedGuestEntitlementCleanerJobTest.java
A lot of async job tests inherit from either BaseJobTest of DatabaseTestFixture even though only a few of them really require it. Jobs that require DatabaseTestFixture are ActiveEntitlementJobTest, ImportRecordCleanerJobTest, OrphanCleanupJobTest and UndoImportsJobTest. For the rest I removed the parent. With parent removed @MockitoSettings(strictness = Strictness.LENIENT) is redundant as unused mocking is no longer present. I also removed @ExtendWith(MockitoExtension.class) where tests do not use Mockito annotations.
- Replace try-catch with assertThrows
- Replace JUnit4 annotations with JUnit5
- Replace deprecated matchers
- Remove redundant annotations
- Remove redundant parents
> Cleanup of async job tests

- server/spec/hypervisor_check_in_spec.rb
- server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
It previously resulted in a null pointer exception that gave
no indication of the problem. The log now has an appropriate
message.
> Handling for bad hypervisor json

- pom.xml
- server/bin/deploy
- server/bin/gen-certs
- server/candlepin.spec.tmpl
- server/code/setup/cpsetup
- server/src/main/java/org/candlepin/pki/impl/JSSLoaderException.java
- server/src/main/java/org/candlepin/pki/impl/JSSProviderLoader.java
- server/src/main/webapp/META-INF/context.xml
- server/src/main/webapp/META-INF/context_tomcat8.xml
- Now the candlepin rpm depends on tomcatjss instead of
jss and tomcat/pki-servlet-container/pki-servlet-engine
to avoid these name changes between RHEL 7, RHEL8 and
RHEL 8.1, since that package is comprehensively taking
care of that itself.
- The spec file and deploy script now update the
META-INF/context.xml file to avoid breaking API changes
between Tomcat 7 and 8+ when altering the classpath to
include the jss jar from the filesystem.
- Updated cpsetup script:
* to be python3 compatible.
* with server.xml and CA cert/key changes for Tomcat 8+
compatibility.
- JSSProvider/CryptoManager are now loaded once, during
context initialization, and not during classloading of
JSSProviderLoader.java.
- Due to the fact that we no longer package the jss jar,
but we load it from the OS, and because …
> ENT-1408: Candlepin RHEL 8 support

- server/src/main/java/org/candlepin/resource/EntitlementResource.java
`Adjust entitlement quantity` for source consumer and `bind by pool quantity` for destination consumer operations are completed in different transactions. Due to this if something goes wrong in `bind by pool quantity` then `adjust entitlement quantity` for source consumer does not rollback. One simple solution to perform operations in one transaction.
> 1569133:Entitlements Removed from Source when transfer fails [ENT-526]

- server/spec/consumer_resource_host_guest_spec.rb
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/resource/util/GuestMigration.java
The API returns duplicate guest ids in the response as the cp_consumer_guests table has duplicate guest entries for a consumer. As per my investigation, this situation occurs when update consumer request contains duplicate guest ids. Currently, there is no check to remove duplicate guest ids from the request.
To fix this, I removed duplicate guests from the response for existing records and also added code to remove duplicate entries from request to avoid duplicate entries in cp_consumer_guests table.
> 1734521: Consumer returning duplicate guests [ENT-1535]

- server/src/main/java/org/candlepin/dto/api/v1/DeletedConsumerDTO.java
- server/src/main/java/org/candlepin/dto/api/v1/DeletedConsumerTranslator.java
- server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- server/src/main/java/org/candlepin/model/ConsumerCurator.java
- server/src/main/java/org/candlepin/model/DeletedConsumer.java
- server/src/main/java/org/candlepin/model/OwnerEnvContentAccessCurator.java
- server/src/main/resources/db/changelog/20190813155224-add-principal-to-deleted-consumers.xml
- server/src/main/resources/db/changelog/changelog-create.xml
- server/src/main/resources/db/changelog/changelog-testing.xml
- server/src/main/resources/db/changelog/changelog-update.xml
- server/src/test/java/org/candlepin/dto/api/v1/DeletedConsumerDTOTest.java
- server/src/test/java/org/candlepin/dto/api/v1/DeletedConsumerTranslatorTest.java
- server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- DeletedConsumer now has a column to store the name of the principal
that triggered the deletion of a consumer
- ConsumerCurator.delete now sets the name of the current principal
on the deleted consumer record it creates
> [M] 1740877: Added principal to consumer deletion records (ENT-1572)
