candlepin/candlepin

gutterball/bin/qpid/configure-qpid.sh
After upgrade deploy appeared broken complaining about an expected "localhost"
but got "ca" in a certificate. Update to use the expected CA name.
@awood does this look ok? Any implications for actual installations? Are we likely to get bit by this there?
=> Fix broken dev deploys after ugprade to qpid 0.30.

common/src/main/java/org/candlepin/common/filter/ServletLogger.java
- Currently only JSON received on the request will be formatted and
formatting is not configurable.
=> Added JSON formatting to ServletLogger

server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRulesTranslator.java
Previous error was causing confusion, hopefully this is better.
=> Improved error message for blocked host restricted pool binds.

server/src/main/java/org/candlepin/resource/util/CalculatedAttributesUtil.java, server/src/test/java/org/candlepin/resource/util/CalculatedAttributesUtilTest.java
For use with pools for unmapped guests only flag
=> 1201520: Addition of (Temporary) to pool description

tasks/eclipse.rake
When running simultaneous tasks with Buildr and Eclipse, all sorts of
problems pop up.  Buildr creates a class file and then Eclipse gets
bent out of shape about it or vice versa.  Generally the error messages
are around byte-code incompatibilities.
This patch gives Eclipse its own target directory that it can manage as
it sees fit.
=> Set Eclipse to use its own target directory.

bin/bash_functions
I had this lead to an error while deploying inside a vm
=> Deploy: Ensure TERM is defined (needed by tput)

server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTask.java, server/src/main/java/org/candlepin/resource/AdminResource.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/PopulateHostedDBTaskTest.java, server/src/test/java/org/candlepin/test/DatabaseTestFixture.java, server/src/test/java/org/candlepin/test/TestUtil.java
- The AdminResource now has a new API call, "pophosteddb," for
populating the database in a hosted environment with product and
content data
- The new API call runs as an asynchronous job performed by the
PopulateHostedDBTask class
=> Added the PopulateHostedDB task and API call

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/Refresher.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/model/Subscription.java, server/src/main/java/org/candlepin/model/SubscriptionCurator.java, server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java, server/src/test/java/org/candlepin/model/SubscriptionCuratorTest.java
=> Fix significant subscription problems in multi-tenant deployment when products change.

server/bin/cmv, server/client/ruby/cpc
- Added the "cmv" tool to server/bin. This tool can be used to create
snapshots for one or more orgs and then validate a deployment against
a previous snapshot at a later date
- Fixed a few typos and cryptic bits of code in cpc
=> Added a data/migration validation utility

README.md, buildfile, common/pom.xml, gutterball/pom.xml, pom.xml, project_conf/checks.xml, server/pom.xml, tasks/checkstyle.rake, tasks/dependency_check.rake
Uses the OWASP Dependency Checker project.
Run with `buildr dependency:check`
=> Build task to check for usage of libraries with vulnerabilities.

server/src/main/resources/db/changelog/20140408160212-add-pool-source-sub-table.xml, server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml, server/src/main/resources/db/changelog/20150401140006-add-pool-type-to-db.xml
Added a dummy precondition to fix an issue with older versions of liquibase which require at least one precondition present.
=> Updated preconditions to be compatible with Liquibase 2.x

server/spec/consumer_resource_activation_key_spec.rb
Ensures that multiple consumers can use the same key to register.
The key is auto attach and has all the pools in the group associated.
Test uses the consumers to exhaust the pools and then one more key
usage to ensure successful registration.
=> Activation key auto bind across pools

docker/README.mkd, docker/build_container.sh, docker/candlepin-oracle/build.sh, docker/rebuild.sh
- All container tags are now pushed, rather than just specific versions
- Updated default Docker registry
=> More Docker build script updates

server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/test/java/org/candlepin/model/ConsumerCuratorSearchTest.java
Assume SystemA is subscribed to SKUs "p1" and "p2".  SystemB is
subscribed to "p1" only.  In the previous implementation, a request to
POST /owners/my_org/consumers?sku=p1&sku=p2
would yield [SystemA, SystemB, SystemA] since SystemA has both p1 and
p2.
This patch changes that behavior so that the new result set would be
[SystemA].
See https://bugzilla.redhat.com/show_bug.cgi?id=1252145
=> Use a logical AND when using  pool-based searching criteria.

gutterball/src/main/java/org/candlepin/gutterball/eventhandler/EventHandler.java, gutterball/src/main/java/org/candlepin/gutterball/eventhandler/EventManager.java, server/src/main/java/org/candlepin/audit/Event.java, server/src/main/java/org/candlepin/audit/EventAdapterImpl.java, server/src/main/java/org/candlepin/audit/EventBuilder.java, server/src/main/java/org/candlepin/audit/EventFactory.java, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
Appends message with information that the expiration occurred when the
guest did not have a host mapping
=> Create new event for Entitlement Expiration

server/src/main/java/org/candlepin/audit/EventFilter.java, server/src/main/java/org/candlepin/audit/EventSinkImpl.java, server/src/main/java/org/candlepin/config/ConfigProperties.java, server/src/test/java/org/candlepin/audit/EventFilterTest.java, server/src/test/java/org/candlepin/audit/EventSinkImplTest.java
@mstead @awood This is the audit events filtering. See javadoc of the following: class EventFilter, ConfigProperties.AUDIT_FILTER*
=> Audit event messages filtering

server/spec/activation_key_spec.rb, server/spec/consumer_resource_content_spec.rb, server/src/main/java/org/candlepin/policy/js/override/OverrideRules.java, server/src/main/resources/rules/rules.js, server/src/test/java/org/candlepin/policy/js/override/OverrideRulesTests.java, server/src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
Affords Satellite users the ability to point to another content source for
a given repo.
=> Allow baseurl to be overridden in standalone

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- When refreshing products and content, the resolved owner will now
always be set
- Product resolution will now throw an exception if the product is
not resolved properly
- Improved warnings when multiple versions of the same product or
content are found on a single subscription
=> Updated CandlepinPoolManager to properly update owners during refresh

server/src/main/java/org/candlepin/model/Status.java
This adds the 'remove_by_pool_id' to the managerCapabilities string. This PR is required for a complete solution to BZ 1285004
=> 1285004: Adds remove_by_pool_id to manager_capabilities

server/spec/derived_product_spec.rb, server/spec/guestid_resource_spec.rb, server/spec/import_spec.rb
Fixing some hosted spec tests, probably more fixes to follow for other tests.
=> Fixed some hosted spec tests for 0.9.51

docker/candlepin-base/cp-test
Moved the artifact collection to the cleanup step to ensure it is always performed and added additional checks to ensure the cleanup isn't performed multiple times, nor that absent artifacts don't halt the collection process.
=> Updated artifact collection to ensure it is always performed

server/src/test/java/org/candlepin/resource/OwnerResourceTest.java, server/src/test/java/org/candlepin/test/TestUtil.java
Backporting @mstead  fix for unit test failures
=> Fixing broken tests due to expiry date

server/spec/candlepin_scenarios.rb, server/spec/import_spec.rb, server/spec/import_warning_spec.rb, server/src/main/java/org/candlepin/audit/EventBuilder.java, server/src/main/java/org/candlepin/audit/EventFactory.java, server/src/main/java/org/candlepin/audit/EventSink.java, server/src/main/java/org/candlepin/audit/EventSinkImpl.java, server/src/main/java/org/candlepin/audit/Eventful.java, server/src/main/java/org/candlepin/audit/NoopEventSinkImpl.java, server/src/main/java/org/candlepin/model/Consumer.java, server/src/main/java/org/candlepin/model/Entitlement.java, server/src/main/java/org/candlepin/model/GuestId.java, server/src/main/java/org/candlepin/model/ImportRecord.java, server/src/main/java/org/candlepin/model/Owner.java, server/src/main/java/org/candlepin/model/Pool.java, server/src/main/java/org/candlepin/model/Rules.java, server/src/main/java/org/candlepin/model/activationkeys/ActivationKey.java, server/src/main/java/org/candlepin/model/dto/Subscription.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/sync/Importer.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java, server/src/test/java/org/candlepin/sync/ImporterTest.java
* Return an ImportRecord upon import success.
* The status of the record marks if:
* There were no active subscriptions in the manifest
* There were one or more inactive subscriptions in the manifest
=> 1297047: Candlepin allows import of expired manifest

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Changes made to a stack derived pool will no longer cause null
pointer exceptions during manifest import or pool refresh
=> 1301812: Fixed an issue with event generation for stack derived pools (0.9.53)

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/PoolManager.java, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/main/java/org/candlepin/model/EntitlementCurator.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/model/ProductEntitlements.java, server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java, server/src/test/java/org/candlepin/test/DatabaseTestFixture.java, server/src/test/java/org/candlepin/test/TestUtil.java
Goal of this  change is to speed up Import Manifest in Standalone Mode
=> Implementation of revokeEntitlements(List)

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/PoolCurator.java
Defensive locking of pools during revocation of entitlements.
=> BZ1304417 Mass Pool lock

docker/candlepin-base/cp-test
Artifacts will now be collected explicitly for checkstyle, unit tests and spec tests.
=> Added additional artifact collection for checkstyle, unit tests and spec tests

docker/candlepin-base/cp-test, docker/candlepin-base/setup-devel-env.sh
- Fixed the bug introduced by piping various commands to tee which
would mask any errors in the original command
- The images are now built with checkstyle dependencies collected and
pull request branches pulled. This should reduce overall network
usage and log noise.
=> Fixed a bug that masked all errors and improved image configuration

server/spec/subscription_resource_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java
See javadoc comments and BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=1292282
https://bugzilla.redhat.com/show_bug.cgi?id=1292283
=> Bugfixes for: BZ1292283, BZ1292282

server/spec/consumer_resource_spec.rb, server/src/main/java/org/candlepin/resource/ConsumerResource.java
Adds the compliance type to outgoing pool json. It is displayed on
Subscription Manager CLI and GUI
=> 1302051: subscription type field for list --consumed

server/src/main/java/org/candlepin/audit/HornetqContextListener.java, server/src/main/java/org/candlepin/config/ConfigProperties.java
@awood @barnabycourt The HornetQ paging for 9.54
=> Forward port of HornetQ paging to 0.9.54

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/PoolManager.java, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/main/java/org/candlepin/model/EntitlementCurator.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/model/ProductEntitlements.java, server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java, server/src/test/java/org/candlepin/test/DatabaseTestFixture.java, server/src/test/java/org/candlepin/test/TestUtil.java
@barnabycourt  @awood This is the PR for forward port of batch revoke to 0.9.54
=> Forward port of Batch Revoke to 0.9.54

gutterball/bin/deploy, gutterball/erb/gutterball.conf.erb, profiles.yaml, server/bin/deploy, server/erb/candlepin.conf.erb
- Using the auto configuration with a custom database name will now
properly generate configuration with the specified DB name
=> Updated the auto configuration to respect a user-specified database name

server/client/ruby/candlepin_api.rb, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
This was requested by our community user.
=> Provide ability to search activation keys by name.

common/po/fr.po
Automatically fixed translations using buildr validate_translation:fix
=> Fix translations - un-escaped single quotes

server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/GuestIdResource.java, server/src/main/java/org/candlepin/resource/HypervisorResource.java, server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java, server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
This is the backport for the fix in #1124
=> 1311664: Ignore empty guest IDs and hypervisor IDs

server/src/main/java/org/candlepin/service/ProductServiceAdapter.java, server/src/main/java/org/candlepin/service/impl/DefaultProductServiceAdapter.java, server/src/test/java/org/candlepin/policy/EnforcerTest.java, server/src/test/java/org/candlepin/policy/PoolRulesTest.java, server/src/test/java/org/candlepin/policy/js/entitlement/EntitlementRulesTestFixture.java, server/src/test/java/org/candlepin/policy/js/entitlement/ManifestEntitlementRulesTest.java, server/src/test/java/org/candlepin/policy/js/entitlement/PreEntitlementRulesTest.java, server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java, server/src/test/java/org/candlepin/service/impl/DefaultProductServiceAdapterTest.java, server/src/test/java/org/candlepin/sync/ExporterTest.java
This PR is combination of updating the docs and pruning unused methods in 2.0.
=> Pruned unused methods and javadocs updates for ProductServiceAdapter (2.0)

common/src/main/java/org/candlepin/common/util/RpmVersionComparator.java, server/src/main/java/org/candlepin/auth/permissions/OwnerPermission.java, server/src/main/java/org/candlepin/auth/permissions/TypedPermission.java, server/src/main/java/org/candlepin/auth/permissions/UsernameConsumersPermission.java, server/src/main/java/org/candlepin/model/AbstractHibernateObject.java, server/src/main/java/org/candlepin/model/Environment.java, server/src/main/java/org/candlepin/model/Owner.java, server/src/main/java/org/candlepin/model/dto/PoolIdAndErrors.java, server/src/main/java/org/candlepin/model/dto/PoolIdAndQuantity.java, server/src/main/java/org/candlepin/policy/js/entitlement/AbstractEntitlementRules.java, server/src/main/java/org/candlepin/resource/EntitlementResource.java, server/src/main/java/org/candlepin/resource/dto/HypervisorCheckInResult.java, server/src/main/java/org/candlepin/resource/dto/HypervisorUpdateResult.java, server/src/main/java/org/candlepin/sync/SubscriptionReconciler.java
@crog This PR can be tacked onto #1152
=> Provide explicit serialVersionUIDs.

server/src/main/java/org/candlepin/model/JobCurator.java, server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java, server/src/test/java/org/candlepin/model/JobCuratorTest.java, server/src/test/java/org/candlepin/pinsetter/core/PinsetterKernelTest.java
@reviewer : please test the fix before you merge it in, I have not re-produced the issue. @Ceiu was able to help me verify on his setup that the principle of this fix works though, so I am confident.
=> Delete purged jobs from job tables in candlepin and qrtz

server/src/main/resources/db/changelog/20160412131122-add-unique-constraint-to-product-certificate-rows.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
One product should have one product certificate.
=> Add unique constraint to product certificate tables.

docker/candlepin-base/Dockerfile, docker/candlepin-base/cp-test, docker/candlepin-postgresql/Dockerfile
quoting cleanup based on shellcheck suggestions
=> Add RSPEC_FILTER option to cp-test

server/spec/ueber_cert_spec.rb, server/src/main/java/org/candlepin/model/ConsumerCurator.java
This fix is the same as the one that was backported to candlepin-0.9.49-HOTFIX in commit: 45b05945ceb63c541354ac8c036e460c50bb587e
=> 1327220: Limit IN queries to no more than 500 {hypervisor, guest}Ids

server/candlepin.spec.tmpl, server/conf/logrotate.conf
=> 1330246: Candlepin logrotate error on RHEL6.7

server/candlepin.spec.tmpl, server/conf/logrotate.conf
=> 1330245:  Candlepin logrotate error on RHEL6.7

server/candlepin.spec, server/conf/logrotate.conf
=> 1330244: Candlepin logrotate error on RHEL6.7

vagrant/candlepin.yml, vagrant/roles/candlepin-root/tasks/main.yml, vagrant/roles/candlepin-user/defaults/main.yml, vagrant/roles/candlepin-user/tasks/main.yml
I spruced up the candlepin ansible roles to make it more like QE's.  I have a pretty jacked up vagrant situation on my box, but it works for me,  could one of the devs try this on their vagrant environment?
=> updating candlepin ansible roles

server/bin/test_data.json
The value '0' can equal false. Should not use as a content id.
=> Changed the content set id to reduce confusion in testing

server/spec/pool_unlimited_master_spec.rb
Ensure that unlimited master pool with finite virt_limit means that each host entitlement spawns a pool with finite quantity.
=> 1335576: Ensure unlimited host dependent pool has finite virt-limit quantity

server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java, server/src/test/java/org/candlepin/model/ModifierTestDataGenerator.java
Functional tests for batch list modifying query.
=> Tests of Batch List Modifying

server/src/main/java/org/candlepin/config/ConfigProperties.java, server/src/main/java/org/candlepin/guice/CandlepinContextListener.java, server/src/main/java/org/candlepin/guice/CandlepinFilterModule.java, server/src/main/java/org/candlepin/guice/CandlepinModule.java
New configuration property candlepin.swagger.enabled that defaults to
true.
=> 1340500: Config for Swagger enable/disable

server/conf/logrotate.conf
This is the forward port for #1269
=> 1344469: logrotate permission denied error

server/src/main/java/org/candlepin/audit/EventAdapterImpl.java, server/src/main/java/org/candlepin/auth/OAuth.java, server/src/main/java/org/candlepin/resource/OwnerContentResource.java, server/src/main/java/org/candlepin/resource/OwnerProductResource.java
- The "product/content is locked" error message has been corrected to use
the correct index for the product ID placeholder.
=> 1348291: Corrected placeholder index for translated "locked" message

server/src/main/java/org/candlepin/model/Content.java, server/src/main/java/org/candlepin/model/Product.java, server/src/main/java/org/candlepin/model/ProductAttribute.java, server/src/main/java/org/candlepin/model/dto/CandlepinDTO.java, server/src/main/java/org/candlepin/model/dto/ContentData.java, server/src/main/java/org/candlepin/model/dto/ProductAttributeData.java, server/src/main/java/org/candlepin/model/dto/ProductContentData.java, server/src/main/java/org/candlepin/model/dto/ProductData.java, server/src/main/java/org/candlepin/util/Util.java, server/src/test/java/org/candlepin/model/dto/CandlepinDTOTest.java, server/src/test/java/org/candlepin/model/dto/ContentDataTest.java, server/src/test/java/org/candlepin/model/dto/ProductAttributeDataTest.java, server/src/test/java/org/candlepin/model/dto/ProductContentDataTest.java, server/src/test/java/org/candlepin/model/dto/ProductDataTest.java, server/src/test/java/org/candlepin/test/TestUtil.java
- Added utility constructors to ProductData and ContentData for creating
DTOs initialized with some values
=> Added utility constructors to some of the new DTOs

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
Dont trigger async compliance during batch revoke. the async job may even begin executing before the current job has commit-ed its transaction. in this case, the entitlement was not marked as dirty at fetch time ( because the consumer compliance job marks it so ) and we had an inconsistent state.
We cannot simply remove the job right now. the only remaining use is in the bind operation, where we need to lock the consumer if we use the sync implementation. The appropriate fix for that, coming soon-ish in a separate PR is to move compliance information to a separate table, *without* foreign key on the consumer.
=> Fix non deterministic test failure in modifier spec

server/src/main/java/org/candlepin/resource/JobResource.java
@nguyenfilip  please take a look and merge if you like it, im hoping I can mention this in demo tomorrow
=> Display list of jobs in error message for schedule job

buildfile, server/src/main/java/org/candlepin/jackson/DateSerializer.java, server/src/main/java/org/candlepin/policy/js/JsRunner.java
Fixup of #1307.
Removed useless dependency from candlepin common project in buildfile
which caused that pom.xml files after "buildr eclipse" were show as
modified in git.
=> Removed useless dependency from buildfile.

docker/candlepin-base/cp-test
- The cleanup at the end of cp-test no longer runs unless
necessary
- cp-test now fetches from FETCH_HEAD after cleaning the local
server directory
=> Fixed a couple bugs in cp-test

server/src/main/resources/db/changelog/20160819090519-delete-all-ueber-cert-data.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
To test, generate an ueber cert for an owner before upgrading candlepin to this version. Check out this branch and redeploy and there should be no trace of any ueber certs for any owner.
1) Check out and deploy the HEAD of candlepin-0.9.54-HOTFIX.
2) curl -k -u admin:admin -X POST https://localhost:8443/candlepin/admin/uebercert
3) Run the verification queries below. Each should result in a count of 1.
4) Check out this branch and deploy
5) Run the validation queries below. Each should result in a count of 0.
**Validation Queries**
```sql
SELECT (SELECT Count(*)
FROM   cp_subscription s
INNER JOIN cp_product p
ON s.product_id = p.id
LEFT OUTER JOIN cp_pool pool
ON pool.productid = p.id
WHERE  p.NAME LIKE '%_ueber_product')    AS UEBER_SUBS,
(SELECT Count(*)
FROM   cp_ent_certificate ec …
```
=> 1366798: Clean up all ueber cert data on DB upgrade

gutterball/src/main/java/org/candlepin/gutterball/receiver/EventReceiver.java, server/spec/one_sub_pool_per_stack_spec.rb, server/src/main/java/org/candlepin/guice/AMQPBusPubProvider.java
Backport of #1275, #1301 and also #1202.
=> 1357596: Candlepin should communicate with broker over "ANONYMOUS"

Gemfile.lock, buildfile, common/pom.xml, gutterball/pom.xml, gutterball/src/main/java/org/candlepin/gutterball/guice/ValidationListenerProvider.java, gutterball/src/main/resources/META-INF/persistence.xml, gutterball/src/test/java/org/candlepin/gutterball/junit/GutterballLiquibaseResource.java, server/pom.xml, server/src/main/java/org/candlepin/guice/ValidationListenerProvider.java, server/src/main/java/org/candlepin/model/CertificateSerialCurator.java, server/src/main/java/org/candlepin/model/JobCurator.java, server/src/main/java/org/candlepin/model/OwnerProductCurator.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/resources/META-INF/persistence.xml, server/src/test/java/org/candlepin/hibernate/EmptyStringInterceptorTest.java, server/src/test/java/org/candlepin/hibernate/EmptyStringUserTypeTest.java, server/src/test/java/org/candlepin/junit/CandlepinLiquibaseResource.java
This upgrade is needed to support EHCache. Reviewer please also verify this works with JDK 1.7 - I checked it, but just to be sure.
=> Upgrade Hibernate to 5.1.1

Gemfile.lock, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
In addition, the new list would be merged in either case, change or not.
=> Capability list change detection wrong

server/src/main/java/org/candlepin/resource/OwnerResource.java
Removal of stack trace logging on identical manifest
import.
=> 1334755: Stack Trace on Identical Manifest

server/src/main/java/org/candlepin/cache/CandlepinCacheRegions.java, server/src/main/java/org/candlepin/model/Content.java, server/src/main/java/org/candlepin/model/ContentCurator.java, server/src/main/java/org/candlepin/model/Product.java, server/src/main/java/org/candlepin/model/ProductAttribute.java, server/src/main/java/org/candlepin/model/Role.java, server/src/main/java/org/candlepin/model/RulesCurator.java, server/src/main/resources/META-INF/persistence.xml
@mstead This PR introduces 2LC for Content, Product and also short (5 seconds cache) for rules query
=> 2LC for Content and Product

server/client/ruby/hostedtest_api.rb, server/spec/client_v1_size_spec.rb, server/spec/entitlement_certificate_v3_spec.rb, server/spec/owner_product_resource_spec.rb, server/spec/refresh_pools_spec.rb, server/src/main/java/org/candlepin/controller/ProductManager.java, server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionResource.java
ProductManager.applyProductChanges should update value of locked column for
existing product, based on the incoming product.
If (incorrectly) the value of locked isn't updated, then Products will be
always marked dirty even though they have never been changed (possible performance
problem)
=> Product.locked is never updated

server/spec/environment_spec.rb, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/resource/EnvironmentResource.java, server/src/main/java/org/candlepin/util/RdbmsExceptionTranslator.java
=> 1357118:  Multiple and/or concurrent demotion of content should not cause exceptions.

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/main/java/org/candlepin/model/EntitlementCurator.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/sync/CdnImporter.java, server/src/main/java/org/candlepin/sync/ConsumerImporter.java, server/src/main/java/org/candlepin/sync/ConsumerTypeImporter.java, server/src/main/java/org/candlepin/sync/DistributorVersionImporter.java, server/src/main/java/org/candlepin/sync/EntitlementImporter.java, server/src/main/java/org/candlepin/sync/Importer.java, server/src/main/java/org/candlepin/sync/RulesImporter.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java, server/src/test/java/org/candlepin/sync/ImporterTest.java
I found some long methods and duplicate code so I did refactoring work around import manifest to make it more readable.
=> Manifest import: refactoring

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/EntitlementCurator.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java
For performance reasons scope 2 additional queries by owner.
=> Scope queries by owner

Vagrantfile
Use 2 space tabs consistently.
=> Fix spacing in Vagrantfile

server/client/ruby/candlepin_api.rb
This was IMO a less invasive change than having the deployment scripts
specify the cert to verify against.
This fixes developer deployment against newer ruby versions.
=> 1382307: Expose verify_ssl, default localhost to NONE

server/src/main/java/org/candlepin/audit/QpidQmf.java, server/src/main/java/org/candlepin/config/ConfigProperties.java, server/src/main/java/org/candlepin/guice/CandlepinContextListener.java
Candlepin will quickly fail at startup if the Qpid Broker is not running and healthy.
=> Startup Check

server/spec/candlepin_scenarios.rb, server/spec/owner_resource_spec.rb, server/spec/system_admin_spec.rb
Found useless parameter owner in method user_client_with_perms
=> Refactoring spec tests and spec utility

server/spec/virt_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java
The bug was caused by calling Arrays.asList(null) - which throws a nullpointer
exception.
=> 1390214: Internal Server Error During Guest Migration

server/spec/autobind_disabled_for_owner_spec.rb, server/spec/healing_spec.rb, server/src/main/java/org/candlepin/controller/Entitler.java, server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/HypervisorResource.java, server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Autobind is generally referred to as auto-attach.
Re-aligning client facing messages.
=> Updating autobind disabled strings (0.9.54)

server/spec/autobind_disabled_for_owner_spec.rb, server/spec/healing_spec.rb, server/spec/hypervisor_check_in_spec.rb, server/src/main/java/org/candlepin/controller/Entitler.java, server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/HypervisorResource.java, server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java, server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java
Autobind is generally referred to as auto-attach.
Re-aligning client facing messages.
=> Updating autobind disabled strings (2.0)

server/spec/consumer_resource_activation_key_spec.rb
Test to ensure that an activation key can utilize pools with differing service
levels to attach for a consumer
=> 1372467: Activation keys and service levels

server/src/main/java/org/candlepin/model/DetachedCandlepinQuery.java
- The DetachedCandlepinQuery object now properly/better restores Criteria
state after calls to the .getRowCount method
=> DetachedCandlepinQuery now better restores Criteria state

server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/resource/test/ConsumerResourceTest.java
Fixing typo in error message.
Previous message: Name of the consumer should be shorter than 255 characters.
Fixed message   : Name of the consumer should be shorter than 256 characters.
=> 1371009: clearer error message (fixed typo) for 0.9.23

docker/build_container.sh
docker tag no longer supports the -f flag, this is causing an error on the push part of this script, breaking the jenkins job.
=> docker tag no longer supports -f tag

server/bin/update-server-xml.py
The AprLifecycleListener attempts to load the Apache Portable Runtime
(APR).  The APR is a native library used to speed up certain operations.
In our case, loading the APR causes an issue because the APR requires
additional attributes in the Connector element (e.g. SSLCertificateFile)
since the APR uses OpenSSL and PEM files instead of Java and JKS files.
See https://tomcat.apache.org/tomcat-8.0-doc/apr.html
In Fedora, the tomcat-native package installs the APR and the tomcat
package pulls in tomcat-native as a suggested dependency.  Rather than
break developers every time they update Tomcat, the easier approach is
just to disable the AprLifecycleListener.
=> Modify server.xml to keep tomcat-native from biting developers.

server/client/ruby/candlepin_api.rb, server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/PoolManager.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/PoolResource.java, server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/model/PoolCuratorFilterTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java, server/src/test/java/org/candlepin/test/TestUtil.java
Flags for adding future pools to current pools list or returning
only future pools. Current is the activeon date used which
defaults to now.
=> 1414425: Future pool listing

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- The per-org products migration task now prints warnings when it
detects a pool or subscription that references a product that
does not exist
=> Added additional warnings to the per-org products migration task

server/src/main/resources/db/changelog/20170130144529-perorgproducts-phase-2.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
- Added a new Liquibase task to cleanup the now-unused tables and
columns left over from the per-org products migration
=> Added a new Liquibase task for cleaning up unused tables

server/client/ruby/candlepin_api.rb, server/spec/autobind_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java
To test, deploy master, checkout this branch and run:
buildr rspec:autobind_spec.rb:"succeeds"
the same test passes in this branch.
=> 1412113: autobind fails when binding 2 pools together with same stackid

server/src/main/resources/db/changelog/20170119162948-cleanup-uebercerts-round3.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
The combonation of customer work-arounds and the
concurrency issues while generating ueber certs
allow for Pools without its Products. The existing
cleanup queries miss this case.
The assumption that a Pool would never exist
without its corresponding Product was incorrect
in the cleanup queries.
This new changeset will use the Pool.productname
for the query comparisons so that they will not be
missed.
**Testing Details**
Some manual steps can be taken to set up the bad data in the candlepin DB for testing the fix. I also have a customer DB that I would like to get this tested against as well. PM me for details.
1. Deploy the latest 0.9.54 candlepin
2. Generate an ueber certificate for an Owner (in my case 'admin').
```bash
$ curl -k -u admin:admin -X POST …
```
=> 1418376: Clean up ueber cert data

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- Fixed an issue with the cp2 per-org products migration that would
cause it to generate prepared statements with too many parameters
if run against a deployment with a large enough number of products
or content
=> 1419193: Fixed an issue with bulk insert statements during migration

server/client/ruby/candlepin_api.rb, server/src/main/java/org/candlepin/resource/OwnerProductResource.java, server/src/test/java/org/candlepin/resource/OwnerProductResourceTest.java
- Added additional unit tests for verifying the behavior of locked
products
=> Added additional tests for testing product locking behavior

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Backported the retry logic for autobind requests from
Candlepin 2.x.
=> 1422126: Backported autobind retry logic from CP 2.x

server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/ContentCurator.java, server/src/main/java/org/candlepin/model/OwnerProductCurator.java, server/src/main/java/org/candlepin/model/Product.java
- Worked around an issue in ContentCurator where the getContentByProducts
method would always return an empty collection
=> Fixed an issue with ContentCurator.getContentByProducts not fetching data

server/bin/deploy, server/bin/import_test_data.rb, server/bin/test_migration.sh
- Added the new test_migration.sh script, which tests deploying
a given version of Candlepin (specified via gitref), then
migrates to another version without clearing the database
- Updated the deploy script to wait for Candlepin to respond rather
than a blind sleep
=> Added the test_migration script

server/spec/entitlement_resource_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/Refresher.java, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/Pool.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/resources/db/changelog/20170206114359-convert-quanity-consumed-exported-to-columns.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml, server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
Adds columns and migrates data on db update.
Programmatically increments and decrements pool
quantities based on entitling.
=> Convert calculated pool quantities to columns

common/src/main/java/org/candlepin/common/filter/LoggingFilter.java, server/client/ruby/candlepin_api.rb, server/spec/import_spec.rb, server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java, server/src/main/java/org/candlepin/pinsetter/tasks/EntitleByProductsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/ExportJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/ImportJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsForProductJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java, server/src/main/resources/db/changelog/20170220133446-add-correlation-id-to-job.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml, server/src/main/resources/logback.xml, server/src/test/java/org/candlepin/model/JobCuratorTest.java
Added to logging for specific REST session
Stored on async jobs spawned by REST call
=> Add Correlation ID to header for external tracking

server/src/main/java/org/candlepin/sync/ProductImporter.java
We hit this bug: 
https://vladmihalcea.com/2013/10/16/hibernate-facts-knowing-flush-operations-order-matters/
following are the logs after we force a flush, we can see the same record is deleted and then inserted again. Without the flush we would insert first:
2017-02-27 08:37:44,281 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] DEBUG org.hibernate.SQL - delete from cp_product_content where product_id=? and content_id=?
2017-02-27 08:37:44,281 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE org.hibernate.type.descriptor.sql.BasicBinder - binding parameter [1] as [VARCHAR] - 276
2017-02-27 08:37:44,281 [thread=http-bio-8443-exec-5] [req=2a4ec7d8-85e5-426e-bf15-f634eeac41f0, org=PSC] TRACE …
=> 1363701: duplicate key value violates unique constraint on product-content

server/bin/import_test_data.rb
Today, in hosted mode, we lose all the test data pools of an owner after a refresh operation.
This pull requests helps to keep test pools in hosted mode post refresh.
Note, if tomcat is restarted though, the next refresh will lose the pools of the owner.
to test:
in master: 
1. ./bin/deploy -gtaH
2. refresh owner admin
3. fetch pools of the owner, should be none.
in current branch , step 3 should return all pools.
=> use hostedtest resources in import test data script

docker/candlepin-mysql/setup-mysql.sh
- Updated the Docker container's MySQL configuration to match
the configuration IT uses for symbolic links and transaction
isolation
=> Updated the mysql config in the Docker containers to match IT

Gemfile.lock
Update for the new qpid-proton version in Centos
=> Update Qpid Proton Gem

server/spec/rules_import_spec.rb, server/src/main/java/org/candlepin/model/Rules.java, server/src/main/java/org/candlepin/model/RulesCurator.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/RulesResource.java
- Fixed an issue where the rules import spec tests weren't generating
a version higher than the current version in Candlepin
- Cleaned up some code surrounding rules management in Candlepin and
added additional debug output
=> Fixed an issue with the rules import spec tests

server/spec/hypervisor_check_in_spec.rb, server/src/main/java/org/candlepin/model/ConsumerCurator.java
Like #1510 and #1504 this PR is blocked on #1479. Rather I should say, the mysql tests will not pass for this branch until #1479 is merged.
=> 1428150: Do not deadlock when processing hypervisor check ins

server/spec/one_sub_pool_per_stack_spec.rb, server/spec/owner_resource_spec.rb
tackles 3 non deterministic failures 
to verify, deploy master and run those tests 10 times, they are bound to fail atleast once there, not so in my branch.
=> Fix non deterministic test failures

server/spec/autobind_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/Cdn.java, server/src/main/java/org/candlepin/model/Pool.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/model/ProductCurator.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/controller/CdnManagerTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/model/ProductCuratorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java, server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java, server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java, server/src/test/java/org/candlepin/resource/util/InstalledProductStatusCalculatorTest.java, server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Added bulk provided and derived provided product lookups to
PoolCurator
- CandlepinPoolManager now makes use of the bulk provided and
derived provided product lookups during various iterative
operations
=> Optimized how pool provided products are checked

server/spec/post_bind_bonus_pool_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/policy/js/entitlement/AbstractEntitlementRules.java, server/src/main/java/org/candlepin/policy/js/entitlement/Enforcer.java, server/src/test/java/org/candlepin/policy/js/entitlement/HostedVirtLimitEntitlementRulesTest.java, server/src/test/java/org/candlepin/policy/js/entitlement/ManifestEntitlementRulesTest.java, server/src/test/java/org/candlepin/policy/js/entitlement/PostEntitlementRulesTest.java, server/src/test/java/org/candlepin/test/EnforcerForTesting.java
Note: the spec test file has been simply copied from master, hope that makes the review easy.
=> 1444719: Update bonus pool quantity when master entitlement is updated

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/policy/js/entitlement/AbstractEntitlementRules.java, server/src/main/java/org/candlepin/policy/js/entitlement/Enforcer.java, server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/test/EnforcerForTesting.java
NOTE:
with this PR we will not have the flexibility of java script rules in update. hence requesting two reviewers on the PR, @awood  and @mstead
=> add or update entitlements mitosis

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/main/java/org/candlepin/model/OwnerCurator.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Several methods used for applying database/entity locks have been
generalized and refactored; extraneous methods have been removed
=> Consolidated and refactored the database locking methods (0.9.54)

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/ContentManager.java, server/src/main/java/org/candlepin/controller/ProductManager.java, server/src/main/java/org/candlepin/model/OwnerContentCurator.java, server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- Optimized the base query for pulling products and content by
their Red Hat ID
- Added additional debug output to the refresh operation
=> Optimized bulk product and content lookups (2.0)

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/ContentManager.java, server/src/main/java/org/candlepin/controller/ProductManager.java, server/src/main/java/org/candlepin/model/OwnerContentCurator.java, server/src/main/java/org/candlepin/model/OwnerProductCurator.java
- Optimized the base query for pulling products and content by
their Red Hat ID
- Added additional debug output to the refresh operation
=> Optimized bulk product and content lookups

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- The per-org products migration task will now fail if it detects
any unresolvable products, rather than continuing with a warning.
This should eliminate the situation where pools ended up with
null or absent product references post-migration.
=> The per-org products migration now fails on unresolvable products (2.0)

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- The per-org products migration task will now fail if it detects
any unresolvable products, rather than continuing with a warning.
This should eliminate the situation where pools ended up with
null or absent product references post-migration.
=> The per-org products migration now fails on unresolvable products

server/src/main/java/org/candlepin/model/Content.java, server/src/main/java/org/candlepin/model/ContentCurator.java, server/src/main/java/org/candlepin/model/Product.java, server/src/main/java/org/candlepin/model/ProductContent.java, server/src/main/java/org/candlepin/model/ProductContentKey.java, server/src/main/java/org/candlepin/model/ProductCurator.java, server/src/main/resources/db/changelog/20170220102027-add-id-column-for-productcontent.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml, server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java, server/src/test/java/org/candlepin/model/ModifierTestDataGenerator.java
- ProductContent is no longer an @Embeddable entity and is a full entity
- Updated product accordingly
=> Changed ProductContent to a full entity

server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml, tasks/liquibase.rake
- Updated the Liquibase buildr task to use a newer version of the
XML validator
- Added a valid checksum to the ueber cert cleanup task to avoid
issues with certain migrations
=> Fixed an issue with certain migration tasks (2.0)

vagrant/README.md
* NFS has to be enabled on firewall at host.
=> Added some notes about NFS and Vagrant.

server/bin/cmv, server/client/ruby/candlepin_api.rb
=> Updated CMV to store and verify activation keys (master)

server/bin/cmv, server/client/ruby/candlepin_api.rb
=> Updated CMV to store and verify activation keys (2.0)

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- Products which provide content used by an environment are
now migrated as part of the product migration step
- Content used by an environment that is not provided by
any product will be migrated during content migration
- Products specified by an activation key are now migrated
- Added additional data validation for activation key products
and environment content before migrating data
=> Per-org products migration now examines activation keys and environments

common/src/main/java/org/candlepin/common/config/PropertyConverter.java
Quick fix coded on a Friday afternoon (please double-check me :smile:). Happy to cherry-pick to other branches as well if wanted.
=> 1474698: Trim String values when converting to num

server/bin/cmv, server/bin/generate_consumers.rb
- The CMV tool now validates consumer entitlements for an org
- CMV no longer checks any field named "updated," as these are
universally problematic timestamp fields that are expected to change
during a migration anyway
- Added a utility script, generate_consumers.rb, for generating
consumers and consuming pools in a Candlepin deployment
=> [0.9.54] Added entitlement validation to CMV

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
- Products which provide content used by an environment are
now migrated as part of the product migration step
- Content used by an environment that is not provided by
any product will be migrated during content migration
- Products specified by an activation key are now migrated
- Added additional data validation for activation key products
and environment content before migrating data
=> Per-org products migration now examines activation keys and environments (master/2.1)

server/src/main/resources/rules/rules.js
Updates the rules version (as it had not been to account for recent rules changes).
=> Update rules to 5.26 (related: 1476897)

server/bin/qpid/configure-qpid.sh, server/spec/candlepin_scenarios.rb
- Corrected a few additional direct calls to systemctl to now check
for the presence of supervisorctl before attempting to use
systemctl directly
=> [M] Corrected additional calls to systemctl

server/src/test/java/org/candlepin/controller/ContentManagerTest.java, server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java
If this doesn't work, this PR should be Closed and the branch deleted.
=> Attempting to fix random test failure in DTO PR.

vagrant/README.md, vagrant/roles/candlepin-user/defaults/main.yml
* Run deploy script with -t option to import test data to database.
=> Update of Vagrant defaults

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
If a user has an activation key referencing a product that no longer
exists, we now just delete that reference rather that halting the entire
migration.
=> 1503179: Delete missing products from activation keys while upgrading.

server/src/main/java/org/candlepin/liquibase/PerOrgProductsMigrationTask.java
If a user has an activation key referencing a product that no longer
exists, we now just delete that reference rather that halting the entire
migration.
=> 1503176: Delete missing products from activation keys while upgrading.

server/src/main/java/org/candlepin/controller/Entitler.java, server/src/test/java/org/candlepin/controller/EntitlerTest.java
- Fixed an exception that could occur on some databases while cleaning up
entitlements for unmapped guest pools
=> [2.0] Fixed an exception while deleting unmapped guest entitlements

server/src/main/java/org/candlepin/controller/Entitler.java, server/src/test/java/org/candlepin/controller/EntitlerTest.java
- Fixed an exception that could occur on some databases while cleaning up
entitlements for unmapped guest pools
=> [2.1] Fixed an exception while deleting unmapped guest entitlements

server/src/main/java/org/candlepin/controller/Entitler.java, server/src/test/java/org/candlepin/controller/EntitlerTest.java
- Fixed an exception that could occur on some databases while cleaning up
entitlements for unmapped guest pools
=> [M] Fixed an exception while deleting unmapped guest entitlements

server/spec/entitlement_resource_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
https://bugzilla.redhat.com/show_bug.cgi?id=1508086
=> 1508086: Need to lock manifest consumer when binding

common/po/zanata.xml
Needed for recent zanata-cli to work
=> Fix zanata url

common/po/as.po, common/po/bn_IN.po, common/po/de.po, common/po/es.po, common/po/fr.po, common/po/gu.po, common/po/hi.po, common/po/it.po, common/po/ja.po, common/po/keys.pot, common/po/kn.po, common/po/ko.po, common/po/ml.po, common/po/mr.po, common/po/or.po, common/po/pa.po, common/po/pt_BR.po, common/po/ru.po, common/po/ta.po, common/po/te.po, common/po/zh_CN.po, common/po/zh_TW.po
* followed following process for updating to and from zanata:
1. buildr gettext:extract
2. buildr gettext:merge
3. zanata push
4. zanata pull
5. buildr validate_translation:fix
=> [M] Zanata translations

common/po/as.po, common/po/bn_IN.po, common/po/de.po, common/po/es.po, common/po/fr.po, common/po/gu.po, common/po/hi.po, common/po/it.po, common/po/ja.po, common/po/keys.pot, common/po/kn.po, common/po/ko.po, common/po/ml.po, common/po/mr.po, common/po/or.po, common/po/pa.po, common/po/pt_BR.po, common/po/ru.po, common/po/ta.po, common/po/te.po, common/po/zanata.xml, common/po/zh_CN.po, common/po/zh_TW.po
* changed zanata project version
* followed following process for updating to and from zanata:
1. buildr gettext:extract
2. buildr gettext:merge
3. zanata push
4. zanata pull
5. buildr validate_translation:fix
=> [2.1] Zanata translations

common/po/as.po, common/po/bn_IN.po, common/po/de.po, common/po/es.po, common/po/fr.po, common/po/gu.po, common/po/hi.po, common/po/it.po, common/po/ja.po, common/po/keys.pot, common/po/kn.po, common/po/ko.po, common/po/ml.po, common/po/mr.po, common/po/or.po, common/po/pa.po, common/po/pt_BR.po, common/po/ru.po, common/po/ta.po, common/po/te.po, common/po/zanata.xml, common/po/zh_CN.po, common/po/zh_TW.po, tasks/validate_translation.rake
* changed zanata project version
* added validate_translations rake task
* followed following process for updating to and from zanata:
1. buildr gettext:extract
2. buildr gettext:merge
3. zanata push
4. zanata pull
5. buildr validate_translation:fix
=> [9.54] zanata translations

common/po/zanata.xml
=> Update zanata URL

server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java, server/src/main/java/org/candlepin/sync/SubscriptionReconciler.java
- Fixed an NPE that could occur when calculating the effective
quantity while running pool rules or subscription reconciliation
=> [M] 1500837: Fixed an exception that could occur when updating pools

server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml
- Optimized the delete orphaned pools Liquibase task, using a separate
set of queries to work around inefficiencies and limitations with
how MySQL/MariaDB handles temporary tables and deletes
=> [M] Optimized the delete orphaned pools Liquibase task

server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml
- Optimized the delete orphaned pools Liquibase task, using a separate
set of queries to work around inefficiencies and limitations with
how MySQL/MariaDB handles temporary tables and deletes
=> [2.1] Optimized the delete orphaned pools Liquibase task

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/EventDTO.java, server/src/main/java/org/candlepin/dto/api/v1/EventTranslator.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/EventResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/PoolResource.java, server/src/main/java/org/candlepin/resource/SubscriptionResource.java, server/src/test/java/org/candlepin/dto/api/v1/EventDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/EventTranslatorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java, server/src/test/java/org/candlepin/resource/EventResourceTest.java, server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java, server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java, server/src/test/java/org/candlepin/resource/PoolResourceTest.java
- Implemented EventDTO/EventTranslator.
- Translated endpoints that use Events to the DTO framework.
- Translated endpoints that use SubscriptionsCertificate to the DTO framework (now using CertificateDTO).
=> [DTO] Implemented EventDTO

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/CdnDTO.java, server/src/main/java/org/candlepin/dto/api/v1/CdnTranslator.java, server/src/main/java/org/candlepin/resource/CdnResource.java, server/src/main/java/org/candlepin/resource/PoolResource.java, server/src/test/java/org/candlepin/dto/api/v1/ActivationKeyTranslatorTest.java, server/src/test/java/org/candlepin/dto/api/v1/CdnDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/CdnTranslatorTest.java
- Implemented CdnDTO/CdnTranslator.
- Translated endpoints that use Cdn to the DTO framework.
=> [DTO] Implemented CdnDTO/CdnTranslator

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/EventDTO.java, server/src/main/java/org/candlepin/dto/api/v1/JobStatusDTO.java, server/src/main/java/org/candlepin/dto/api/v1/JobStatusTranslator.java, server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java, server/src/main/java/org/candlepin/resource/JobResource.java, server/src/main/java/org/candlepin/resteasy/filter/PinsetterAsyncFilter.java, server/src/test/java/org/candlepin/dto/api/v1/JobStatusDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/JobStatusTranslatorTest.java, server/src/test/java/org/candlepin/pinsetter/core/model/JobStatusTest.java, server/src/test/java/org/candlepin/resource/JobResourceTest.java, server/src/test/java/org/candlepin/resteasy/filter/PinsetterAsyncFilterTest.java
- Moved JobStatus endpoints (JobResource, PinsetterAsyncFilter) to the DTO framework.
- Added toString method in EventDTO.java
=> [DTO] Implemented JobStatusDTO/JobStatusTranslator

server/src/main/resources/db/changelog/20170206114359-convert-quanity-consumed-exported-to-columns.xml, server/src/main/resources/db/changelog/20170227140343-convert-consumer-entitlement-count-to-column.xml
Performance tests of master branch can pass step called: "Update liquibase checksum" using this branch (PR):
https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/candlepin/job/CandlepinPerformance/122/console
and it is falling with master branch:
https://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/candlepin/job/CandlepinPerformance/121/console
=> Added preConditions into two liquibase files to fix perf tests.

buildfile, common/pom.xml, server/bin/data_generator.rb, server/bin/import_test_data.rb, server/client/ruby/candlepin_api.rb, server/client/ruby/hostedtest_api.rb, server/pom.xml, server/spec/multi_org_spec.rb, server/spec/spec_helper.rb, server/spec/virt_spec.rb, server/src/main/java/org/candlepin/audit/EventFactory.java, server/src/main/java/org/candlepin/bind/BindContext.java, server/src/main/java/org/candlepin/bind/PreEntitlementRulesCheckOp.java, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/Entitler.java, server/src/main/java/org/candlepin/jackson/PoolSerializer.java, server/src/main/java/org/candlepin/model/AbstractHibernateObject.java, server/src/main/java/org/candlepin/model/Pool.java, server/src/main/java/org/candlepin/model/SourceSubscription.java, server/src/main/java/org/candlepin/policy/js/RulesObjectMapper.java, server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java, server/src/main/java/org/candlepin/resource/EntitlementResource.java, server/src/main/java/org/candlepin/resteasy/JsonProvider.java, server/src/main/java/org/candlepin/sync/SyncUtils.java, server/src/test/java/org/candlepin/policy/js/RulesObjectMapperTest.java, server/src/test/java/org/candlepin/sync/ConsumerExporterTest.java
- Updated the version of Jackson to 2.9.4
- Updated a couple uses of XmlElement to use JsonIgnore instead
- Added additional testing output for a couple of JSON tests
- SourceSubscription is no longer processed from clients
=> [M] Updated Jackson version to 2.9.4

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/rules/v1/PoolDTO.java, server/src/main/java/org/candlepin/dto/rules/v1/PoolTranslator.java, server/src/main/java/org/candlepin/policy/js/activationkey/ActivationKeyRules.java, server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java, server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java, server/src/main/java/org/candlepin/policy/js/quantity/QuantityRules.java, server/src/test/java/org/candlepin/dto/api/v1/PoolTranslatorTest.java, server/src/test/java/org/candlepin/dto/rules/v1/PoolDTOTest.java, server/src/test/java/org/candlepin/dto/rules/v1/PoolTranslatorTest.java, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java, server/src/test/java/org/candlepin/policy/js/activationkey/ActivationKeyRulesTest.java, server/src/test/java/org/candlepin/policy/js/entitlement/EntitlementRulesTestFixture.java, server/src/test/java/org/candlepin/policy/js/quantity/QuantityRulesTest.java
- Replaced the Pool model entity with PoolDTO throughout the Rules framework input.
=> [DTO] Implemented the PoolDTO API for the Rules framework.

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java, server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java, server/src/main/java/org/candlepin/policy/js/pool/PoolRules.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java
- Fixed an issue that prevented custom pools from being shared
properly
- Fixed an issue that prevented custom pools from being updated
- Fixed an issue that prevented entitlements for custom pools from
being regenerated after the pool was updated
- Fixed an issue that prevented host-restricted pools from being
created for pools that did not have a source subscription
- Removed an extraneous .create method from PoolCurator
=> [M] Fixed several issues surrounding custom pools

server/spec/virt_spec.rb
Added 3 seconds sleep on yet another spec test failure due to mysql time limitation
=> Fixed non deterministic test failure

server/src/main/java/org/candlepin/dto/ModelTranslator.java, server/src/main/java/org/candlepin/dto/SimpleModelTranslator.java, server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/rules/v1/EntitlementDTO.java, server/src/main/java/org/candlepin/dto/rules/v1/EntitlementTranslator.java, server/src/main/java/org/candlepin/policy/js/JsRunner.java, server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java, server/src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java, server/src/main/java/org/candlepin/policy/js/quantity/QuantityRules.java, server/src/test/java/org/candlepin/dto/rules/v1/EntitlementDTOTest.java, server/src/test/java/org/candlepin/dto/rules/v1/EntitlementTranslatorTest.java, server/src/test/java/org/candlepin/policy/EnforcerTest.java
- Added the new EntitlementDTO and EntitlementTranslator for processing
object translation for the JS rules
- Added unit tests for the afore mentioned classes
- Added a new translator method, .getStreamMapper to fetch a mapping
function to be used with the Java 8 streaming API to perform bulk,
lazy object translation
- Updated several rules executors to use the new EntitlementDTO
object and the streaming API for translating objects
=> [M] Added the EntitlementDTO for the JavaScript rules

server/mead.chain
=> [M] Add Java 8 to mead packages argument

server/bin/request_scanner.rb
- Added the showall option, to display info for every processed
request
- Added the idsonly option for displaying only the request IDs for
processed requests
- Added checks and reporting for failed requests, where failed is
a request returning a response code outside the 200 range
- Added the --uri and --method options for filtering requests to
those matching the method and/or URI filters specified
=> [M] Added several improvements to the request scanner

common/po/de.po, common/po/es.po, common/po/fr.po, common/po/it.po, common/po/ja.po, common/po/ko.po, common/po/pt_BR.po, common/po/ru.po, common/po/zh_CN.po, common/po/zh_TW.po
Fixed in zanata instance, just used `zanata-cli pull` followed by `buildr gettext:merge`.
=> [2.1] Fix quoting issues in translations

server/src/main/java/org/candlepin/audit/EventFactory.java, server/src/test/java/org/candlepin/audit/EventFactoryTest.java
Katello only uses name and message. See https://github.com/Katello/katello/blob/8bc1ef327073f03149b4dd29e0284b65c4b5626a/app/services/katello/candlepin/consumer.rb#L125
=> Add reasons back to compliance.created events

common/src/main/java/org/candlepin/common/resteasy/filter/LinkHeaderResponseFilter.java, server/client/ruby/candlepin_api.rb, server/spec/owner_resource_spec.rb
back port of https://github.com/candlepin/candlepin/pull/1943
=> 1560054: Add total count of records as a header when paging is used. [2.2]

server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- The listPools end point now supports filtering on pool IDs
- listPools now supports multiple matches filters
=> [M] Added pool ID filtering functionality to OwnerPoolResource.listPools

server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- The listPools end point now supports filtering on pool IDs
- listPools now supports multiple matches filters
=> [2.2] Added pool ID filtering functionality to OwnerPoolResource.listPools

server/src/main/java/org/candlepin/dto/api/v1/BrandingDTO.java, server/src/main/java/org/candlepin/dto/api/v1/ConsumerTypeDTO.java, server/src/main/java/org/candlepin/dto/api/v1/ContentDTO.java, server/src/main/java/org/candlepin/dto/api/v1/EnvironmentDTO.java, server/src/main/java/org/candlepin/dto/api/v1/EventDTO.java, server/src/main/java/org/candlepin/dto/api/v1/GuestIdDTO.java, server/src/main/java/org/candlepin/dto/api/v1/OwnerDTO.java, server/src/main/java/org/candlepin/dto/api/v1/PoolQuantityDTO.java, server/src/main/java/org/candlepin/dto/api/v1/ProductDTO.java, server/src/main/java/org/candlepin/dto/manifest/v1/BrandingDTO.java, server/src/main/java/org/candlepin/dto/manifest/v1/ContentDTO.java, server/src/main/java/org/candlepin/dto/manifest/v1/EntitlementDTO.java, server/src/main/java/org/candlepin/dto/manifest/v1/OwnerDTO.java, server/src/main/java/org/candlepin/dto/manifest/v1/ProductDTO.java, server/src/main/java/org/candlepin/pinsetter/tasks/UniqueByEntityJob.java, server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- Removed all extra constructors from the DTOs aside from the default
and copy constructors
=> [M] 1561737: Removed extraenous DTO constructors

server/src/main/java/org/candlepin/dto/api/v1/UserDTO.java, server/src/main/java/org/candlepin/dto/api/v1/UserTranslator.java, server/src/test/java/org/candlepin/dto/api/v1/UserDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/UserTranslatorTest.java
- Added the new UserDTO
- Added the UserTranslator for translating User entities to UserDTOs
=> [M] Added the new UserDTO for the API v1 DTO package

server/bin/qpid_watch.py
E.g. bin/qpid_watch.py -c bin/qpid/keys/qpid_ca.crt -k
bin/qpid/keys/qpid_ca.key -s allmsg --drain
=> Add --drain option to qpid_watch to empty clogged queues.

server/src/main/java/org/candlepin/controller/ManifestManager.java, server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java, server/src/main/java/org/candlepin/pinsetter/tasks/EntitleByProductsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/ExportJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/ImportJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/RegenEnvEntitlementCertsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/controller/ManifestManagerTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/BaseJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTaskTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/ExportJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/ImportRecordJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/JobCleanerTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/SweepBarJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Jobs run within the context of a specific owner now respect and use
owner/org log levels
=> [M] 1517978: Jobs now respect owner-specific logging level where appropriate

server/src/main/java/org/candlepin/dto/api/v1/PermissionBlueprintDTO.java, server/src/main/java/org/candlepin/dto/api/v1/PermissionBlueprintTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/RoleDTO.java, server/src/main/java/org/candlepin/dto/api/v1/RoleTranslator.java, server/src/test/java/org/candlepin/dto/api/v1/PermissionBlueprintDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/PermissionBlueprintTranslatorTest.java, server/src/test/java/org/candlepin/dto/api/v1/RoleDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/RoleTranslatorTest.java
This is just for implementation the new DTOs; application is a separate task
=> [M] Added the RoleDTO and PermissionBlueprintDTO

server/src/main/java/org/candlepin/audit/EventSinkImpl.java, server/src/main/java/org/candlepin/hibernate/EmptyStringInterceptor.java, server/src/main/java/org/candlepin/pinsetter/core/PinsetterKernel.java, server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java, server/src/main/java/org/candlepin/pinsetter/tasks/CancelJobJob.java
Backport to 2.1 from https://github.com/candlepin/candlepin/pull/1958
=> 1566217: Downgrade the logging when no jobs are cancelled

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/DeletedConsumerDTO.java, server/src/main/java/org/candlepin/dto/api/v1/DeletedConsumerTranslator.java, server/src/main/java/org/candlepin/resource/DeletedConsumerResource.java, server/src/test/java/org/candlepin/dto/api/v1/DeletedConsumerDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/DeletedConsumerTranslatorTest.java
- DeletedConsumerResource now uses DeletedConsumerDTO
=> Implemented DeletedConsumerDTO

server/spec/filter_response_spec.rb, server/src/main/java/org/candlepin/dto/CandlepinDTO.java
- Added the missing @JsonFilter annotation to the CandlepinDTO
class. This will re-enable the include/exclude filtering on DTOs
=> [M] 1581873: Added missing JsonFilter annotation to the DTOs

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/ImportRecordDTO.java, server/src/main/java/org/candlepin/dto/api/v1/ImportRecordTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/ImportUpstreamConsumerDTO.java, server/src/main/java/org/candlepin/dto/api/v1/ImportUpstreamConsumerTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/OwnerDTO.java, server/src/main/java/org/candlepin/model/ImportRecord.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/dto/api/v1/ImportRecordDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/ImportRecordTranslatorTest.java, server/src/test/java/org/candlepin/dto/api/v1/ImportUpstreamConsumerDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/ImportUpstreamConsumerTranslatorTest.java, server/src/test/java/org/candlepin/dto/api/v1/PoolQuantityTranslatorTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Added the new ImportRecordDTO and ImportUpstreamConsumerDTO
- Updated OwnerResource to use the ImportRecordDTO where appropriate
=> [M] Added the ImportRecordDTO and ImportUpstreamConsumerDTO

server/src/main/resources/db/changelog/20130425102131-distributor-capabilities.xml, server/src/main/resources/db/changelog/20130501152202-add-content-arch.xml, server/src/main/resources/db/changelog/20130722140547-add-cdn-table.xml, server/src/main/resources/db/changelog/20130912153356-create-import-upstream-consumer.xml, server/src/main/resources/db/changelog/20131002150608-consumer-content-override.xml, server/src/main/resources/db/changelog/20140210083318-add-hypervisorid.xml, server/src/main/resources/db/changelog/20140306150357-constrain-one-subpool-per-stack.xml, server/src/main/resources/db/changelog/20140313155734-create-branding.xml, server/src/main/resources/db/changelog/20140317115036-index-facts-consumerid.xml, server/src/main/resources/db/changelog/20140408160212-add-pool-source-sub-table.xml, server/src/main/resources/db/changelog/20150123105016-add-consumer-checkin-table.xml, server/src/main/resources/db/changelog/20150210094558-perorgproducts-phase-1.xml, server/src/main/resources/db/changelog/20150211111319-add-last-guest-update-table.xml, server/src/main/resources/db/changelog/20150316122833-add-entitlement-end-date-override.xml, server/src/main/resources/db/changelog/20150820140403-revert-to-lastcheckin-column.xml, server/src/main/resources/db/changelog/20160419092221-add-db-file-storage.xml, server/src/main/resources/db/changelog/20161013145834-add-content-access-cert-column-to-consumer.xml, server/src/main/resources/db/changelog/20161025103454-cleanup-ueber-certs-round2.xml, server/src/main/resources/db/changelog/20161109145238-add-owner-environment-content-access.xml, server/src/main/resources/db/changelog/20170125112728-cleanup-uebercerts-round3-2-0.xml, server/src/main/resources/db/changelog/20170202093945-add-ueber-cert-to-owner.xml, server/src/main/resources/db/changelog/20170206114359-convert-quanity-consumed-exported-to-columns.xml, server/src/main/resources/db/changelog/20170220102027-add-id-column-for-productcontent.xml, server/src/main/resources/db/changelog/20170224113816-add-productshare-table.xml, server/src/main/resources/db/changelog/20170227140343-convert-consumer-entitlement-count-to-column.xml, server/src/main/resources/db/changelog/20170301083925-update-revoked-cert-serial-data.xml, server/src/main/resources/db/changelog/20170718095058-purge-orphaned-pools.xml, server/src/main/resources/db/changelog/20171020150559-add-index-to-cp-consumer-content-tags.xml
Essentially a backport of #2010 to 2.3.x. See that PR for context, etc.
=> [2.3] 1576868: Update liquibase checksums

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/AbstractCertificateDTO.java, server/src/main/java/org/candlepin/dto/api/v1/AbstractCertificateTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/CertificateDTO.java, server/src/main/java/org/candlepin/dto/api/v1/UeberCertificateDTO.java, server/src/main/java/org/candlepin/dto/api/v1/UeberCertificateTranslator.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/dto/api/v1/UeberCertificateDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/UeberCertificateTranslatorTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java, server/src/test/java/org/candlepin/util/X509CRLStreamWriterTest.java
- Added the UeberCertificateDTO and UeberCertificateTranslator
- Split the CertificateDTO and translator into AbstractCertificateDTO
and AbstractCertificateTranslator to work around a limitation with
generics, overrides and Java's polymorphism
- Updated OwnerResource to use the new UeberCertificateDTOs in place
of the UeberCertificate entity
=> [M] Added the UeberCertificateDTO and translator

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/PoolManager.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/main/java/org/candlepin/resource/PoolResource.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Also delete pointless override of find method in PoolCurator.
=> [2.4] 1608426: API call to get list of consumer UUIDs entitled from a pool [ENT-740]

server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
Because we are no longer ignoring unknown properties
in the ConsumerDTO via annotations, async checkins will
fail due to additional properties sent by virt-who.
This PR creates a custom ObjectMapper in the update
job so that it can be customized to ignore unknown
properties when processing the JSON.
###Testing
Check out and deploy master. Then run:
```bash
curl -X POST -k -u admin:admin -d '{"hypervisors": [{"hypervisorId": {"hypervisorId": "fe16edca-cd38-4f98-bb8f-e322d9718dad"}, "guestIds": [{"guestId": "b9cedf43-6554-4ed9-9faf-97fec58bb016", "state": 5}]}]}' -H "Content-Type: text/plain" https://localhost:8443/candlepin/hypervisors/admin
```
The job should fail.
Check out this branch and deploy. Then run the same command and it should pass.
=> Ignore unknown JSON properties in checkin data

server/src/main/java/org/candlepin/audit/EventSinkImpl.java
- EventSink now closes its sessions after performing either a
commit or rollback to help avoid leaving dangling sessions
around indefinitely
- Minor code rearrangements and adjustments to align/standardize
operation order, style and flow
=> [M] ActiveMQ sessions are now closed after a commit or rollback (ENT-880)

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Fixed an issue where consumer instances could become desync'd
during CPM.deletePools while recalculating compliance status
for consumers in some cases, leading to an EntityExistsException
=> [2.4] 1643582: Fixed an issue with object desync during pool cleanup (ENT-939)

server/src/main/java/org/candlepin/hibernate/EmptyStringInterceptor.java, server/src/test/java/org/candlepin/model/ConsumerTest.java
- Added additional nullability tests for two syspurpose fields
=> [M] Added additional tests for syspurpose fields

server/spec/autobind_disabled_for_owner_spec.rb, server/spec/content_access_spec.rb, server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java, server/src/main/java/org/candlepin/controller/Entitler.java, server/src/main/java/org/candlepin/model/Owner.java, server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/HypervisorResource.java, server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java, server/src/main/java/org/candlepin/service/impl/DefaultContentAccessCertServiceAdapter.java
…tach for org
Add detail to the exception message to indicate content access
Consolidate content access enabled check in owner
=> 1591383: When content access mode is org_environment, disable auto-at… [ENT-814]

server/spec/hypervisor_check_in_spec.rb, server/src/main/java/org/candlepin/resource/util/GuestMigration.java
Fact or hypervisor id change without guest change would lead to migration exception.
=> [2.4] 1651710: Unneeded guest migration call leads to exception

README.md, buildSrc/src/main/groovy/Gettext.groovy, common/build.gradle
Also, mask generated source files form checkstyle
=> Add ability to run msgmerge via gradle & update the readme.

server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java
- Now the output of GET /consumers/{consumer_uuid}/compliance will have the
owner field of compliant products' entitlements' pools populated.
=> 1588097: Expose owner of ComplianceStatusDTO's pools [ENT-783]

server/spec/hypervisor_check_in_spec.rb, server/src/main/java/org/candlepin/resource/util/GuestMigration.java
Fact or hypervisor id change without guest change would lead to migration exception.
=> [2.3] 1651713: Unneeded guest migration call leads to exception

server/bin/test_data.json
***This needs to be verified by QE before it gets merged. Marking as IN PROGESS until it has been verified.***
Notes:
* Marketing product names reflect the SP attributes as follows:
S: Service Level
U: Usage
R: Roles
A: Addons
=> Added test data to support system purpose functionality

server/bin/test_data.json
Added sockets to sp-server-layered-prod to allow QE
to work around the sockets attibute auto-attach bug
for system purpose (BZ 1655703).
=> Added sockets to SP test data

docker/candlepin-base/cp-test, docker/candlepin-base/setup-db.sh, docker/candlepin-base/setup-devel-env.sh
Trying to get the containers to build more reliably.  Work in progress, adding fixes as I find them...
- rvm needs an extra gpg key to install properly
=> fixing container builds

server/src/main/java/org/candlepin/async/JobBuilder.java, server/src/main/java/org/candlepin/async/JobDataMap.java, server/src/main/java/org/candlepin/async/JobExecutionContext.java, server/src/main/java/org/candlepin/async/JobExecutionException.java, server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/model/AsyncJobStatus.java, server/src/main/resources/db/changelog/20181121151738-add-async-job-tables.xml
- Updated JobManager to use the new JobBuilder in place of the Quartz
JobDetail class
=> [F] Added the JobBuilder, JobExecutionContext and CandlepinAsyncJob classes (ENT-1001)

server/spec/refresh_pools_spec.rb
Added some additional spec tests in an attempt to make a reproducer for a reported issue. Didn't end up catching said issue, but the tests themselves still have some value.
=> [M] Added additional spec tests for pool refresh scenarios

server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/JobMessage.java, server/src/main/java/org/candlepin/async/impl/ActiveMQSessionFactory.java, server/src/main/java/org/candlepin/async/impl/ArtemisJobMessageDispatcher.java, server/src/main/java/org/candlepin/guice/CandlepinModule.java, server/src/main/java/org/candlepin/model/AsyncJobStatus.java, server/src/main/resources/broker.xml
Found/fixed a couple of message sending issues while working on the message receiving bits.
=> [F] Async Jobs: Fixed a couple issues with job message sending code 

server/spec/autobind_spec.rb, server/src/main/resources/rules/rules.js
Also corrects logging compatibility issue with rules in Candlepin 2.1
=> 1677338: An existing entitlement with exempt sla will block other auto attaches. [ENT-1158]

server/spec/autobind_spec.rb, server/src/main/resources/rules/rules.js
Also corrects logging compatibility issue with rules in Candlepin 2.1
=> 1677340: An existing entitlement with exempt sla will block other auto attaches. [ENT-1158]

server/spec/autobind_spec.rb, server/src/main/resources/rules/rules.js, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Now, during auto-attach, stackable pools that provide either
identical or unsatisfactory roles & addons will be removed from
the stack (assuming they also dont provide necessery products).
=> [2.3] 1684508: Remove redundant role & addon pools from stacks; ENT-1199

server/spec/autobind_spec.rb, server/src/main/resources/rules/rules.js, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Now, during auto-attach, stackable pools that provide either
identical or unsatisfactory roles & addons will be removed from
the stack (assuming they also dont provide necessery products).
=> [M] 1683169: Remove redundant role & addon pools from stacks; ENT-1199

server/code/setup/cpdb, server/code/setup/cpsetup
These are the easiest pieces that I could find to change. Some help/guidance with setting up how test these would be much appreciated.
=> Make cpdb and cpsetup python3 compatible

server/src/main/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptor.java, server/src/test/java/org/candlepin/resteasy/filter/CandlepinQueryInterceptorTest.java
- Wrap session with a try-catch to prevent leaking the session when exception occurs
- Extract paging and output streamer to their own method to clarify the intent of postProcess method
=> Close session when exception occurs[ENT-509]

server/bin/cp_connectors.py, server/bin/org_migrator.py
- It is no longer require to specify the account on import
- Removed an extraneous entry in the help info
- Added some explicit conversion for juggling mysql and
postgresql exports
- Reworked the binary decoder mechanism to be more generic
- Added support for fetching column types as strings
- Exports will now include column types for each table
- The export operation will no longer attempt to run if the
org ID resolution fails
- Added the --list operation to list orgs in a given DB
=> [M] Made some improvements to the org_migrator utility

server/src/main/resources/db/changelog/20190401093722-add-content-override-index.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
- Added an index on the key_id column in the table cp_content_override
to reduce query time when fetching activation key details
=> [M] 1683733: Added index on column key_id in cp_content_override

server/src/main/resources/rules/rules.js, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Now, when all pools get removed from a stack group
during autoattach, no TypeError will occur.
- Added method that returns identifier type & value
for stack groups in the rules, to be used for logging.
=> [M] 1695619: Fix rules TypeError; ENT-1243

server/src/main/resources/rules/rules.js, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
- Now, when all pools get removed from a stack group
during autoattach, no TypeError will occur.
- Added method that returns identifier type & value
for stack groups in the rules, to be used for logging.
=> [2.3] 1696690: Fix rules TypeError; ENT-1243

server/src/main/java/org/candlepin/controller/ManifestManager.java, server/src/main/java/org/candlepin/pinsetter/core/model/JobStatus.java, server/src/main/java/org/candlepin/pinsetter/tasks/EntitleByProductsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/EntitlerJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/ExportJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/ImportJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/KingpinJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/RefreshPoolsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/RegenEnvEntitlementCertsJob.java, server/src/main/java/org/candlepin/pinsetter/tasks/UndoImportsJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/controller/ManifestManagerTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/BaseJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/CertificateRevocationListTaskTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/EntitleByProductsJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/EntitlerJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/ExportJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/ImportRecordJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/JobCleanerTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/SweepBarJobTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/UndoImportsJobTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Jobs run within the context of a specific owner now respect and use
owner/org log levels
=> [2.3] Jobs now respect owner-specific logging level where appropriate

server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/tasks/ExportJob.java, server/src/main/java/org/candlepin/model/AsyncJobStatus.java, server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- Migrate ExportJob and its test to the new Artemis framework
=> Port ExportJob To The New Messaging Framework[ENT-849]

server/src/main/java/org/candlepin/async/JobBuilder.java, server/src/main/java/org/candlepin/async/JobConstraint.java, server/src/main/java/org/candlepin/async/JobConstraints.java, server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/impl/UniqueByArgConstraint.java, server/src/main/java/org/candlepin/model/AsyncJobStatus.java, server/src/main/java/org/candlepin/model/AsyncJobStatusCurator.java, server/src/test/java/org/candlepin/async/JobManagerTest.java, server/src/test/java/org/candlepin/async/impl/UniqueByArgConstraintTest.java, server/src/test/java/org/candlepin/model/AsyncJobStatusCuratorTest.java, server/src/test/java/org/candlepin/test/DatabaseTestFixture.java
- Added the UniqueByArg job queuing constraint and updated the
JobManager and JobBuilder to specify and respect these
constraints
- Added additional queries to the AsyncJobStatusCurator
=> [F] Added job constraints and the UniqueByArg constraint (ENT-844)

server/src/main/java/org/candlepin/async/tasks/ExportJob.java, server/src/test/java/org/candlepin/async/tasks/ExportJobTest.java
- Added the UniqueByArgument constraint to ExportJob, preventing it
from being queued if another is already active for the same
consumer
- Changed a few job arguments to metadata or explicit job
configuration as appropriate
=> [F] Added the UniqueByArgument constraint to the async ExportJob (ENT-1265)

server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/api/v1/AsyncJobStatusDTO.java, server/src/main/java/org/candlepin/dto/api/v1/AsyncJobStatusTranslator.java, server/src/main/java/org/candlepin/model/AsyncJobStatus.java, server/src/test/java/org/candlepin/dto/api/v1/AsyncJobStatusDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/AsyncJobStatusTranslatorTest.java
- Added the AsyncJobStatusDTO and AsyncJobStatusTranslator
- Updated StandardTranslator accordingly
=> [F] Added the AsyncJobStatusDTO and associated translator (ENT-1321)

server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java
String change needed for the message- Error subscribing: Owner autobind disabled
=> 1418996: Need string change for the message Error subscribing: Owner autobind disabled (ENT 1340)

server/spec/system_purpose_compliance_spec.rb, server/src/main/java/org/candlepin/pinsetter/tasks/ActiveEntitlementJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Added missing @Transactional
- UpdateConsumer endpoint now updates consumer's system purpose status
=> 1697518: Syspurpose status does not reflect system purpose matching status

docker/candlepin-base/cp-test
The docker images will need to be rebuilt after this is completed.
=> Run checkstyle on the test classes as well as the production files.

server/spec/system_purpose_compliance_spec.rb, server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1673662
* John requested some messages and it's IMHO reasonable
* PR created for subman (for testing):
https://github.com/candlepin/subscription-manager/pull/2106
=> 1673662: Better reason messages for Mismatched syspurpose status; ENT-1247

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/model/PoolCurator.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java
Added an additional endpoint GET /owners/{owner_key}/pools_ordered_by_product along with Junit tests.
=> 1600588: [RFE] Add sorting by product to GET /owners/{owner_key}/pools  (ENT-745)

server/src/main/java/org/candlepin/guice/CandlepinModule.java, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java, server/src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java, server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java
- Split transaction into a series of bulk operations per 10 items
=> ENT-1314: Modify the locking and transaction size for the hypervisor report

server/spec/consumer_resource_spec.rb, server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Add check to prevend updating hypervisor id to one already in use
=> 1502193: Periodic mysql exceptions when updating consumers in production

server/client/ruby/candlepin_api.rb, server/spec/consumer_resource_activation_key_spec.rb, server/spec/consumer_resource_spec.rb, server/src/main/java/org/candlepin/dto/api/v1/ConsumerDTO.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java
- Added support for syspurpose attributes on consumer creation
=> [M] Consumer creation will now respect syspurpose attributes (ENT-1362)

server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/tasks/CRLUpdateJob.java, server/src/main/java/org/candlepin/config/ConfigProperties.java, server/src/main/java/org/candlepin/guice/CandlepinModule.java, server/src/test/java/org/candlepin/async/tasks/CRLUpdateJobTest.java
- Ported the CertificateRevocationListTask to the Artemis job
system as the CRLUpdateJob
- Updated the tests to use junit 5 paradigms
=> [F] Ported the CertificateRevocationListTask to the Artemis job system (ENT-860)

server/spec/job_schedule_spec.rb, server/src/main/java/org/candlepin/async/tasks/ExpiredPoolsCleanupJob.java, server/src/main/java/org/candlepin/config/ConfigProperties.java, server/src/main/java/org/candlepin/guice/CandlepinModule.java, server/src/test/java/org/candlepin/async/tasks/ExpiredPoolsCleanupJobTest.java
- Ported the ExpiredPoolsJob to the Artemis job system as the
ExpiredPoolsCleanupJob
=> [F] Ported the ExpiredPoolsJob to the Artemis job system (ENT-861)

server/src/main/java/org/candlepin/async/JobMessageReceiver.java, server/src/main/java/org/candlepin/async/tasks/JobCleaner.java, server/src/test/java/org/candlepin/async/tasks/RegenEnvEntitlementCertsJobTest.java
- Now acknowledging a message will not autocommit the session.
- Fix test extending the wrong class.
- Add missed JOB_NAME to JobCleaner job.
=> Enable redelivery of Artemis messages

server/src/main/java/org/candlepin/async/tasks/HealEntireOrgJob.java
@Ceiu Updated code changes as per your suggestions in https://github.com/candlepin/candlepin/pull/2386. 
Please review.
=> [F] HealEntireOrgJob review comment fix (ENT-848)

server/src/main/java/org/candlepin/async/JobConstraint.java, server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/impl/UniqueByArgConstraint.java, server/src/test/java/org/candlepin/async/impl/UniqueByArgConstraintTest.java
- The JobConstraint interface now accepts a collection of jobs for
the existing jobs, rather than a singular job
=> [F] Reverted binary job constraint interface changes

server/build.gradle, server/pom.xml, server/src/main/webapp/META-INF/context.xml
- Make JSS a compile only dependency
- Add spec comand to include locally installed JSS into shared classpath
=> 1713420: Load JSS jar from file system

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/dto/api/v1/PoolDTO.java, server/src/main/java/org/candlepin/dto/api/v1/PoolTranslator.java, server/src/main/java/org/candlepin/model/Pool.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/resources/db/changelog/20190729122218-add-locked-column-to-cp-pool.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml, server/src/test/java/org/candlepin/dto/api/v1/PoolDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/PoolTranslatorTest.java
=> [ENT-288] Need a better way to identify pools as being 'custom'

build.gradle
Update the jackson & jackson-databind version
=> Update jackson databind version

server/src/main/resources/db/changelog/20190813155224-add-principal-to-deleted-consumers.xml
- Updated the comment in the deleted consumer changeset that adds
a principal to the table
=> [M] Fixed incorrect wording in the deleted consumer changeset

server/spec/system_purpose_compliance_spec.rb, server/src/main/java/org/candlepin/model/Consumer.java, server/src/test/java/org/candlepin/model/ConsumerTest.java
- Role and Usage attributes are set to EmptyStringUserType
- Updated JUnit test cases
- Updated rspec test case
=> [M] 1738215 - change role and usage values to blank [ENT-1561]

server/src/main/java/org/candlepin/async/JobConstraints.java, server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/impl/ThrottledByJobKeyConstraint.java, server/src/main/java/org/candlepin/async/tasks/EntitlerJob.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/async/impl/ThrottledByJobKeyConstraintTest.java, server/src/test/java/org/candlepin/async/tasks/EntitlerJobTest.java
- Add throttling for the EntitlerJob
=> [ENT-1478] Investigate & implement job constraint for EntitlerJob

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/Refresher.java, server/src/main/java/org/candlepin/policy/js/pool/PoolHelper.java
- Restricting Locked Pool Scope
=> Restricting Locked Pool Scope

server/spec/activation_key_spec.rb, server/src/main/java/org/candlepin/resource/ActivationKeyResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java
- Restrict Special Characters while updating Activation keys
=> [ENT-1632]1665277: Restrict special characters in update activate key API

server/bin/create_test_repos.py
* When it is not possible to create or sign dummy RPM package,
then deploy script is terminated
* When creating or signing of RPm is terminated, then some
error is printed
* WIP: signing of RPM is executed with rebose=True option to see
more details
=> Make creating of test repositories more bullet proof

server/src/main/java/org/candlepin/model/Pool.java
- Added a default value for the Pool.locked field to properly
handle pools which existed before the addition of this field
=> [M] 1753750: Added a default value for Pool.locked

build.gradle, common/pom.xml, server/build.gradle, server/pom.xml
Also updated the pom files which picked up some earlier library changes.
=> Update the version of org.hibernate.validator

server/src/main/java/org/candlepin/model/ConsumerCurator.java
The Stage/Production deployments do not use the configuration entry that
was in use
=> Use more reliable method for detecting the hibernate dialect

server/src/main/resources/db/changelog/20190927153020-index-facts-element.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
- Created a change-set with index suggested in bug
- Updated change-log files to call newly created index
=> 1615405: Create index for table cp_consumer_facts on (lower(element)) column

server/spec/hypervisor_check_in_spec.rb, server/src/main/java/org/candlepin/model/ConsumerCurator.java, server/src/main/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJob.java
=> 1757542: Handle matching of system uuid regardless of casing [ENT-1688]

server/spec/candlepin_scenarios.rb, server/src/main/java/org/candlepin/dto/StandardTranslator.java, server/src/main/java/org/candlepin/dto/manifest/v1/PoolTranslator.java, server/src/main/java/org/candlepin/dto/manifest/v1/ProductBrandingTranslator.java, server/src/test/java/org/candlepin/dto/manifest/v1/PoolTranslatorTest.java, server/src/test/java/org/candlepin/dto/manifest/v1/ProductBrandingTranslatorTest.java, server/src/test/java/org/candlepin/dto/manifest/v1/ProductTranslatorTest.java, server/src/test/java/org/candlepin/test/TestUtil.java
- Populate branding information from marketing product instead of pool
=> [F] ENT-1614:use branding from product in manifest export

server/bin/import_test_data.rb
- Updated test data generation flow (./server/bin/deploy -gt) to populate product branding table.
=> ENT-1692: Generate test data to populate product branding

server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- Fixed an issue that could cause a NullPointerException during
system purpose status calculation
=> [M] 1762815: Fixed NPE during system purpose status calculation (ENT-1705)

server/code/setup/cpdb
- Corrected the value for ssl option.
- Improvements in error messages, help options for newly added options.
=> 1698469: Add options for cpdb command

server/spec/derived_product_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
=> [2.9] 1768473 - Unable to enable the tools repository for Satellite 6.6

server/spec/derived_product_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
Entitlements are not getting marked dirty for derived provided products
on pool refresh in hosted
=> 1767981: Unable to enable the tools repository for Satellite 6.6

server/bin/org_migrator.py
- Updated the tables targeted for migrating branding
- Updated how content is exported to work around a desync issue
that can cause products to reference content that is not owned
by the same org
- Added the TRACE logging level which, when enabled, will output
very verbose details about inserts performed during an import
=> [M] Updated branding and workaround for content desync in org_migrator

server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
This was omitted from the previous PR.
=> 1774640: Allow config entry to stop uuid match on consumers

server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/util/Transactional.java, server/src/test/java/org/candlepin/util/TransactionalTest.java
- Added the Transactional class and its nested interfaces for wrapping
transaction-oriented logic
- Added a method to AbstractHibernateCurator to create transactional
wrappers
=> [F] Added the Transactional class and interfaces (ENT-1769)

server/spec/consumer_resource_spec.rb, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/EnvironmentCurator.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/model/AbstractHibernateCuratorTest.java, server/src/test/java/org/candlepin/model/EnvironmentCuratorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java
- Allowing updating consumer environment by env name. Modified consumer PUT update API.
- Added spec test for different scenarios.
=> [ENT-1670] 1640822: [RFE] Change or switch content view from content host

build.gradle
- Added the javax.xml.bind module for continued JAXB functionality
=> [M] Added required module for Java 11 support (ENT-1027)

server/src/main/java/org/candlepin/audit/QpidEventMessageReceiver.java, server/src/test/java/org/candlepin/audit/QpidEventMessageReceiverTest.java
- Updated the QpidEventMessageReceiver to properly handle TEXT_TYPE
messages
=> [M] 1772194: Updated Qpid event messaging to use TEXT_TYPE and simple strings

server/pom.xml
- Added the javax.xml.bind entry for continued JAXB functionality
=> [M] Updated pom.xml for Java 11 support

server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceVirtEntitlementTest.java, server/src/test/java/org/candlepin/test/TestUtil.java
Added util method to create future date after N years.
Updated pool end date in JUnit from 2020-01-01 to date after 1 year.
=> Change pool end date from 2020-01-01 to future date

server/bin/update-server-xml.py
- update-server-xml.py no longer attempts to use the print function
as a keyword
=> [M] Updated the update-server-xml script to be more python3 compatible

server/src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml
- Added queries to insert the existing data into newly created tables.
=> [F] ENT-1833: Migration to populate data from old tables to new tables

server/client/ruby/candlepin_api.rb, server/spec/owner_product_resource_spec.rb, server/src/main/java/org/candlepin/controller/ProductManager.java, server/src/main/java/org/candlepin/dto/api/v1/ProductDTO.java, server/src/main/java/org/candlepin/dto/api/v1/ProductTranslator.java, server/src/main/java/org/candlepin/model/Product.java, server/src/test/java/org/candlepin/controller/ProductManagerTest.java, server/src/test/java/org/candlepin/dto/api/v1/ProductDTOTest.java, server/src/test/java/org/candlepin/dto/api/v1/ProductTranslatorTest.java
- Changes made in product Model & ProductDTO to support and return provided products.
- Changes made to product translator to copy provided product and derived provided product from model to DTO.
- Changes made to product manager to allow updating & applying changed related to provided product.
- Added a utility comparator method to compare two product by ID.
- Spec tests modified for creating/update product with provided product and verifying product version upgrade scenarios.
- Junit test for all the above changes.
=> [F] ENT-1827 Return provided products and derived provided products in the product API response

server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- Fixed an issue that could cause a NullPointerException during
system purpose status calculation
=> [2.5] 1794041: Fixed NPE during ExpiredPoolsJob execution

server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- Fixed an issue that could cause a NullPointerException during system purpose status calculation
=> [2.6] 1794042: Fixed NPE during ExpiredPoolsJob execution

server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- Fixed an issue that could cause a NullPointerException during system purpose status calculation
=> [2.9] 1794043: Fixed NPE during ExpiredPoolsJob execution

server/bin/import_test_data.rb, server/bin/test_data.json
- Updated test_data.json to move derived provided products to it's product definition.
- Updated import_test_data.rb to pass provided products while product creation.
=> [F] ENT-1834 - Update rspec test data generation flow

server/src/main/java/org/candlepin/guice/CandlepinContextListener.java, server/src/main/java/org/candlepin/guice/CandlepinModule.java, server/src/main/java/org/candlepin/resteasy/AnnotationLocator.java
- AnnotationLocator is now bound in CandlepinModule as a singleton
- AnnotationLocator is now initialized in the context listener
=> [M] Added the AnnotationLocator to the context listener and Candlepin module

server/client/ruby/candlepin_api.rb, server/spec/autobind_spec.rb, server/spec/consumer_resource_host_guest_spec.rb, server/spec/derived_product_spec.rb, server/spec/entitlement_certificate_v3_spec.rb, server/spec/healing_spec.rb, server/spec/hypervisor_check_in_spec.rb, server/spec/instance_spec.rb, server/spec/virt_spec.rb, server/src/main/java/org/candlepin/dto/rules/v1/PoolTranslator.java, server/src/main/java/org/candlepin/hostedtest/HostedTestSubscriptionServiceAdapter.java, server/src/test/java/org/candlepin/dto/rules/v1/PoolTranslatorTest.java, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java, server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
into org.candlepin.dto.rules.v1.PoolDTO from product model
- Updated Pool Translator, JUnit and rspec files.
=> [F] ENT-1829: Populate provided products and derived provided products

server/src/main/java/org/candlepin/config/ConfigProperties.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/test/java/org/candlepin/model/ConsumerCuratorTest.java, server/src/test/java/org/candlepin/pinsetter/tasks/HypervisorUpdateJobTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationLiberalNameRules.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java
constraint in Satellite 6
Changes are done from reference of:
1774640: Provide configuration option to disable UUID uniqueness constraint in Satellite 6.
=> 1787600: Provide configuration option to disable UUID uniqueness

server/spec/conditional_content_spec.rb, server/spec/derived_product_spec.rb, server/spec/sku_level_enable_override_spec.rb, server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java, server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java, server/src/main/java/org/candlepin/jackson/PoolSerializer.java, server/src/main/java/org/candlepin/jackson/ProductCachedSerializationModule.java, server/src/main/java/org/candlepin/model/EntitlementCurator.java, server/src/main/java/org/candlepin/model/Pool.java, server/src/main/java/org/candlepin/model/Product.java, server/src/main/java/org/candlepin/model/ProductEntitlements.java, server/src/main/java/org/candlepin/model/dto/Subscription.java, server/src/main/java/org/candlepin/policy/js/autobind/AutobindRules.java, server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java, server/src/main/java/org/candlepin/sync/Exporter.java, server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java, server/src/test/java/org/candlepin/controller/PoolManagerTest.java, server/src/test/java/org/candlepin/model/EntitlementCuratorTest.java, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java, server/src/test/java/org/candlepin/sync/ExporterTest.java
- Updated Product.java to cache provided products
- Updated Pool.java to populate providedProductDtos from product.providedProducts
- Updated code to fetch provided products from pool.product.providedProducts
- Updated Junit and rspec based on these changes
=> [F] Fetch provided products from pool.product (ENT-2026)

build.gradle, checks/pom.xml, config/checkstyle/checkstyle.xml
- Remove obsolete properties from checkstyle.xml
=> [M] Bump checkstyle from 8.27 to 8.29

docker/.env, docker/gating-test-images/README.mkd, docker/gating-test-images/build.sh, docker/gating-test-images/run.sh
The old one has been decommissioned
=> [M] ENT-2065 Migrate to new docker registry

docker/.env, docker/gating-test-images/README.mkd, docker/gating-test-images/build.sh, docker/gating-test-images/run.sh
The old one has been decommissioned
=> [F] ENT-2065 Migrate to new docker registry

server/src/main/java/org/candlepin/controller/Entitler.java
- Removed adding installed products of the consumer.
- Added provided products of dev_sku.
=> [F] ENT-1686: Change the way Dev Pools are created

server/src/main/java/org/candlepin/resource/OwnerResource.java
- Added @Transactional annotation to the method listPools()
=> ENT-2134: 1806578 - GET /owners/{owner_key}/pools is very slow

server/src/main/java/org/candlepin/resource/OwnerResource.java
- Added @transactional annotation to the method listPools()
=> [ENT-2134] 1806574 - GET /owners/{owner_key}/pools is very slow

buildSrc/build.gradle, buildSrc/src/main/java/org/openapitools/codegen/DefaultCodegen.java, buildSrc/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
- Override java codegen to generate set as a workaround until Openapi merges our contribution to support sets
=> ENT-2060: Handle Set in openapi generated DTOs

server/bin/update-server-xml.py, server/spec/content_access_spec.rb, server/src/main/java/org/candlepin/dto/api/v1/ContentDTO.java, server/src/main/java/org/candlepin/service/impl/DefaultContentAccessCertServiceAdapter.java, server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java, server/src/main/java/org/candlepin/util/X509Util.java, server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java, server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java, server/src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
=> 1813981: EUS Content not available in content access mode ENT-2175 [2.9]

.github/workflows/main.yml
Note: this is a cherry-pick from master, to get the github auto-assign reviewers action working on this branch.
=> [F] Add workflow for auto-assign reviewer action

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/CdnResource.java
- Added yaml definitions of Cdn resource.
- Updated CdnResource file.
=> ENT-1852: Port CdnResource to spec-first

server/spec/consumer_resource_activation_key_spec.rb, server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java
Leverage auto-heal value available in consumer during registration with auto-attach enable activation key.
=> [M] 1792278: use autoheal value during registration (ENT-2187)

api/candlepin-api-spec.yaml
Fixes - 
- Added example strings in all APIs. 
- Fixed incorrect `$ref` in `distributor_versions` GET api.
- Fixed incorrect `$ref` in DistributorVersionDTO.
=> ENT-2171 - Investigation: Fix swagger.json generation swagger UI

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/GuestIdResource.java, server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java
- Added GuestIdResource defination in yaml file
- Changes related to newly generated API interface
=> [F]ENT-1875: Port GuestIdResource to spec-first

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Added an additional null check during entitlement revocation
to avoid a null-pointer exception
- Removed an unnecessary list copy during entitlement revocation
=> [M] 1827426: Added an additional null check during entitlement revocation

server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
- Added an additional null check during entitlement revocation
to avoid a null-pointer exception
- Removed an unnecessary list copy during entitlement revocation
=> [2.9] 1826545: Added an additional null check during entitlement revocation (ENT-2320)

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/RoleResource.java
- Updated candlepin.yaml schema file with API definition.
- Updated RoleResouce file with API implementation.
=> ENT-1885: Port RoleResource to spec-first

server/spec/consumer_resource_spec.rb, server/src/main/resources/rules/rules.js, server/src/test/java/org/candlepin/policy/AutobindRulesTest.java
Fixes : 
- Removed Pool validation on Consumer Existing SLA from rules.js
- SLA is only going to be used to prioritize/de-prioritize pools.
(cherry picked from commit 442877f10a7e9f10c3ad5aac873bb8d4e60e03c6)
=> 1834221: Stopped checking & consider pools irrespective of Consumer Entitlement SLA for auto attach. (ENT-2278) (2.9-HOTFIX)

buildSrc/src/main/resources/templates/pojo.mustache
Changes:
- Added custom generic template to generate add/remove methods.
=> ENT-2329 : Generation of add/remove methods for java collection element

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/ActivationKeyResource.java
- Updated Candlepin Schema file
- Updated ActivationKeyResource API
=> ENT-1847: Port ActivationKeyResource to spec-first

server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/policy/ValidationResult.java
already in the key.
- Fixed the condition to add pool into filtered pools
- Added a spec test to validate the activation key filter is working
=> 1836973 - Listing pools available for an activation_key lists pools

server/src/main/resources/db/changelog/20200525150632-switch-job-data-to-longtext.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml
- Updated column type of job_data to longtext
=> 1839246: Mariadb job_data cannot store more than 64K

server/src/main/java/org/candlepin/guice/CandlepinContextListener.java, server/src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java
- Added a check to initialize the CRL file if it is missing during the Candlepin startup
=> 1834762: crl file candlepin-crl.crl is not found on the candlepin server

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/OwnerContentResource.java, server/src/test/java/org/candlepin/resource/OwnerContentResourceTest.java
- Changed the method name listContent to listOwnerContent and getContent to getOwnerContent
- Changed the OwnerContentResourceTest file to test the right methods as above
- Made changes in candlepin-api-spec for OwnerContentResource
=> [F] Ported OwnerContentResource to spec-first (ENT-1878)

server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/resources/logback.xml, server/src/test/java/org/candlepin/async/JobManagerTest.java
- Added the job key to the log context (MDC)
- Changes related to log format.
=> [Bug 1844258]: Job Manager Logging Format Changes for Splunk (ENT-2480)

server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/tasks/ActiveEntitlementJob.java, server/src/test/java/org/candlepin/async/JobManagerTest.java
- The JobManager now logs Quartz trigger misfire events as they occur
=> [M] 1844243: Added Quartz trigger misfire logging (ENT-2479)

server/src/main/java/org/candlepin/audit/EventSinkImpl.java
Changes -
- Added a check to open the session on-demand if it is closed for while queuing messages.
- Hardened `sendMessages` & `cancelMessages` methods to allow execution only if AMQ session is open.
=> 1847879: Artemis errors while trying to send events during hypervisor update job (ENT-2529)

build.gradle
The dependencyUpdates task can be used to analyze all
the libraries that Candlepin uses & look for updates that
we may wish to install.
=> Add the dependencyUpdates task to our gradle.

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/PoolResource.java, server/src/test/java/org/candlepin/resource/PoolResourceTest.java
- Added Pool reseaource specification
- Upated related files
=> ENT-1882: Port PoolResource to spec-first

docker/gating-test-images/build.sh, docker/gating-test-images/temp-cp/docker-compose.yml
Fix for "invalid mount config" error while trying to deploy candlepin using `docker stack deploy`.
=> ENT-2515: Fix for invalid mount config (jenkins docker build)

common/src/main/java/org/candlepin/common/resteasy/filter/LinkHeaderResponseFilter.java, common/src/test/java/org/candlepin/common/resteasy/filter/LinkHeaderResponseFilterTest.java
- Now, on APIs that support paging, the Link header added to the
response will no longer have URLs for next/prev/first/last pages
with duplicate query parameters, e.g.:
...candlepin/entitlements?per_page=1&page=2&per_page=1&page=1...
=> Don't duplicate params in Link header URLs when paging

server/src/main/java/org/candlepin/async/JobMessageReceiver.java, server/src/main/java/org/candlepin/messaging/impl/artemis/ArtemisMessage.java
- The JobMessageReciever now has better logging of job message
details during exception handling
=> [M] Improved job message related exception logging (ENT-2678)

server/src/main/java/org/candlepin/guice/CandlepinCapabilities.java
This adds the string "insights_auto_register" to the capabilities returned from the status response.
=> 1865906: Add "insights_auto_register" capability

server/src/main/java/org/candlepin/resource/UserResource.java
- Remove some forgotten annotations from UserResource
=> Remove redundant JAX-RS & Swagger annotations

api/candlepin-api-spec.yaml, server/src/main/java/org/candlepin/resource/RulesResource.java, server/src/test/java/org/candlepin/resource/RulesResourceTest.java
Changes made to port RulesResource to OpenAPI
=> ENT-2789: Port RulesResource to spec-first

server/src/main/java/org/candlepin/async/JobManager.java, server/src/test/java/org/candlepin/async/JobManagerTest.java
- Jobs which cannot be loaded for any reason will now be removed
from the scheduler when the JobManager is initialized
=> [M] 1877340: JobManager now removes dead jobs from the scheduler (ENT-2859)

server/spec/candlepin_scenarios.rb, server/spec/content_access_spec.rb, server/src/main/java/org/candlepin/guice/CandlepinModule.java, server/src/main/java/org/candlepin/sync/CertificateExporter.java, server/src/main/java/org/candlepin/sync/Exporter.java, server/src/test/java/org/candlepin/sync/ExporterTest.java
Changes  :-
- Changes made to export content access certs for a consumer who's owner in SCA mode.
- Added Spec test to verify it.
=> 1884761: Candlepin presents a different number of certificates for a consumer based on accept header (ENT-3127)

server/client/ruby/candlepin_api.rb, server/spec/consumer_resource_spec.rb, server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/controller/OwnerContentAccess.java, server/src/main/java/org/candlepin/dto/api/v1/ContentAccessDTO.java, server/src/main/java/org/candlepin/model/OwnerCurator.java, server/src/main/java/org/candlepin/model/OwnerNotFoundException.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/util/Util.java, server/src/test/java/org/candlepin/model/OwnerCuratorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java, server/src/test/java/org/candlepin/resource/GuestIdResourceTest.java, server/src/test/java/org/candlepin/resource/HypervisorResourceTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java
- Add a new endpoint GET /consumers/{consumer_uuid}/content_access
- Add a new endpoint GET /owners/{owner_key}/content_access
=> ENT-2594: Mechanism to determine if SCA can be enabled for a consumer

docker/candlepin-base/cp-test
- Added '-i' parameter to validated translated strings.
This lets jenkins to execute the command -> ./gradlew validate_translation
=> ENT-3110: Create Jenkins job for validating translation strings

vagrant/README.md
- Added a section for explaining How to switch to Java version in vagrant box.
=> Updated README file for testing Candlepin with Vagrant

docker/docker-compose-mysql.yml, docker/docker-compose-postgres.yml
Using copies of the database from our own repos
=> using vendored docker images

buildSrc/src/main/groovy/Gettext.groovy
(gettext/msgattrib)
- Added a Gradle task to perform msgattrib on po files.
=> ENT-3109: Create Jenkins job for translation extraction

buildSrc/src/main/groovy/Gettext.groovy
(gettext/msgattrib)
- Added a Gradle task to perform msgattrib on po files
=> [3.1]ENT-3109: Create Jenkins job for translation extraction

buildSrc/src/main/groovy/Gettext.groovy
(gettext/msgattrib)
- Added a gradle task to perform msgattrib on po files
- Added `validate_translation` task. It was initially added
in latest versions
=> [2.9]ENT-3109: Create Jenkins job for translation extraction

server/bin/refresh_data_extractor.sh, server/src/main/java/org/candlepin/model/OwnerContentCurator.java, server/src/main/java/org/candlepin/model/OwnerProductCurator.java, server/src/test/java/org/candlepin/model/OwnerContentCuratorTest.java, server/src/test/java/org/candlepin/model/OwnerProductCuratorTest.java
- Fixed a bug that would cause stack overflows when fetching entities
by versions with large sets of version information
- Fixed a bug with the refresh_data_extractor that prevented it
from parsing large log files
=> [M] Fixed a bug with entity lookups by version

docker/gating-test-images/cp-latest-stage/setup-env-extras.sh, docker/gating-test-images/temp-base-cp/setup-env.sh, docker/gating-test-images/temp-cp/cp-test
- Updated the scripts to use Java 11.
=> [M] ENT-3227: Upgrade gating-test-images docker build to Java 11

server/spec/autobind_spec.rb, server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java
- Updated the `rules.js` to ignore pool in priority calculation
- Updated `SystemPurposeComplianceRules` to ignore
=> [2.6] ENT-2725: Update system purpose status to NOT consider Layered SLA

server/spec/product_versioning_spec.rb
- Added additional testing to verify product versioning is
correct with the n-tier product hierarchy
=> [F] Add tests to verify n-tier product versioning (ENT-2078)

server/spec/derived_product_import_spec.rb
derived_product_import_spec.
- Updated the code to setup the products and pool
in the correct order.
=> ENT-3546:Address sporadic spec test failure in 

server/bin/import_test_data.rb, server/src/main/java/org/candlepin/model/ProductCertificateCurator.java, server/src/test/java/org/candlepin/service/impl/ProductCertCreationTest.java
- The Candlepin test data importer will now resolve product references
to ensure products are created in the right order during test data
import
- Changed product certificate generation such that any unexpected
exception results in an InternalServerError rather than a null
certificate
=> [M] Fixed product creation order in test data importer (ENT-3552)

server/candlepin.spec.tmpl
- Switch filedigest algorithm to sha-256
=> 1913441: Candlepin will not install in FIPS mode

api/pom.xml, build.gradle, checks/pom.xml, common/pom.xml, server/pom.xml
- Upgrade jackson-databind to 2.10.5.1
- Upgrade all other jackson deps to 2.10.5
=> [M] Upgrade jackson to 2.10.5 & 2.10.5.1

api/pom.xml, build.gradle, checks/pom.xml, common/pom.xml, server/pom.xml
- Upgrade jackson-databind to 2.10.5.1
- Upgrade all other jackson deps to 2.10.5
=> [3.1] Upgrade jackson to 2.10.5 & 2.10.5.1

server/spec/content_access_spec.rb, server/src/main/java/org/candlepin/async/tasks/HealEntireOrgJob.java, server/src/main/java/org/candlepin/async/tasks/UndoImportsJob.java, server/src/main/java/org/candlepin/controller/ContentAccessManager.java, server/src/main/java/org/candlepin/controller/ContentManager.java, server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java, server/src/main/java/org/candlepin/controller/Entitler.java, server/src/main/java/org/candlepin/controller/ProductManager.java, server/src/main/java/org/candlepin/model/Owner.java, server/src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java, server/src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/EnvironmentResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/PoolResource.java, server/src/main/java/org/candlepin/resource/SubscriptionResource.java, server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java, server/src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java, server/src/main/java/org/candlepin/util/Util.java, server/src/main/java/org/candlepin/util/X509V3ExtensionUtil.java, server/src/main/resources/db/changelog/20210211154615-add-owner-last-content-updated-column.xml, server/src/main/resources/db/changelog/changelog-create.xml, server/src/main/resources/db/changelog/changelog-testing.xml, server/src/main/resources/db/changelog/changelog-update.xml, server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java, server/src/test/java/org/candlepin/controller/ContentManagerTest.java, server/src/test/java/org/candlepin/controller/ProductManagerTest.java, server/src/test/java/org/candlepin/resource/SubscriptionResourceTest.java
- SCA certificates will now be regenerated on request if the org's
content, products, or pools change after the last cert update
=> [3.1] 1935300: Added additional checks for regenerating SCA certificates (ENT-3521)

server/bin/org_migrator/org_migrator.py
- Fixed an issue/bug in the org_migrator's export ordering of products
with derived products in the new product model. Products will now
be exported such that derived products will occur earlier in the
list than products which reference them.
=> [M] Fixed an issue with the org_migrator's export order of derived products (ENT-3675)

server/spec/content_access_spec.rb
- Add utility method that indirectly sets the content access
mode of an owner in standalone mode through export/import
- Allow SCA-related tests to run in both hosted and
standalone modes, and make them mode-aware where needed,
such as when asserting content urls contain a prefix or not
- Added a couple of missing assertions such as testing
the removal of content access mode of a manifest consumer
when sending an empty string for that value on an update request
=> ENT-3214: Test SCA in Standalone mode

server/src/main/java/org/candlepin/model/Product.java, server/src/test/java/org/candlepin/model/ProductTest.java
Fix for Stack Overflow issue in product equality check.
=> ENT-3677: Fix for Stack Overflow issue in product equality check.

server/spec/content_access_spec.rb, server/src/main/java/org/candlepin/controller/ContentAccessManager.java, server/src/main/java/org/candlepin/model/Owner.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/test/java/org/candlepin/controller/ContentAccessManagerTest.java, server/src/test/java/org/candlepin/model/OwnerCuratorTest.java, server/src/test/java/org/candlepin/resource/ConsumerResourceTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
This satisfies a requirement of the upcoming opt-in for hosted customers to simple content access mode.
=> [M] change default content access mode list

server/src/main/java/org/candlepin/policy/SystemPurposeComplianceStatus.java
- Updated the system purpose compliance reasons to mark
to be translated. After `./gradlew gettext`, the `keys.pot`
file gets updated. These text will be available for translation.
=> ENT-3747: 1947354 - Missing Compliance/SyspurposeCompliance translations

api/pom.xml, build.gradle
Bumped version of openapi generator maven (& gradle) plugin to v5.1.0
=> Bumped version of Openapi generator maven (& gradle) plugin

server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/model/Entitlement.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/util/CalculatedAttributesUtil.java
- Fixed a NullPointerException that could occur while listing future
pools that had associated entitlements
=> [3.2] 1960150: Fixed NPE when listing future pools with entitlements (ENT-3862)

server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/model/Entitlement.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/util/CalculatedAttributesUtil.java
- Fixed a NullPointerException that could occur while listing future
pools that had associated entitlements
=> [M] 1959122: Fixed NPE when listing future pools with entitlements (ENT-3862)

server/spec/owner_resource_spec.rb, server/src/main/java/org/candlepin/model/Entitlement.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/util/CalculatedAttributesUtil.java
- Fixed a NullPointerException that could occur while listing future
pools that had associated entitlements
=> [4.0] 1960148: Fixed NPE when listing future pools with entitlements (ENT-3862)

common/src/main/java/org/candlepin/common/util/VersionUtil.java, server/src/main/java/org/candlepin/async/JobManager.java, server/src/main/java/org/candlepin/async/JobMessageReceiver.java, server/src/main/java/org/candlepin/audit/ActivationListener.java, server/src/main/java/org/candlepin/audit/EventFilter.java, server/src/main/java/org/candlepin/controller/Entitler.java, server/src/main/java/org/candlepin/guice/CandlepinContextListener.java, server/src/main/java/org/candlepin/hibernate/ResultDataUserType.java, server/src/main/java/org/candlepin/model/AbstractHibernateCurator.java, server/src/main/java/org/candlepin/model/CdnCurator.java, server/src/main/java/org/candlepin/model/EnvironmentCurator.java, server/src/main/java/org/candlepin/model/ProductCertificateCurator.java, server/src/main/java/org/candlepin/resource/CloudRegistrationResource.java, server/src/main/java/org/candlepin/resource/ConsumerResource.java, server/src/main/java/org/candlepin/resource/EntitlementResource.java, server/src/main/java/org/candlepin/resource/OwnerResource.java, server/src/main/java/org/candlepin/resource/util/ConsumerBindUtil.java, server/src/main/java/org/candlepin/resource/util/ResourceDateParser.java, server/src/main/java/org/candlepin/sync/Importer.java, server/src/main/java/org/candlepin/util/JSSX509CRLStreamWriter.java
- Make sure exceptions are propagated/logged so that stacktraces are not lost
- Merge identical catch blocks
=> ENT-3832: Improve error logging

server/bin/org_migrator/cp_connectors.py, server/bin/org_migrator/org_migrator.py
- Updated how the loggers are created in cp_connectors and
org_migrator
- Updated how cp_connector returns cursors, allowing them to
be used with blocks and auto-close
=> [M] Refactored logging and cursor handling in the org migrator

docker/test, jenkins/Jenkinsfile, jenkins/cleanup.sh
- Add post-step cleanup to pipeline stages
=> ENT-4018: Cleanup docker containers & networks on Jenkins pipeline abort

docker/test, jenkins/Jenkinsfile, jenkins/cleanup.sh
- Add post-step cleanup to pipeline stages
=> [4.0] ENT-4018: Cleanup docker containers & networks on Jenkins pipeline abort

docker/test, jenkins/Jenkinsfile, jenkins/cleanup.sh
- Add post-step cleanup to pipeline stages
=> [3.1] ENT-4018: Cleanup docker containers & networks on Jenkins pipeline abort

src/main/java/org/candlepin/controller/ContentAccessManager.java, src/main/java/org/candlepin/resource/OwnerResource.java
Changes
- Logging changes to content access mode for owner.
=> [M] Log changes to content access mode for owner (ENT-4121)

server/src/main/java/org/candlepin/controller/ContentAccessManager.java, server/src/main/java/org/candlepin/resource/OwnerResource.java
Changes
- Logging changes to content access mode for owner.
=> [4.0] Log changes to content access mode for owner (ENT-4121)

spec/pool_unlimited_master_spec.rb, spec/post_bind_bonus_pool_spec.rb, src/main/java/org/candlepin/model/Pool.java, src/main/java/org/candlepin/policy/js/entitlement/EntitlementRules.java, src/main/java/org/candlepin/policy/js/pool/PoolRules.java
Changes :
- All unlimited pools are restricted to -1 quantity.
- Unmapped guest & Bonus pools specifically to have unlimited quantity in both cases: a) the master pool quantity is unlimited, b) virt_limit is unlimited.
=> [M] 1800811: Fix for pool quantity calculations (ENT-3974)

api/candlepin-api-spec.yaml, src/main/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJob.java, src/main/java/org/candlepin/model/OwnerCurator.java, src/main/java/org/candlepin/resource/ProductResource.java, src/test/java/org/candlepin/async/tasks/RegenProductEntitlementCertsJobTest.java, src/test/java/org/candlepin/model/OwnerCuratorTest.java, src/test/java/org/candlepin/resource/ProductResourceTest.java
Final query was exceeding the overall query parameter limit for /products/owners endpoint
Changes -
- Broke the query to avoid exceeding the limit for IN clause & overall query parameter limit.
=> 1989981: Fix to avoid exceeding the overall query parameter limit

src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml, src/main/resources/db/changelog/20210127105630-migrate-product-hierarchy.xml
- Added a validChecksum to the modified provided product migration
Liquibase tasks
=> [M] Added validChecksums for modified provided product migration changes

server/src/main/resources/db/changelog/20191218180815-create-provided-product-mappings.xml, server/src/main/resources/db/changelog/20210127105630-migrate-product-hierarchy.xml
- Added a validChecksum to the modified provided product migration
Liquibase tasks
=> [4.0] Added validChecksums for modified provided product migration changes

build.gradle
Adding a single task to make it easier to run checkstyleTest & checkstyleMain
=> Add a single checkstyle task

server/bin/upstream_subscription_injector.rb
- Changed how the upstream subscription injector loads subscriptions
from JSON files; subscription data will be read individually as a
pseudo-stream rather than attempting to load the entire JSON file
at once. This allows for very large JSON files to be read without
killing the Ruby process.
=> [4.0] Added support for very large JSON files to the upstream sub injector

server/src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java, server/src/main/java/org/candlepin/model/EntitlementCurator.java, server/src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
Should solve issue with performance and the concurrent
database errors as well
=> [3.1] 1973257: Update method to mark entitlements dirty

bin/scripts/upstream_subscription_injector.rb
- Changed how the upstream subscription injector loads subscriptions
from JSON files; subscription data will be read individually as a
pseudo-stream rather than attempting to load the entire JSON file
at once. This allows for very large JSON files to be read without
killing the Ruby process.
=> [M] Added support for very large JSON files to the upstream sub injector

spec/environment_cert_v3_spec.rb, src/main/java/org/candlepin/controller/EntitlementCertificateGenerator.java, src/main/java/org/candlepin/model/EntitlementCurator.java, src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java
Should solve the issue with performance and the concurrent
database errors as well
=> 2016418: Update method to mark entitlements dirty [M]

server/src/main/java/org/candlepin/model/ConsumerCurator.java
As written it was taking more time than needed while updating all consumers in the org.
=> 2028766: Change to query for correct updating and performance [4.0]

src/main/java/org/candlepin/model/ConsumerCurator.java
As written it was taking more time than needed while updating all consumers in the org.
=> 2028765: Change to query for correct updating and performance [M]

server/bin/upstream_subscription_injector.rb
- The upstream subscription injector no longer requires the
organization to be specified on the command line and will
now use the organization present in the subscription info
- The USI now supports gzipped subscription JSON files
- Added a flag to automatically create local organizations
in Candlepin during subscription injection
=> [4.0] Improved upstream subscription injector usability

build.gradle, pom.xml, src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, src/test/java/org/candlepin/model/PoolCuratorTest.java, src/test/java/org/candlepin/model/PoolTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Updated HSQLDB to v2.6.1
- Updated several tests accordingly
- Moved some tests to more suitable test suites
=> [M] Updated HSQLDB to 2.6.1 (ENT-2784)

api/pom.xml, build.gradle, checks/pom.xml, common/pom.xml, server/pom.xml, server/src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, server/src/test/java/org/candlepin/model/PoolCuratorTest.java, server/src/test/java/org/candlepin/model/PoolTest.java, server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Updated HSQLDB to v2.6.1
- Updated several tests accordingly
- Moved some tests to more suitable test suites
=> [4.0] Updated HSQLDB to 2.6.1 (ENT-2784)

build.gradle, pom.xml, src/main/resources/logback.xml
- Also update syslog / logstash configuration example
to work with latest logstash version.
=> [M] Update logging libraries (incl. logback) to latest version

api/pom.xml, build.gradle, checks/pom.xml, common/pom.xml, server/pom.xml, server/src/main/resources/logback.xml
- Also update syslog / logstash configuration example
to work with latest logstash version.
=> [4.0] Update logging libraries (incl. logback) to latest version

bin/deployment/test_data_importer.py, src/main/java/org/candlepin/util/X509ExtensionUtil.java, src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java, src/test/java/org/candlepin/util/X509ExtensionUtilTest.java
- Update testdata to generate content id without dash
- Strip non-numeric characters from content id before we use it for oid
=> 2036746: Fix Illegal embedded sign character

spec/environment_spec.rb, src/main/java/org/candlepin/model/EntitlementCurator.java, src/main/java/org/candlepin/model/EnvironmentContentCurator.java, src/main/java/org/candlepin/resource/ConsumerResource.java, src/main/java/org/candlepin/resource/util/EntitlementEnvironmentFilter.java, src/main/java/org/candlepin/util/Util.java, src/test/java/org/candlepin/controller/EntitlementCertificateGeneratorTest.java, src/test/java/org/candlepin/model/EntitlementCuratorTest.java, src/test/java/org/candlepin/resource/ConsumerContentOverrideResourceTest.java, src/test/java/org/candlepin/resource/ConsumerResourceCreationTest.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java, src/test/java/org/candlepin/resource/ConsumerResourceUpdateTest.java, src/test/java/org/candlepin/resource/GuestIdResourceTest.java, src/test/java/org/candlepin/resource/HypervisorResourceTest.java, src/test/java/org/candlepin/resource/util/EntitlementEnvironmentFilterTest.java, src/test/java/org/candlepin/util/UtilTest.java
Regenerate entitlements certs when environment list is modified aka environments being added/removed/re-prioritized.
=> ENT-4514 : Regen entitlements certs when environment list is modified

vagrant/candlepin.yml
- Removed extraneous environment and Ansible variable declarations
- Corrected syntax on the custom role task
=> [M] Corrected a few issues in the Ansible playbook used by Vagrant

CONTRIBUTING.md, build.gradle, client/build.gradle, jenkins/unit-tests.sh, settings.gradle, spec-tests/README.md, spec-tests/build.gradle, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClientFactory.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ConfigKey.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/DefaultProperties.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/OwnerClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/PropertiesConfiguration.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/SpecTestClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/SpecTestFixture.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/SystemProperties.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/NestedOwnerDTOBuilder.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/OwnerDTOBuilder.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/Util.java, spec-tests/src/test/java/org/candlepin/spec/OwnerApiTest.java, spec-tests/src/test/java/org/candlepin/spec/SpecTest.java, spec-tests/src/test/java/org/candlepin/spec/StatusApiTest.java, spec-tests/src/test/java/org/candlepin/spec/bootstrap/client/DefaultPropertiesTest.java, spec-tests/src/test/resources/settings.properties
Includes some foundation for the test conversion.
=> Client for java spec tests

bin/deployment/artemis/configure-artemis.py, build.gradle
- Update the external artemis deployment script to work on python3,
and to use the latest artemis version.
=> [M] Upgrade artemis to 2.20.0

api/candlepin-api-spec.yaml, spec/entitlement_resource_spec.rb, spec/entitlement_spec.rb, spec/owner_resource_spec.rb, src/main/java/org/candlepin/resource/ConsumerResource.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Removed on consumers and owners APIs
=> [M] Removed the matches parameter on entitlement APIs (ENT-4325)

jenkins/Jenkinsfile
- Images are publicly available, so the login is not needed
=> [M] Do not login to quay.io to pull images

api/candlepin-api-spec.yaml, src/main/java/org/candlepin/model/ContentOverride.java, src/main/java/org/candlepin/util/ContentOverrideValidator.java, src/main/resources/db/changelog/20220328090000-accommodate_large_overrides.xml, src/main/resources/db/changelog/changelog-create.xml, src/main/resources/db/changelog/changelog-testing.xml, src/main/resources/db/changelog/changelog-update.xml, src/test/java/org/candlepin/resource/ActivationKeyContentOverrideResourceTest.java, src/test/java/org/candlepin/resource/ConsumerContentOverrideResourceTest.java, src/test/java/org/candlepin/util/ContentOverrideValidatorTest.java
- Updated the values column in cp_content_override table to be text.
=> [M] Updated content override accept a long string of overrides (ENT-4139)

src/main/java/org/candlepin/policy/SystemPurposeComplianceRules.java, src/main/java/org/candlepin/resource/ConsumerResource.java, src/test/java/org/candlepin/policy/SystemPurposeComplianceRulesTest.java
Stack trace for the issue:
https://gist.github.com/JoshAlbrecht23/cef375638668ea41ac74c06e094d8884
=> [M] Added a check for null service level for consumer (ENT-3977)

candlepin.spec.tmpl
Confirmed correct function under the command in the daily cron job.
=> 1976153: Update permission on candlepin log directory [m]

.gitignore, .settings/org.eclipse.jdt.core.prefs, .vscode/settings.json
* Added settings to use eclipse-formatter.
* Added gitignore entries for generated directories.
=> Added configurations for using Visual Studio Code

.gitignore, .settings/org.eclipse.jdt.core.prefs, .vscode/settings.json
* Added settings to use eclipse-formatter.
* Added gitignore entries for generated directories.
=> [4.1] Added configurations for using Visual Studio Code

.gitignore, .settings/org.eclipse.jdt.core.prefs, .vscode/settings.json
* Added settings to use eclipse-formatter.
* Added gitignore entries for generated directories.
=> [4.0] Added configurations for using Visual Studio Code

.gitignore, .settings/org.eclipse.jdt.core.prefs, .vscode/settings.json
* Added settings to use eclipse-formatter.
* Added gitignore entries for generated directories.
=> [3.1] Added configurations for using Visual Studio Code

src/test/java/org/candlepin/model/AsyncJobStatusCuratorTest.java
General updates to the AsyncJobStatusCuratorTest unit tests. Locally, this reduced runtime from over 20 minutes to ~30 seconds.  
* Remove extraneous flushes
* Re-organize the createJobsForQueryTests() in order to reduce database load / time to execute.
=> Optimize hibernate use in AsyncJobStatusCuratorTest

src/main/java/org/candlepin/model/IdentityCertificateCurator.java, src/test/java/org/candlepin/model/IdentityCertificateCuratorTest.java
=> 2084517: CertificateCleanupJob fails with foreign key constraint violation [4.1] ENT-4986

server/src/main/java/org/candlepin/resteasy/filter/AuthenticationFilter.java, server/src/test/java/org/candlepin/resteasy/filter/AuthenticationFilterTest.java
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2076914
- The BZ was opened against sub-man, but we will be able to
verify the fix only using sub-man or cockpit plugin for
sub-man
* Card ID: ENT-4943
* Marked two strings for translations and modified one
string a little to be the same as existing translated string
* Modified unit tests according changes in AuthenticationFilter
(cherry picked from commit bfe716a42e5bcc3ab07dba2dae2ac9fcc319e784)
Backport of PR #3349 to 4.0.
=> [4.0] 2076914: Translate few strings.

src/main/java/org/candlepin/resteasy/filter/AuthenticationFilter.java, src/test/java/org/candlepin/resteasy/filter/AuthenticationFilterTest.java
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2076914
- The BZ was opened against sub-man, but we will be able to
verify the fix only using sub-man or cockpit plugin for
sub-man
* Card ID: ENT-4943
* Marked two strings for translations and modified one
string a little to be the same as existing translated string
* Modified unit tests according changes in AuthenticationFilter
(cherry picked from commit bfe716a42e5bcc3ab07dba2dae2ac9fcc319e784)
Backport of PR #3349 to 4.1.
=> [4.1] 2076914: Translate few strings.

buildSrc/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java, client/build.gradle, client/buildSrc/src/main/resources/templates/pojo.mustache, dependencies.gradle
Used 2 commits so that the update from the new openapi version would be separate from our additions.
=> Update openapi jars [ENT-5076]

spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Products.java, spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/pools/PoolSpecTest.java
The product types were reversed.
=> Update builder methods

spec-tests/build.gradle, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/CertificateUtil.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/X509HuffmanDecodeUtil.java, spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateV3SpecTest.java, spec/entitlement_certificate_v3_spec.rb
This also converts one of the tests to ensure that it works
=> Convert huffman decoding to java [ENT-5230]

src/main/java/org/candlepin/model/IdentityCertificateCurator.java, src/main/java/org/candlepin/sync/Exporter.java, src/test/java/org/candlepin/dto/api/v1/GuestIdArrayElementTranslatorTest.java, src/test/java/org/candlepin/dto/api/v1/GuestIdTranslatorTest.java, src/test/java/org/candlepin/model/IdentityCertificateCuratorTest.java
Plus a bit of checkstyle cleanup
=> 2118759: Leave manifest consumer identity certificate

spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/JsonDeserializationException.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/JsonSerializationException.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/RequestException.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Response.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/ResponseProcessingException.java
- Added the Request and Response objects for building generic
requests without needing a specific API class or method
=> [M] Added an API for performing generic requests

spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/request/Request.java
- The Request object now uses the underlying client's JSON
serializer to handle object serialization
- The Request content-type now defaults to "application/json"
when omitted
- Fixed a bug where setting an object or JSON string as the
Request body would cause it to be doubly JSON-serialized
- Fixed a bug that would cause an exception to be thrown in
cases where a non-object body was set or the body was
omitted entirely, due to a lack of a content-type header
=> [M] Fixed a couple issues with the custom spec Request object

src/main/java/org/candlepin/model/AbstractHibernateCurator.java
- Creation of system locks will attempt to use an INSERT IGNORE
style of statement to avoid parallel operations from creating
the same lock and causing one of them to fail
=> [M] Updated how system locks are created (ENT-5364)

client/build.gradle, client/src/main/java/org/candlepin/resource/HostedTestApi.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/ConsumerClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/JobsClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/OwnerClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/PoolsClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/util/UserUtil.java, spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateV3SpecTest.java, spec-tests/src/test/java/org/candlepin/spec/HostedTestSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/StatusSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/ActivationKeyAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/BasicAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/NoAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/SslAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/TrustedConsumerAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/TrustedUserAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/consumers/IdentityCertificateSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/InactiveConsumerCleanerJobSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/JobScheduleSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/pools/PoolSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
- Setup OpenAPI to use runtime expection
- Remove redundant throws from method signatures
=> Setup OpenAPI to generate ApiException as RuntimeException

buildSrc/src/main/groovy/test-logging-convention.gradle
- Prints a test summary as a list of failed test method names
=> Add test summary

spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/ContentResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/OwnerProductResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/StatusSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/ActivationKeyAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/BasicAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/NoAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/SslAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/TrustedConsumerAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/auth/TrustedUserAuthSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/bootstrap/client/DefaultPropertiesTest.java, spec-tests/src/test/java/org/candlepin/spec/bootstrap/client/ExternalPropertiesTest.java, spec-tests/src/test/java/org/candlepin/spec/consumers/IdentityCertificateSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/consumers/LocalizationSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/content/OwnerContentSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceFilteringSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/InactiveConsumerCleanerJobSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/JobScheduleSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/pools/PoolSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
- updated test names to should and should not format
- removed per class test instance annotations
=> [M] Removed test display names from java spec tests (ENT-5394)

spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java, src/main/java/org/candlepin/jackson/GuestIdDeserializer.java, src/main/java/org/candlepin/resteasy/JsonProvider.java
- deserializer that creates GuestIdDTO from id string
- deserializer that creates GuestIdDTO from containing object
=> [M] 2128583: Added deserializer for GuestIdDTO (ENT-5422)

bin/scripts/org_migrator/org_migrator.py
- The org migrator no longer imports or exports the 'cp_owner_env_content_access' table
- The default filename used during export now includes the org's key and date, following the format 'export-{org_key}-{yyyymmdd}'
- Added support for the following tables: cp_act_key_sp_add_on, cp_consumer_activation_key, cp2_product_dependent_products
=> [M] Updated the org migrator for recent changes to Candlepin's schema

src/main/java/org/candlepin/jackson/GuestIdDeserializer.java, src/main/java/org/candlepin/resteasy/JsonProvider.java
- Updated GuestIdDeserializer to use existing ObjectMapper
This is a fix for the original PR (#3606) for the issue
=> [M] 2128583: Updated GuestIdDeserializer to use existing ObjectMapper (ENT-5422)

spec-tests/src/test/java/org/candlepin/spec/EntitlementCertificateSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/entitlements/CertRevocationSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementCertificateV3SpecTest.java, spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java
Note that I corrected the client instantiations for the spec tests I converted. I'll let others correct their own.
=> Update spec tests for proper use of consumer clients

spec-tests/README.md
- Updated spec-tests/README.md in accordance with the updated testing guidelines
- Updated test examples using those from the guidelines doc
=> [M] Updated spec test README in accordance with the testing guidelines (ENT-5393)

candlepin.spec.tmpl
https://fedoraproject.org/wiki/SELinux/IndependentPolicy
- Fix available policy "variants"
- Add missing dependencies
- Invert dependency between candlepin and candlepin-selinux
- Start shipping interface file
- Set proper module priority
- Advertise ownership of binary policy files (%ghost)
Signed-off-by: Vit Mojzis <vmojzis@redhat.com>
=> SELinux: Update based on packaging guide

Vagrantfile
- Updated the networking configuration in the Vagrantfile
to use the correct attributes when running on newer
versions of Vagrant
=> Updated Vagrant networking configuration

bin/deployment/create_test_repos.py
Do not use a shell where there is no need for a shell: this is basically the case for the majority of the commands run. For this:
- change the non-shell command invocations to be a list of parameters, disabling the shell in that case
- disable all the manual quoting of parameters for non-shell command
This gives a noticeable speed improvement, as there are way less shell invocations.
=> test data importers: use less shell

src/main/java/org/candlepin/config/PropertyConverter.java, src/main/java/org/candlepin/pki/impl/JSSPKIUtility.java, src/test/java/org/candlepin/controller/refresher/visitors/ProductNodeVisitorTest.java, src/test/java/org/candlepin/model/ActivationKeyTest.java, src/test/java/org/candlepin/model/ContentTest.java, src/test/java/org/candlepin/model/OwnerProductCuratorTest.java, src/test/java/org/candlepin/model/ProductCuratorTest.java, src/test/java/org/candlepin/pki/impl/JSSPKIUtilityTest.java, src/test/java/org/candlepin/policy/PoolRulesInstanceTest.java, src/test/java/org/candlepin/policy/PoolRulesTest.java, src/test/java/org/candlepin/policy/activationkey/ActivationKeyRulesTest.java, src/test/java/org/candlepin/policy/js/pool/PoolHelperTest.java, src/test/java/org/candlepin/policy/js/quantity/QuantityRulesTest.java, src/test/java/org/candlepin/resource/AdminResourceTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java
For development
Issues accounted for:
Boxed primitives
Increase in time precision of Instance class
Removal of SHA-1 from JSS
=> CANDLEPIN-467: Updates to allow Candlepin to run on Java 17

bin/deployment/test_data_importer.py
Factorize all the datetime operations that do not change.
=> test data importers: reduce datetime operations

bin/deployment/create_test_repos.py
The current approach to add the productid certificate to each created repositories is:
- get the content of the certificate:
- if it exists locally, read it fully, and return it
- if it does not exists, fetch it from Candlepin, save it, and return it
- write it as "productid"
- add it to the repository
- delete this temporary "productid" file
Simplify all the above process a bit:
- always return the path to the certificate file, no matter whether it existed already or it was fetched from Candlepin
- when adding it to the repository, create "productid" as temporary link to the file
This has few improvements:
- existing certificates are not read at all
- creating & removing the temporary "productid" is a cheap link/unlink operation
- the internal get_productid_cert() does not return bytes …
=> test data importers: simplify productid addition to repos

.github/workflows/main.yml
- A reviewer is already assigned when the PR is opened.
=> [M] Do not assign reviewer when PR is marked ready for review

buildSrc/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java, client/buildSrc/src/main/resources/templates/pojo.mustache, dependencies.gradle, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClientFactory.java
=> CANDLEPIN-461: Update openapi-generator to 6.3.0

src/main/resources/db/changelog/20230220150433-drop-act-key-env-tables.xml, src/main/resources/db/changelog/changelog-create.xml, src/main/resources/db/changelog/changelog-testing.xml, src/main/resources/db/changelog/changelog-update.xml, src/test/java/org/candlepin/liquibase/SchemaCompatibilityTest.java
- cp2_activation_key_products
- cp2_environment_content tables
=> CANDLEPIN-443: drop obsolete tables

spec-tests/src/test/java/org/candlepin/spec/imports/ImportSuccessSpecTest.java, src/test/java/org/candlepin/sync/ProductImporterTest.java
- Fix was already done so this only adds tests
=> 2172535: Fix setting of metadata expiration during import

jenkins/Jenkinsfile
For Conscious Language Project
=> CANDLEPIN-518: [4.0-SAT] Update for renamed default branch in fh-pipeline-library

jenkins/Jenkinsfile
For Conscious Language Project
=> CANDLEPIN-518: [4.1] Update for renamed default branch in fh-pipeline-library

jenkins/Jenkinsfile
For Conscious Language Project
=> CANDLEPIN-518: [4.2] Update for renamed default branch in fh-pipeline-library

buildSrc/src/main/groovy/PomToolkit.groovy, pom.xml, rel-eng/releasers.conf
We need to make sure the target is ready to go before merging.
=> CANDLEPIN-532: Update build target for Java 17

containers/candlepin-base-cs9/setup-devel-env.sh
Needs to be merged after [PR-3899](https://github.com/candlepin/candlepin/pull/3899)
=> CANDLEPIN-471: Remove jss workaround

bin/scripts/README.md
update to better explain the refresh data usage.
=> CANDLEPIN-534: Update to doc for refresh_data_extractor

containers/candlepin-base-cs8/setup-devel-env.sh
It is needed by update-server-xml.py.
=> Install python3-libxml2 also on c8s

src/main/root/META-INF/context.xml
Use the new way to declare web application resources:
https://tomcat.apache.org/migration-8.html#Web_application_resources
=> Adapt META-INF/context.xml for webapp to Tomcat 8+

.github/workflows/woke.yaml, .woke.yaml
The description on rule changes here:
https://github.com/get-woke/woke/blob/main/docs/rules.md
Listing of the default rules:
https://github.com/get-woke/woke/blob/main/pkg/rule/default.yaml
=> CANDLEPIN-530: Added Conscious Language Initiative check to pipeline

.github/workflows/pr_verification.yml
- Unit tests will now run in Github actions along with the other PR verification jobs
=> [M] CANDLEPIN-510: Added unit tests to the Github actions

bin/scripts/code/setup/cpdb
- Action options reorganized to separate tasks
- Added --status option for a report only mode
- Removed obsolete --verify action
- Consolidated changelog use to match previous merge of scripts
=> CP-571: Update cpdb to reflect current use

.github/workflows/sonar_branch_analysis.yml
- Remove the metaspace setting because it is not needed and also
causes an error when run through the GH Actions yaml
=> [M] Fix 'Invalid maximum heap size' for gradle sonar

.github/workflows/pr_verification.yml, build.gradle
=> CANDLEPIN-505: Migrate sonar to GH Actions

src/main/java/org/candlepin/async/tasks/UndoImportsJob.java, src/main/java/org/candlepin/controller/CandlepinPoolManager.java, src/main/java/org/candlepin/controller/PoolManager.java, src/main/java/org/candlepin/model/Pool.java, src/main/java/org/candlepin/policy/js/pool/PoolRules.java, src/test/java/org/candlepin/async/tasks/UndoImportsJobTest.java, src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, src/test/java/org/candlepin/controller/PoolManagerTest.java, src/test/java/org/candlepin/policy/PoolRulesTest.java, src/test/java/org/candlepin/policy/js/entitlement/EntitlementRulesTestFixture.java, src/test/java/org/candlepin/policy/js/entitlement/HostedVirtLimitEntitlementRulesTest.java, src/test/java/org/candlepin/policy/js/entitlement/PostEntitlementRulesTest.java, src/test/java/org/candlepin/policy/js/entitlement/PreEntitlementRulesTest.java
Another dependency cycle resolving PR.
=> CANDLEPIN-600: Move isManaged check to pool

api/candlepin-api-spec.yaml, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/OwnerClient.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Contents.java, spec-tests/src/test/java/org/candlepin/spec/pools/RefreshPoolsSpecTest.java, src/main/java/org/candlepin/async/tasks/RefreshPoolsJob.java, src/main/java/org/candlepin/controller/CandlepinPoolManager.java, src/main/java/org/candlepin/controller/PoolManager.java, src/main/java/org/candlepin/controller/Refresher.java, src/main/java/org/candlepin/controller/refresher/RefreshWorker.java, src/main/java/org/candlepin/controller/refresher/mappers/AbstractEntityMapper.java, src/main/java/org/candlepin/controller/refresher/mappers/EntityMapper.java, src/main/java/org/candlepin/policy/js/pool/PoolRules.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/test/java/org/candlepin/async/tasks/RefreshPoolsForProductJobTest.java, src/test/java/org/candlepin/async/tasks/RefreshPoolsJobTest.java, src/test/java/org/candlepin/controller/PoolManagerTest.java, src/test/java/org/candlepin/controller/RefresherTest.java, src/test/java/org/candlepin/controller/refresher/RefreshWorkerTest.java, src/test/java/org/candlepin/policy/PoolRulesInstanceTest.java, src/test/java/org/candlepin/policy/PoolRulesStackDerivedTest.java, src/test/java/org/candlepin/policy/PoolRulesTest.java
This reverts commit c9ed71f4b920857564f78e6cb5eeaf8fbf404b49.
=> [M] Revert "CANDLEPIN-589: Added support for forced-update owner refresh"

ansible/roles/candlepin/tasks/el9/el9_base_deps.yml, candlepin.spec.tmpl, containers/candlepin-base-cs9/setup-devel-env.sh, pom.xml
- Change package from pki-servelet-engine to tomcat in candlepin.spec.tmpl and for cs9 images
=> [M] CANDLEPIN-531: Update RHEL dependency from pki-servlet-engine to tomcat

.github/scripts/i18n.sh, .github/workflows/i18n.yml
GH actions job of the internationalization job running in on this branch: 
https://github.com/candlepin/candlepin/actions/runs/5523927019/jobs/10075523568
=> [M] CANDLEPIN-613: Migrated the i18n job to GH actions

.github/scripts/i18n.sh
Adding the i18n.sh script so that the i18n Github actions workflow can run for the candlepin-4.2-HOTFIX branch.
=> [4.2] CANDLEPIN-613: Added i18n.sh script for GH actions job

.github/scripts/i18n.sh
Adding the i18n.sh script so that the i18n Github actions workflow can run for the candlepin-4.1-HOTFIX branch.
=> [4.1] CANDLEPIN-613: Added i18n.sh script for GH actions job

buildSrc/src/main/groovy/Gettext.groovy
Updating the Gettext.groovy file to match the version that exists in the main branch as there is logic for setting up the gettext_manifest.txt file that is necessary to run the gettext gradle task.
To verify, you can run `gradlew gettext` in a vagrant VM where there is no current `./build` directory.
These changes are targeted to address the GH actions i18n job failures for this codeline: https://github.com/candlepin/candlepin/actions/runs/5635078888/job/15265648838
=> [4.2] CANDLEPIN-613: Updated Gettext.groovy to main version

buildSrc/src/main/groovy/Gettext.groovy
Updating the Gettext.groovy file to match the version that exists in the main branch as there is logic for setting up the gettext_manifest.txt file that is necessary to run the gettext gradle task.
To verify, you can run `gradlew gettext` in a vagrant VM where there is no current `./build` directory.
These changes are targeted to address the GH actions i18n job failures for this codeline: https://github.com/candlepin/candlepin/actions/runs/5635078888/job/15265648838
=> [4.1] CANDLEPIN-613: Updated Gettext.groovy to main version

src/main/java/org/candlepin/async/tasks/CloudAccountOrgSetupJob.java, src/main/java/org/candlepin/hostedtest/HostedTestCloudRegistrationAdapter.java, src/main/java/org/candlepin/model/Owner.java, src/main/java/org/candlepin/service/CloudProvider.java, src/main/java/org/candlepin/service/CloudRegistrationAdapter.java, src/main/java/org/candlepin/service/exception/CouldNotAcquireCloudAccountLockException.java, src/main/java/org/candlepin/service/exception/CouldNotEntitleOrganizationException.java, src/main/java/org/candlepin/service/impl/DefaultCloudRegistrationAdapter.java, src/main/java/org/candlepin/service/model/CloudAccountData.java, src/main/resources/db/changelog/20230725171517-add-anonymous-claimed_column.xml, src/main/resources/db/changelog/changelog-update.xml, src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
- Create interface crateAndEntitleOrg to interact with adapters
- Create job for anonymous register and entitle offering from cloud provider and add unit tests for that
=> CANDLEPIN-623: Implement Anonymous Org Creation & Entitlement Job

config/codestyle/eclipse-formatter.xml
- Update spotless configuration
=> CANDLEPIN-642: Investigate Spotless issues and find potential solutions

.github/workflows/pr_verification.yml
- With some of the step in GH action we dont need JSS package so we can remove fedora container
=> [M] Remove fedora container from CI

src/main/java/org/candlepin/model/AnonymousCloudConsumer.java, src/main/java/org/candlepin/resource/CloudRegistrationResource.java, src/main/resources/db/changelog/20230803000000-create-anonymous-consumers.xml, src/test/java/org/candlepin/model/AnonymousCloudConsumerCuratorTest.java, src/test/java/org/candlepin/model/AnonymousCloudConsumerTest.java, src/test/java/org/candlepin/resteasy/filter/VerifyAuthorizationFilterTest.java
- fix anonymous cloud consumer instance ID max length
=> [F] CANDLEPIN-686: Add cloud offering ID to anonymous cloud consumer

src/main/java/org/candlepin/resource/ConsumerResource.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Fixed locale settings on date-parser for If-Modified-Since header
=> [4.2] 2242455: Fix date-time parsing for If-Modified-Since header

src/main/java/org/candlepin/resource/ConsumerResource.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Fixed locale settings on date-parser for If-Modified-Since header
=> [M] 2242299: Fix date-time parsing for If-Modified-Since header

src/main/java/org/candlepin/resource/ConsumerResource.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Fixed locale settings on date-parser for If-Modified-Since header
=> [4.3] 2242502: Fix date-time parsing for If-Modified-Since header

api/candlepin-api-spec.yaml, spec-tests/src/main/java/org/candlepin/spec/bootstrap/data/builder/Environments.java, spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentSpecTest.java, src/main/java/org/candlepin/dto/api/v1/EnvironmentTranslator.java, src/main/java/org/candlepin/model/Environment.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/main/resources/db/changelog/20231024083400-add-environment-content-prefix.xml, src/main/resources/db/changelog/changelog-update.xml, src/test/java/org/candlepin/dto/api/v1/EnvironmentTranslatorTest.java
- Updated DB schema
- Updated DTO and entity population
=> [Entity Layering] CANDLEPIN-689: Add environment prefix

client/src/main/java/org/candlepin/resource/HostedTestApi.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/CloudRegistrationClient.java, spec-tests/src/test/java/org/candlepin/spec/CloudRegistrationSpecTest.java, spec-tests/src/test/java/org/candlepin/spec/ExportSpecTest.java, src/main/java/org/candlepin/controller/ContentAccessManager.java, src/main/java/org/candlepin/controller/util/AnonymousContentPrefix.java, src/main/java/org/candlepin/hostedtest/HostedTestProductServiceAdapter.java, src/main/java/org/candlepin/model/AnonymousCloudConsumer.java, src/main/java/org/candlepin/model/AnonymousContentAccessCertificate.java, src/main/java/org/candlepin/model/AnonymousContentAccessCertificateCurator.java, src/main/java/org/candlepin/resource/ConsumerResource.java, src/main/java/org/candlepin/service/ProductServiceAdapter.java, src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java, src/main/java/org/candlepin/service/impl/DefaultProductServiceAdapter.java, src/main/java/org/candlepin/service/impl/ImportProductServiceAdapter.java, src/main/java/org/candlepin/util/X509Util.java, src/main/java/org/candlepin/util/X509V3ExtensionUtil.java, src/main/resources/db/changelog/20230803000000-create-anonymous-consumers.xml, src/main/resources/db/changelog/202310040000000-create-anonymous-certificates.xml, src/main/resources/db/changelog/changelog-update.xml, src/test/java/org/candlepin/controller/ContentAccessManagerDBTest.java, src/test/java/org/candlepin/controller/ContentAccessManagerTest.java, src/test/java/org/candlepin/controller/PoolManagerFunctionalTest.java, src/test/java/org/candlepin/controller/util/AnonymousContentPrefixTest.java, src/test/java/org/candlepin/model/AnonymousCloudConsumerTest.java, src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java, src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java, src/test/java/org/candlepin/service/impl/DefaultProductServiceAdapterTest.java, src/test/java/org/candlepin/test/DatabaseTestFixture.java
- added support for fetching anonymous content access certificates
=> [F] CANDLEPIN-626: Added anonymous content access certificate

.github/containers/mariadb.docker-compose.yml, .github/containers/postgres.docker-compose.yml, .github/workflows/pr_verification.yml
- Removed the Github actions build_image job
- Added build section to spec Github actions docker-compose files
=> [4.2] Build Github actions spec test containers using docker compose build

.github/containers/mariadb.docker-compose.yml, .github/containers/postgres.docker-compose.yml, .github/workflows/pr_verification.yml
- Removed the Github actions build_image job
- Added build section to spec Github actions docker-compose files
=> [4.1] Build Github actions spec test containers using docker compose build

spec-tests/src/main/java/org/candlepin/spec/bootstrap/assertions/JobStatusAssert.java, spec-tests/src/test/java/org/candlepin/spec/jobs/JobStatusSpecTest.java
Isolated spec tests requiring stopping of job scheduler from the rest of spec tests.
=> Fix job spec test timeouts

spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ExternalProperties.java
Fixes issue hit by assertj version update.
=> Fix ambiguous constructor call

spec-tests/src/test/java/org/candlepin/spec/bootstrap/client/ExternalPropertiesTest.java
=> Fix ambiguous assert call

.github/containers/Dockerfile, .github/containers/mariadb.docker-compose.yml, .github/containers/postgres.docker-compose.yml, .github/workflows/spec_tests.yml
This reverts commit 936b210b941e45a9b745dc3781225c76db39875c.
Temporarily reverting this commit until we can sort out exactly what change is breaking the health checks.
=> [M] Revert "CANDLEPIN-735: Updated CI with removal of JSS dependency"

src/main/java/org/candlepin/controller/ContentAccessManager.java, src/main/java/org/candlepin/guice/CandlepinModule.java, src/main/java/org/candlepin/model/ProductCertificateCurator.java, src/main/java/org/candlepin/model/UeberCertificateGenerator.java, src/main/java/org/candlepin/pki/DistinguishedName.java, src/main/java/org/candlepin/pki/PKIUtility.java, src/main/java/org/candlepin/pki/impl/BouncyCastlePKIUtility.java, src/main/java/org/candlepin/pki/impl/ProviderBasedPKIUtility.java, src/main/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapter.java, src/main/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapter.java, src/test/java/org/candlepin/pki/DistinguishedNameTest.java, src/test/java/org/candlepin/pki/impl/BouncyCastlePKIUtilityTest.java, src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java, src/test/java/org/candlepin/service/impl/DefaultIdentityCertServiceAdapterTest.java
- Extracted DN construction into builder and value object.
=> CANDLEPIN-718: Refactor Distinguished Name construction

CONTRIBUTING.md
- Updated CONTRIBUTING.md to include standards for Git commits
=> Added Git commit standards

candlepin.spec.tmpl
Just a couple of cherry-picks to make the 4.1 branch releasable again.
=> [4.1] Make candlepin-4.1-HOTFIX releasable

api/candlepin-api-spec.yaml, src/main/java/org/candlepin/controller/Entitler.java, src/main/java/org/candlepin/model/EntitlementCurator.java, src/main/java/org/candlepin/model/GuestIdCurator.java, src/main/java/org/candlepin/policy/js/compliance/ComplianceRules.java, src/main/java/org/candlepin/resource/GuestIdResource.java, src/test/java/org/candlepin/controller/EntitlerTest.java, src/test/java/org/candlepin/model/EntitlementCuratorTest.java, src/test/java/org/candlepin/model/GuestIdCuratorTest.java, src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java, src/test/java/org/candlepin/resource/GuestIdResourceTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java, src/test/java/org/candlepin/resource/util/InstalledProductStatusCalculatorTest.java
- CdnResource
- CdnCurator
- GuestIdResource
- GuestIdCurator
- EntitlementCurator
=> CANDLEPIN-131: Removed CP Query from CDN, GuestId, and Entitlement 

src/main/java/org/candlepin/model/DeletedConsumerCurator.java, src/test/java/org/candlepin/model/DeletedConsumerCuratorTest.java
Affected classes:
- DeletedConsumerResource
- DeletedConsumerCurator
=> CANDLEPIN-221: Removed CP Query from Deleted Consumer

spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/ApiClientFactory.java
- Changed protocol from SSL to TLSv1.3 for spec test client.
=> [M] CANDLEPIN-701: Sonar issue: ApiClientFactory

api/candlepin-api-spec.yaml, src/main/java/org/candlepin/async/tasks/HealEntireOrgJob.java, src/main/java/org/candlepin/model/OwnerCurator.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/test/java/org/candlepin/async/tasks/HealEntireOrgJobTest.java, src/test/java/org/candlepin/model/OwnerCuratorTest.java
- removed CandlepinQuery from OwnerResource
- removed CandlepinQuery from OwnerCurator
- removed EmptyCandlepinQuery from HealEntireOrgJobTest related to method in OwnerCurator
=> CANDLEPIN-192: Removed CP Query from Owner

src/main/java/org/candlepin/guice/CandlepinModule.java, src/main/java/org/candlepin/model/ProductCertificateCurator.java, src/main/java/org/candlepin/pki/certs/CertificateCreationException.java, src/main/java/org/candlepin/pki/certs/ProductCertificateGenerator.java, src/main/java/org/candlepin/resource/OwnerProductResource.java, src/main/java/org/candlepin/service/impl/DefaultProductServiceAdapter.java, src/test/java/org/candlepin/model/ProductCertificateCuratorTest.java, src/test/java/org/candlepin/pki/certs/ProductCertificateGeneratorTest.java, src/test/java/org/candlepin/service/impl/DefaultProductServiceAdapterTest.java
- Extracted product certificate creation into ProductCertificateGenerator
=> CANDLEPIN-797: Create product certificate generator

src/main/java/org/candlepin/config/ConfigProperties.java, src/main/java/org/candlepin/config/validation/AbstractConfigurationValidator.java, src/main/java/org/candlepin/config/validation/ConfigurationValidator.java, src/main/java/org/candlepin/config/validation/ConfigurationValidatorUtil.java, src/main/java/org/candlepin/config/validation/IntegerConfigurationValidator.java, src/main/java/org/candlepin/guice/CandlepinContextListener.java, src/main/java/org/candlepin/paging/PageRequest.java, src/main/java/org/candlepin/resource/ConsumerResource.java, src/main/java/org/candlepin/resource/JobResource.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/main/java/org/candlepin/resteasy/filter/PageRequestFilter.java, src/test/java/org/candlepin/config/TestConfig.java, src/test/java/org/candlepin/config/validation/AbstractConfigurationValidatorTest.java, src/test/java/org/candlepin/config/validation/IntegerConfigurationValidatorTest.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java, src/test/java/org/candlepin/resteasy/filter/PageRequestFilterTest.java
- Created default page size configuration
- Created default max page size configuration
- Updated existing paginated endpoints to use the new pagination configurations
- Added configuration validation classes to validate configurations on startup
=> [F] CANDLEPIN-246: Defined default and max page size for pagination

src/main/java/org/candlepin/model/EntitlementCurator.java, src/test/java/org/candlepin/controller/EntitlerTest.java, src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
- Also updated tests for code cleanup
=> CANDLEPIN-123: Updated EntitlementCurator to not use Hibernate Criteria

api/candlepin-api-spec.yaml, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/api/OwnerClient.java, spec-tests/src/test/java/org/candlepin/spec/hypervisors/HypervisorCheckInSpecTest.java, src/main/java/org/candlepin/model/ConsumerCurator.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java, src/test/java/org/candlepin/model/ConsumerCuratorTest.java, src/test/java/org/candlepin/model/ConsumerTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java
- Added paging params to getHypervisors endpoint spec
- Added pagination for getting hypervisors by owner
- Added pagination for getting hypervisors by ids
- Removed unused code from consumer curator
=> CANDLEPIN-150: Add pagination to getHypervisors endpoint

src/main/java/org/candlepin/model/OwnerCurator.java, src/main/java/org/candlepin/resteasy/filter/StoreFactory.java, src/test/java/org/candlepin/auth/permissions/OwnerCuratorPermissionsTest.java
- Added a method using secure criteria for StoreFactory to list Owners.
=> CANDLEPIN-816: Added secure method to OwnerCurator for StoreFactory

CONTRIBUTING.md
- Corrected some typos and formatting issues in CONTRIBUTING.md
=> [M] Addressed CONTRIBUTING.md typos and formatting

src/main/java/org/candlepin/model/ConsumerCurator.java, src/main/java/org/candlepin/resource/ConsumerResource.java, src/main/java/org/candlepin/service/impl/HypervisorUpdateAction.java, src/main/java/org/candlepin/util/Util.java, src/test/java/org/candlepin/async/tasks/HypervisorUpdateJobTest.java, src/test/java/org/candlepin/model/ConsumerCuratorTest.java
- Updated ConsumerCurator to not use Hibernate Criteria in queries.
=> [M] CANDLEPIN-252: Updated ConsumerCurator to not use Hibernate Criteria

spec-tests/src/test/java/org/candlepin/spec/pools/RefreshPoolsSpecTest.java
- Adding sleep should fix the random crash test because it seemed that the certificate regeneration is working. However, the operations are too quick in succession, causing both certificates to have the same timestamp. I also swapped the comparison of the certificate content and the timestamp in case this test crashes again, so we will know whether it was due to the timestamp or the certificates being the same.`
=> CANDLEPIN-847: Fixed intermittent failure in RefreshPoolsSpecTest

src/main/resources/db/changelog/20190927153020-index-facts-element.xml, src/main/resources/db/changelog/20200902123935-add-product-derived-product.xml, src/main/resources/db/changelog/20231003113535-entity_layering_schema.xml
- Updated the entity layering migration to avoid unnecessarily copying all content to every org's namespace
- Added some valid checksums on some other scripts which were modified across branches
=> [M] Added fixes for various database migration scripts

src/main/java/org/candlepin/model/OwnerInfoCurator.java
- Rewrote the getPoolAttributeValues helper method to use JPA criteria along with the Candlepin security predicate
=> [M] Restored missing security predicate in OwnerInfoCurator

src/main/java/org/candlepin/config/ConfigProperties.java, src/main/java/org/candlepin/config/validation/StringConfigurationValidator.java, src/main/java/org/candlepin/database/DatabaseConnectionManager.java, src/test/java/org/candlepin/config/validation/StringConfigurationValidatorTest.java, src/test/java/org/candlepin/database/DatabaseConnectionManagerTest.java
- Gracefully handled missing DB driver configuration to prevent NPE for Candlepin users.
=> [M] CANDLEPIN-864: Gracefully handled DB driver class conf not existing

src/main/java/org/candlepin/model/ConsumerCurator.java, src/main/java/org/candlepin/model/GuestIdCurator.java, src/test/java/org/candlepin/model/ConsumerCuratorTest.java, src/test/java/org/candlepin/model/GuestIdCuratorTest.java
- Updated GuestIdCurator and ConsumerCurator to use secure predicate.
- Updated access modifier of some tests in ConsumerCuratorTest.
=> [M] CANDLEPIN-874: Updated select curators to use secure predicate

src/main/java/org/candlepin/model/ConsumerContentOverrideCurator.java
- Updated the query backing the getLayeredContentOverrides method to avoid using a left join, to work around an issue with MySQL/ MariaDB that prevents it from using table indexes during the join operation
- Updated the verbiage on the in-code documentation to be clearer as to where the issues are occurring
=> [M] CANDLEPIN-881: Refactored Consumer ContentOverride Fetching Query

src/main/java/org/candlepin/model/PoolCurator.java
- The issue was that some of these methods might have needed to hide/filter entities that were retrieved from the database based on the current principal, and some of our changes might have removed that functionality.
=> [M] CANDLEPIN-873: Rewrited methods in PoolCurator to use secure predicate

api/candlepin-api-spec.yaml, spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceSpecTest.java, src/main/java/org/candlepin/model/ConsumerCurator.java, src/main/java/org/candlepin/resource/ConsumerResource.java, src/test/java/org/candlepin/model/ConsumerCuratorSearchTest.java, src/test/java/org/candlepin/resource/ConsumerResourceIntegrationTest.java, src/test/java/org/candlepin/resource/ConsumerResourceTest.java
- Enhanced 'GET /consumers' API to support 'environmentId' parameter.
=> [M] CANDLEPIN-893: Added API for listing consumers in a specific environment

Vagrantfile
- Added Git safe directory configuration using git config command
=> [M] Added owner and group options to synced folder configuration

src/main/java/org/candlepin/guice/CandlepinContextListener.java, src/main/java/org/candlepin/guice/DefaultConfig.java, src/main/java/org/candlepin/service/EventAdapter.java, src/main/java/org/candlepin/service/impl/DefaultEventAdapter.java, src/main/java/org/candlepin/service/model/AdapterEvent.java, src/main/java/org/candlepin/service/model/CloudCheckInEvent.java, src/main/java/org/candlepin/service/model/EventType.java, src/main/java/org/candlepin/service/model/SerializationType.java, src/test/java/org/candlepin/TestingModules.java, src/test/java/org/candlepin/guice/CandlepinContextListenerTest.java, src/test/java/org/candlepin/service/model/CloudCheckInEventTest.java
- Created the EventAdapter interface.
- Updated CandlepinContextListener class to call the EventAdapter startup and shutdown method during the application lifecycle.
=> [M] CANDLEPIN-898: Create EventAdapter interface

bin/scripts/register_consumer.py
- Added the register_consumers.py script for creating fake consumers for manually testing consumer-focused flows
=> [M] Added a utility script for creating consumers for testing

src/main/java/org/candlepin/model/ContentCurator.java, src/main/java/org/candlepin/paging/PagingUtil.java, src/test/java/org/candlepin/model/ContentCuratorTest.java
- Removed the now-obsolete ContentQueryArguments object and any query operations which used them
=> [M] CANDLEPIN-913: Removed obsoleted content queries

src/main/java/org/candlepin/controller/ConsumerManager.java, src/main/java/org/candlepin/resteasy/filter/ConsumerCheckInFilter.java, src/main/java/org/candlepin/service/model/CloudCheckInEvent.java, src/test/java/org/candlepin/controller/ConsumerManagerTest.java, src/test/java/org/candlepin/resteasy/filter/ConsumerCheckInFilterTest.java
- Added ConsumerManager to publish cloud consumer check-in events for various consumers
=> [M] CANDLEPIN-899: Created ConsumerManager class with updateLastCheckIn

src/main/java/org/candlepin/util/BatchSpliterator.java, src/test/java/org/candlepin/util/BatchSpliteratorTest.java
- Added a new utility class, the BatchSpliterator, to assist in performing semi-lazy bulk operations on collections and streams
=> [M] CANDLEPIN-923: Added BatchSpliterator utility class

src/main/java/org/candlepin/audit/EventSinkImpl.java, src/main/java/org/candlepin/messaging/impl/artemis/ArtemisMessage.java, src/test/java/org/candlepin/audit/DefaultEventMessageReceiverTest.java
- Updated the methods used for creating SimpleString instances to avoid older, now-deprecated methods
=> [M] Updated creation of SimpleString instances

src/main/java/org/candlepin/model/Owner.java
- Added the cache annotation to the Owner entity, with the READ_WRITE cache strategy
=> [M] CANDLEPIN-938: Added caching to the Owner entity

src/main/java/org/candlepin/model/ConsumerType.java
- Added the cache annotation to the ConsumerType entity, with the READ_WRITE cache strategy
=> [M] CANDLEPIN-938: Added caching to the ConsumerType entity

src/main/java/org/candlepin/model/AnonymousCloudConsumer.java
- Added documentatio explaining stored format of offering ids in database.
- Change limit for offering ids according to database field limit.
=> [M] CANDLEPIN-929: Added documentation for offeringIds in AnonCloudConsumer

build.gradle
- Added the "async" and "paging" packages to the apiJar gradle task so that the classes are included in the candlepin-api jar.
Verified the changes by running the `./gradlew apiJar` command to produce the candlepin-api jar and then decompiled the candlepin-api jar to verify that the classes from the "async" and "paging" packages are included.
=> [M] CANDLEPIN-946: Update apiJar dependency list

src/main/java/org/candlepin/model/CdnCurator.java, src/main/java/org/candlepin/pki/certs/AnonymousCertificateGenerator.java, src/main/java/org/candlepin/pki/certs/EntitlementCertificateGenerator.java, src/main/java/org/candlepin/pki/certs/EntitlementPayloadGenerator.java, src/main/java/org/candlepin/pki/certs/IdentityCertificateGenerator.java, src/main/java/org/candlepin/pki/certs/ProductCertificateGenerator.java, src/main/java/org/candlepin/pki/certs/SCACertificateGenerator.java, src/main/java/org/candlepin/pki/certs/UeberCertificateGenerator.java, src/main/java/org/candlepin/util/X509ExtensionUtil.java, src/main/java/org/candlepin/util/X509V3ExtensionUtil.java
- Updated several utility classes to be declared as singletons for the purposes of dependency injection
=> [M] CANDLEPIN-938: Updated several utility classes to be singletons

bin/scripts/register_consumer.py
- Added the ability to set the architecture of the mock systems being created by the register_consumer.py script
=> [M] Added enhancements to the register_consumer.py dev utility

src/main/java/org/candlepin/model/CloudProfileFacts.java, src/main/java/org/candlepin/model/Consumer.java, src/main/java/org/candlepin/util/X509Util.java, src/test/java/org/candlepin/pki/certs/EntitlementCertificateGeneratorTest.java, src/test/java/org/candlepin/util/X509V3ExtensionUtilTest.java
- Renamed the UNAME_MACHINE consumer fact to ARCHITECTURE.
=> [F] CHAINSAW-360: Moved the fact constants from X509Util to Consumer.Facts

api/candlepin-api-spec.yaml, spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java, src/main/java/org/candlepin/config/ConfigProperties.java, src/main/java/org/candlepin/controller/ConsumerManager.java, src/main/java/org/candlepin/controller/ContentAccessManager.java, src/main/java/org/candlepin/model/Consumer.java, src/main/java/org/candlepin/model/ConsumerCurator.java, src/main/java/org/candlepin/model/ContentAccessCertificateCurator.java, src/main/java/org/candlepin/model/EnvironmentCurator.java, src/main/java/org/candlepin/resource/OwnerResource.java, src/main/java/org/candlepin/util/NonNullLinkedHashSet.java, src/test/java/org/candlepin/config/TestConfig.java, src/test/java/org/candlepin/controller/ConsumerManagerTest.java, src/test/java/org/candlepin/controller/ContentAccessManagerTest.java, src/test/java/org/candlepin/model/ConsumerCuratorTest.java, src/test/java/org/candlepin/model/ContentAccessCertificateCuratorTest.java, src/test/java/org/candlepin/model/EnvironmentCuratorTest.java, src/test/java/org/candlepin/resource/OwnerResourceOwnerClaimingTest.java, src/test/java/org/candlepin/resource/OwnerResourceTest.java, src/test/java/org/candlepin/resource/OwnerResourceUeberCertOperationsTest.java, src/test/java/org/candlepin/resteasy/filter/ConsumerCheckInFilterTest.java, src/test/java/org/candlepin/util/NonNullLinkedHashSetTest.java
- Created PUT /owners/{owner_key}/consumers/environments endpoint for setting the environments of multiple consumers in one operation.
=> [M] CANDLEPIN-936: Create bulk set consumer environments endpoint

build.gradle, gradle/libs.versions.toml, spec-tests/build.gradle
- Switched from individual JUnit artifacts to JUnit BOM
- Updated libs.versions.toml to reference new JUnit modules
- Added junit-platform-launcher to runtime dependencies
- Reflected these changes in build.gradle and spec-tests/build.gradle
=> [M] Updated JUnit dependencies to 5.12.0 using the BOM

src/main/java/org/candlepin/model/ContentCurator.java, src/main/java/org/candlepin/resource/ContentResource.java, src/main/java/org/candlepin/resource/OwnerContentResource.java, src/test/java/org/candlepin/model/ContentCuratorTest.java
- Reverts commit 285644b525460623645831487905a50eac461c69 that reverted the patch for explicit bulk content translation
=> [M] Revert "CANDLEPIN-938: Reverted explicit content bulk translation"

buildSrc/src/main/java/org/candlepin/gradle/SpecVersion.java, spec-tests/src/main/java/org/candlepin/spec/bootstrap/client/DefaultProperties.java, src/main/java/org/candlepin/async/JobManager.java, src/main/java/org/candlepin/model/ManifestFileRecordCurator.java
- Removed duplicate logging branch logic in JobManager.
- Refactored createBlob method to use try-with-resources to properly close FileInputStream, preventing resource leaks.
=> [4.4] CANDLEPIN-1003: Fixed SAST scan issues

.github/workflows/sonar.yml
We were contacted by Product Security — Red Hat requested a security analysis of all our open-source projects, and our repository was flagged for argument injection. Once the reviewer approves the fix, we should also backport it to older branches.
=> [M] Prevent argument injection in SonarQube analysis step
